### ISSUE TITLE
Count query with group by returns wrong result [DATAJPA-656]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1034]
**[Glenn Volckaert](https://jira.spring.io/secure/ViewProfile.jspa?name=glenner003)** opened **[DATAJPA-656](https://jira.spring.io/browse/DATAJPA-656?redirect=false)** and commented

The `count` method of `SimpleJpaRepository`.

```java
public long count(Specification<T> spec) {
	return getCountQuery(spec).getSingleResult();
}
```

Gives a wrong result when using a specification having a group by.

While the method below does this correctly for grouped queries.

```java
protected Page<T> readPage(TypedQuery<T> query, Pageable pageable, Specification<T> spec) {

	query.setFirstResult(pageable.getOffset());
	query.setMaxResults(pageable.getPageSize());

	Long total = QueryUtils.executeCountQuery(getCountQuery(spec));
	List<T> content = total > pageable.getOffset() ? query.getResultList() : Collections.<T> emptyList();

	return new PageImpl<T>(content, pageable, total);
}
```

---

**Affects:** 1.7 GA (Evans)

**Backported to:** [1.7.3 (Evans SR3)](https://github.com/spring-projects/spring-data-jpa/milestone/54?closed=1), [1.6.6 (Dijkstra SR6)](https://github.com/spring-projects/spring-data-jpa/milestone/55?closed=1)

**Comment by vkrylosov** [comment]
Hello.
I met the same problem.

Method `count` of `JpaSpecificationExecutor` (`SimpleJpaRepository`) return wrong value.

```
@Override
public long count(@Nullable Specification<T> spec) {
    return executeCountQuery(getCountQuery(spec, getDomainClass()));
}
```

```
private static long executeCountQuery(TypedQuery<Long> query) {
    Assert.notNull(query, "TypedQuery must not be null!");
    List<Long> totals = query.getResultList();
    long total = 0L;
    for (Long element : totals) {
        total += element == null ? 0 : element;
    }
    return total;
}
```

If query doesn't contain grouping then `totals` will be list with 1 element - selected rows count.
But if query will have grouping then `totals` will have N elements with grouping rows count.
Actually I cannot imagen situation when we need sum of totals element.

For correct count method we need use list size - count of selected rows in original select.
I.e. something like:
```
List<Long> totals = new ArrayList<Long>();
if (totals.size() > 1) {
    return (long) totals.size();
 else  if (totals.size() == 0) {
    return 0L;
} else return totals.get(0);
```

Or we should change SQL generation for rows count if used "group by" in query...

**Comment by prateek550** [comment]
If you check the implementation its not an issue, but the a different way of calculation the count (by adding number of results).
`
for (Long element : totals) {
	total += element == null ? 0 : element;
}
`

 It can be raised as a feature to allow custom count logic or a predefined method for returning the number of rows, instead of sum of results.

**Comment by prateek550** [comment]
Any updates on this ?

**Comment by pkuzmenkov** [comment]
Hi, guys, faced the same issue. Unfortunately, this "feature" totally breaks the pagination. Is it planned to be fixed? Or do I need to find some workaround?
