### ISSUE TITLE
Investigate potential resource leak in Procedure support [DATAJPA-663]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1041]
**[Thomas Darimont](https://jira.spring.io/secure/ViewProfile.jspa?name=thomasd)** opened **[DATAJPA-663](https://jira.spring.io/browse/DATAJPA-663?redirect=false)** and commented

---

**Reference URL:** http://stackoverflow.com/questions/28054479/procedure-annotation-orphaning-database-connections-spring-data-jpa

**Comment by giuseppemilicia** [comment]
Hello, are there any updates on this issue?

**Comment by schauder** [comment]
According to Thomas reproducer this is fixed. 

As far as I can tell by https://github.com/spring-projects/spring-framework/commit/3c8c99664fcf444d72183a5bf8eec609c7706dbf

@giuseppemilicia if you still see a resource leak, please create a new ticket and provide a reproducer.
