### ISSUE TITLE
Cursor based pagination Support [DATAJPA-668]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1046]
**[John Mill](https://jira.spring.io/secure/ViewProfile.jspa?name=himan)** opened **[DATAJPA-668](https://jira.spring.io/browse/DATAJPA-668?redirect=false)** and commented

It'll be nice to have support for cursor based pagination like others

---

**Reference URL:** https://dev.twitter.com/rest/public/timelines

10 votes, 8 watchers

**Comment by gregturn** [comment]
Based on @odrotbohm 's comments on this not being achievable through standard JPA, I'm closing this issue. If someone has a proposal, feel free to open a new ticket to track such an effort.
