### ISSUE TITLE
update derived query from method names [DATAJPA-688]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1064]
**[Alireza Zerafati](https://jira.spring.io/secure/ViewProfile.jspa?name=bludream)** opened **[DATAJPA-688](https://jira.spring.io/browse/DATAJPA-688?redirect=false)** and commented

derived queries are very useful, we have a lot of small update queries too, why don't we implement update derive queries too, would be awesome at least for me.

sample:

```
updateByNameSetAge(String name, int age);

updateByNameAndEmailSetAge(String name,String email, int age);

updateByNameSetAgeAndNumber(String name, int age,String number);
```

---
No further details from [DATAJPA-688](https://jira.spring.io/browse/DATAJPA-688?redirect=false)

**Comment by gregturn** [comment]
Essentially, the flow of:

```java
Employee e = repository.findByName(name);
e.setAge(30);
repository.save(e);
```
...is pretty simple to follow. JPA knows when to use INSERT vs. UPDATE, so in this scenario, it WOULD do an update.

The proposal isn't clear on whether these updates are aimed at applying to one record or multiple. The current paradigm would force the user to choose how to handle that, deliberately, and that's a good thing. For example, if this were to affect multiple rows, the code would look more like this:

```java
List<Employee> employees = repository.findByName(name);
employees.forEach(e -> e.setAge(30));
repository.saveAll(employees);
```
Again, the proposal is vague about which one we'd be dealing with. The former example may look straightforward, but the latter really seems a bit strange to blindly update so many rows with an arbitrary value. Unless that's what is REALLY needed. And by sticking with this paradigm, the user is forced to contemplate this properly.

On top of that, this proposal would probably require a huge overhaul of the query parsing algorithm that I frankly don't see the benefit. Not when we have a straightforward solution already in place.
