### ISSUE TITLE
Pageable Always Adding From Entity to Sort Field Name [DATAJPA-726]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1066]
**[Corey Mosher](https://jira.spring.io/secure/ViewProfile.jspa?name=twistymcgee)** opened **[DATAJPA-726](https://jira.spring.io/browse/DATAJPA-726?redirect=false)** and commented

When using `@Query` in a JPA repository along with `Pageable` and attempting to sort on a field in a joined entity, the from entity gets prepended to the sort field. For example, if I do the following query:

```java
@Query(value = "select p from Customer c join c.productOrder p where p.delayed = true")
```

If I pass a `PageRequest` sorting on a field in the from entity (`Customer`), everything will work fine:

```java
PageRequest page = new PageRequest(0, 20, Direction.DESC, "lastName");
```

However, if I simply decide to sort by a field in the `ProductOrder` entity with this `PageRequest`:

```java
PageRequest page2 = new PageRequest(0, 20, Direction.DESC, "p.lineItems");
```

I will get the following error:

```
Caused by: org.hibernate.QueryException: could not resolve property: p of: hello.Customer [select p from hello.Customer c join c.productOrder p where p.delayed = true order by c.p.lineItems desc]
```

`c.` was prepended onto the sort field. I am attaching a modified version of the Spring Data JPA tutorial from the Spring site that illustrates the issue

---

**Attachments:**
- [gs-accessing-data-jpa-master.zip](https://jira.spring.io/secure/attachment/22822/gs-accessing-data-jpa-master.zip) (_86.25 kB_)

**Referenced from:** commits https://github.com/spring-projects/spring-data-jpa/commit/51a88854b7f0bec03a6c9015ee61898ebed02930, https://github.com/spring-projects/spring-data-jpa/commit/baae6c7149ce64d64a90d15905f48bc1b29aa1ea, https://github.com/spring-projects/spring-data-jpa/commit/28ac667d8d825b1cc69d25e773cb3010e6ab5456, https://github.com/spring-projects/spring-data-jpa/commit/67b93c2073e0a0eb204fecb0e9df0ed5e24456c1

**Backported to:** [1.8.1 (Fowler SR1)](https://github.com/spring-projects/spring-data-jpa/milestone/53?closed=1), [1.7.3 (Evans SR3)](https://github.com/spring-projects/spring-data-jpa/milestone/54?closed=1), [1.6.6 (Dijkstra SR6)](https://github.com/spring-projects/spring-data-jpa/milestone/55?closed=1)

**Comment by Dawood-ibn-Kareem** [comment]
I still have this problem.  I'm using spring-core 5.3.22 and spring-data-jpa 2.7.2.  What versions of each do I need to have the fix?

**Comment by odrotbohm** [comment]
Would be cool if you could provide us with a minimal reproducer and create a new ticket for that.

**Comment by gregturn** [comment]
@Dawood-ibn-Kareem Please follow #2960 and you can track our progress on resolving this issue. Pay note, that while that ticket is assigned to Spring Data JPA 3.2, the solution will certainly be backported to 3.1. However, it's unlikely to be backported to 2.7, considering we don't have the newly built HQL/JPQL parser available, and such detailed operations are very difficult with the old QueryUtils.
