### ISSUE TITLE
Allow access to query method parameters from within the query declaration [DATAJPA-723]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1098]
**[Caleb Cushing](https://jira.spring.io/secure/ViewProfile.jspa?name=xenoterracide)** opened **[DATAJPA-723](https://jira.spring.io/browse/DATAJPA-723?redirect=false)** and commented

So we have some code that uses some complex logic for sorting, in an external if statement we determine which of these 2 implementations to run. I would like to not have to do both of these methods, but instead have the one that takes Pageable and find a way to encode the order by into an Order object as either a jpql snippet or a criteria builder object. That way I could only have the one query and just conditionally choose the order (and have it support the asc/desc parameter).

if this is already possible, documentation would be wonderful

```Java
	Page<UserActivityLog> findByActivityTargetUserId( Long id, Pageable pageable );

	@Query( "from UserActivityLog al where al.activityTargetUser.id = ?1 "
			        + " order by case "
			        + " when al.activitySourceUser.primaryOrganization.ownerOrganization = true "
			        + " then al.activitySourceUser.role.roleType "
			        + " else al.activitySourceUser.contact.fullName "
			        + " end ?#{ #pageable.getOrderFor('activitySourceUser.contact.fullName').direction } ")	Page<UserActivityLog> findByActivityTargetUserIdOrderByUserForNonAdmin( Long id, Pageable pageable );
```

---
No further details from [DATAJPA-723](https://jira.spring.io/browse/DATAJPA-723?redirect=false)

**Comment by gregturn** [comment]
I don't see anything specific here that needs to be addressed inside Spring Data JPA.

Either work with one of our currently supported options: Specification, QueryDSL, SpEL, native or JPQL.

Veering into the range of CLOBs further pushes this out of range. CLOB columns are really data store specific and require custom handling.
