### ISSUE TITLE
Delete event not flushed before Save in JpaRepository [DATAJPA-727]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1100]
**[Tom Matthews](https://jira.spring.io/secure/ViewProfile.jspa?name=tom14)** opened **[DATAJPA-727](https://jira.spring.io/browse/DATAJPA-727?redirect=false)** and commented

I've come across an issue when using a `@UniqueConstraint` and deleting/inserting entities using JpaRepository within a transaction.  If I have a model object with a unique constraint on a property, then within a transaction I delete the original object and save another with the same property value, a constraint violation is thrown.  When looking at hibernate logs it appears that the "DELETE" is not flushed before the "INSERT" is executed.

For example I have a model object "UniqueEntity" which has a property "value" with a unique constraint defined:

```
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = "value", name = "UK_ENTITY_DATA"))
public class UniqueEntity {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	Integer id;

	@Column(name = "value")
	Integer value;

	public UniqueEntity() {
	}

	public UniqueEntity(Integer value) {
		this.value = value;
	}

	public Integer getValue() {
		return value;
	}
}
```

If I call the following method within a transaction a DataIntegrityViolationException is thrown:

```
@Transactional
public UniqueEntity addSameValue(UniqueEntity originalEntity) {
	UniqueEntity newEntity = new UniqueEntity(originalEntity.getValue());

	repository.delete(originalEntity);

	// no flush here

	newEntity = repository.save(newEntity);

	return newEntity;
}
```

Exception thrown is:

```
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint ["UK_ENTITY_DATA_INDEX_B ON PUBLIC.UNIQUEENTITY(VALUE) VALUES (1, 1)"; SQL statement:
insert into UniqueEntity (id, value) values (null, ?) [23505-187]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
```

If between the DELETE and INSERT I read from the repository, the DELETE is flushed and the INSERT completes as expected.

This was tested with both mysql and h2.

An example with 2 JUnit tests is attached. One test demonstrates the constraint violation and the other shows the flush with a read between the INSERT and DELETE.  Run with "mvn test"

---

**Affects:** 1.8 GA (Fowler)

**Attachments:**
- [jpatest.zip](https://jira.spring.io/secure/attachment/22825/jpatest.zip) (_8.42 kB_)

8 votes, 15 watchers

**Comment by Alaincruzc90** [comment]
I found a "hacky" way to solve this "bug". It seems we can force the order of the persistence events by fetching the entity again.

```
this.entityManager.delete(entity);
Entity e = this.entityManager.findById(id)
otherEntity.setId(entity.getId());
this.entityManager.save(otherEntity);
```

Hope this example helps anyone else surfing for a solution.

**Comment by simtape** [comment]
I faced this bug when trying to delete an entity which was the child of a one-to-one relationship, and after the delete i needed to recreate and save a new one for the same parent entity. I solved it by doing this:

`entityParent.setEntityChild(null);
entityParentRepository.save(entityParent);
entityChildRepository,delete(entityChild);
entityChildRepository.flush();
EntityChild newEntityChildToStore = new EntityChild();
entityChildRepository.save(newEntityChildToStore);`

**Comment by FutureFlash94** [comment]
I had the same issue, took some time to understand but here is the answer:

Have a look at that: https://stackoverflow.com/questions/12616336/how-is-hibernate-deciding-order-of-update-insert-delete
(or here: https://docs.jboss.org/hibernate/orm/6.1/javadocs/org/hibernate/event/internal/AbstractFlushingEventListener.html#performExecutions(org.hibernate.event.spi.EventSource))

> Execute all SQL (and second-level cache updates) in a special order so that foreign-key constraints cannot be violated:
> 
>Inserts, in the order they were performed
>Updates
>Deletion of collection elements
>Insertion of collection elements
>Deletes, in the order they were performed
