### ISSUE TITLE
Provide a Slice based implementation of PagingAndSortingRepository [DATAJPA-734]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1107]
**[Brandon Vulaj](https://jira.spring.io/secure/ViewProfile.jspa?name=bvulaj)** opened **[DATAJPA-734](https://jira.spring.io/browse/DATAJPA-734?redirect=false)** and commented

This may belong in DATAREST, but I figured I'd start here.

As has already been recognized, sometimes the extra count( * ) query can be incredibly expensive, depending on the database engine.  Currently, within Spring Data REST, there is no way to re-map an entity's collection resource to utilize a method that returns a Slice instead of a Page.  Of course you can write your own methods that do this, but this does not affect the collection resource for SDR.

SO Reference: http://stackoverflow.com/questions/29946477/disable-row-count-of-findall-collection-resource-in-spring-data-rest

---

**Issue Links:**
- [DATAJPA-961](https://jira.spring.io/browse/DATAJPA-961) Slice support on JpaSpecificationExecutor

2 votes, 3 watchers

**Comment by gregturn** [comment]
In general we aren't going to create more variations of repository definitions. It leads to too much maintenance. 

If you prefer the Slice-based abstraction, you are free to create your own base repository and extensions. Spring Data JPA will work just fine with it and Thomas mentioned up above. But we aren't going to managed that change ourselves.
