### ISSUE TITLE
duplicate results when sorting by collection property  [DATAJPA-744]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1115]
**[Martin Ždila](https://jira.spring.io/secure/ViewProfile.jspa?name=m.zdila)** opened **[DATAJPA-744](https://jira.spring.io/browse/DATAJPA-744?redirect=false)** and commented

Given entities and repository:

```java
@Entity
public final class Partner {

    @Id
    private String id;

    @OneToMany(mappedBy = "partner", fetch = FetchType.LAZY)
    private List<Merchant> merchants;

    ...
}

@Entity
public final class Merchant {

    @Id
    private String id;

    @Column
    private String name;

    @ManyToOne(fetch = FetchType.LAZY)
    private Partner partner;

    ...
}

public interface PartnerRepository
        extends JpaRepository<Partner, String>, QueryDslPredicateExecutor<Partner> {

}
```

If there is only one partner having two merchants in the DB then the following code incorrectly returns list with two instances of the same parnter.

```java
partnerRepository.findAll(new Sort("merchants.name"));
```

This is caused internally by the DB join. By creating custom implementation that adds the distinct to the selection the result is correctly the single partner.

Wouldn't it be correct to do distinct selection per default?

---

**Affects:** 1.9 M1 (Gosling)

3 votes, 8 watchers

**Comment by gregturn** [comment]
I'm afraid that the original problem hints at a more complex solution than. The clue is here:

> If there is only one partner having two merchants in the DB then the following code incorrectly returns list with two instances of the same parnter [sic].

Simply put, a query that would only return the "parent" rows of data, yet sort by a "child's" attribute REQUIRES a JOIN operation. And as alluded to in that quote, this will cause a cartesian product.

In essence, you NEED to do a parent-to-child JOIN, sort based upon the child's attribute, but then ultimately ONLY select the parent's columns. There are multiple ways to get this semantically out of relational database with a DISTINCT-based operation being the most obvious.

In a pure SQL nature, it should be something like this:

```sql
SELECT DISTINCT p.*
FROM partner AS p
JOIN merchant AS m
ON p.merchant_fk = m.id
ORDER BY m.name
```
This query generates the complete cartesian product, orders by `MERCHANT.NAME`, and then only selects the `PARTNER` columns, finally applying a DISTINCT over the final result set, thus removing duplicate rows.

This query also [handles the situation mentioned by where one partner is listed twice for two different merchants](https://github.com/spring-projects/spring-data-jpa/issues/1115#issuecomment-752438055), considering 1+ merchants is enough to get that particular partner into the result set.

Whether you prefer writing a Hibernate query and taking advantage of our HQL parser with `@Query` or using a [custom implementation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations), or simply sticking with a native query, I leave that up to you.

But I believe this firmly suggests that trying to force it into a custom finder is really not practical and instead exactly what these other query options are for. 

In any event, this is not a bug in Spring Data JPA, but instead an example of a complex query that doesn't fit our simpler query solutions.
