### ISSUE TITLE
AbstractPersistable id with Access Type Property [DATAJPA-746]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1117]
**[Caleb Cushing](https://jira.spring.io/secure/ViewProfile.jspa?name=xenoterracide)** opened **[DATAJPA-746](https://jira.spring.io/browse/DATAJPA-746?redirect=false)** and commented

My understanding is that hibernate will generally lazy load an entire entity on when requesting a joined entity including id which it already has

http://256.com/gray/docs/misc/hibernate_lazy_field_access_annotations.shtml

it would seem that it would be beneficial to annotate the id field in AbstractPersistable

with 
```java
@Access( AccessType.PROPERTY )
```
---

1 votes, 2 watchers

**Comment by gregturn** [comment]
There is no identifying reason why this needs to be done at framework level (vs. for a specific project's JPA modeling).
