### ISSUE TITLE
JSR-310 converters result in Hibernate attempting to map columns as TIMESTAMP [DATAJPA-753]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1124]
**[Thomas Golden](https://jira.spring.io/secure/ViewProfile.jspa?name=tomrk1089)** opened **[DATAJPA-753](https://jira.spring.io/browse/DATAJPA-753?redirect=false)** and commented

I've created a simple JPA entity class which as one of its fields has a `java.time.LocalDate`. In order to map this field, I've registered the `Jsr310JpaConverters` class in my Spring Boot application's `@EntityScan` annotation, alongside my own base package. The application validates Hibernate mappings at startup.

The issue is that I've declared the field as a Postgres DATE type, which does not include time information. When the validation occurs, the JSR-310 converters are consulted, and it _appears_ that since they return `java.util.Date` as the converted type, that Hibernate assumes I must want to store a date with time. Thus, I get the message "found date, expected timestamp" when starting my application.

The simple workaround is to change the database column to a timestamp and simply ignore the time portion, but this is somewhat unsatisfying. I can't apply a `@Type` or `@Temporal` annotation to the entity because the converter is being used and it's not of type `java.util.Date`. I can't say I know enough about the JPA spec or internals to suggest a solution, but it'd be nice if I could "hint" somehow what I'd like that converted date to be treated as

---

**Affects:** 1.8 GA (Fowler)

**Comment by gregturn** [comment]
I wrote the following test case to check this scenario,

```java
@ExtendWith(SpringExtension.class)
@ContextConfiguration
public class StoringJsr310LocalDateAsDateInPostgresIntegrationTests {

	@Autowired MyEntityRepository repository;

	@Test
	void foo() {

		LocalDate now = LocalDate.now();
		System.out.println(now);

		MyEntity firstEntity = repository.saveAndFlush(new MyEntity("test1", now));

		List<MyEntity> values = repository.findByValue("test1");

		assertThat(values).hasSize(1);
		assertThat(values).extracting(MyEntity::getDate).containsExactly(now);

		System.out.println(values.get(0));
	}

	@Entity
	@Table(name = "my_entity")
	@Data
	@NoArgsConstructor(access = AccessLevel.PROTECTED)
	static class MyEntity {

		@Id
		@GeneratedValue private Long id;

		String value;

		@Column(name = "local_date", columnDefinition = "DATE") //
		private LocalDate date;

		public MyEntity(String value, LocalDate date) {

			this.value = value;
			this.date = date;
		}
	}

	interface MyEntityRepository extends JpaRepository<MyEntity, Long> {

		List<MyEntity> findByValue(String value);
	}

	@Configuration
	@EnableJpaRepositories(basePackageClasses = MyEntityRepository.class, considerNestedRepositories = true,
			includeFilters = @ComponentScan.Filter(value = { MyEntityRepository.class }, type = FilterType.ASSIGNABLE_TYPE))
	@EnableTransactionManagement
	static class Config {

		@SuppressWarnings("resource")
		@Bean(initMethod = "start")
		public PostgreSQLContainer<?> container() {

			return new PostgreSQLContainer<>("postgres:9.6.12") //
					.withUsername("postgres");
		}

		@Bean
		public DataSource dataSource(PostgreSQLContainer<?> container) {

			PGSimpleDataSource dataSource = new PGSimpleDataSource();
			dataSource.setUrl(container.getJdbcUrl());
			dataSource.setUser(container.getUsername());
			dataSource.setPassword(container.getPassword());
			return dataSource;
		}

		@Bean
		public AbstractEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {

			LocalContainerEntityManagerFactoryBean factoryBean = new LocalContainerEntityManagerFactoryBean();
			factoryBean.setDataSource(dataSource);
			factoryBean.setPersistenceUnitRootLocation("simple-persistence");
			factoryBean.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
			factoryBean.setPackagesToScan(this.getClass().getPackage().getName(), Jsr310JpaConverters.class.getPackageName());

			Properties properties = new Properties();
			properties.setProperty("hibernate.hbm2ddl.auto", "create");
			properties.setProperty("hibernate.dialect", PostgreSQL91Dialect.class.getCanonicalName());
			factoryBean.setJpaProperties(properties);

			return factoryBean;
		}

		@Bean
		PlatformTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
			return new JpaTransactionManager(entityManagerFactory);
		}
	}
}
```
And it appears that this issue is no longer of any concern. The logs show that `java.time.LocalDate` values are properly being stored in a Postgres database (testcontainers) with no problem.
