### ISSUE TITLE
@Procedure can not return a ResultList using JPA 2.1 [DATAJPA-801]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1163]
**[ofbiz](https://jira.spring.io/secure/ViewProfile.jspa?name=ofbizbrazil)** opened **[DATAJPA-801](https://jira.spring.io/browse/DATAJPA-801?redirect=false)** and commented

If a procedure returns a select from a table, and if we try to map into a JPA repository, it gives error saying we do not have the output parameter specified. If a procedure does not have output parameters, so Spring Data should understand it and just map the result list into domain.

For example:

```java
interface TestRepository extends JpaRepository<Test, Serializable> {

    @Procedure(procedureName = "Test.dbo.calculate")
    Test calculate(final String type, final Integer id);
}
```

Via EclipseLink message error:

```
The CallableStatement.registerOutParameter(int, int, String method is not implemented.
```

Via Hibernate message error:

```
Caused by: java.sql.SQLException: Output parameters have not yet been processed. Call getMoreResults().
	at net.sourceforge.jtds.jdbc.ParamInfo.getOutValue(ParamInfo.java:159)
	at net.sourceforge.jtds.jdbc.JtdsCallableStatement.getOutputValue(JtdsCallableStatement.java:124)
	at net.sourceforge.jtds.jdbc.JtdsCallableStatement.getBytes(JtdsCallableStatement.java:271)
```

---

**Affects:** 1.9 GA (Gosling), 1.10.1 (Hopper SR1)

1 votes, 3 watchers

**Comment by mp911de** [comment]
Fixed via #1959
