### ISSUE TITLE
Verify return type matches the declared query

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1184]
**[Jacopo Carravieri](https://jira.spring.io/secure/ViewProfile.jspa?name=from.the.darkest.past)** opened **[DATAJPA-824](https://jira.spring.io/browse/DATAJPA-824?redirect=false)** and commented

When using a wrong query, that extracts only a portion of particular object

```java
// Home contains other fields
@Query("SELECT home.id, home.address FROM Home")
List<Home> findAll();
```

The framework silently casts the result to List\<Home>, but actually it turns out to be a List<Object[]>. As soon as a call to get() is made an exception is raised.

I would expect a ClassCastException or something similar thrown by the framework itself. I made some tests, it is possible to make such kind of casts only when the List is first instantiated without the template argument.

```java
// No complain
List list = new ArrayList();
list.add(new Object());
return (List<Home>) list;
```

---

**Affects:** 1.9.1 (Gosling SR1)

**Comment by gregturn** [comment]
Merged to `main`, backported to `3.1.x` and `3.0.x`.
