### ISSUE TITLE
Make synchronized block around a cached query optional [DATAJPA-841]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1199]
**[Milan Mimica](https://jira.spring.io/secure/ViewProfile.jspa?name=mmimica)** opened **[DATAJPA-841](https://jira.spring.io/browse/DATAJPA-841?redirect=false)** and commented

It turns out that in my application the following synchronized block is a major bottleneck. Most of application's business logic consists of spring data jpa queries, and it runs them in multiple threads, and that's where contentions occur.

`PartTreeJpaQuery$QueryPreparer.createQuery(CriteriaQuery<?>)`

```java
		private TypedQuery<?> createQuery(CriteriaQuery<?> criteriaQuery) {

			if (this.cachedCriteriaQuery != null) {
				synchronized (this.cachedCriteriaQuery) {
					return getEntityManager().createQuery(criteriaQuery);
				}
			}

			return getEntityManager().createQuery(criteriaQuery);
		}
```

I do understand why this was introduced in [DATAJPA-396](https://jira.spring.io/browse/DATAJPA-396), but I find it unfair to have this lock here just because one JPA provider is found to be (legitimately) thread-unsafe. I have managed to divert JPA queries to an in-memory cache, by intercepting calls to hibernate so I'm not using hibernate at all. I can guarantee that my implementation is thread-safe, I just need a way to bypass this synchronization somehow. I still do want query caching feature though

---
No further details from [DATAJPA-841](https://jira.spring.io/browse/DATAJPA-841?redirect=false)

**Comment by gregturn** [comment]
In light of #804 and the fact that this is a Hibernate issue (not Spring Data JPA), there is little we can do.
