### ISSUE TITLE
Query hints on repository methods do not support hints that allow duplicate values for the same name [DATAJPA-872]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1229]
**[David Spivey](https://jira.spring.io/secure/ViewProfile.jspa?name=dspivey1@gmail.com)** opened **[DATAJPA-872](https://jira.spring.io/browse/DATAJPA-872?redirect=false)** and commented

Query hints on repository methods are stored in a map before they are applied. Certain hints, like EclipseLink Batch Fetch, allow multiple values with the same name.

In SimpleJpaRepository.java -

```java
private void applyQueryHints(Query query) {

	for (Entry<String, Object> hint : getQueryHints().entrySet()) {
		query.setHint(hint.getKey(), hint.getValue());
	}
}
```

CrudMethodMetadataPostProcessor.java -

```java
private static Map<String, Object> findQueryHints(Method method) {

	Map<String, Object> queryHints = new HashMap<String, Object>();
	QueryHints queryHintsAnnotation = AnnotationUtils.findAnnotation(method, QueryHints.class);

	if (queryHintsAnnotation != null) {

		for (QueryHint hint : queryHintsAnnotation.value()) {
			queryHints.put(hint.name(), hint.value());
		}
	}

	QueryHint queryHintAnnotation = AnnotationUtils.findAnnotation(method, QueryHint.class);

	if (queryHintAnnotation != null) {
		queryHints.put(queryHintAnnotation.name(), queryHintAnnotation.value());
	}

	return Collections.unmodifiableMap(queryHints);
}
```

Keeping each QueryHint in a list then parsing it out when applying the hint to the query seems like one solution.

---

**Affects:** 1.9.4 (Gosling SR4)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/426

4 votes, 6 watchers

**Comment by MelleD** [comment]
How do the QueryHints work for findById? Only the last entry is still transferred when you use multiple eclipselink.left-join-fetch as key

SimpleJpaRepository
```
Map<String, Object> hints = new HashMap<>();
		getQueryHints().withFetchGraphs(em).forEach(hints::put);

		return Optional.ofNullable(type == null ? em.find(domainType, id, hints) : 
```
