### ISSUE TITLE
CDI extension conflicts with other Spring Data modules [DATAJPA-875]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1232]
**[Bartek](https://jira.spring.io/secure/ViewProfile.jspa?name=bg_eagle)** opened **[DATAJPA-875](https://jira.spring.io/browse/DATAJPA-875?redirect=false)** and commented

CDI extension does not allow for existence of two different Spring data modules - checked for Spring Data Jpa and Solr, but it looks like the problem is general.

CDI extension looks for every interface extending Repository interface and registers a new repository bean for each found interface without checking the specific repository type related to a concrete Spring Data Module. Each Spring Data module registers a separate CDI extension and do the same processing, trying to register beans specific to that module but including interfaces that are designed for other modules, eg JpaRepositoryExtension processes an interface extending SolrRepository and SolrRepositoryExtension processes an interface extending JpaRepository.

We couldn't find any way to configure this process in CDI environment. We use a simple work around which works for Us but needs replacing files in jars (e.g.  javax.enterprise.inject.spi.Extension and extension classes)  and publishing fix artifacts when We need upgrade version of a Spring data module.

In the code We create a copy of extension class e.g. JpaRepositoryExtensionFix as a copy of JpaRepositoryExtension and make a small change in the method:
void afterBeanDiscovery(`@Observes` AfterBeanDiscovery afterBeanDiscovery, BeanManager beanManager)
we add additional check in the main loop:
if (JpaRepository.class.isAssignableFrom(repositoryType))

final code is:

```java
	void afterBeanDiscovery(@Observes AfterBeanDiscovery afterBeanDiscovery, BeanManager beanManager) {

		for (Map.Entry<Class<?>, Set<Annotation>> entry : getRepositoryTypes()) {

			Class<?> repositoryType = entry.getKey();
			if (JpaRepository.class.isAssignableFrom(repositoryType)) {
				Set<Annotation> qualifiers = entry.getValue();

				// Create the bean representing the repository.
				CdiRepositoryBean<?> repositoryBean = createRepositoryBean(repositoryType, qualifiers, beanManager);
				LOGGER.info("Registering bean for '{}' with qualifiers {}.", repositoryType.getName(), qualifiers);

				// Register the bean to the extension and the container.
				registerBean(repositoryBean);
				afterBeanDiscovery.addBean(repositoryBean);
			}
		}
	}

```

More generic solution could incldue changes in spring-data-commons – org.springframework.data.repository.cdi.CdiRepositoryExtensionSupport class, methods: isRepository, processAnnotatedType.

I have made a similar bug in Solr module: [DATASOLR-286](https://jira.spring.io/browse/DATASOLR-286)

---

**Affects:** 1.9.4 (Gosling SR4)

**Issue Links:**
- [DATASOLR-286](https://jira.spring.io/browse/DATASOLR-286) CDI extension conflicts with other Spring Data modules

**Comment by gregturn** [comment]
Closing based on recommended solution from @mp911de.
