### ISSUE TITLE
java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [XXX] on this ManagedType [DATAJPA-890]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1247]
**[Andrei Navrotski](https://jira.spring.io/secure/ViewProfile.jspa?name=_andrei_n_)** opened **[DATAJPA-890](https://jira.spring.io/browse/DATAJPA-890?redirect=false)** and commented

In our project we have such JPA entity:
`@Entity`
`@Table`(name = "orders")
public class Order {

    @EmbeddedId
    private OrderPrimaryKey id;
    
    @Column(name = "last_modified_time")
    private Date lastModifiedTime;
    
    @Transient
    private final Set<Item> items = new HashSet<>();
    
    public Order() {
        // TODO Auto-generated constructor stub
    }
    
    public PrimaryKey getPrimaryKey() {
        return id;
    }
    
    public Date getLastModifiedTime() {
        return lastModifiedTime;
    }
    
    @Override
    public List<EntitiesConnection> getConnections() {
    ...
    here is some logic, and this class doesn't have "connections" field.
    }

**Everything works fine with spring-data-jpa v. 1.9.4.RELEASE.**
But after upgrading to spring-data-jpa v. 1.10.1.RELEASE, spring fails to load application context with exception:
`Caused by: java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [connections] on this ManagedType [com.acme.Order]`

It seems that not only fields, but methods also are fetched as JPA entities.
Class annotation `@Access`(AccessType.FIELD) not helps.
Annotating method getConnections() with `@Transient` not helps also

---

**Affects:** 1.10.1 (Hopper SR1)

2 votes, 12 watchers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by barrychapman** [comment]
The join it is failing on is a `OneToMany`

**Comment by barrychapman** [comment]
The only thing I think that could be causing it, is that the base properties are inherited from a `MappedSuperClass` - that is the `Model` it is referring to in the first line.

**Comment by schauder** [comment]
We still need a reproducer in order to work on this.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by PAX523** [comment]
> **[codewitch](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49886)** commented
> 
> I am seeing a similar error and this is what it looks like:
> 
> I am getting an exception when creating a custom findBy method by a foreign key.
> 
> Entity class:
> 
> ```java
> @Entity
> @Getter
> @Setter
> public class Thread {
> 
>   private @Id @GeneratedValue Long id;
>   private String subject;
> 
>   @ManyToOne(fetch = FetchType.LAZY)
>   @JsonIgnore
>   private Classroom classroom;
> 
>   protected Thread() {}
> 
>   public Long getClassroomId() {
>     return this.classroom.getId();
>   }
> }
> ```
> 
>  
> 
> ThreadRepository class:
> 
>  
> 
> ```java
> public interface ThreadRepository extends CrudRepository<Thread, Long> {
>  List<Thread> findByClassroomId(Long id);
> }
> ```
> 
>  
> 
> I get the exception:
> 
> ```java
> java.lang.IllegalArgumentException: Unable to locate Attribute with the the given name [classroomId] on this ManagedType [com.futurerprood.unicycleservice.entity.threads.Thread]
> ```
> 
> But the exception goes away if I remove the `getClassroomId()` in the `Thread` class. I have this function so that the json serialization will pick up only the classroom id instead of the whole classroom object in an endpoint response.
> 
> Why is this function causing the foreign key unable to be found?

Was it not possible to reproduce the issue with this minimal example?

**Comment by schauder** [comment]
A reproducer is a complete project, preferable as a Github repository.
