### ISSUE TITLE
Select columns in query methods [DATAJPA-895]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1251]
**[cemo koc](https://jira.spring.io/secure/ViewProfile.jspa?name=cemokoc)** opened **[DATAJPA-895](https://jira.spring.io/browse/DATAJPA-895?redirect=false)** and commented

I am a big fan of query methods and I would like use to select necessary columns only for querying.

```java
@Query("SELECT b.buildName FROM Build b")
Set<String> findAllBuildNames();
```

What I want to do is something like this:

```java
Set<String> findWithBuildNameAll();
```

Maybe this sounds weird but I am sure you can find a better way than me.

Thanks

---

**Affects:** 1.10.1 (Hopper SR1)

1 votes, 2 watchers

**Comment by gregturn** [comment]
With a solution like this, there is little value offered by Spring Data.
