### ISSUE TITLE
Annotations CreatedDate, LastModifiedDate not run with java.time.LocalDateTime [DATAJPA-900]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1255]
**[Dario Scoppelletti](https://jira.spring.io/secure/ViewProfile.jspa?name=dario@scoppelletti.it)** opened **[DATAJPA-900](https://jira.spring.io/browse/DATAJPA-900?redirect=false)** and commented

If I define an entity property as LocalDateTime (Java 8) and apply CreatedDate or LastModifiedDate annotation, the database insertion fails with the following exception:

com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '\xAC\xED\x00\x05sr\x00\x0Djava.time.Ser\x95]\x84\xBA\x1B"H\xB2\x0C\x00\x00xpw\x0E\x05\x00\x00\x07\xE0\x05\x12\x08\x07"\x10\x08\x' for column 'last_modified_date' at row 1

The Spring Data JPA - Reference Documentation says:

For the annotations capturing the points in time can be used on properties of type JodaTimes DateTime, legacy Java Date and Calendar, JDK8 date/time types as well as long/Long

---

**Affects:** 1.10.1 (Hopper SR1)

**Attachments:**
- [example-900.tar.gz](https://jira.spring.io/secure/attachment/23408/example-900.tar.gz) (_4.43 kB_)
- [spring-data-examples.tar.gz](https://jira.spring.io/secure/attachment/23404/spring-data-examples.tar.gz) (_4.56 kB_)

1 votes, 4 watchers

**Comment by gregturn** [comment]
Based on comments from @odrotbohm, I'm closing this as invalid. Appears to be an invalid JPA configuration issue.
