### ISSUE TITLE
Add JpaSpecificationExecutor.delete(…) and ….deleteAll(…) [DATAJPA-907]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1262]
**[SPT Developer](https://jira.spring.io/secure/ViewProfile.jspa?name=hk)** opened **[DATAJPA-907](https://jira.spring.io/browse/DATAJPA-907?redirect=false)** and commented

I have to delete massive entities. And I cannot add `deleteByXxxxx(...)` to repository by some reason. So, I implemented `deleteAll(Specification)` myself for general-purpose. I think it would be nice that `JpaSpecificationExecutor` has `deleteAll(Specification)` interface.

Please consider this.

Example for `SimpleJpaRepository` (Worked with transaction)

```java
private EntityManager entityManager;
private Class<E> entityClass;

public int deleteAll(Specification<E> spec) {
	
	CriteriaBuilder builder = entityManager.getCriteriaBuilder();
	CriteriaDelete<E> query = builder.createCriteriaDelete(entityClass);
	
	Predicate predicate = spec.toPredicate(query.from(entityClass), null, builder);
	query.where(predicate);
	
	return entityManager.createQuery(query).executeUpdate();
}
```

---

2 votes, 3 watchers

**Comment by s-jepsen** [comment]
Any plans on implementing this anytime soon?
