### ISSUE TITLE
Issue of Repository output sql [DATAJPA-942]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1293]
**[Ben Li](https://jira.spring.io/secure/ViewProfile.jspa?name=benli)** opened **[DATAJPA-942](https://jira.spring.io/browse/DATAJPA-942?redirect=false)** and commented

I found an issue of spring data jpa. Details are as follow:

1. There are 3 Entities. Entity A (member variable: protected C c), EntityB (which extends A), and Entity C.
2. BRepository. List\<B> findAllByCAndName(C c, String name);

When execute the repo “findAllByCAndName(c,name)”, output sql like this:
“select b0_.id as id1_0_, b0_.c_id as c_id3_0_, b0_.name as name2_0_ from b b0_ left outer join c c1_ on b0_.c_id=c1_.id where **c1_.id**=? and b0_.name=?”

However, my expectation is “select b0_.id as id1_0_, b0_.c_id as c_id3_0_, b0_.name as name2_0_ from b b0_ left outer join c c1_ on b0_.c_id=c1_.id where **b0_.c_id**=? and b0_.name=?”

The difference between two sql might reduce the sql efficiency greatly. How to change the repo output sql from “where c1_.id=?” to “where b0_.c_id=?” ? Any suggestion will be appreciated.

Here is my demo project, please run it to recur the issue. We are looking forward to your reply. Thanks a lot

---

**Affects:** 1.9.4 (Gosling SR4)

**Attachments:**
- [demo.zip](https://jira.spring.io/secure/attachment/23492/demo.zip) (_136.09 kB_)

**Issue Links:**
- [DATAJPA-1076](https://jira.spring.io/browse/DATAJPA-1076) Use foreign key instead of joining the full table when possible
 (_**"is duplicated by"**_)

1 votes, 3 watchers

**Comment by gregturn** [comment]
If you modeled using `optional=true`, then as the javadocs read, "If set to false then a non-null relationship must always exist," this infers that `null` CAN be the case.

And this is what left outer join is for. Essentially, an optional match. 

Indeed, left outer joins CAN be more expensive. You have the chance of retrieving more data, which costs more in time and memory consumption. But fundamentally, you have to model things as they are and work on optimization after that.

If you wish to use the Criteria API to write your own hand-optimized queries, that's fine. But we can't optimize in this fashion AGAINST the modeling annotations of JPA.
