### ISSUE TITLE
Register converters for o.s.d.geo.Point from/to com.vividsolutions.jts.geom.Point when hibernate 5.2 is used. [DATAJPA-957]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1308]
**[Christoph Strobl](https://jira.spring.io/secure/ViewProfile.jspa?name=cstrobl)** opened **[DATAJPA-957](https://jira.spring.io/browse/DATAJPA-957?redirect=false)** and commented

---

**Reference URL:** http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#spatial-types

**Comment by gregturn** [comment]
For a library that is 12 years old and appearing dead, we aren't supporting this.
