### ISSUE TITLE
Specifications applies conditions in the wrong order [DATAJPA-959]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1309]
**[Triqui Galletas](https://jira.spring.io/secure/ViewProfile.jspa?name=triqui)** opened **[DATAJPA-959](https://jira.spring.io/browse/DATAJPA-959?redirect=false)** and commented

This may sound stupid but I think the method Specifications.and(final Specification\<T> other) should be written a bit differently.
These two lines should be swapped:

```java
Predicate otherPredicate = other == null ? null : other.toPredicate(root, query, builder);
Predicate thisPredicate = spec == null ? null : spec.toPredicate(root, query, builder);
```

The call to other.toPredicate should happen after the call to spec.toPredicate.
I'm not sure if there is a better way, but I use to have query.distinct(), query.join() and query.fetch() calls inside the toPredicate methods in some specifications, and in some cases I need to know if a join, for instance, has been already applied or not. The only way to know is if the toPredicate methods for every specification is called in the same order they were created.

For example I build a dynamic specification where I have this:

```java
public class mandatorySpecification {
    toPredicate(...) {
        Fetch child = root.fetch("child", JoinType.LEFT);
        return cb.equal(child.get("width"), 1024);
    }
}
```

And then I have some 'ifs' where I add more specifications that need to reference a property from that join.

```java
public class optionalSpecification {
    toPredicate(...) {
        Fetch child = getFetchOrJoin(root, "child");
        return cb.equal(child.get("height"), 768);
    }
}
```

My method getFetchOrJoin uses root.getJoins() and root.getFetches() to retrieve the already existing join, but it doesn't work if I add the first specification first and the second second. It only works if I add the second specification first and the first second.

This doesn't work:

```java
spec.and(mandatorySpecification());
if (something) {
    spec.and(optionalSpecification());
}
```

This works:

```java
if (something) {
    spec.and(optionalSpecification());
}
spec.and(mandatorySpecification());
```

---

**Affects:** 1.10.1 (Hopper SR1)

**Comment by pgv** [comment]
Thankfully. I finally updated my old project to a new version and now I see that someone smarter fixed this in [2146](https://github.com/spring-projects/spring-data-jpa/issues/2146).
Maybe you should change the resolution to 'fixed'
