### ISSUE TITLE
Slice support on JpaSpecificationExecutor [DATAJPA-961]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1311]
**[Ali Shahbour](https://jira.spring.io/secure/ViewProfile.jspa?name=shahbour)** opened **[DATAJPA-961](https://jira.spring.io/browse/DATAJPA-961?redirect=false)** and commented

Currently interface [JpaSpecificationExecutor](http://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaSpecificationExecutor.html)   expose the findAll as List and Page , so if you are querying on a very big table the count(*) will slow down the performance , i suggest to support Slice with Page same as in other Repositories .

---

**Reference URL:** http://stackoverflow.com/questions/39367046/slice-on-jpaspecificationexecutor/39389393#39389393

**Issue Links:**
- [DATAJPA-734](https://jira.spring.io/browse/DATAJPA-734) Provide a Slice based implementation of PagingAndSortingRepository

3 votes, 5 watchers

**Comment by mvdobrinin** [comment]
Would be really nice to have this. 👍

**Comment by gregturn** [comment]
Duplicate of #1107.

**Comment by jgslima** [comment]
@gregturn , could you give some directions regarding how to achieve a `Slice` return with a query based on a `Specification`?

In issue #1107, Thomas Darimong suggested this:

`Slice<BusinessObject> findAllBy(Pageable pageable);`

But this does not solve the requirement of getting a `Slice` from a `Specification`.

I tried here to just declare a method in my repository like this:

`Slice<BusinessObject> findAllBy(Specification<BusinessObject> spec, Pageable pageable);`

but this does not work (we get a `At least 1 parameter(s) provided but only 0 parameter(s) present in query.`) .

So is this really possible to achive? Would it be through some more advanced extension of the repository infra-structure?

Both dynamic queries an slicing without count are important features for many applications, so this is a valid concern.

Thank you.
