### ISSUE TITLE
Query Syntax error in Spring JPA pagination for native query [DATAJPA-987]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1333]
**[PRANESH RADHAKRISHNAN](https://jira.spring.io/secure/ViewProfile.jspa?name=pranesh002)** opened **[DATAJPA-987](https://jira.spring.io/browse/DATAJPA-987?redirect=false)** and commented

I am using Spring JPA with DB2, when i use paging repository and queries for second page it throws error.

This is the generated query

```sql
select * from ( select inner2_.*, rownumber() over(order by order of
inner2_) as rownumber_ from ( select db2DATAa0_.C_TYPE as col_0_0_, db2DATAa0_.H_PROC 
as col_1_0_, db2DATAa0_.N_VIN as col_2_0_, db2DATAa0_.I_CUST as
 col_3_0_ from DCU.V_RPT_DATA_HIST db2DATAa0_ where db2DATAa0_.REPORTID= '0H000488089'
 and (db2DATAa0_.C_TYPE='S' or db2DATAa0_.C_TYPE='N' or 
 db2DATAa0_.C_TYPE='A' or db2DATAa0_.C_TYPE='T') 
 order by db2DATAa0_.H_PROC desc fetch first 30 rows only ) as inner2_ ) 
as inner1_ where rownumber_ > 15 order by rownumber_
```

Error:

2719372 [2016-10-21 16:29:02,040] [RxCachedThreadScheduler-13] WARN  org.hibern
ate.engine.jdbc.spi.SqlExceptionHelper  - SQL Error: -199, SQLState: 42601
2719379 [2016-10-21 16:29:02,047] [RxCachedThreadScheduler-13] ERROR org.hibern
ate.engine.jdbc.spi.SqlExceptionHelper  - DB2 SQL Error: SQLCODE=-199, SQLSTATE=
42601, SQLERRMC=OF;??( [ DESC ASC NULLS RANGE CONCAT || / MICROSECONDS MICROSECO
ND, DRIVER=3.57.82

Any idea?

---

**Issue Links:**
- [DATAJPA-1406](https://jira.spring.io/browse/DATAJPA-1406) NativeQuery pageable sort with existing inner ORDER BY

1 votes, 3 watchers

**Comment by gregturn** [comment]
This situation appears too complicated for `QueryUtils` to handle, and we aren't likely to approve a change there that would meet your needs. Your best best moving forward may be to implement a custom implementation. Check out https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations for more details on how to hook such a solution into your repository.
