### ISSUE TITLE
Stored procederes with out parameters not working under oracle 11 + hibernate 5.0.11 [DATAJPA-996]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1341]
**[alephx](https://jira.spring.io/secure/ViewProfile.jspa?name=alephx@live.com)** opened **[DATAJPA-996](https://jira.spring.io/browse/DATAJPA-996?redirect=false)** and commented

After upgrading spring boot from 1.3 to 1.4 and hibernate from 4 to 5, stored procedure working earlier, now returns "PLS-00306: wrong number of types of arguments in call to YYYY".

Code is exactly the same as in reference documentation (5.4. Stored procedures), (only difference beside procedure and parameters names is other type of parameters - String instead of Integer ).

Little debugging shows change in hibernate 5 to using named parameters instead of position indexed as in 4.
But Spring Data JPA for returning out parameter passes name "out"
`static final String SYNTHETIC_OUTPUT_PARAMETER_NAME = "out"`
which differs from real procedure out parameter name, and as I guess is cause of error...

---

**Affects:** 1.10.4 (Hopper SR4)

2 votes, 5 watchers

**Comment by mp911de** [comment]
Is this still an issue?
