### ISSUE TITLE
PageableAdapter is not public [DATAJPA-1001]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1347]
**[Enrique Ruiz (DiSiD)](https://jira.spring.io/secure/ViewProfile.jspa?name=eruiz)** opened **[DATAJPA-1001](https://jira.spring.io/browse/DATAJPA-1001?redirect=false)** and commented

`PageableAdapter` is only visible inside the package it reside and it cannot be used as follows:

```java
@WebService(...)
public interface SomeWebService {

    @XmlJavaTypeAdapter(PageAdapter.class)
    @RequestWrapper(...)
    @ResponseWrapper(...)
    @WebMethod(...)
    @WebResult(...)
    public abstract Page<Pet> findByOwnerAndPageable(
        @WebParam(...) Owner owner, 
        @WebParam(...)
        @XmlJavaTypeAdapter(PageableAdapter.class)
        Pageable pageable);
}
```

I'm not sure if it isn't the way to use it or it is a bug.

---

**Affects:** 1.10.4 (Hopper SR4)

**Comment by gregturn** [comment]
`PageableAdapter` is an internal type used to support Spring Data Commons' JAXB support for marshaling/unmarshaling page requests. It's not meant for public consumption.
