### ISSUE TITLE
Projections with @Query don't work as expected when projecting to class [DATAJPA-1003]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1349]
**[Robert Hunt](https://jira.spring.io/secure/ViewProfile.jspa?name=roberthunt87@gmail.com)** opened **[DATAJPA-1003](https://jira.spring.io/browse/DATAJPA-1003?redirect=false)** and commented

When projecting to an `interface` everything seems to work as expected with the fields are being mapped correctly. When I attempt to project into a `class` (with a compatible constructor) it all seems work fine unless I use an `@Query` annotation where it fails with this exception:

```java
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.util.HashMap<?, ?>] to type [uk.co.rbrt.PersonSummaryClass]
```

```java
// works
PersonSummaryClass findPersonSummaryClassById(long id);
// doesn't work
@Query("SELECT name AS name, age AS age FROM Person WHERE id = :id")
PersonSummaryClass findPersonSummaryClassByIdQuery(@Param("id") long id);
```

Example Project: https://github.com/roberthunt/spring-data-query-projection

---

**Reference URL:** https://github.com/roberthunt/spring-data-query-projection

**Referenced from:** pull request https://github.com/spring-projects/spring-data-commons/pull/277

7 votes, 10 watchers

**Comment by mafei-dev** [comment]
you can use an interface with that property names like below 
`
public class StatisticsDTO {
  Long getCounts;
  BigDecimal getAmounts;
  Status getStatus;
}
`

**Comment by javaHelper** [comment]
Can we not use the Class based DTO rather than Interface based DTO. What's the solution?
