### ISSUE TITLE
No default ordering for pagination [DATAJPA-1010]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1355]
**[Moritz Becker](https://jira.spring.io/secure/ViewProfile.jspa?name=mobe)** opened **[DATAJPA-1010](https://jira.spring.io/browse/DATAJPA-1010?redirect=false)** and commented

Currently, no default ordering is applied for pagination methods like in `org.springframework.data.repository.PagingAndSortingRepository` causing indeterministic result ordering.

Default ordering could be done e.g. by entity id

---

**Affects:** 1.10.5 (Hopper SR5)

**Comment by gregturn** [comment]
Since adding sorting changes the behavior, and can induce potentially extra costs to a query, I don't think it's best to implement this. By default, queries don't have ordering applied, and the order is hence undecided. If ordering is key, it should really be decided by the developer.
