### ISSUE TITLE
Reduce log output for Travis build [DATAJPA-1015]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1360]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATAJPA-1015](https://jira.spring.io/browse/DATAJPA-1015?redirect=false)** and commented

---
No further details from [DATAJPA-1015](https://jira.spring.io/browse/DATAJPA-1015?redirect=false)

**Comment by gregturn** [comment]
This is no longer relevant since we don't use Travis anymore.
