### ISSUE TITLE
Support projections on query methods that take a dynamic query type (Specification or Querydsl Predicate) [DATAJPA-1033]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1378]
**[Sebastian Staudt](https://jira.spring.io/secure/ViewProfile.jspa?name=koraktor)** opened **[DATAJPA-1033](https://jira.spring.io/browse/DATAJPA-1033?redirect=false)** and commented

Currently there seems no (at least no obvious) way to mix projections and specifications.

```java
class ExampleRepository extends JpaRepository<Example, Integer>, JpaSpecificationExecutor<Example> {

    // Overriden from JpaRepository, just to show the whole picture
    // Works without problems
    @Override
    List<Example> findAll();

    // A bit odd, due to the "By", but works - see DATAJPA-680
    List<ExampleProjection> findAllProjectedBy();

    // Overriden from JpaRepository, just to show the whole picture
    // Works without problems
    @Override
    List<Example> findAll(Specification<Example> spec);

    // This would be great, but doesn't work.
    List<ExampleProjection> findAllProjectedBy(Specification<Example> spec);

}
```

A query method like the last above causes a `java.util.NoSuchElementException` inside `org.springframework.data.jpa.repository.query.CriteriaQueryParameterBinder#bind` during query. (Which may be another problem on its own.)

---

**Affects:** 2.0 M1 (Kay), 1.11 RC1 (Ingalls), 1.10.6 (Hopper SR6)

**Issue Links:**
- [DATAJPA-393](https://jira.spring.io/browse/DATAJPA-393) Add support for QueryDSL projections in JPA repositories

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/430

107 votes, 96 watchers

**Comment by 474846718** [comment]
i need this feature too. i search google to flow the problem it lead me here.
if the project maintainer could implement Spec with Projections that would be great thing for me. 
thank you!

**Comment by olantobi** [comment]
Do we have any update on this. Is it a WIP yet ? Thank you.

**Comment by alexandertsukanov** [comment]
Any updates to this feature?

**Comment by bilalahmed54** [comment]
Any update on this please?

**Comment by BESAFX** [comment]
Guys, since 3 years until now, i looking for this feature!

**Comment by masteryyh** [comment]
almost 6 years passed since this issue opened guys, any update now?

**Comment by ZaheerUdDeen** [comment]
We desperately need this.

**Comment by kth13** [comment]
This would be a really great feature. Would appreciate if Spring implements this

**Comment by puce77** [comment]
Also make sure expressions like the following work:
`select(cb.construct(MyValueClass.class,...`

**Comment by raghera** [comment]
Another thumbs up from me for implementing this.  We may consider stop using Specifications due to this.  I have tried the workaround on Github: https://github.com/pramoth/specification-with-projection
But it's not ideal, is not particularly active and seems incompatible with the latest versions of Springboot.

**Comment by ZaheerUdDeen** [comment]
@mp911de can you update us on this please ?

**Comment by mp911de** [comment]
Projection support for Querydsl was added with Spring Data JPA 2.6 via #2294. Projection support for the specification executor will be available in version 3.0, see #2274.

**Comment by gustavodecarli** [comment]
this case does not respect the UserDTO interface and returns the full User objects.is there any solution to this?

Page<UserDTO> findAll(Specification<Usuario> specification, Pageable pageable)

**Comment by Muhammad-Sherif** [comment]
there is a solution for this  
 public List<Integer> findIdsBySpecification(Specification<Order> specification) {
        CriteriaBuilder builder = entityManager.getCriteriaBuilder();
        CriteriaQuery<Integer> query = builder.createQuery(Integer.class);
        Root<Order> root = query.from(Order.class);
        query.select(root.get("id")).where(specification.toPredicate(root, query, builder));
        return entityManager.createQuery(query).getResultList();
    }
    Just replace Order model with ur model
