### ISSUE TITLE
Is it possible to create a custom converter for custom repository queries? [DATAJPA-1052]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1396]
**[Jonas Trevisan](https://jira.spring.io/secure/ViewProfile.jspa?name=jonhkr)** opened **[DATAJPA-1052](https://jira.spring.io/browse/DATAJPA-1052?redirect=false)** and commented

Hi,
I'm trying to return a custom object instead of the entity of the repository, but I'm getting an error saying that it is not possible to convert the database record to the type. Here are the details of the implementation:

```java
public interface UserRepository extends CrudRepository<User, UUID> {
   @Query("select sum(o.amount), o.currency from operation o join ... omitted ... group by o.currency ")
   List<Amount> getBalances(UUID id);
}
class Amount {
  private BigDecimal amount;
  private Currency currency;

 // Getters, setters and constructors
}
```

Is it possible to write a converter to convert the database result to the amount Type?

---
No further details from [DATAJPA-1052](https://jira.spring.io/browse/DATAJPA-1052?redirect=false)

**Comment by gregturn** [comment]
https://docs.spring.io/spring-data/jpa/docs/3.0.0-M6/reference/html/#projections contains all the various options for doing projections with Spring Data JPA.

Also see https://github.com/spring-projects/spring-data-jpa/commit/fea2a1a515f5bd9f87604ac80abc0d7b76054633 for details on class-based DTOs.
