### ISSUE TITLE
Sorting doesn't work for field alias [DATAJPA-1061]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1404]
**[Sergey Skryabin](https://jira.spring.io/secure/ViewProfile.jspa?name=skrser)** opened **[DATAJPA-1061](https://jira.spring.io/browse/DATAJPA-1061?redirect=false)** and commented

```java
    @Query("SELECT c.name AS n FROM cats c")
    List<String> findCats(Sort sort);
...
    findCats(new Sort("n"));
```

doesn't work ("The state field path 'c.n' cannot be resolved to a valid type."). Although

```java
    @Query("SELECT lower(c.name) AS n FROM cats c")
    List<String> findCats(Sort sort);
...
    findCats(new Sort("n"));
```

works fine.

http://docs.spring.io/spring-data/jpa/docs/1.11.x/reference/html/#jpa.query-methods.sorting
says: The properties actually used within the Order instances of Sort need to match to your domain model, which means they need to resolve to either a property **or an alias used within the query.**

---

**Affects:** 1.11 GA (Ingalls)

**Attachments:**
- [DATAJPA-1061.log](https://jira.spring.io/secure/attachment/23711/DATAJPA-1061.log) (_8.10 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/276

**Backported to:** [2.1.10 (Lovelace SR10)](https://github.com/spring-projects/spring-data-jpa/milestone/153?closed=1), [1.11.23 (Ingalls SR23)](https://github.com/spring-projects/spring-data-jpa/milestone/152?closed=1)

3 votes, 9 watchers

**Comment by abccbaandy** [comment]
still happen with 2.3.4
I have to use `JpaSort.unsafe( "(my_alias)")` to prevent Unknown column `my_table.my_alias` error.

**Comment by yalecason** [comment]
Looks like using a FUNCTION_PATTERN of `(?:\w+\s*\([\w\.,\s'=\(]+\)+)+\s+[as|AS]+\s+([\w\.]+)` would work in at least the case I've run into today.

**Comment by darioseidl** [comment]
As per the comments, I don't think this bug was fixed for all cases. Could this issue be reopened?

**Comment by schauder** [comment]
If there is still a problem please create a new issue.
