### ISSUE TITLE
Wasting a lot of memory in JpaMetamodel [DATAJPA-1062]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1405]
**[Gábor Pelládi](https://jira.spring.io/secure/ViewProfile.jspa?name=gabor.pelladi)** opened **[DATAJPA-1062](https://jira.spring.io/browse/DATAJPA-1062?redirect=false)** and commented

In [DATAJPA-929](https://jira.spring.io/browse/DATAJPA-929) you have created a wrapper around Metamodel to work around a Hibernate issue.
The problem is, that each JpaMetamodel instance stores all of the managedTypes in a collection. And each entity property has it's own JpaMetamodel instance.
In our system, we have more than 700 entities, and a lot of properties in those entities. This managedTypes is stored for each property separately. It takes 140 MB of heap just to store this same 700 element collection in multiple thousand copies.
This additional information should be stored only once per Metamodel, to avoid wasting 140 MB of memory

---

**Affects:** 1.10.5 (Hopper SR5)

**Issue Links:**
- [DATAJPA-1066](https://jira.spring.io/browse/DATAJPA-1066) Spring Data JPA OutOfMemoryError: GC overhead limit exceeded

1 votes, 1 watchers

**Comment by gregturn** [comment]
This type has been through extensive changes since first introduced, including wrapping the metadata with a Spring Data Commons `Lazy`.

If this continues to be a problem, feel free to let us know.
