### ISSUE TITLE
Implement a findAll(Specification, Pageable) that returns a Slice [DATAJPA-1063]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1406]
**[Michaël Leneveut](https://jira.spring.io/secure/ViewProfile.jspa?name=mleneveut)** opened **[DATAJPA-1063](https://jira.spring.io/browse/DATAJPA-1063?redirect=false)** and commented

Hi,

We can use a Slice to avoid a count request, but we can't use it with a Specification.

Page<> findAll(Specification, Pageable) exists.

It could be good to have a : Slice<> findAll(Specification, Pageable)

---

3 votes, 5 watchers

**Comment by gregturn** [comment]
`Page<T> findAll(@Nullable Specification<T> spec, Pageable pageable)` is the API you seek.

Given `public interface Page<T> extends Slice<T>` in Spring Data Commons, this is already available through casting.

On top of that, Spring Data supported using `Slice<T>` as the return type of custom finders.

```java
@NoRepositoryBean
public interface MappedTypeRepository<T extends AbstractMappedType> extends JpaRepository<T, Long> {

	@Query("SELECT o FROM #{#entityName} o where o.attribute1=:attribute1")
	Slice<T> findByAttribute1Custom(@Param("attribute1") String attribute1, Pageable pageable);
}
```

I just verified that this test repository works with existing test cases. So everything you need is already there.

**Comment by tuucan** [comment]
This usage seem to trigger an unnecessary count query. Since it's the point of using slices, can we also get around that?

**Comment by hedza06** [comment]
Why is this closed? 😄 Is reopened somewhere?

**Comment by schauder** [comment]
Comments on closed issues are likely to fall through all the filters. 
We also don't reopen issues, once a fix is released.

Please create a new issue if the original solution doesn't work for you.
