### ISSUE TITLE
QueryUtils.toOrders should take From instead of Root [DATAJPA-1068]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1411]
**[Istvan Ratkai](https://jira.spring.io/secure/ViewProfile.jspa?name=selindek)** opened **[DATAJPA-1068](https://jira.spring.io/browse/DATAJPA-1068?redirect=false)** and commented

QueryUtils is a abstract utility class with a private constructor, so it cannot be extended.

It has the following method:
public static List<javax.persistence.criteria.Order> toOrders(Sort sort, Root<?> root, CriteriaBuilder cb)

This method is quite useful and could be used from other classes, but it has an unnecessary strict type restriction. It should look like this:

public static List<javax.persistence.criteria.Order> toOrders(Sort sort, From\<?,?> from, CriteriaBuilder cb)

---
No further details from [DATAJPA-1068](https://jira.spring.io/browse/DATAJPA-1068?redirect=false)

**Comment by gregturn** [comment]
Fundamentally, we are not making any more changes to `QueryUtils` but instead putting it into read-only configuration barring any critical bugs.
