### ISSUE TITLE
QueryUtils detects wrong alias [DATAJPA-1088]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1429]
**[Nikolay Semykin](https://jira.spring.io/secure/ViewProfile.jspa?name=nsemykin)** opened **[DATAJPA-1088](https://jira.spring.io/browse/DATAJPA-1088?redirect=false)** and commented

I'm not sure if it is a bug or I misunderstand the meaning of alias. However, the description of the detectAlias method says that the alias belongs to the entity to be retrieved. But the ALIAS_MATCH regex looks for the alias of the Entity after "from" keyword, which is not inevitably the entity retrieved by the query.
E.g.:

```sql
select b from EntityA a inner join a.listObBs b where b.name = :name
```

The alias of this query will be "a" instead of "b", thus sorting provided by Pageable won't work as would add something like:

```sql
select b from EntityA a inner join a.listObBs b where b.name = :name order by a.name
```

You notice the query will order by the name of EntityA even though EntityA is not what the query retrieves. It should be:

```sql
select b from EntityA a inner join a.listObBs b where b.name = :name order by b.name
```

instead.

Excerpt from QueryUtils:

```java
/**
 * Resolves the alias for the entity to be retrieved from the given JPA query.
 * 
 * @param query
 * @return
 */
public static String detectAlias(String query) {

	Matcher matcher = ALIAS_MATCH.matcher(query);

	return matcher.find() ? matcher.group(2) : null;
}
```

---

1 votes, 2 watchers

**Comment by gregturn** [comment]
The alias is essentially the `FROM` alias, hence these tests offer the right responses:

```java
assertThat(detectAlias("select b from EntityA a inner join a.listObBs b where b.name = :name")).isEqualTo("a");
assertThat(detectAlias("SELECT c.name AS n FROM cats c")).isEqualTo("c");
```
