### ISSUE TITLE
Java 8ify EntityGraph calculation [DATAJPA-1093]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1434]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATAJPA-1093](https://jira.spring.io/browse/DATAJPA-1093?redirect=false)** and commented

---

**Issue Links:**
- [DATAJPA-1075](https://jira.spring.io/browse/DATAJPA-1075) Dynamic entity graphs may still omit subgraphs
 (_**"depends on"**_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/204

**Comment by gregturn** [comment]
Given this issue's related PR was closed, and that optimizing toward Java `Optional` is risky since it can be expensive on critical code paths, this issue is declined.
