### ISSUE TITLE
Switch to non-standard output folders of the APT plugin [DATAJPA-1106]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1447]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATAJPA-1106](https://jira.spring.io/browse/DATAJPA-1106?redirect=false)** and commented

---
No further details from [DATAJPA-1106](https://jira.spring.io/browse/DATAJPA-1106?redirect=false)

**Comment by gregturn** [comment]
This is no longer an issue being on maven-compiler-plugin `3.11.0`.
