### ISSUE TITLE
Enable usage of projections in QueryDslPredicateExecutor [DATAJPA-1119]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1463]
**[Simon Endele](https://jira.spring.io/secure/ViewProfile.jspa?name=sendele)** opened **[DATAJPA-1119](https://jira.spring.io/browse/DATAJPA-1119?redirect=false)** and commented

In a spontaneous conversation with Oliver Gierke at the JAX 2017 in Mainz recently we came up with the idea of using projections together with Querydsl, i.e. it would be cool if the `QueryDslPredicateExecutor` was able to return a projection.

Thanks a lot for the nice and helpful conversation btw. :)

---

**Issue Links:**
- [DATAJPA-393](https://jira.spring.io/browse/DATAJPA-393) Add support for QueryDSL projections in JPA repositories

**Comment by mp911de** [comment]
Fixed via #2294 (Fluent query API for Querydsl)
