### ISSUE TITLE
Auditable and Persistable interface improvements [DATAJPA-1199]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1534]
**[Douglass Parker](https://jira.spring.io/secure/ViewProfile.jspa?name=douglassparker)** opened **[DATAJPA-1199](https://jira.spring.io/browse/DATAJPA-1199?redirect=false)** and commented

Consider these interfaces:

```
public interface Identifiable<ID extends Serializable> { ID getId(); }

public interface Persistable<ID extends Serializable> extends Serializable {
	ID getId();
	boolean isNew();
}

public interface Auditable<U, ID extends Serializable> extends Persistable<ID> {
	U getCreatedBy();
	void setCreatedBy(final U createdBy);
	DateTime getCreatedDate();
	void setCreatedDate(final DateTime creationDate);
	U getLastModifiedBy();
	void setLastModifiedBy(final U lastModifiedBy);
	DateTime getLastModifiedDate();
	void setLastModifiedDate(final DateTime lastModifiedDate);
}
```

There is no logical reason for Auditable to extend Persistable.  They deal with separate concerns. If I want to implement Auditable, I have to implement Persistable. For JPA, the implementation of isNew() merely checks to see if the ID is null. This is of use only for generated keys.  It will always return true for user supplied, i.e. “natural” keys. I am familiar with the arguments that generated keys are preferable to natural keys, but sometimes we work with legacy tables where we have no choice.  Indeed, the whole concept of an object knowing its “newness”, i.e., its lack of persistence seems misplaced. That should be a concern of the repository.

As far as the Auditable interface goes, it uses Joda. It would be nice to parameterize this class to use any supported temporal types in java.util, java.sql, or java.time.

If starting from scratch, I would get rid of Persistable. To maintain backward compatibility, consider this:

```
//new interfaces 

//Not recommended, but needed for backward compatibility.
public interface NewAware {
	boolean isNew();
}
public interface Audited<U, D> {
	U getCreatedBy();
	void setCreatedBy(final U createdBy);
	D getCreatedDate();
	void setCreatedDate(final D creationDate);
	U getLastModifiedBy();
	void setLastModifiedBy(final U lastModifiedBy);
	D getLastModifiedDate();
	void setLastModifiedDate(final D lastModifiedDate);
}

//refactored interfaces
@Deprecated
public interface Persistable<ID extends Serializable>
    extends Identifiable<ID>, NewAware, Serializable {
}
@Deprecated
public interface Auditable<U, ID extends Serializable> 
    extends Identifiable<ID>, NewAware, Audited<DateTime>, Serializable {
}
```

All existing code would still work, but classes would be free to implement the three orthogonal concepts (identity, newness, and auditing) independently. One problem here is that there is no common base class or interface for the java.util and java.time dates. Type safety might be improved by making Audited an enum with an instance for each supported type.

I understand that I am looking at this with a JPA focus and there may be considerations in other Spring Data flavors that I have not considered.

---
No further details from [DATAJPA-1199](https://jira.spring.io/browse/DATAJPA-1199?redirect=false)

**Comment by gregturn** [comment]
These two types are from Spring Data Commons. And it's to serve persistent data stores. So trying to decouple them when all the subclassing entities (JPA or not) is kind of beside the point.

The criticisms regarding JodaTime have been taken care of, since they have moved to JSR-310 `java.time` types.

If someone wishes to revisit this topic, feel free to open a new ticket.

**Comment by onacit** [comment]
IMHO, this is a reasonable suggestion. The `Auditable` interface, as an another name, needs to be separated from the `Persistable` interface.
