### ISSUE TITLE
Remove plugin repository declaration [DATAJPA-1211]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1548]
**[Oliver Drotbohm](https://jira.spring.io/secure/ViewProfile.jspa?name=olivergierke)** opened **[DATAJPA-1211](https://jira.spring.io/browse/DATAJPA-1211?redirect=false)** and commented

---
No further details from [DATAJPA-1211](https://jira.spring.io/browse/DATAJPA-1211?redirect=false)

**Comment by gregturn** [comment]
@odrotbohm Is there something specific that needs to be pruned out of Spring Data JPA's build system?

**Comment by gregturn** [comment]
This is an old ticket and the build details have changed considerably since then. Closing.
