### ISSUE TITLE
spring jpa nested projection generating incorrect query [DATAJPA-1218]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1555]
**[Zain Mansoor](https://jira.spring.io/secure/ViewProfile.jspa?name=bcssp10)** opened **[DATAJPA-1218](https://jira.spring.io/browse/DATAJPA-1218?redirect=false)** and commented

Just check [this](https://stackoverflow.com/questions/47159647/spring-jpa-nested-projection-generating-incorrect-query) stackoverflow.com question

---

**Affects:** 1.11.8 (Ingalls SR8)

**Reference URL:** https://stackoverflow.com/questions/47159647/spring-jpa-nested-projection-generating-incorrect-query

**Comment by alkismavridis** [comment]
This is very surprising, especially seeing no solution 4 years later.
I always though that one of the main benefits of using projections was to fetch less data from the database.
Seems like this is not true. Or am I missing something?

**Comment by roma2341** [comment]
I thought I found a way to make Hibernate not so slow, but Hibernate is still a piece of junk. And I spent a bunch of time only to understand that "Projections" don't work.
