### ISSUE TITLE
FindFirst named queries don't use LIMIT when are used with EntityGraph [DATAJPA-1227]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1564]
**[Artem Saidanov](https://jira.spring.io/secure/ViewProfile.jspa?name=artemsaidanov)** opened **[DATAJPA-1227](https://jira.spring.io/browse/DATAJPA-1227?redirect=false)** and commented

Hello!
When you use named query with "findFirst", Spring creates query with "LIMIT" that depends on number that you write after "findFirst". But when you add "EntityGraph" annotation - Spring stops using "LIMIT" and takes all info from DB and then sorts it.
Please fix this bug, because this behavior can reduce performance of applications

---
No further details from [DATAJPA-1227](https://jira.spring.io/browse/DATAJPA-1227?redirect=false)

**Comment by mp911de** [comment]
Hibernate uses JOIN's for your fetchgraph to fetch the associated collection. Applying a `LIMIT` would materialize the result only partially. Please report that issue against Hibernate.
