### ISSUE TITLE
querydsl.packageSuffix messes with QueryDslJpaRepository [DATAJPA-1234]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1571]
**[Puneet Mehta](https://jira.spring.io/secure/ViewProfile.jspa?name=panih2o)** opened **[DATAJPA-1234](https://jira.spring.io/browse/DATAJPA-1234?redirect=false)** and commented

This https://github.com/querydsl/querydsl/issues/2219 captures the problem which was reported on QueryDSL github issues page

---

**Issue Links:**
- [DATACMNS-1235](https://jira.spring.io/browse/DATACMNS-1235) Additional implementations of EntityPathResolver for supporting Querydsls packageSuffix
 (_**"depends on"**_)
- [DATAJPA-1394](https://jira.spring.io/browse/DATAJPA-1394) Avoid repeated lookups of EntityPathResolver from JpaRepositoryFactory

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/239

**Comment by nschimek** [comment]
I am using QueryDSL 4.4.0 with Spring Boot 2.3.7.RELEASE and am still facing this issue.  Do I need to provide the suffix configuration somewhere else?

Plugin:
```
	<plugin>
		<groupId>com.mysema.maven</groupId>
		<artifactId>apt-maven-plugin</artifactId>
		<version>1.1.3</version>
		<executions>
			<execution>
				<goals>
					<goal>process</goal>
				</goals>
				<configuration>
					<outputDirectory>target/generated-sources/java</outputDirectory>
					<processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
					<options>
						<querydsl.packageSuffix>.querydsl</querydsl.packageSuffix>
					</options>
				</configuration>
			</execution>
		</executions>
	</plugin>
```

```
Caused by: java.lang.IllegalArgumentException: Did not find a query class com.transunion.daq.data_pulse_service.entity.QApplication for domain class com.transunion.daq.data_pulse_service.entity.Application!
	at org.springframework.data.querydsl.SimpleEntityPathResolver.createPath(SimpleEntityPathResolver.java:78) ~[spring-data-commons-2.3.6.RELEASE.jar:2.3.6.RELEASE]
	at org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor.<init>(QuerydslJpaPredicateExecutor.java:78) ~[spring-data-jpa-2.3.6.RELEASE.jar:2.3.6.RELEASE]

```

This was also happening with Spring Boot 2.2.5.RELEASE and QueryDSL 4.1.4.

**Comment by BrunoVandekerkhove** [comment]
Same error at my end but then with the use of `<querydsl.suffix>Ref</querydsl.suffix>` or `<querydsl.prefix></querydsl.prefix>`.

**Comment by schauder** [comment]
This issue is closed, if anybody still sees similar/the same issue, please create a new issue with a reproducer.

**Comment by mmm8955405** [comment]
How should querydsl-maven-plugin configure the q class?  When the q class and entity are not in the same package path.  Spring boot can work normally only under the same package

**Comment by mmm8955405** [comment]
I have no idea what the solution to this problem is
