### ISSUE TITLE
SpEL template behavior is inconsistent [DATAJPA-1266]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1597]
**[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** opened **[DATAJPA-1266](https://jira.spring.io/browse/DATAJPA-1266?redirect=false)** and commented

The following tests succeed when added to `ExpressionBasedStringQueryUnitTests`

```java
	@Test
	public void doesTemplatingWhenEntityNameSpelIsPresent() {

		StringQuery query = new ExpressionBasedStringQuery("select #{#entityName + 'Hallo'} from #{#entityName} u", metadata, SPEL_PARSER);

		assertThat(query.getQueryString(), is("select UserHallo from User u"));
	}

	@Test
	public void doesNotTemplatingWhenEntityNameSpelIsNotPresent() {

		StringQuery query = new ExpressionBasedStringQuery("select #{#entityName + 'Hallo'} from User u", metadata, SPEL_PARSER);

		assertThat(query.getQueryString(), is("select #{#entityName + 'Hallo'} from User u"));
	}

	@Test
	public void doesTemplatingWhenEntityNameSpelIsPresentForBindParameter() {

		StringQuery query = new ExpressionBasedStringQuery("select u from #{#entityName} u where name = :#{#something}", metadata, SPEL_PARSER);

		assertThat(query.getQueryString(), is("select u from User u where name = :"));
	}
```

We only apply templating if `#\{#entityName\`} is present in the query string. If we do so, we use the full-blown SpEL templating mechanism, i.e also other SpEL expressions get evaluated and replaced.

Also, SpEL expressions for bind parameters only get protected from this when they start with `?#` not when they start with `:#`

---
No further details from [DATAJPA-1266](https://jira.spring.io/browse/DATAJPA-1266?redirect=false)

**Comment by schauder** [comment]
I think the second should be `select UserHallo from User u`

**Comment by gregturn** [comment]
Merged to `main`. Backported to `3.1.x`.
