### ISSUE TITLE
Add Distinct support in repositories extending QueryDslPredicateExecutor [DATAJPA-1289]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1615]
**[Miguel Martín-Forero](https://jira.spring.io/secure/ViewProfile.jspa?name=miguel.martin@cycle-it.com)** opened **[DATAJPA-1289](https://jira.spring.io/browse/DATAJPA-1289?redirect=false)** and commented

The idea is to be able to have methods like findAllDistinct and countDistinct when extending QueryDslPredicateExecutor like the ones you have when extending Repository<T, ID> as [told by the documentation](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-creation).

I presume that this could be done extending QueryDslJpaRepository adding findAllDistinct overloaded methods which add distinct() to the JPQLQuery but it would be great to have this support integrated directly in QueryDslPredicateExecutor to avoid creating custom repositories

---

**Reference URL:** https://stackoverflow.com/questions/26712275/spring-data-jpa-querydslpredicateexecutor-find-distinct-results

3 votes, 3 watchers

**Comment by curena-contrast** [comment]
Bump, this would definitely be useful.
