### ISSUE TITLE
Rrepository query methods with 'join fetch' produce duplicated parent entities [DATAJPA-1299]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1623]
**[Sergei Poznanski](https://jira.spring.io/secure/ViewProfile.jspa?name=cepr0)** opened **[DATAJPA-1299](https://jira.spring.io/browse/DATAJPA-1299?redirect=false)** and commented

Repository query methods with 'join fetch' leads to the duplicate parents.
Number of duplicates corresponds to the number of nested children.

To work around this situation we can use 'distinct' in the query. But this still does not work with projections.

The similar methods with `@EntityGraph` work as expected.

Example:

```java
@Entity
class Parent extends BaseEntity {
	private String name;
	@OneToMany(mappedBy = "parent")
	private List<Child> children;
}

@Entity
class Child extends BaseEntity {
	private String name;
	@ManyToOne(fetch = LAZY)
	private Parent parent;
}

interface ParentProjection {
	Integer getId();
	String getName();
	List<Child> getChildren();
}

interface ParentRepo extends JpaRepository<Parent, Integer> {

	@EntityGraph(attributePaths = "children")
	@Override
	List<Parent> findAll(); // works as expected 

	@Query("select p from Parent p left join fetch p.children")
	List<Parent> findWithQuery(); // has duplicated parents
	
	@Query("select distinct p from Parent p left join fetch p.children")
   	List<Parent> findDistinctWithQuery(); // does not have duplicated parents
	
	@EntityGraph(attributePaths = "children")
	List<ParentProjection> findProjectionsBy(); // works as expected
		
	@Query("select distinct p from Parent p left join fetch p.children")
   	List<ParentProjection> findDistinctProjectionsWithQuery(); // has duplicated parents 
}
```

More tests is [here](https://github.com/Cepr0/duplicate-parent-entities/blob/master/src/test/java/io/github/cepr0/demo/repo/ParentRepoTest.java)

---

**Affects:** 2.0.5 (Kay SR5)

**Reference URL:** https://github.com/Cepr0/duplicate-parent-entities

1 votes, 4 watchers

**Comment by gregturn** [comment]
I'm afraid that according to the results from https://hibernate.atlassian.net/browse/HHH-12489, this is currently considered "Works as Designed" per the existing JPA specs.

If you wish to attempt to alter the specs, please visit https://github.com/eclipse-ee4j/jpa-api/issues/177 and upvote this proposed change. If this moves forward, feel free to come back and pursue changing Spring Data JPA in the future.
