### ISSUE TITLE
Supports findByFieldIgnoreCaseIn(Collection<> fieldValues) [DATAJPA-1303]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1627]
**[Kovalev Andrey](https://jira.spring.io/secure/ViewProfile.jspa?name=krupt)** opened **[DATAJPA-1303](https://jira.spring.io/browse/DATAJPA-1303?redirect=false)** and commented

We have some user entity:

```java
public class User {

  @Id
  @GeneratedValue
  private Long id;

  private String name;
}
```

We have unique index for column "name" based on upper function:

```
CREATE UNIQUE INDEX user_name_unique_idx ON user (UPPER(name));
```

We have repository with methods that finding users by name using index:

```java
public interface UserRepository extends JpaRepository<User, Long> {

  findOneByNameIgnoreCase(String name);

  findAllByNameIgnoreCaseIn(Collection<String> names);
}
```

Method findOneByNameIgnoreCase calls:

```sql
SELECT *
FROM user
WHERE upper(name) = upper(?);
```

But method findAllByNameIgnoreCaseIn calls:

```sql
SELECT *
FROM user
WHERE name IN (?, ?, ...);
```

---

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/261

**Comment by gregturn** [comment]
Duplicates #1053
