### ISSUE TITLE
Allow configuration of SqlResultSetMapping for native queries [DATAJPA-1354]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1674]
**[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** opened **[DATAJPA-1354](https://jira.spring.io/browse/DATAJPA-1354?redirect=false)** and commented

We need to add the ability to define the `SqlResultSetMapping` to be used in the `@Query` annotation. Only valid if `native` is set to `true`. Needs to short circuit the type selection algorithm and rather forward the name of the mapping to `em.createNativeQuery(…)`

---

**Issue Links:**
- [DATAJPA-1338](https://jira.spring.io/browse/DATAJPA-1338) Repository method with native query, that should return Optional\<Enum>, instead return Optional\<String>

1 votes, 2 watchers

**Comment by mp911de** [comment]
Fixed via #3155 in `@NativeQuery(sqlResultSetMapping=…)`
