### ISSUE TITLE
JpaRepository.getOne(ID id) method name is inconsistent with other xById(ID id) method names [DATAJPA-1377]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1697]
**[Nathan Niesen](https://jira.spring.io/secure/ViewProfile.jspa?name=nniesen)** opened **[DATAJPA-1377](https://jira.spring.io/browse/DATAJPA-1377?redirect=false)** and commented

The other JpaRepository xOne(ID id) methods were changed to xById(ID id) but the getOne method was not

---

**Affects:** 2.0.8 (Kay SR8)

**Comment by JesseW28** [comment]
I would like to start contributing to this issue.

**Comment by mp911de** [comment]
@JesseW28 feel free to submit a pull request to update the signature in a non-breaking way (i.e. deprecating `getOne`). That method is an oversight during our Java 8 migration.
