### ISSUE TITLE
EntityManagerBeanDefinitionRegistrarPostProcessor should implement Ordered [DATAJPA-1380]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1700]
**[Dave Syer](https://jira.spring.io/secure/ViewProfile.jspa?name=david_syer)** opened **[DATAJPA-1380](https://jira.spring.io/browse/DATAJPA-1380?redirect=false)** and commented

`EntityManagerBeanDefinitionRegistrarPostProcessor` is a `BeanFactoryPostProcessor` that creates and registers bean definitions. To allow other `BeanFactoryPostProcessors` to see those bean definitions and have a chance to post process them, it should either implement `Ordered` or `BeanDefinitionRegistryPostProcessor`

---

**Affects:** 2.0.8 (Kay SR8)

**Referenced from:** commits https://github.com/spring-projects/spring-data-jpa/commit/99b946563a7caa48bad166cc534eea8f0f4a1c11

**Comment by gregturn** [comment]
This was resolved in https://github.com/spring-projects/spring-data-jpa/commit/99b946563a7caa48bad166cc534eea8f0f4a1c11.
