### ISSUE TITLE
Is Null query does not return entities [DATAJPA-1404]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1722]
**[Arlo O'Keeffe](https://jira.spring.io/secure/ViewProfile.jspa?name=arlo)** opened **[DATAJPA-1404](https://jira.spring.io/browse/DATAJPA-1404?redirect=false)** and commented

In a scenario where two `@Entity`'s are connected by `@OneToOne` the created query for an findByOtherIsNull is not correct. This is demonstrated in the attached reproduction project.

Given the following (redacted) setup:

```java
@Entity
public class StorageLocation {

  @Id
  @GeneratedValue
  private Long id;

  @OneToOne(fetch = FetchType.LAZY, mappedBy = "storageLocation")
  private Item item;

}

@Entity
public class Item {

  @Id
  @GeneratedValue
  private Long id;

  @OneToOne(fetch = FetchType.LAZY)
  private StorageLocation storageLocation;

}

@Repository
public interface StorageLocationRepository extends CrudRepository<StorageLocation, Long> {

  Iterable<StorageLocation> findByItemIsNull();

}
```

findByItemIsNull() will never return a StorageLocation because the resulting query is:

```sql
select storageloc0_.id as id1_1_ from storage_location storageloc0_ where storageloc0_.id is null
```

I have gone back in the spring-data-jpa versions and found that the issue was introduced in 2.0.8 and 1.11.13. If you manually set the spring-data-jpa version to 2.0.7 the query looks like this

```sql
select storageloc0_.id as id1_1_ from storage_location storageloc0_ left outer join item item1_ on storageloc0_.id=item1_.storage_location_id where item1_.id is null
```

Please let me know if I can be of more assistance

---

**Affects:** 1.11.14 (Ingalls SR14), 2.0.9 (Kay SR9)

**Reference URL:** https://github.com/ArloL/spring-data-jpa-isnull-demo

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/304

**Backported to:** [2.1.6 (Lovelace SR6)](https://github.com/spring-projects/spring-data-jpa/milestone/141?closed=1), [2.0.14 (Kay SR14)](https://github.com/spring-projects/spring-data-jpa/milestone/139?closed=1)

6 votes, 5 watchers

**Comment by membersound** [comment]
I could work around  this issue with `findByItemIdIsNull()`. Note the Item**Id** change.
