### ISSUE TITLE
Add support for IFNULL in Sort/Order [DATAJPA-1413]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1728]
**[Bruno](https://jira.spring.io/secure/ViewProfile.jspa?name=bruno.vilhena)** opened **[DATAJPA-1413](https://jira.spring.io/browse/DATAJPA-1413?redirect=false)** and commented

For queries of the following nature:

**_select * from [a_table] order by IFNULL(update_date, create_date) DESC;_**

**Currently with org.springframework.data.domain.Sort.Order there's no way of implementing this type of ordering.

JQL accepts IFNULL, so this ought to be possible?

---
No further details from [DATAJPA-1413](https://jira.spring.io/browse/DATAJPA-1413?redirect=false)

**Comment by gregturn** [comment]
`IFNULL` is not covered including special functions in JPA's section 4.9. And as @odrotbohm has said, that affords us no API to reach for.

If your code is working with it, then it may be a special feature of your JPA provider (Hibernate?) and not something we can handle.
