### ISSUE TITLE
Using class based projections throws ConverterNotFoundException in SB 2.0.x [DATAJPA-1414]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1729]
**[Sergei Poznanski](https://jira.spring.io/secure/ViewProfile.jspa?name=cepr0)** opened **[DATAJPA-1414](https://jira.spring.io/browse/DATAJPA-1414?redirect=false)** and commented

In SB 2.0.x class based projections don't work as [expected](https://github.com/spring-projects/spring-data-examples/blob/586c3d512021af382c348923a0c2851fb57ded59/jpa/example/src/main/java/example/springdata/jpa/projections/CustomerRepository.java#L58). Using them leads to the exception:

`org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.example.MyEntity] to type [com.example.MyEntityDto]`

See my [example](https://github.com/Cepr0/sd-jpa-projections/blob/5f8cc6a567ceb65963bff1aa66e576eb223b45b0/src/test/java/io/github/cepr0/projections/ProjectionTests.java#L55) which works in SB 1.5.x, and doesn't work in SB 2.0.4.

[SB 1.5.x example](https://github.com/Cepr0/sd-jpa-projections/tree/SB1.5.x)

[SB 2.0.x example](https://github.com/Cepr0/sd-jpa-projections/tree/SB2.0.4)

---

**Affects:** 2.0.9 (Kay SR9)

**Reference URL:** https://github.com/Cepr0/sd-jpa-projections

2 votes, 3 watchers

**Comment by eltonbfw** [comment]
me too

**Comment by Sun26-Avrin** [comment]
that's why it doesn't work at all...

**Comment by gregturn** [comment]
Class-based projections, in general, don't work with Spring Data JPA. JPQL **will** work with constructor expressions (see https://github.com/spring-projects/spring-data-jpa/commit/fea2a1a515f5bd9f87604ac80abc0d7b76054633), but native queries won't work at all.
