### ISSUE TITLE
Java 8 Stream on JpaSpecificationExecutor with @QueryHint fetchSize support [DATAJPA-1438]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1752]
**[László Csatlós](https://jira.spring.io/secure/ViewProfile.jspa?name=plutoz)** opened **[DATAJPA-1438](https://jira.spring.io/browse/DATAJPA-1438?redirect=false)** and commented

Actual method `findAll(Specification<T> spec)` on interface `JpaSpecificationExecutor<T>` can return only with `List` or `Page` but not with `Stream<T>`.

This would be useful for huge resultSets combined with `@QueryHint(name="org.hibernate.fetchSize", value="50" )` to truly benefit the power of streaming concept and not to exhaust all of the JVM memory. Hibernate already has the capability to do this with `ScrollableResults`:

```java
Query query = session.createQuery(query);
query.setReadOnly(true);
query.setFetchSize(100);
ScrollableResults results = query.scroll(ScrollMode.FORWARD_ONLY);
```

If ambiguous method name is a problem (mentioned at [DATAJPA-906](https://jira.spring.io/browse/DATAJPA-906)), then a
`Stream<T> streamAll(Specification<T> spec, Long fetchSize)`
signiture would also perfect

---

2 votes, 3 watchers

**Comment by schauder** [comment]
This issue will eventually offer a solution based on Querydsl https://github.com/spring-projects/spring-data-commons/pull/2421
