### ISSUE TITLE
Documentation mistake [DATAJPA-1444]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1761]
**[liangxiong3403](https://jira.spring.io/secure/ViewProfile.jspa?name=liangxiong3403)** opened **[DATAJPA-1444](https://jira.spring.io/browse/DATAJPA-1444?redirect=false)** and commented

Section:Web Databinding Support

Content:Spring Data projections (described in Projections) can be used to bind incoming request payloads by either using JSONPath expressions (requires Jayway JsonPath or XPath expressions (requires XmlBeam), as shown in the following example.

What I think it should be :I think there losed a  'right parentheses' after Jayway JsonPath,It should be Spring Data projections (described in Projections) can be used to bind incoming request payloads by either using JSONPath expressions (requires Jayway JsonPath) or XPath expressions (requires XmlBeam), as shown in the following example.

I don't know whether i am right,but i just confused

---

**Affects:** 1.11.16 (Ingalls SR16)

**Reference URL:** https://docs.spring.io/spring-data/jpa/docs/1.11.16.RELEASE/reference/html

**Comment by gregturn** [comment]
See https://github.com/spring-projects/spring-data-commons/issues/2629.
