### ISSUE TITLE
Spring Data JPA depends on aspectjrt [DATAJPA-1456]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1776]
**[Matej Spiller-Muys](https://jira.spring.io/secure/ViewProfile.jspa?name=mspiller)** opened **[DATAJPA-1456](https://jira.spring.io/browse/DATAJPA-1456?redirect=false)** and commented

Spring Data JPA depends on the aspectjrt. On the other hand spring-aspects depends on aspectjweaver. aspectjweaver is a superset of aspectjrt.

The problem is when using modular java (or any duplicate classes checker), because it complains that duplicate classes in the same packages are presented on classpath. Using jigsaw this is no longer allowed.

Error generated from InteliJ IDE:
Error:java: module XYZZZ reads package org.aspectj.internal.lang.reflect from both org.aspectj.runtime and org.aspectj.weaver

I propose changing to the aspectjweaver based on [SPR-8896](https://jira.spring.io/browse/SPR-8896)

---

**Affects:** 2.1.2 (Lovelace SR2)

**Comment by gregturn** [comment]
This was solved in https://github.com/spring-projects/spring-data-jpa/commit/80669a5ffdff0fe0897ebe2d36a70d0d8d29cdb4.
