### ISSUE TITLE
Multiple Sequence Generators [DATAJPA-1507]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1819]
**[Gleydson Lima](https://jira.spring.io/secure/ViewProfile.jspa?name=gleydson)** opened **[DATAJPA-1507](https://jira.spring.io/browse/DATAJPA-1507?redirect=false)** and commented

I'm migrating project from Spring 4.x, Sprint boot 1.x to latest version of Spring Boot, Spring JPA and Spring Core.

In my JPA entities we have  definition of different sequence generators of the same sequence (hibernate_sequence):

!image-2019-02-25-20-46-47-958.png|width=1083,height=144!

Another class:

!image-2019-02-25-20-47-30-754.png|width=872,height=142!

 

When I try to start up the project I got the following error:

Caused by: org.hibernate.HibernateException: Multiple references to database sequence [hibernate_sequence] were encountered attempting to set conflicting values for 'increment size'.  Found [1] and [50]

 

Actually, I know that this definition of SequenceGenerator is unnecessary, but this definition already exists in my project and there are no allocationSizes in SequenceGenerator. The exception thrown says that we have to increment size, but it's not true.

I think that the problem is multiples definition of the SequenceGenerator regardless of the incrementSize.   I think this is a BUG but all definitions of SequenceGenerator doesn't define any incrementSize and uses the default value.

 

 

---

**Affects:** 2.1.5 (Lovelace SR5)

**Attachments:**
- [image-2019-02-25-20-46-47-958.png](https://jira.spring.io/secure/attachment/26188/image-2019-02-25-20-46-47-958.png) (_52.70 kB_)
- [image-2019-02-25-20-47-30-754.png](https://jira.spring.io/secure/attachment/26187/image-2019-02-25-20-47-30-754.png) (_46.38 kB_)
- [image-2019-02-25-20-48-05-905.png](https://jira.spring.io/secure/attachment/26186/image-2019-02-25-20-48-05-905.png) (_46.38 kB_)

**Comment by ripu502-deloitte** [comment]
I too have similar problem. were you able to fix this.

**Comment by schauder** [comment]
This is outside the scope of Spring Data JPA.
Schema generation is handled by Hibernate or whatever JPA implementation you use.
