### ISSUE TITLE
Improve Documentation to list variables supported by SpEL in Spring Data JPA [DATAJPA-1516]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1828]
**[MICHAEL L JOHNSON](https://jira.spring.io/secure/ViewProfile.jspa?name=mljohns89)** opened **[DATAJPA-1516](https://jira.spring.io/browse/DATAJPA-1516?redirect=false)** and commented

On the documentation website:  https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query.spel-expressions

It specifies that SpEL supports only a predefined set of variables:

As of Spring Data JPA release 1.4, we support the usage of restricted SpEL template expressions in manually defined queries that are defined with `@Query`. Upon query execution, these expressions are evaluated against a predefined set of variables. 

 

But it does not specify an exhaustive list of what these variables are.  In the documentation, it gives "entityName" as one example.  Through Googling, I found "principal" as another.  Are these the only two or are there more?

---
No further details from [DATAJPA-1516](https://jira.spring.io/browse/DATAJPA-1516?redirect=false)

**Comment by gregturn** [comment]
Closing as we don't need to track an exhaustive list and the OP signaled it was okay his end.
