### ISSUE TITLE
Select / Multiselect Not Working with toPredicate method of Specification [DATAJPA-1532]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1842]
**[Swapnil Vaidya](https://jira.spring.io/secure/ViewProfile.jspa?name=svaidya401)** opened **[DATAJPA-1532](https://jira.spring.io/browse/DATAJPA-1532?redirect=false)** and commented

Select clause in JPA Specification is returning the entire object. Please refer to the code snippet - 

```java
public class TodoSpecifications implements Specification<TodoEntity> {
    @Override
    public Predicate toPredicate(
        Root<LocationEntity> root, CriteriaQuery<?> query, CriteriaBuilder criteriaBuilder) {
        List<Predicate> predicateList = createPredicateList(root, criteriaBuilder);
        return query.multiselect(
                root.get("id"), 
                root.get("name")).where(
                        criteriaBuilder.and(predicateList.toArray(new Predicate[] {})
                )
            ).getRestriction();
    }
}
```

 

And I am Calling this from - 

```java
TodoSpecifications todoSpecifications = new TodoSpecifications();

Page<TodoEntity> todoPageList = todoRepository.findAll(todoSpecifications, pageRequest);
List<TodoEntity> todoEntityList =  todoRepository.findAll(todoSpecifications, sort);
```

---

**Issue Links:**
- [DATAJPA-1189](https://jira.spring.io/browse/DATAJPA-1189) Dynamic projections in combination with Specifications and Pagination not working
 (_**"duplicates"**_)

**Comment by CarlosTTRR** [comment]
[Swapnil Vaidya](https://jira.spring.io/secure/ViewProfile.jspa?name=svaidya401) have you found a solution for this?
