### ISSUE TITLE
Unexpected token count in with Pageable [DATAJPA-1598]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1869]
**[Phil Webb](https://jira.spring.io/secure/ViewProfile.jspa?name=pwebb)** opened **[DATAJPA-1598](https://jira.spring.io/browse/DATAJPA-1598?redirect=false)** and commented

Originally raised in https://github.com/spring-projects/spring-boot/issues/17961 but this looks like a Spring Data issue. I'll ask the OP for more info.

&mdash;

After upgrading spring boot to 2.1.7  from 2.1.6, running application are failing due to the issue:

```
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: count near line 1, column 8 [select count(new map(model as levelTingkat)) from com.jasamedika.medifirst2000.entity.LevelTingkat model left join model.id id  where id.kdProfile=:kdProfile  and model.statusEnabled=true  ]
```

```java
public interface  interface LevelTingkatDao extends CrudRepository.
```

```
Query : "select new map(model as levelTingkat) " 
            + " from LevelTingkat model left join model.id id "
            + " where id.kdProfile=:kdProfile "
            + " and model.statusEnabled=true  "
```

```
method: Page<Map<String, Object>> findAllList(
            @Param("kdProfile") Integer kdProfile,
            Pageable pageable);
```

In new `CrudRepository`,  it seem, has adding "count" to Query HQL, because present of `Pageable` parameter.

---

0 votes, 5 watchers

**Comment by geferon** [comment]
This issue is still persistent and slightly annoying, any news about it?

**Comment by rpastoruma** [comment]
Hi, is this problem fixed in the new JPA versions?

**Comment by rpastoruma** [comment]
This issue does not appears when the constructor has more than one parameter. As a provisional solution you can make a DTO constructor with one dummy parameter like this:

`    public LogDTO(Log l, Boolean dummy)
    {  
         this(l); 
    }
`

And then in the query you can do the following:

`@Query("SELECT new test.model.dto.LogDTO(x, true) FROM Log x WHERE ...`

**Comment by khwilo** [comment]
Having the DTO with more than one constructor parameter seems to solve the issue.

**Comment by gregturn** [comment]
This no longer seems to be a problem:

```java
class FirstNameDto {

	private String firstname;

	public FirstNameDto(String firstname) {
		this.firstname = firstname;
	}
}
```

```java
@Query("SELECT new org.springframework.data.jpa.repository.sample.FirstNameDto(u.firstname) from User u where u.firstname = :firstname")
List<FirstNameDto> findByNamedQueryWithSingleConstructor(@Param("firstname") String firstname);
```

```java
@Test
void executesNamedQueryWithSingleConstructorExpression() {
	userRepository.findByNamedQueryWithSingleConstructor("Dave");
}
```
This runs green on Spring Data JPA's `main` branch. I've coded a commit with this test case.

**Comment by gregturn** [comment]
Actually confirmed. There is an escape clause built up around `select distinct new com.example.User(...`. This thing doesn't properly handle `select new com.example.User(...` for single-arg situations.

**Comment by gregturn** [comment]
Backported to `2.7.x`

**Comment by pablogalegoc** [comment]
@gregturn thanks for the fix! These days we found a corner case that I believe still triggered this bug with one of our queries This is a simplified version of what we had:
```java
  @Query("SELECT DISTINCT NEW versionDTO(thing.version)"
      + " FROM Thing thing"
      + " WHERE thing.id = :id ORDER BY thing.version ASC")
  List<VersionDTO> findVersion(@Param("id") UUID id);
```
So when we wanted to paged it, just by
```diff
+   Page<VersionDTO> findVersion(@Param("id") UUID id, Pageable pageable);
-   List<VersionDTO> findVersion(@Param("id") UUID id);
```
We got `Caused by: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: NEW near line 1, column 23 [select count(DISTINCT NEW ...` that could be workarounded by changing `NEW` to `new`:
```diff
+  @Query("SELECT DISTINCT NEW versionDTO(thing.version)"
-  @Query("SELECT DISTINCT new versionDTO(thing.version)"
```
It's not a big deal but one can't guess it quickly by the error message. IMO, the escape clauses would need a `toLowerCase` before `startsWith`.
