### ISSUE TITLE
saveAndFlush could accept iterable as well [DATAJPA-1574]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1883]
**[Vladimir Nemergut](https://jira.spring.io/secure/ViewProfile.jspa?name=vlado_nemo)** opened **[DATAJPA-1574](https://jira.spring.io/browse/DATAJPA-1574?redirect=false)** and commented

JpaRepository interface only has saveAndFlush method that takes a single instance.

\<S extends T> S saveAndFlush(S var1)

Would be handy if an overloaded method exists that takes the iterable, similar to save method, e.g.:

\<S extends T> List\<S> saveAndFlush(Iterable\<S> var1)

\<S extends T> List\<S> save(Iterable\<S> var1);

---
No further details from [DATAJPA-1574](https://jira.spring.io/browse/DATAJPA-1574?redirect=false)

**Comment by SKrabbenborg** [comment]
Hi, I would like to start contributing and this seems like a good issue to start with.

**Comment by mp911de** [comment]
Thanks for letting us know, @SKrabbenborg. Feel free to submit a pull request. Also, check out our [contribution guide](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc) that should get you started on contributing.
