### ISSUE TITLE
Spring Data run INSERT twice while persist history record in PostPersist for manual id entities [DATAJPA-1599]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1905]
**[hawkx](https://jira.spring.io/secure/ViewProfile.jspa?name=hawkx)** opened **[DATAJPA-1599](https://jira.spring.io/browse/DATAJPA-1599?redirect=false)** and commented

Background: I want to record entity change history, then I defined a base entity and annotated with EntityListeners, and save entity change history.

But I found that, if the changing entity has an automatic genarated id, then the change history can be successfully saved in PostPersist event, but if the changing entity has a manual set id, the spring data execute INSERT statement twice and cause primary key violation.

After this, I found that, for manual id entity, the change history can successfully saved in PrePersist event.

The problem is, why spring data execute INSERT statement twice in PostPersist event for manual id entity.

this is a sample project: https://github.com/hawkxu/test-entity-history. clone this project and run mvn:test to see messages.

this project using PrePersist for manual id entity in default, it can be run and access using browser to see entity change history through below url:

http://localhost:8080/auto-id

http://localhost:8080/manual-id

http://localhost:8080/history

---

**Reference URL:** https://github.com/hawkxu/test-entity-history

**Comment by Basuliic** [comment]
For other strugglers - It seems appropriate for me to use @Transactional(propagation = Propagation.REQUIRES_NEW) for such auditing services. This way we do not interact with EntityManeger of initial transaction and don't interfere with entities.
