### ISSUE TITLE
Optimize domain events batching by sending special event after all transactional domain events are published for the current transaction [DATAJPA-1601]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1907]
**[pragmasoft-ua](https://jira.spring.io/secure/ViewProfile.jspa?name=pragmasoft-ua)** opened **[DATAJPA-1601](https://jira.spring.io/browse/DATAJPA-1601?redirect=false)** and commented

I'm trying to implement https://microservices.io/patterns/data/transactional-outbox.html Transactional outbox pattern using domain events feature of Spring Data JPA.

Often, one domain even can cause a cascade of derived events. For performance reasons, it is better to send them in batch to the centralized event bus or event store (kafka, redis streams, etc).

To simplify batching strategy, it would be helpful to be notified, when all domain events, bound to one transaction, were successfully published.

Such, I propose to publish Spring Data JPA specific event to mark successful completion of transaction, which caused Domain events published, similar in spirit to `Spring's RequestHandledEvent. It may have a property of the number of domain events fired. `
Alternatively, we may have more generalized transaction demarcation events ie TransactionStarted/TransactionCommitted/TransactionRolledBack

 

 

---
No further details from [DATAJPA-1601](https://jira.spring.io/browse/DATAJPA-1601?redirect=false)

**Comment by gregturn** [comment]
You are free to craft something like this in your code:

```java
@TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT) // AFTER_COMMIT is actually the default
public void afterCommit(ApplicationEvent event) {
    // whatever you need to do knowing that the transaction just completed
}
```
