### ISSUE TITLE
not(null) seems to be wrong [DATAJPA-1625]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1927]
**[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** opened **[DATAJPA-1625](https://jira.spring.io/browse/DATAJPA-1625?redirect=false)** and commented

A `null} {{Specification` is essentially a `true` value.
But if this gets negated it still seems to be a `true` value, although a different one.

```java
static <T> Specification<T> not(@Nullable Specification<T> spec) { static <T> 
    Specification<T> not(@Nullable Specification<T> spec) {
        return spec == null // ? (root, query, builder) -> null// : (root, query, builder) -> 
            builder.not(spec.toPredicate(root, query, builder)); }
 
```

---
No further details from [DATAJPA-1625](https://jira.spring.io/browse/DATAJPA-1625?redirect=false)

**Comment by schauder** [comment]
This is outdated.
