### ISSUE TITLE
Using same Parameter for LIKE and = the equals check will always fail [DATAJPA-1627]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1929]
**[jonasblumer](https://jira.spring.io/secure/ViewProfile.jspa?name=jonasblumer)** opened **[DATAJPA-1627](https://jira.spring.io/browse/DATAJPA-1627?redirect=false)** and commented

Using the same parameter for an equals comparison and a LIKE comparison will always pre- and append `%` to the parameter making the equals comparison always fail.

`@Query("SELECT * FROM User u WHERE u.name = :term OR u.username LIKE %:term%") List<Users> getUsers(final String term);`

The parameter, when calling this with `getUsers("Jonas")` and checking SQL logging, is `%Jonas%`, which means the `= :term` check will always fail

---
No further details from [DATAJPA-1627](https://jira.spring.io/browse/DATAJPA-1627?redirect=false)

**Comment by lorentzforces** [comment]
I came across this behavior recently and I'd like to contribute a fix for it (should a fix be desired). @schauder are you currently engaged on this issue, and would you mind if I took it?

**Comment by schauder** [comment]
A fix for this would be very welcome.

**Comment by gregturn** [comment]
@lorentzforces If you're still interested, I'd suggest beginning with writing a simple test case that exposes this issue then working your way toward a solution.

**Comment by gregturn** [comment]
Superceded by #3041.
