### ISSUE TITLE
Fix mismatch in tests between Repository declaration and the id type of the entity [DATAJPA-1654]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1956]
**[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** opened **[DATAJPA-1654](https://jira.spring.io/browse/DATAJPA-1654?redirect=false)** and commented

---

**Issue Links:**
- [DATAJPA-1649](https://jira.spring.io/browse/DATAJPA-1649) Repository with wrong ID doesn't fail start-up of application context

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/403

**Comment by gregturn** [comment]
I think this was resolved in https://github.com/spring-projects/spring-data-jpa/commit/9d5c13e0185a0.
