### ISSUE TITLE
CrudRepository.deleteAll doesn't work [DATAJPA-1659]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1960]
**[Michał Winiarski](https://jira.spring.io/secure/ViewProfile.jspa?name=winiarski)** opened **[DATAJPA-1659](https://jira.spring.io/browse/DATAJPA-1659?redirect=false)** and commented

CrudRepository.deleteAll() doesn't work on Entity repository if the proxies loaded by findAll are not initialized. Simplified example:

entities:

```java
@MappedSuperclass
class Base {
  @EmbeddedId
  protected EntityId id;

  @Version
  private Timestamp timestamp;
}

@Entity
class A extends Base {

  @ManyToOne(optional = false, fetch = FetchType.LAZY)
  private B b;
}

@Entity
class B extends Base {
}
```

 

client:

```java
// create A and related B entities in a separate transaction

// start transaction
aRepository.deleteAll();
bRepository.deleteAll();
//end transaction
```

 

B entities are not deleted in this case because: SimpleJpaRepository.delete(T entity):

```java
if (entityInformation.isNew(entity)) {
 return;
}
```

 

entityInformation.isNew returns true for B entities

---

**Affects:** 2.2.3 (Moore SR3)

**Issue Links:**
- [DATAJPA-1576](https://jira.spring.io/browse/DATAJPA-1576) JpaMetamodelEntityInformation.getId(…) uses field access for proxied entities

**Comment by gregturn** [comment]
I have verified that @schauder 's proposal to add getters to the `Base` entity type indeed fixes everything for this situation.

I'm not completely convinced we need to battle with the proxies in this circumstance, since good design of entity types should include providing at least getters for the necessary fields. Of course, the spec says that field access will be used, so we can't lean on the spec to ensure this.

**Comment by muhammad-asn** [comment]
Is there any update on this? Currently we have an issue for random `DataIntegrityViolationException` error when try to run Unit Test with Junit

In local it's working, but in CI/CD or server sometimes it's failed.

Thank you

**Comment by gregturn** [comment]
@muhammad-asn Have you ensured that all the necessary getters are in place? That seems to be the quickest path to success.
