### ISSUE TITLE
Using Pageable and EntityGraph, entire collection is loaded from database [DATAJPA-1677]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-jpa#1976]
**[Christoffer](https://jira.spring.io/secure/ViewProfile.jspa?name=christoffer)** opened **[DATAJPA-1677](https://jira.spring.io/browse/DATAJPA-1677?redirect=false)** and commented

I noticed some weird behavior when I added an `EntityGraph` to my `findAll` repository method:
* When I use an `EntityGraph`, that specifies an attribute node on a field that uses a `@OneToMany` relationship, the entire collection will be loaded from the database (however, the `Page` object only contains my 25 limit objects).

* No limit is added to the SQL statement
* The number of rows loaded ~= playlists + items (which I believe should be ~= 25 + items)

* The same thing **does not** happen if I add a `@OneToOne` or `@ManyToOne` field to my attribute nodes.
  * The limit (25) is then added as expected to the SQL statement
  * The number of rows loaded = 25

 

Highly simplified code from my project:

 

```java
@Entity
@NamedEntityGraph(
        name = "graph",
        attributeNodes = {
                @NamedAttributeNode(value = "items")
        }
)
public class Playlist {

    ....
    @OneToMany(mappedBy = "playlist")
    private Set<Item> items;
}
```

 

 

```java
interface PlaylistAdminRepository extends JpaRepository<Playlist, Integer>, JpaSpecificationExecutor<Playlist> {
    @EntityGraph(value = "graph")
    Page<Playlist> findAll(Pageable pageable);
}
```

 

 

---

**Affects:** 2.2.4 (Moore SR4)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by schauder** [comment]
As described by Michael Stochmal this is normal JPA behavior.
