### ISSUE TITLE
QueryDslPredicateExecutor more subclass friendly

### ISSUE THREAD

**Issue by ralscha** [spring-projects/spring-data-jpa#2]
Hi

I created my own Repository interface 
public interface MyRepository<T, ID extends Serializable> extends JpaRepository<T, ID>, QueryDslPredicateExecutor<T> {...}
and the corresponding implementation
public interface MyRepository<T, ID extends Serializable> extends JpaRepository<T, ID>, QueryDslPredicateExecutor<T> {...}

Together with a FactoryBean and a Factory everything works fine. The only problem I had was that everything in QueryDslPredicateExecutor is private. So I had to copy a lot of code from this class into my implementation because I wanted to use the createQuery method. Is it possible to make QueryDslPredicateExecutor more subclass friendly or is this a bad idea?

Ralph

**Comment by gregturn** [comment]
Considering:

A) `QuerydslJpaPredicateExecutor` now has `createQuery()` protected (as suggested by @odrotbohm), 

and

B) `QuerydslRepositorySupport` has everything protected as well, meaning you can really control everything you need

...I think we can close this ticket.

To answer the last question, is it possible to apply `QuerydslRepositorySupport` to multiple repositories at once, perhaps. You can extend `QuerydslRepositorySupport` and plug in all the parts as needed, but leave the `Class<?> domainClass` portion open. This doesn't totally take it off your hands, but should make things operate as desired.
