### ISSUE TITLE
Projection fails when using subquery [DATAJPA-1713]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2008]
**[Manu VIDAL](https://jira.spring.io/secure/ViewProfile.jspa?name=z8manu8z)** opened **[DATAJPA-1713](https://jira.spring.io/browse/DATAJPA-1713?redirect=false)** and commented

When using a subquery in query defined with `@Query`, JPA projection fails.
Return type is not of projection class but

**_org.springframework.data.jpa.repository._**_query.AbstractJpaQuery$TupleConverter$TupleBackedMap_**

Example :

```java
@Entity
public class Employee {
   @Id
   @GeneratedValue(strategy=GenerationType.AUTO)
   private Long id;
   private String firstName;
   private String lastName;
   private Integer salary;

   // Constructors, getters and setters
}
```

Projection class :

```java
public interface EmployeeProjection {

    public Long getId();

    public String getFirstName();
 
    //@Value("#{target.firstName + ' ' + target.lastName}") 
    //String getFullName();
}
```

Repo :

```java
public interface EmployeeRepository extends CrudRepository<Employee, Long> {
   @Query("select c from Employee c where c.salary >= "
          //+ "500"
          + "(select avg(salary) from Employee )"
   )
   List<EmployeeProjection> findProjections();
}
```

When using condition "_c.salary >= 500"_, method returns a correct result, i.e. a List\<EmployeeProjection>.

But when using a subquery "_c.salary >= (select avg(salary) from Employee)_", method returns a list of **_AbstractJpaQuery$TupleConverter$TupleBackedMap_**.

On this object, calling any getter returns null.
Using `@Value` (open projection) throws an exception.

Example sources are attached.
Thanks in advance.

 

---

**Affects:** 2.2.6 (Moore SR6)

**Attachments:**
- [demo.zip](https://jira.spring.io/secure/attachment/27809/demo.zip) (_4.51 kB_)
- [demo2.zip](https://jira.spring.io/secure/attachment/27821/demo2.zip) (_5.76 kB_)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/420

**Comment by jamesdh** [comment]
Likewise, seeing something similar when using a Postgres jsonb function to try and render a jsonb array of objects as a list of entity types, e,g...

```java
@Query(
    nativeQuery = true,
    value = """
        SELECT
            x.path,
            x.base64
        FROM
            claim c,
            jsonb_to_recordset(c.files) as x(path varchar, base64 varchar)
        WHERE c.id = :id
    """)
List<SupportFile> findFiles(@RequestParam UUID id);
```

**Comment by gregturn** [comment]
The original reporter on this ticket had a problem with:

```java
@Query("select c from Employee c where c.salary >= (select avg(salary) from Employee )")
List<EmployeeProjection> findProjections();
```

This is non-native query that involves a subselect and projections. @schauder coded a simple reproducer of the same issue that fits into our existing test machinery:

```java
// DATAJPA-1713
@Query("select u from User u where firstname >= (select Min(u0.firstname) from User u0 )")
List<NameOnly> findProjectionBySubselect();


@Test // DATAJPA-1713
public void selectProjectionWithSubselect() {

	List<UserRepository.NameOnly> list = userRepository.findProjectionBySubselect();
	assertThat(list).isNotEmpty() //
			.allSatisfy(no -> {

				assertThat(no.getFirstname()).describedAs("firstname").isNotNull();
				assertThat(no.getLastname()).describedAs("lastname").isNotNull();
			});
}
```

This test scenario is overcome by the new query parser and passes.

NOTE: This ticket was closed due to an unrelated native query, for which the query parser does NOT get applied, so that's why it's reopened.
