### ISSUE TITLE
@Procedure returns NULL when I use parametermode.REFCursor [DATAJPA-1719]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2014]
**[pratikbhattacharya2017](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49516)** opened **[DATAJPA-1719](https://jira.spring.io/browse/DATAJPA-1719?redirect=false)** and commented

You can see the example here

https://www.logicbig.com/tutorials/spring-framework/spring-data/stored-procedure-ref-cursor.html

---

**Reference URL:** https://www.logicbig.com/tutorials/spring-framework/spring-data/stored-procedure-ref-cursor.html

**Comment by gregturn** [comment]
#1959 was recently resolved. Feel free to test out the snapshots to see if it results your issue as well.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
