### ISSUE TITLE
Cannot receive multiple output parameters from stored procedure with @NamedStoredProcedureQuery [DATAJPA-1722]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2017]
**[AlexanderStepchkov](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49541)** opened **[DATAJPA-1722](https://jira.spring.io/browse/DATAJPA-1722?redirect=false)** and commented

I'm trying to receive out parameters from simple stored procedure (using Oracle 11g and/or MSSQL 2012).

```java
CREATE OR REPLACE PROCEDURE test_sp(x OUT INTEGER, y OUT INTEGER) AS
BEGIN
 x := 17; y := 93;
END;
```

 

```java
@Data
@Entity
@NamedStoredProcedureQueries({
        @NamedStoredProcedureQuery(name = "testSp", procedureName = "test_sp", parameters = {
                @StoredProcedureParameter(mode = ParameterMode.OUT, name = "x", type = Integer.class),
                @StoredProcedureParameter(mode = ParameterMode.OUT, name = "y", type = Integer.class)
        })
})
public class SomeEntity {
    @Id
    private Long id;
}
```

Please check attached demo project for details.

Using annotations I always receive errors: 

java.lang.IllegalArgumentException: OUT/INOUT parameter not available: x

java.lang.IllegalArgumentException: OUT/INOUT parameter not available: 1

However if I use entityManager's createStoredProcedureQuery method it works fine.

 

Link to SO https://stackoverflow.com/questions/61655464/spring-boot-data-jpa-receive-multiple-out-parameters-from-sql-servers-stored-pr

---

**Affects:** 2.2.7 (Moore SR7)

**Attachments:**
- [demo.zip](https://jira.spring.io/secure/attachment/27889/demo.zip) (_5.83 kB_)

1 votes, 2 watchers

**Comment by satscreate** [comment]
Any update on this issue using @Procedure annotation?

**Comment by schauder** [comment]
The example relies on downloading oracles jdbc driver which resolves as forbidden, it also doesn't come with a database.

Please provide a reproducer that uses an in memory database or brings everything it needs with it, using for example Testcontainers.

If the reproducer is highly database dependent it's likely that the issue is really one of the JPA implementation, i.e. Hibernate in this case. After all Spring Data JPA is based on JPA which is supposed to provide an abstraction over the different databases.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by satscreate** [comment]
Am on it...will create a quick in memory db setup and attach shortly.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
