### ISSUE TITLE
Exception swallowed in CreateIfNotFoundQueryLookupStrategy.resolveQuery [DATAJPA-1723]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2018]
**[ckalan](https://jira.spring.io/secure/ViewProfile.jspa?name=ckalan1)** opened **[DATAJPA-1723](https://jira.spring.io/browse/DATAJPA-1723?redirect=false)** and commented

Exception thrown from lookupStrategy.resolveQuery() is swallowed without proper logging before falling back to createStrategy. 

In my case it occured when I used `@Query` annotation in my repo method with "name" attribute pointing to a JPA Named Query declared on the entity. The problem was I also used Sort parameter and I got "propert not found for type ..." exception. In fact the inner exception was thrown by "NamedQueries" class with this code:

```java
throw new IllegalStateException(String.format("Finder method %s is backed " + "by a NamedQuery and must "
  + "not contain a sort parameter as we cannot modify the query! Use @Query instead!", method));
```

It took me a couple of hours to identify the issue and I had to deep dive in the code because there was no debug log for the actual error. In addition to the logs, it might be a good idea to update the docs to mention this limitation. 

Note that this happens in 2.2.6 RELEASE version that comes with Spring Boot but that version is not listed in the Affects Version/s field above.  

 

---
No further details from [DATAJPA-1723](https://jira.spring.io/browse/DATAJPA-1723?redirect=false)

**Comment by gregturn** [comment]
Part of the problem is that `JpaQueryLookupStrategy` is using exceptions for flow control inside `resolveQuery`

```java
@Override
protected RepositoryQuery resolveQuery(JpaQueryMethod method, QueryRewriter queryRewriter, EntityManager em,
		NamedQueries namedQueries) {

	try {
		return lookupStrategy.resolveQuery(method, queryRewriter, em, namedQueries);
	} catch (IllegalStateException e) {
		return createStrategy.resolveQuery(method, queryRewriter, em, namedQueries);
	}
}
```

This method will catch an `IllegalStateException` and pivot to creating a query instead of simply looking it up. But in some circumstances this is the wrong action to take.

This also stems at least down into `NamedQuery`, where the same exception type is captured and transformed into a `null`.

**Comment by gregturn** [comment]
Backported to `2.7.x`, `2.6.x`, and `2.5.x`.
