### ISSUE TITLE
CountQuery fails to be auto generated when not using explicit alias [DATAJPA-1737]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2032]
**[Jonas Tänzer](https://jira.spring.io/secure/ViewProfile.jspa?name=jtaenzer)** opened **[DATAJPA-1737](https://jira.spring.io/browse/DATAJPA-1737?redirect=false)** and commented

Consider the following repository: 

```java
public interface BookErrorRepository extends Repository<BookError, Long> {

    @Query("FROM BookError b WHERE portal = :portal AND date >= :startDate AND date <= :endDate" +
           " AND (:search IS NULL OR keyword LIKE :search%)" +
           " AND (:state IS NULL OR errors = :#{#state?.shortMessage})")
    Page<BookError> findByPortalInDateRange(@Param("portal") Portal portal,
            @Param("startDate") LocalDate startDate,
            @Param("endDate") LocalDate endDate,
            @Param("search") Optional<String> search,
            @Param("state") Optional<State> state,
            Pageable pageable);

}
```

When changing this to 

```java
FROM BookError WHERE portal [...]
```

the attached exception occurs on startup.

At first it seems like an issue with the HQL parser, but upon further inspection it seems that spring-data-jpa doesn't generate the count query correctly, because it recognizes WHERE as the alias. 

```java
Caused by: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: WHERE near line 1, column 14 [select count(WHERE) FROM com.example.project
```

This isn't a huge issue issue of course, but I figured I'd report to at least receive feedback anyway.

 

 

---

**Attachments:**
- [count_query_error.txt](https://jira.spring.io/secure/attachment/27900/count_query_error.txt) (_49.63 kB_)

**Comment by gregturn** [comment]
Part of this query's issue is that the LIKE clause details should be wrapped inside single-quotes. As for the rest, we're working up a solution to handle missing aliases.

**Comment by gregturn** [comment]
I also opened up #2875 to track implementation of the SpEL safe navigation operation in the query parser.
