### ISSUE TITLE
Working with JSON(B) Postgre [DATAJPA-1738]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-jpa#2033]
**[VladislavK777](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49649)** opened **[DATAJPA-1738](https://jira.spring.io/browse/DATAJPA-1738?redirect=false)** and commented

Hello. I have a problems with Spring JPA and JSONb(select, update, delete, insert). I need to use the other library for work with JSONb (com.vladmihalcea.hibernate.type.json)
This is lib no popular.

Maybe you will add new feature. For excample:

I have Entity 

```java
import com.vladmihalcea.hibernate.type.json.JsonBinaryType;

@Entity
@Table(name = "Table")
@TypeDefs({
        @TypeDef(name = "jsonb", typeClass = JsonBinaryType.class)
})
public class MyTable {
    @Id
    private UUID id;

    @Type(type = "jsonb")
    @Column(columnDefinition = "jsonb")
    @Basic(fetch = FetchType.LAZY)
    private List<MyModel> models;
}
```

models is Array of Objects

Now I searched so

```java
@Query(value = "select e.* from table t, jsonb_array_elements(t.models) e where e ->> 'numConnect' = ?1", nativeQuery = true)
List<Object> findByObject(String num);
```

Next I converted via ObjectMapper to List\<MyModel>.

And I would be to search data inside JSON and return List\<MyModel>.

```java
@Query(value = "select e.* from table t, jsonb_array_elements(t.models) e where e ->> 'numConnect' = ?1", nativeQuery = true, jsonMode = true)
List<MyModel> findByObject(String num);
```

Maybe add in `@Query` the new param "jsonMode = true"?

It woulde be a very usful for developers.

 

---
No further details from [DATAJPA-1738](https://jira.spring.io/browse/DATAJPA-1738?redirect=false)

**Comment by schauder** [comment]
Closing since the request is not clear.
