### ISSUE TITLE
tinyint unsigned to Boolean [DATAJPA-1765]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2058]
**[Neil Kwon](https://jira.spring.io/secure/ViewProfile.jspa?name=neil%20kwon)** opened **[DATAJPA-1765](https://jira.spring.io/browse/DATAJPA-1765?redirect=false)** and commented

mysql version : 8.x

column type : tinyint(1) unsigned

 

once Java interface projected from native query (with `@Query` annotation)

and original column type is **tinyint(1) unsigned** to **java type  Boolean**

 

 

```java
// code placeholder
java.lang.IllegalArgumentException: Projection type must be an interface!
```

exception occurred which did not happen on 2.1.x version

 

But, column type : tinyint(1) is OKAY

 

 AS you guys know, Altering table makes us seek... 

 

 

---

**Affects:** 2.2.9 (Moore SR9), 2.3.2 (Neumann SR2)

1 votes, 2 watchers

**Comment by gregturn** [comment]
As stated on #2157, we don't support custom conversions for projections.
