### ISSUE TITLE
CascadeType Merge is ignored when Persist is set [DATAJPA-1771]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2063]
**[William Keyser](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50063)** opened **[DATAJPA-1771](https://jira.spring.io/browse/DATAJPA-1771?redirect=false)** and commented

When we have a relationship A->B with it's cascade type set to MERGE, we can create and save a new entity A associated with an existing entity B (the latter being merged).

If the relationship is set to PERSIST, we can create and save a new entity A associated with a new entity B (the latter will also be inserted in the database).

However is the relationship it set to PERSIST AND MERGE, the first scenario no longer works. 

I believe the MERGE is ignored when PERSIST is set.

There is github project https://github.com/willix71/persistVsMerge.git that demonstrates the issue. There are two entities and a test class with four tests and I can't find a way of having all four test succeed. Two of them will succeed if the CascadeType is set to MERGE, the others will fail. As soon as I set the CascadeType to PERSIST, the other test succeed and the first two fail. Yet by setting the CascadeType to PERSIST and MERGE, the same happens. 

---

**Affects:** 2.3.3 (Neumann SR3)

**Reference URL:** https://stackoverflow.com/questions/63371545/cascadetype-merge-is-ignored-when-persist-is-set

**Comment by garlontas** [comment]
I have the same problem. Are there any updates on this bug?
