### ISSUE TITLE
StringQuery incorrect alias definition for hql have join query [DATAJPA-1781]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2074]
**[sdandroid](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50363)** opened **[DATAJPA-1781](https://jira.spring.io/browse/DATAJPA-1781?redirect=false)** and commented

`@Query`("select u from User as u left join  u.roles as r")

the StringQuery  get alias is  as.

 

---

**Affects:** 2.3.4 (Neumann SR4)

**Comment by gregturn** [comment]
Added a couple test cases verifying that the new HQL/JPQL parsers correctly pick the FROM clause's alias.
