### ISSUE TITLE
Add JSR 310 converters which support nanosecond precision [DATAJPA-1784]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2077]
**[Jonas Kongslund](https://jira.spring.io/secure/ViewProfile.jspa?name=kongslund)** opened **[DATAJPA-1784](https://jira.spring.io/browse/DATAJPA-1784?redirect=false)** and commented

Some of the non-time-zoned JSR-310 types (`Instant`, `LocalDateTime`, `LocalTime`) support nanosecond precision but each converter in `Jsr310JpaConverters` maps to `java.util.Date` which only support millisecond precision. The implication is that precision may be lost even though the underlying database column supports e.g. nanoseconds or microseconds.

Could a new class of converters which map to `java.sql.Timestamp` be a solution? At least `java.sql.Timestamp` supports nanosecond precision

---

1 votes, 3 watchers

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by schauder** [comment]
We solved this for JDBC already: https://github.com/spring-projects/spring-data-jdbc/issues/855
Therefore we should fix it for JPA as well.

**Comment by gregturn** [comment]
Updated the `java.time.Instant` converter to default to `java.sql.Timestamp` instead of `java.util.Date`, preserving precision.
