### ISSUE TITLE
ID String bug ddl auto_increment [DATAJPA-1788]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2083]
**[lj19950508](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50464)** opened **[DATAJPA-1788](https://jira.spring.io/browse/DATAJPA-1788?redirect=false)** and commented

application:
```
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
```
Entity:
```
@Id
@Column(columnDefinition = " varchar(32) comment 'ID'")
@GeneratedValue(strategy = GenerationType.AUTO, generator = "custom-id")
@GenericGenerator(name = "custom-id", strategy = "pers.gon.infrastructure.common.idgenerator.SnowFlakeId")
private String id;
```
Error:
```
Error executing DDL "create table sys_dict_item (id varchar(32) default '' comment 'ID' not null auto_increment

SnowFlakeId extend IdentityGenerator 
```
 When I user UUIDGenerator  ,  It's works.

I don't need  auto_increment   , but it generators   from   hibernate.ddl

 

 

---

**Affects:** 2.3.4 (Neumann SR4)

**Comment by gregturn** [comment]
This looks like a MySQL configuration issue and not a Spring Data JPA one. I'd suggest attempting to create this table manually with SQL loader script in order to hammer out the issues.

If that is not enough, feel free to come back to us with more details.
