### ISSUE TITLE
Add support for QueryDSL projections in JPA repositories [DATAJPA-1796]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2090]
**[marcusvoltolim](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50351)** opened **[DATAJPA-1796](https://jira.spring.io/browse/DATAJPA-1796?redirect=false)** and commented

### QueryDSL projections

QueryDSL projections are simple DTO classes that represent a group of properties to fetch from a database. Projections may be useful when we need only a small subset of columns from the queried entities. In such cases, they help us reduce the traffic between the database and our application.

### Spring Data JPA + QueryDSL

Spring Data JPA provides support for the QueryDSL library via the `QuerydslPredicateExecutor` interface.

 

```java
public interface QuerydslPredicateExecutor<T> {
    Optional<T> findOne(Predicate predicate);
    Iterable<T> findAll(Predicate predicate);
    Iterable<T> findAll(Predicate predicate, Sort sort);
    Iterable<T> findAll(Predicate predicate, OrderSpecifier<?>... orders);
    Iterable<T> findAll(OrderSpecifier<?>... orders);
    Page<T> findAll(Predicate predicate, Pageable pageable);
    long count(Predicate predicate);
    boolean exists(Predicate predicate);
}
```

The only required step is to create a repository that extends the executor interface.

```java
interface UserRepository extends JpaRepository<User, Long>, QuerydslPredicateExecutor<User>
```

From the interface definition, we can clearly see that projections are not supported - there is only one type parameter for the main entity class. Yet, we can quite easily extend the executor interface and provide support for projections and more sophisticated QueryDSL queries.

 

Article: https://www.talkischeap.dev/querydsl-projections-spring-data

 

---

**Affects:** 2.3.4 (Neumann SR4)

**Comment by gregturn** [comment]
This request now duplicates what was resolved via #2294.
