### ISSUE TITLE
Spring Data JPA pollutes child contexts with SharedEntityManagerCreator [DATAJPA-1797]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2091]
**[Ihor Herasymenko](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50559)** opened **[DATAJPA-1797](https://jira.spring.io/browse/DATAJPA-1797?redirect=false)** and commented

Reproducible with the latest Spring Data (Neumann-SR4) and Spring Framework 5.2.9.

Not reproducible with the latest Spring Data (Neumann-SR4) and Spring Framework 5.2.5.

Looks like a regression that was introduced by fixing https://github.com/spring-projects/spring-framework/issues/24852

The reproducer is on my [Github](https://github.com/iherasymenko/spring-data-jpa-child-context-pollution-reproducer).

Run all tests by executing _*gradlew test*_ — one test will fail.

Run **_gradlew test --tests com.example.Config2Test_** and then **_gradlew test --tests com.example.ConfigTest_** — both tests will succeed

---

**Affects:** 2.3.4 (Neumann SR4)

**Reference URL:** https://github.com/iherasymenko/spring-data-jpa-child-context-pollution-reproducer

**Comment by adjenks** [comment]
So... This is still an issue eh?

**Comment by adjenks** [comment]
@schauder 
Sorry for my ignorance and sorry to bother you, but how exactly do I specify release 5.2.5 as my dependency so that I can just work around this error for now? I'm actually a bit new to the whole Java ecosystem so I might be doing something wrong.

I added this to my pom file:
```
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-framework-bom</artifactId>
      <version>5.2.5.RELEASE</version>
      <type>pom</type>
    </dependency>
```
but the tests still fail saying I have duplicate entity managers:

> 
> required a single bean, but 2 were found:
> 	- org.springframework.orm.jpa.SharedEntityManagerCreator#0: defined by method 'createSharedEntityManager' in null
> 	- org.springframework.orm.jpa.SharedEntityManagerCreator#1: defined by method 'createSharedEntityManager' in null

**Comment by schauder** [comment]
There is an article about this https://spring.io/blog/2016/04/13/overriding-dependency-versions-with-spring-boot

Putting the dependency definition into `<dependencyManagement>` and adding a `<scope>import</scope>` should do the trick.

**Comment by adjenks** [comment]
Thank you 🙏
I'll give that a try.
