### ISSUE TITLE
Select Query returns Arraylist<String> instead of ArrayList<Entity> [DATAJPA-1825]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2114]
**[Stefan Scheid](https://jira.spring.io/secure/ViewProfile.jspa?name=4braincells)** opened **[DATAJPA-1825](https://jira.spring.io/browse/DATAJPA-1825?redirect=false)** and commented

`@Query` returns list of strings instead of list of entites 
{{
As we found no hints on stackoverflow and in documentation, we cannot explain that}}

```java
@Repository @Cacheable("topic") 
public interface TopicRepo extends Repo<Topic> { 
@Query("Select t from Topic t where ...(some condition on t)...") 
List<Topic> getTopics(@Param("schoolId") Integer schoolId); }
```

`returns an Arraylist<String> instead of ArrayList<Topic>, ans thus rises a cast exception.`

The extended Repo works fine, BTW.

`@NoRepositoryBean`
public interface Repo\<RepoType> extends JpaRepository<RepoType, BaseIdentity> {
Optional\<RepoType> findByBaseIdentitySchoolIdAndBaseIdentityId(Integer schoolId, Integer id);
List\<RepoType> findAllByBaseIdentitySchoolId(Integer schoolId);
}

 

 

---

**Affects:** 2.3.5 (Neumann SR5)

**Comment by SKrabbenborg** [comment]
I think we need the exact query you are running, the stacktrace you are getting and what the entity looks like. Currently I am not able to reproduce this issue and @Query works as I would expect.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
