### ISSUE TITLE
Update CI jobs with Docker Login [DATAJPA-1828]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2116]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAJPA-1828](https://jira.spring.io/browse/DATAJPA-1828?redirect=false)** and commented

---
No further details from [DATAJPA-1828](https://jira.spring.io/browse/DATAJPA-1828?redirect=false)

**Comment by gregturn** [comment]
We have moved to a different strategy for Docker management on Ci.
