### ISSUE TITLE
Pagination error [DATAJPA-1835]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2123]
**[Sergey](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50794)** opened **[DATAJPA-1835](https://jira.spring.io/browse/DATAJPA-1835?redirect=false)** and commented

I use findAll(Specification spec, Pageable page) of  JpaSpecificationExecutor.

The specification is generated in the method toPredicate and contain to much JOINs.

For pagination, the count method must be executed first and then the select done.

The problem is that with complex queries, the select works earlier and gets the first page, no matter which one I requested, and the count takes a long time and completes later than receiving data.

In the hibernate log, first executed select field1,field2, ......from t1 join t2.... and later ends select count(*) from t1 join t2....   This does not always happen.  But on long-term requests very often.

 

I have to get all the data through findAll(Specification spec), and then get the desired page from them. It work, but it is very resource intensive.

 

Used Spring Data JPA 2.3.1 and Kotlin

---
No further details from [DATAJPA-1835](https://jira.spring.io/browse/DATAJPA-1835?redirect=false)

**Comment by schauder** [comment]
Sorry, I don't understand the problem. The order of execution for the count select and the data select shouldn't matter. 

If this is not about the order, but about superfluous/wrong joins I would need a reproducer, i.e. a minimal project demonstrating the problem. Please make sure to use an in memory database or Testcontainers for setting up the database.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
