### ISSUE TITLE
How to call and pass List<Object> as an input to stored procedure using spring JPA

### ISSUE THREAD

**Issue by satscreate** [spring-projects/spring-data-jpa#2137]
I can call a stored procedure in Spring JPA like this (one way),

```
@Query(value = "CALL SP_NAME(:name);", nativeQuery = true)
List<Employee> findEmployees(@Param("name") String name);
```

or using Named one like below

```
@Entity
@NamedStoredProcedureQuery(name = "Employee.findEmployees", 
  procedureName = "SP_NAME", parameters = {
    @StoredProcedureParameter(mode = ParameterMode.IN, name = "name", type = String.class),
    @StoredProcedureParameter(mode = ParameterMode.OUT, name = "other", type = Integer.class)})
public class Employee {
    // class definition
}
```

```
@Procedure(name = "Employee.findEmployees")
int findEmployees(@Param("name") String model);
```
Now how can I pass the List<Employee> to the stored procedure? Also I can do an iteration of the records in stored procedure side so. Please help!

**Comment by schauder** [comment]
This seems to be a usage question and therefore should be asked on StackOverflow. We like to keep our issue tracker for bugs and feature requests.

This is especially true for questions that are have a large JPA aspect (as opposed to Spring Data JPA).

If you consider this a bug or feature request please add information to clarify this.
