### ISSUE TITLE
@Lock causes PSQL exception in read-only transactions

### ISSUE THREAD

**Issue by stefanrybacki** [spring-projects/spring-data-jpa#2141]
When using `@Lock` with pessimistic locking on e.g., `findOne` repository method it works as long as it is not called from a execution branch having `@Transactional(readOnly=true)`. In that case I get an SQL error stating the use of SELECT FOR SHARE, or SELECT FOR UPDATE cannot be executed in read-only transactions.

Maybe `@Lock` aspect/repoprocessor should be aware of readOnly state of the calling transaction and skip FOR SHARE/FOR UPDATE in that case.

Spring Data Version: 2.1.12
DB: Postresql 11

**Comment by gregturn** [comment]
Spring Data JPA doesn't do any special handling here. Instead, the `@Lock` annotation gives you the ability to apply JPA-defined `LockModeType` settings to a query, such that we can pick it up and pass it along to the `EntityManager`.

Check this out:

```java
@Override
public Optional<T> findById(ID id) {

	Assert.notNull(id, ID_MUST_NOT_BE_NULL);

	Class<T> domainType = getDomainClass();

	if (metadata == null) {
		return Optional.ofNullable(em.find(domainType, id));
	}

	LockModeType type = metadata.getLockModeType();

	Map<String, Object> hints = new HashMap<>();
	getQueryHints().withFetchGraphs(em).forEach(hints::put);

	return Optional.ofNullable(type == null ? em.find(domainType, id, hints) : em.find(domainType, id, type, hints));
}
```
This is extracting `LockModType` from the method's metadata (`@Lock`) and passing it along.

The spec also clearly talks about leaving it up to providers as to how they will handle these lock modes and apply their locks. Probably not every database has the same deep level locks as others. (H2 maybe locks whole tables, while I know Oracle can do row-level locking).

The spec also clearly has different versions of PESSIMISTIC locking: `PESSIMISTIC_READ`, `PESSIMISTIC_WRITE`, and `PESSIMISTIC_FORCE_INCREMENT`. Not sure what one you are using. But if even `PESSIMISTIC_READ` results in these SQL statements that don't work with your provider, then I'm afraid it's a signal that your provider doesn't support PESSIMISTIC locking when it's in `readOnly` mode.
