### ISSUE TITLE
Code doesn't show in the "Accessing data with JPA" learning guide

### ISSUE THREAD

**Issue by nthali** [spring-projects/spring-data-jpa#2142]
Apologies if this is the wrong place to submit this docs issue, but i couldn't find any instructions on where and how to submit this issue on the spring.io site:
on the learning guide page: https://spring.io/guides/gs/accessing-data-jpa/
All the code errors out with the following:
Unresolved directive in <stdin> - include::complete/pom.xml[]
Unresolved directive in <stdin> - include::complete/src/main/java/com/example/accessingdatajpa/Customer.java[]
etc.

**Comment by schauder** [comment]
Thanks, this is a good place to raise such issue. We'll take a look.

**Comment by mp911de** [comment]
Actually, https://github.com/spring-guides/gs-accessing-data-jpa/issues is the right place for the guide. I filed https://github.com/spring-guides/gs-accessing-data-jpa/issues/57 so closing this issue in favor of the newly created one.
