### ISSUE TITLE
Unable to use the :: in the native query, that lead to being unable to use the Microsoft Syntax

### ISSUE THREAD

**Issue by wer-mathurin** [spring-projects/spring-data-jpa#2171]
Here the problem,
when declaring a native query

```
@Query(value = 
"DECLARE @h geography;"+
"SET @h = geography::Point(45.27353320, -73.43387729, 4326); "
 , nativeQuery = true)
```

when executing the query here is what Hibernate is trying to execute:
`DECLARE @h geography;SET @h = geography:Point(45.27353320, -73.43387729, 4326);`

It remove a ":"

Is there any known workarounds in spring?
In the mean time I can probably use a STORE PROCEDURE, but would like to prevent that.

Best regards

**Comment by gregturn** [comment]
@wer-mathurin Have you had a chance to revisit this since https://github.com/spring-projects/spring-data-jpa/commit/1fe4cf598d7087ad8d434eb7b99bff90e033f164?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
