### ISSUE TITLE
Cache data in READ-COMMITED isolation didnt work well.

### ISSUE THREAD

**Issue by JeenoD** [spring-projects/spring-data-jpa#2175]
springboot version : V2.4.3

**BackGround**:
       1. Two transactions (call them A, B);
       2. Each transaction used `@Transactional` which isolation used "READ-COMMITTED";
       3. Mysql InnoDB engine uses "READ-COMMITTED" isolation, too.
       4. Transaction A contains Three steps :   query -> sleep 5 seconds -> query, then commited.
       5. Transaction B contains Three steps as well : query -> update -> query, then commited.
  
**Description**:  
        In my case, while A's thread is sleeping after first query, B would be done and commited.  As A is back and query again, B's updated data should be seen in A's query result in my prediction. However, A's second query result is same as its first query result, not updated data (by transaction B).  I still cannot figure out why, is it an issue ? hope you can help to figure out, thanks anyway.

My demo's code: [https://github.com/JeenoD/springboot-tx](url)

Here attaches some thoughts during position the issue.
1. hypothetical： Cache data makes A's second query result same as first query.
    However, I see the second query sql displayed in the console by setting `"spring.jpa.show-sql=true"`, And mysql server received the sql and executed (imageattacked in my demo). So, i believed its not the cache data lead to it. 
2. Mysql InnoDB default isolation. In order to figure out where the problem is, I have set it "READ-COMMITTED", and check the isolation worked.(simulate my case by sql directly).
3. I used **jdbcTemplate** as a contrast, it worked as "READ-COMMITTED" mechanism with the same `@Transactional` used. 

**Temporary solution**:
 I used EntityManager.clear() before the second query. But i still not think its a suitable solution, if you think it should give the cache data, but why still send the query sql to mysql server, no helping for performance.

Hoping for you reponse, Thank you in advance.

**Comment by schauder** [comment]
This is expected behaviour of JPA. JPA uses a first level cache to ensure that every class/id combination is only present at most once in the `EntityManager`. See for example https://stackoverflow.com/questions/22533399/why-do-i-not-see-changes-issued-through-an-update-query-with-spring-data-jpa
