### ISSUE TITLE
Using native Query with distinct is returning wrong total count 

### ISSUE THREAD

**Issue by OctavioCega** [spring-projects/spring-data-jpa#2177]
Hello, It seems that Hibernate is removing the "distinct" key word from the native Query when using the count to get the total elements. 

Any Workaround for this?

Springboot 2.3.7

A fragment for the logs:

The log for the get entities
```
select distinct e.* from schema.entity e 
(more statements...)
...
```

The log for the count query generated by hibernate (as you can see, for some reason, it is removing the "distinct" keyword)
```
select count(e) from  schema.entity e 
(more statements...)
...
```

This seems like bug for me. I saw this issue from a long ago time but without any solution (a part from generating my own count query) https://github.com/spring-projects/spring-data-jpa/issues/750

**Comment by ruslanys** [comment]
Looks like changes leads to the following:  https://github.com/spring-projects/spring-data-jpa/issues/2260#issuecomment-1111986155

**Comment by ruslanys** [comment]
I found out that this commit has bug: https://github.com/spring-projects/spring-data-jpa/commit/3e64d9ad9b7d45fcf1231dbaf207be49cc481e7a

Especially, the line 494: `&& !variable.contains("*");`

The invocation of method

```
createCountQueryFor("SELECT * FROM User WHERE created_at > $1")
```

returns `select count(WHERE) FROM User WHERE created_at > $1`

**Comment by ruslanys** [comment]
Commits and tests marked with issue #2341

**Comment by DiegoKrupitza** [comment]
> I found out that this commit has bug: https://github.com/spring-projects/spring-data-jpa/commit/3e64d9ad9b7d45fcf1231dbaf207be49cc481e7a

Ok I will take a look at this. I think I have a fix for this. PR will come soon.

**Comment by ruslanys** [comment]
@DiegoKrupitza Thank you!
