### ISSUE TITLE
Dynamic projections retrieve all columns from MySQL

### ISSUE THREAD

**Issue by s3curitybug** [spring-projects/spring-data-jpa#2179]
Hello. I have an entity representing a MySQL table:

```java
@Entity
@Table(name = "account")
@Getter
@Setter
@SuppressWarnings("serial")
public class AccountEntity implements AccountBaseEntity, AccountRoleEntity, Serializable {

    @Id
    @GeneratedValue(generator = "uuid2")
    @Column(name = "account_id")
    private UUID accountId;

    @Column(name = "email")
    @NotBlank
    private String email;

    @Column(name = "role")
    @NotBlank
    private String role;

    @Column(name = "creation_time")
    @NotNull
    private Timestamp creationTime;

}
```

It implements this interface:

```java
public interface AccountBaseEntity {

    UUID getAccountId();

}
```

And then I have some projections also implementing it. For instance:

```java
public interface AccountRoleEntity extends AccountBaseEntity {

    String getRole();

}
```

This is my repository, which has a dynamic projection:

```java
public interface AccountsRepository extends JpaRepository<AccountEntity, UUID> {

    <T extends AccountBaseEntity> T findByEmail(String email, Class<T> type);

}
```

And I use it with this code:

```java
AccountRoleEntity accountRoleEntity = accountsRepository.findByEmail(email, AccountRoleEntity.class);
```

I inspect the query setting the property `spring.jpa.show-sql = true` and this is what I see:

```sql
Hibernate: select accountent0_.account_id as account_1_0_, accountent0_.creation_time as creation2_0_, accountent0_.email as email3_0_, accountent0_.role as role10_0_ from account accountent0_ where accountent0_.email=?
```

I was expecting the query to select only the account_id and role columns, but it seems like it is retrieving the entity and converting it to the projection, instead of retrieving the projection itself. Is this a bug or am I doing something wrong?

**Comment by s3curitybug** [comment]
I just realized this is because `AccountEntity` extends `AccountRoleEntity`. Is this the normal behaviour?

I want the entity to extend the projection so that I can have a common interface to be used in some methods that should work both with the entity and the projection.

**Comment by mp911de** [comment]
This is expected behavior. If the entity type is an instance of the requested target type (`AccountEntity instanceof AccountRoleEntity`), then we select and materialize the entity instead of issuing a tuple query and creating a projection proxy.

**Comment by s3curitybug** [comment]
All right. I solved it creating a super interface implemented by both the entity and the projection. Thank you!
