### ISSUE TITLE
Selectively evict L2 cache using nativeQuery

### ISSUE THREAD

**Issue by matejsp** [spring-projects/spring-data-jpa#2185]
We are using L2 hibernate cache using hazelcast. And we are creating UPSERT using native query. It works well. 
However when native query is called since it is not bound to the ReportJPA ALL cache is invalidated. Because this is called very often whole application crawls.

So ... we are using QueryHint for query cache.

According to Hibernate:
```
https://www.baeldung.com/hibernate-second-level-cache:
However, when it comes to native SQL DML statements, Hibernate cannot guess what is being updated, so it invalidates the entire second level cache
```

```
@Repository
public interface ReportRepositoryJPA extends CrudRepository<ReportJPA, String> {

    @QueryHints({ @QueryHint(name = "org.hibernate.cacheable", value ="true") })
    List<ReportJPA> findAllByTransactionId(String transactionId);

    @Modifying
    @Query(value="INSERT INTO REPORT " +
            "(ID, TYPE, CURRENCY_ID, AMOUNT, TIMESTAMP) VALUES " +
            "(:id, :type, :currencyId, :currencyAmount, :timestamp) ON DUPLICATE KEY UPDATE " +
            "AMOUNT=AMOUNT+:currencyAmount", nativeQuery=true)
    void incrementForCurrency(
            @Param("id")String id,
            @Param("type")String type,
            @Param("fundId")String fundId,
            @Param("currencyId")String currencyId,
            @Param("currencyAmount")BigDecimal currencyAmount,
            @Param("usdAmount")BigDecimal usdAmount,
            @Param("eurAmount")BigDecimal eurAmount,
            @Param("timestamp") Instant timestamp
    );

}
```

Fix is to use entityManager api with unwrap:
```
Query nativeQuery = entityManager.createNativeQuery("update FOO set ... where ...");
nativeQuery.unwrap(org.hibernate.SQLQuery.class).addSynchronizedEntityClass(Foo.class);
nativeQuery.executeUpdate();
```

But this is not possible when using repository.
I propose extending Query (or new annotation) with synronizedentityClasses list that is passed to hibernate.

**Comment by mp911de** [comment]
The approach above is specific to Hibernate. Does the following code yield the same as you sample?

```
EntityManagerFactory emf = …;

emf.getCache().evict(Foo.class):
```

**Comment by matejsp** [comment]
No, I don't think it does. I mean my code is changing (behind the scenes):

from:
- emf.getCache().evictAll();
to
- emf.getCache().evict(Foo.class):

The main issue is how to get Hibernate NOT to call evictAll() for native query (insert or update)

**Comment by mp911de** [comment]
Thanks. This functionality is specific to Hibernate so I would rather not like to see us providing such a feature. I wasn't able to find such functionality for Eclipselink. 

Having a feature that isn't part of the JPA specification and that works with one JPA implementation but not the other one always asks for trouble in regards to expectations.

**Comment by matejsp** [comment]
There is the same problem with mixing native and managed queries in eclipselink.
https://stackoverflow.com/questions/32779197/can-i-hint-eclipselink-to-use-the-shared-cache-after-a-native-query

Each implementation have the same problem and specific solution as well it seems.

**Comment by mp911de** [comment]
Following the links above the SO post (and the Eclipse link forum post) are unanswered since 2015.

**Comment by matejsp** [comment]
I don't except spring data to have custom code for each provider (or to provide a such feature). 

But I would like to have a possibility to pass parameters to the backend provider.

Well I am looking for something like QueryHints ... Or perhaps some spring interceptor for Query before calling execute update. So developers can adapt execution to their need.

Alternative is to not use Repository pattern for native query ...

**Comment by matejsp** [comment]
example:
``` 
    @Query(value="INSERT INTO REPORT " +
            "(ID, TYPE, CURRENCY_ID, AMOUNT, TIMESTAMP) VALUES " +
            "(:id, :type, :currencyId, :currencyAmount, :timestamp) ON DUPLICATE KEY UPDATE " +
            "AMOUNT=AMOUNT+:currencyAmount", 
            queryInterceptor=QueryInterceptorImplementation.class, 
            nativeQuery=true)
```

now in queryInterceptor I would call:
```
class QueryInterceptorImplementation extends IJPAQueryIncerceptor {

   @Override
   public Query process(Query query) {
       query.unwrap(org.hibernate.SQLQuery.class).addSynchronizedEntityClass(Foo.class);
       return query;
   }

}
```
