### ISSUE TITLE
Feature request - query method aliases

### ISSUE THREAD

**Issue by Drezir** [spring-projects/spring-data-jpa#2186]
Hi,

I am searching for a solution for auto generated query methods. Have a look at this:

In JpaRepository, we have for example this method:
`List<T> findAllById(Iterable<ID> var1);`

Problem with hibernate is that I want to create another method that also finds entities by their ids but fetches some lazy associations. 

This I cannot do just by changing return type (projection). Only solution to this is to write @Query sql with another method name.

Dynamic projections is probably solution for custom methods but not already existing ones. 
I imagine to introduce some form of aliasing like this:

```
    @AliasFor("findAllByIds")
    @EntityGraph(attributePaths = "lazyAssociation")
    List<Entity> findAllByIdsWithLazyInitialized(Iterable<PK> ids);
```
This could reuse same implementation and apply fetch graph only.

**Comment by mp911de** [comment]
How about (assuming your primary key name is `id`):

```java
    @EntityGraph(attributePaths = "lazyAssociation")
    List<Entity> findAllWithLazyInitializedById(Iterable<PK> ids);
```

**Comment by Drezir** [comment]
It could resolve this usecase if "`WithLazyInitialized`" is ignored by query generation algorithm.

**Comment by mp911de** [comment]
Yes, almost everything between `find` and `By` is descriptive. See https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#appendix.query.method.subject for further details.

**Comment by Drezir** [comment]
Is it possible to handle left/right join fetch with @EntityGraph?
