### ISSUE TITLE
Query hints on findById do not support hints that allow duplicate values for the same name

### ISSUE THREAD

**Issue by MelleD** [spring-projects/spring-data-jpa#2190]
This is a similar issue to https://github.com/spring-projects/spring-data-jpa/issues/1229

If you use multiple Query hints for findById. This is not working, because it is transformed to a HashMap. 

```
 @Override
   @QueryHints( {
                      @QueryHint( name = "eclipselink.left-join-fetch", value = "f.bars" ),
                      @QueryHint( name = "eclipselink.left-join-fetch", value = "t.bars.as" )
                } )
   Optional<Foo> findById( String id );
```

Issue is here at SimpleJpaRepository

```		
               Map<String, Object> hints = new HashMap<>();
		getQueryHints().withFetchGraphs(em).forEach(hints::put);

		return Optional.ofNullable(type == null ? em.find(domainType, id, hints) : em.find(domainType, id, type, hints));
```

I'm not sure if you can solve this problem with the em.find

**Comment by schauder** [comment]
This is a limitation in JPA and an inconsistency in EclipseLink.

`EntityManager.find` takes a `Map` as an argument, so there is no (reasonable) way to provide two hints with the same key.
We also can't switch to using a query based on the Criteria-API or JPQL, because that would change the behaviour of the method.

**Comment by MelleD** [comment]
@schauder thanks for you answer. 

Why does CritertiaApi change the loading behavior?
As a workaround, I tested it like this that it would go through the CriteriaApi. Actually looked good so far

```
   @Override
   default Optional<Foo> findById( final I id ) {
      return readById( id );
   }

 @Override
   @QueryHints( {
                      @QueryHint( name = "eclipselink.left-join-fetch", value = "f.bars" ),
                      @QueryHint( name = "eclipselink.left-join-fetch", value = "t.bars.as" )
                } )
   Optional<Foo> readById( String id );
```

**Comment by schauder** [comment]
@MelleD a `find` will look directly in the first level cache, while. A query will hit the database first, retrieve the data for the entity, and only then check if it is already present in the cache.

Lazy loading might be affected as well, I'm currently not sure about that.

Thanks for posting the workaround.

**Comment by MelleD** [comment]
@schauder Thanks for the explanation. That means with the workaround the performance could be worse than before because the first cache is bypassed?

Do you think there is a chance to expand the EntityManager?

**Comment by schauder** [comment]
Regarding a change in the `EntityManager` feel free to ask for it https://github.com/eclipse-ee4j/jpa-api/issues
I don't see a great chance that something like this will actually get implemented.

The current API strongly suggests that the behaviour of EclipseLink is really just abusing it.
And the JPA spec isn't exactly moving fast: https://github.com/eclipse-ee4j/jpa-api/pulse/monthly

**Comment by MelleD** [comment]
@schauder thanks a lot. I'll take my chances ;)
