### ISSUE TITLE
Table name is binding with single quotes when using as query param in @Query  which leads to "invalid table name error"

### ISSUE THREAD

**Issue by naveenkan** [spring-projects/spring-data-jpa#2194]
@Modifying
	@Query(value = "ALTER TABLE :table TRUNCATE PARTITION :partition UPDATE INDEXES", nativeQuery = true)
	void cleanupPartition(@Param("table") String table, @Param("partition") String partition);

when I am using above method in my repository, looks like the spring data jpa binding the table name with single quotes which leads to invalid table name, Please help/guide me how to resolve above issue.(**FYI: i am using native query**)

**Comment by schauder** [comment]
This is a limitation of JDBC. You can not use bind variables for identifiers. Some databases offer special function for this. See https://docs.snowflake.com/en/sql-reference/identifier-literal.html for an example. 

In general you would need to write a custom method for this.

In other Spring Data JPA we offer a way to use SpEL to customize entity/table names. 
I'll leave the ticket open for now so we can discuss internally if we want to offer something like this of Spring Data JDBC as well.

**Comment by mp911de** [comment]
Going forward, that's a limitation of databases where certain parts of SQL cannot be parametrized.

**Comment by naveenkan** [comment]
Thank You very much for your Response Jens,Mark, Please let me Know if any feature is added to Spring data JDBC to resolve this issue.**(FYI, I used native Query)**

**Comment by schauder** [comment]
As said above: in Spring Data JPA you may use SpEL expressions for this https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query.spel-expressions

We'll discuss if we want this feature for Spring Data JDBC and create a separate ticket for it, if so.
