### ISSUE TITLE
How to invalidate @where on the entity

### ISSUE THREAD

**Issue by ChenZheOnePiece** [spring-projects/spring-data-jpa#2204]
i have a entity UserInfo 

```
@Where(flag=1)
public class UserInfo{
}
```
if i want query flag=0  What should I do without using native SQL

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by schauder** [comment]
`Where` is a Hibernate annotation and Spring Data JPA does not provide any special support for it. If you want to disable it for certain queries you have to use the facilities that Hibernate might have to offer.
