### ISSUE TITLE
Remote mysql database connection with spring boot JPA

### ISSUE THREAD

**Issue by kalyandammu-bytesedge** [spring-projects/spring-data-jpa#2205]
I have connected remote database by following below properties:

```
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://<server-ip>:3306/db_name
spring.datasource.username=
spring.datasource.password=
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

spring.jpa.database=MYSQL
spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
```
I didn't get any error of database while building application. All crud operations are successfully done without any error while testing the application in local. But data is not updating in remote database. I didn't catch the issue. Could you please help me to solve that issue.

Thanks in advance.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
