### ISSUE TITLE
JPA issue with Postgres RETURNING clause

### ISSUE THREAD

**Issue by hadiyarajesh** [spring-projects/spring-data-jpa#2208]
I'm using PostgreSQL and Spring data jpa to execute update as following
```
@Transactional
@Modifying(flushAutomatically = true, clearAutomatically = true)
@Query(
     "UPDATE posts SET comments_count = comments_count +1 WHERE post_id = :postId RETURNING comments_count",
      nativeQuery = true
)
fun incrementCommentCounter(@Param("postId") postId: Long): Int
```
As i'm using native query with RETURNING clause, it throws exception as
`o.h.engine.jdbc.spi.SqlExceptionHelper : A result was returned when none was expected.`

How should this query be executed with spring boot?

**Comment by mp911de** [comment]
`@Modifying` issues an update query where Hibernate doesn't expect a result other than the number of affected rows. Using `RETURNING` will return a result set so you cannot use `@Modifying`.

**Comment by hadiyarajesh** [comment]
So what's the solution? just not using `@Modifying`?

**Comment by mp911de** [comment]
Yes, exactly.
