### ISSUE TITLE
JPA annotations is doesn't work on getter

### ISSUE THREAD

**Issue by Michael1024-CJX** [spring-projects/spring-data-jpa#2216]
I tried adding @Column and @Versioin to the getter, but none of them worked.
```
@Entity
@Table(name = "contact")
public class ContactEO {
    @Id
    private Integer id;
    private String name;

    @Column(name = "contact_name", nullable = false, length = 512)
    public String getName() {
        return name;
    }
    // other getter setter
}
```
log output create table sql:
create table contact (id int4 not null, name varchar(255), primary key (id))

**Comment by tco0427** [comment]
I'm not sure, but it seems that Getter is not working properly because the maximum length (255) of the table and the character length of the annotation do not match the constraints.

**Comment by Michael1024-CJX** [comment]
@tco0427 I tried to change the value of length to 10, but SQL still uses the name attribute instead of the contact_name I hope. It seems that the program did not parse the getter method of @Column, I am not sure whether it is because of Hibernate or Spring.

**Comment by tco0427** [comment]
I think you want to do as follows.

```java
@Entity
@Table(name="contact")
public class ContactE0 {
    @Id
    private Integer id;

    private String contactName;
    @Column(name="name", nullable = false,length=512)
    public String getName(){
        return contactName;
    }
}

```

**Comment by Michael1024-CJX** [comment]
@tco0427 https://github.com/Michael1024-CJX/Test-JPA/tree/master  ,I wrote a simple spring-data-jpa demo, when the application is started, the database table will be created automatically, but the field is not the value of the name in @Column that I want. If you have time, can you help me see what's wrong?

**Comment by tco0427** [comment]
In such cases, it is reasonable to give Column annotation to the field.
And if you do that, you'll be able to create the table you want.
like this
<img width="936" alt="스크린샷 2021-05-16 오후 7 33 56" src="https://user-images.githubusercontent.com/57028386/118394121-b512af80-b67d-11eb-8ed9-c83b8ba946c0.png">

**Comment by Michael1024-CJX** [comment]
@tco0427 Thank you for your help, the definition of @Column on the Field can indeed take effect, but I want to study how to define @Column on the getter. 
Because I want to implement this kind of interface：
```java
/**
 * If the entity needs to implement optimistic locking, implement this interface
 */
public interface Verifiable<T> {
    @Version
    T getVersion();
}

@Entity
@Table(name="someEntity")
public class someEntity implements Verifiable<Integer> {
    @Id
    private Integer id;

    private Integer version;

    @Override
    public Integer getVersion() {
        return version;
    }
}
```

**Comment by Michael1024-CJX** [comment]
@tco0427 I know the reason!!! Hibernate does not support mixing field annotations and getter method annotations, you can only choose one of them. So I only need to define @Id on the getter. 
```java
@Entity
@Table(name = "contact")
public class ContactEO {
    private Integer id;
    private String name;
    @Id  //It's important here
    private Integer getId() {
        return id;
    }
    @Column(name = "contact_name", nullable = false, length = 50)
    public String getName() {
        return name;
    }
    // setter
}
```

**Comment by tco0427** [comment]
Thanks to you, I learned something new!
