### ISSUE TITLE
Unused org.aspectj:aspectjrt compile time dependency

### ISSUE THREAD

**Issue by iherasymenko** [spring-projects/spring-data-jpa#2218]
I see no compile time usages in the codebase and other aspect dependencies are marked as optional.

https://github.com/spring-projects/spring-data-jpa/blob/da9eddd83ffa74258a3d76306c7e5a63718a14ed/pom.xml#L168-L172

**Comment by mp911de** [comment]
Thanks for letting us know. That looks like a leftover that we can clean up with the next version.
