### ISSUE TITLE
Spring-Retry @Retryable not working with Spring-data Repositories

### ISSUE THREAD

**Issue by jopuneet** [spring-projects/spring-data-jpa#2223]
While trying @Retryable with spring-data-jpa, the retry for the repository is not working and it was always called only once.

```
@Repository
public interface TestRepository extends CrudRepository<Test, String> {

  @Retryable(value = { Exception.class }, maxAttempts = 4, backoff = @Backoff(delay = 2000))
  List<Test> findAll();
}
```

Spring-retry is wrapping the JPA proxy in another proxy that only implements Retryable, @Retryable is not supported directly on JPA repositories.

An open issue in Spring-Retry [Issue-214](https://github.com/spring-projects/spring-retry/issues/214)

This would be a good feature to have in spring-data-jpa. 

Referring to this [Stackoverflow answer](https://stackoverflow.com/questions/42730104/retryable-doesnt-work-in-spring-data-repository-interface)

Old issue: [Issue-1980](https://github.com/spring-projects/spring-data-jpa/issues/1980)

Spring-boot: 2.3.0.RELEASE
Spring-Retry: 1.2.5.RELEASE
Spring-data: 2.3.0.RELEASE

**Comment by mp911de** [comment]
Isn't that a problem of how Spring Retry creates proxies? Spring Data JPA isn't involved in the business with `@MockBean` so I'm not sure there's anything we can do here.

**Comment by jopuneet** [comment]
How about adding a feature in Spring-Data JPA for a support for retry?

**Comment by mp911de** [comment]
Spring Data already allows already customization of the proxy factory:

```java
RepositoryFactoryBeanSupport factoryBean = …;
factoryBean.addRepositoryFactoryCustomizer(repositoryFactory -> {
	
	repositoryFactory.addRepositoryProxyPostProcessor((proxyFactory, repositoryInformation) -> {
				  proxyFactory.addAdvisor(…);
	});
});
```

so there's little need to create another proxy.

Taking a step back, can you elaborate on your need to issue retries? What is the problem you're trying to solve?

**Comment by jopuneet** [comment]
Thanks for this solution and this will completely work. 
I wanted to use `@Retryable` over the Spring-Data Repositories directly without cutomizing the proxy factory.

As there is one use case, with this customization of the proxy factory, if we want to write `@Recover` function for diffrerent factory methods, then we need to write custom proxy factory setting for all the functions separately in a config where this customisation is defined.

Rather, customising the factory beans, wouldn't it be better to get a fucntionality to set the retry from configuration itself as a feature?

**Comment by mp911de** [comment]
Thanks. In the context of JPA, which heavily makes use of transactions (and hence requires an active database connection), I am under the impression that retries cannot be based on I/O resiliency needs. Retrying operations because of database error responses (unique index constraint validation, lock timeouts) is actually something that requires retries on the entire transaction. So I'm still missing the concrete use-case to justify any effort that we would want to put into this request.

Likely, an integration within Spring Retry (or an integration module) would make sense to not duplicate any bootstrapping code.
