### ISSUE TITLE
Maven artifact org.springframework.data:spring-data-jpa signed by unknown gpg key

### ISSUE THREAD

**Issue by buesse** [spring-projects/spring-data-jpa#2225]
Looks like these artifacts are signed by GPG Key with KeyID: 1661DCD1 /0xEF6AD6684034B0CB67A9B5714406B84C1661DCD1 which can't be found on all GPG Keyservers I tried

https://hkps.pool.sks-keyservers.net/pks/lookup?op=get&options=mr&search=0xEF6AD6684034B0CB67A9B5714406B84C1661DCD1
https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&search=0xEF6AD6684034B0CB67A9B5714406B84C1661DCD1

I would have expected these artifacts to be signed by KeyId: 0xE2ACB037933CDEAAB7BF77D49A2C7A98E457C53D UserIds: [Spring Buildmaster <buildmaster@springframework.org>]

**Comment by odrotbohm** [comment]
So far, the individual team members actually performing the releases have used their GPG keys to sign the release. We've started to round robin releases across the team and it looks like one of the keys hasn't made it to a publicly available server yet. That's gonna be fixed ASAP.

**Comment by buesse** [comment]
Thanks for the quick reply.

**Comment by mp911de** [comment]
I've re-uploaded the key and it can be retrieved from https://keys.openpgp.org/search?q=EF6AD6684034B0CB67A9B5714406B84C1661DCD1.
