### ISSUE TITLE
JpaRepository.getOne/getById method name should indicate that it returns a reference

### ISSUE THREAD

**Issue by kdebski85** [spring-projects/spring-data-jpa#2232]
JpaRepository methods getOne/getById methods are often used by accident by inexperienced developers instead of findById.
These methods call EntityManager::getReference and return a reference.
The method name should indicate that.
We should consider adding method JpaRepository::getReferenceById and deprecating getById (getOne is already deprecated).

**Comment by schauder** [comment]
Related: #1645, #510, #1540, #1473

**Comment by schauder** [comment]
We agree with the proposed solution.
