### ISSUE TITLE
Upgrade Eclipselink to 3.0.0

### ISSUE THREAD

**Issue by igorsekuloski-brd** [spring-projects/spring-data-jpa#2233]
Is there a planned update for Eclipselink to version 3.0+?
Asking specifically because of the namespace change from javax.persistence to jakarta.persistence.

**Comment by mp911de** [comment]
Unless Spring Framework migrates first to the JakartaEE namespace, we cannot proceed. We plan to migrate to JakartaEE with Spring Data 3.0. Note that such a change is a breaking one and we will no longer support javax.persistence.

**Comment by mp911de** [comment]
Resolved via #2305
