### ISSUE TITLE
Does it support kotlin sequence query

### ISSUE THREAD

**Issue by edcjian** [spring-projects/spring-data-jpa#2236]
```
fun findAllByPassword(pass:String):Sequence<MyUser>?
``` 
i want query like this

**Comment by mp911de** [comment]
Care to elaborate what a `Sequence` is?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
