### ISSUE TITLE
Support BooleanExpressions in Querydsl Web Support

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-data-jpa#2240]
While simply queries like `?firstname=John&lastname=Doe` are nice, I would even be better if simply boolean expressions could be used, eg:

`?person.state=ne(2)`.
So this should return all persons that are **not** in state = 2.

The syntax could simply resemble to the existing `com.querydsl.core.types.dsl.BooleanExpression`s from `com.querydsl.core.BooleanBuilder`, as there are: `eq, ne, gt, goe, lt, loe...`.

That would be super helpful to build more advanced rest queries without having to change the Querydsl web support setup, which in general is a great concept, but simply lacks those advanced features.

**Comment by mp911de** [comment]
We do not want to introduce a query language over HTTP and Querydsl. You can register a `QuerydslBinderCustomizer` to provide such functionality. See the [reference documentation for Querydsl web support](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#core.web.type-safe) for further reference.

**Comment by membersound** [comment]
Well but that would actually be just an enhancement of the querydsl supported syntax? Because right now `?firstname=John` is mapped by spring to a querydsl `Predicate` that is translated to `eq(John)`. So why not supporting the type of boolean check explicit in the parameter already?

**Comment by schauder** [comment]
Because it opens the question where to stop. We support simple equality and not much more.
