### ISSUE TITLE
Implementing Persitable<ID> on EntityClass  with EmbeddableID has broken the deleteAll() functionality  in Spring Data JPA 

### ISSUE THREAD

**Issue by bmvsprasad** [spring-projects/spring-data-jpa#2243]
I have implemented Persistable<ID> on an Entity class that has EmbeddableID, Inorder to avoid N+1 Select query.
Later the default deleteAll()   JpaRepository (no code repository Spring Boot JPA) functionality has broken.

The deleteAll() internally generating select query to retrieve the entities from database. But not issuing any delete query to delete.

Moreover the records are not deleted from database.

**Comment by bmvsprasad** [comment]
Hibernate is the JPA Vendor Used in the above scenario.

**Comment by bmvsprasad** [comment]
Little more  analysis of the  issue - internally spring JpaRepository proxy uses SimpleJpaRepository  implementaion class.
SImpleJpaRepository uses EntityInformation to detect whether the entity isNew() . As the Entity in my project implements Persistable , it always returns true.  Because of this the following code breaking the delete operation.

SimpleJpaRepository.Java
@Transactional
@SuppressWarnings("unchecked")	public void delete(T entity) {
		Assert.notNull(entity, "Entity must not be null!");
		if (entityInformation.isNew(entity)) {			
                        return;		}

		Class&lt;?&gt; type = ProxyUtils.getUserClass(entity);

		T existing = (T) em.find(type, entityInformation.getId(entity));

		// if the entity to be deleted doesn't exist, delete is a NOOP		if (existing == null) {
			return;		}

		em.remove(em.contains(entity) ? entity : em.merge(entity));	
}

**Comment by bmvsprasad** [comment]
Adding a additional check to the above delete function code.

public  void delete(T entity) {

		Assert.notNull(entity, "Entity must not be null!");

		if(!(entityInformation instanceof JpaPersistableEntityInformation))
		
		if (entityInformation.isNew( entity)) {
			System.out.println("  entityInformation.isNew(entity) ");
			
			return;
		}

		Class<?> type = ProxyUtils.getUserClass(entity);
		System.out.println("  Entity =  (T) em.find(type, entityInformation.getId(entity)) ");

		T existing =  (T) em.find(type, entityInformation.getId( entity));
		 

		// if the entity to be deleted doesn't exist, delete is a NOOP
		if (existing == null) {
			System.out.println("existing is null");
			
			return;
		}
		
		
		System.out.println("Just before remove");
		em.getTransaction().begin();

		em.remove(em.contains(entity) ? entity : em.merge(entity));
		em.flush();
		
		em.getTransaction().commit();
		
		System.out.println("Just after remove");
	}

**Comment by mp911de** [comment]
I'm not sure I follow. How is the `delete` method supposed to delete an entity that is `new`, i.e. not expected to exist in the database?

**Comment by schauder** [comment]
Probably basically the same question but a different angle. 
I don't understand the following statement:
> As the Entity in my project implements `Persistable` , it always returns `true`.

The `isNew()` of a `Persistable` should only return `true` when the entity is actually new. Therefore this currently looks like an implementation error on your side.
Or am I misunderstanding something?

**Comment by bmvsprasad** [comment]
Here if an entity class is implemented with Persistable and persisted. The entity class overrides isNew Method such that it always return true,because of this Select query is not issued by JPA. Because of this behaviour the deleteAll has broken since it checks isNew which is overidden in Entity Class always return true.  see the below code of EntityClass.


/**
 * 
 */
package com.nokia.dis.mda.adapter.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.springframework.data.domain.Persistable;
import org.springframework.stereotype.Component;

/**
 *  * @param <ID>
 *
 */

@Component
@Entity
@Table(name="ENTITY_STATS")
public class EntityStats  /** implements Persistable<EntityStatsKey> **/ {

	@EmbeddedId
	private EntityStatsKey entityStatsKey;
	@Column(name="report_time")
	private Date   reportTime;	
	@Column(name="records_inserted")
	private Long   recordsInserted;
		
	public EntityStatsKey getEntityStatsKey() {
		return entityStatsKey;
	}
	public void setEntityStatsKey(EntityStatsKey entityStatsKey) {
		this.entityStatsKey = entityStatsKey;
	}
	public Date getReportTime() {
		return reportTime;
	}
	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}
	public Long getRecordsInserted() {
		return recordsInserted;
	}
	public void setRecordsInserted(Long recordsInserted) {
		this.recordsInserted = recordsInserted;
	}
	
	/** @Override
	public boolean isNew() {
		// TODO Auto-generated method stub
		return true;
	}
	@Override
	public EntityStatsKey getId() {
		// TODO Auto-generated method stub
		return getEntityStatsKey(); 
	} **/
}

**Comment by schauder** [comment]
It is up to you to implement `isNew()` in the proper way.

Sorry, I still don't understand the problem .

**Comment by bmvsprasad** [comment]
I understood , In the entity class isNew() always returning true does not suite the functionality of SimpleJpaRepository.

If JPA generated key  is used then isNew() detection is valid one. But if a userdefined key like composite primary key through embeddable ID is used does isNew() detection is at all needed while deleting the entity ?

**Comment by schauder** [comment]
*If* you implement `Persistable` the implementation of `isNew()` is required and it has to return `true` before the first `save` operation and `false` afterwards.

There is nothing that forces you to implement `Persistable`.
