### ISSUE TITLE
Small mistake in Documentation

### ISSUE THREAD

**Issue by DaniBa1** [spring-projects/spring-data-jpa#2251]
Hey there, 
i'm new to contributing so correct me if I'm doing anything wrong. 
While reading through the documentation at https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html I saw that the description of the `saveAllAndFlush` method reads, entities to be **deleted**. This is likely a mistake, but I wasn't sure if I can open a pull request for just that.

**Comment by schauder** [comment]
Hi @DaniBa1,

Yes, that is a bug. A PR would be appreciated.

With small stuff like that it is ok to create a PR without issue. 

If you are going to invest some serious time in a PR an issue is a good way to make sure that we are actually interested in the PR before starting to work on it.
