### ISSUE TITLE
Generated query for page attributes when a subquery exists is incorrect

### ISSUE THREAD

**Issue by AnishJoseph** [spring-projects/spring-data-jpa#2258]
```
public interface InvoiceRepository extends JpaRepository<Invoice, Long> {
   @Query(value = "select i.id as id,  " +
            "i.invoiceStatus as invoiceStatus, " +
            "(select sum(r.id) from Invoice r ) as paid " +
            "from Invoice i ")
    Page<InvoiceQuery> getInvoicesByStatusAndName(Pageable pageable);

}

```
The spring boot application fails come up as an exception is thrown during bootup. Springboot version is 2.4.5
The query and the sub-query looks silly, which it is, but this is sufficient to prevent springboot from startiing. My real query is very different

> Caused by: java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: expecting EOF, found ')' near line 1, column 62 [select count(r) from com.a.webacc.orm.entities.Invoice r ) as paid from com.a.webacc.orm.entities.Invoice i ] at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:138) ~[hibernate-core-5.4.30.Final.jar:5.4.30.Final]

The issue is that the query generated to determine the page attributes is incorrect and hibernate barfs. The parantheses in the subquery seems to be the issue.

InvoiceQuery is a projection defined like 
```
public interface InvoiceQuery {
       Long getId(); 
       InvoiceStatus getInvoiceStatus();
       Double getPaid(); 
}

```
It appears like the regex used in the method createCountQueryFor in QueryUtils is looking for the 1st occurance of the 'from' keyword and since this query has a subquery the 'from' from the 1st query gets picked resuting in a weirdly formed query

**Comment by schauder** [comment]
That is a known weakness in the query parser of Spring Data JPA. You'll have to provide your own `countQuery` for now.

**Comment by AnishJoseph** [comment]
Ok. Thanks
