### ISSUE TITLE
NativeQuery with Pagination

### ISSUE THREAD

**Issue by Johnczek** [spring-projects/spring-data-jpa#2260]
Hello, I am facing issue similiar with [https://github.com/spring-projects/spring-data-jpa/issues/1282](https://github.com/spring-projects/spring-data-jpa/issues/1282).

I am trying to run this native query with spring-data on version `2.5.0`

`@Query(value = "SELECT dense_rank() OVER (ORDER BY rank DESC)," +
        "t.id, " +
        "FROM table t WHERE t.x > 0 ",
        nativeQuery = true)
Page<Object[]> getT(Pageable pageable);`

But I am getting SQLGrammarException because the spring-data engine will translate this query into

`SELECT dense_rank() OVER (ORDER BY rank DESC),t.id FROM table t WHERE t.x > 0 , t.y desc limit 20`

Where the problem is pretty obvious. There is ORDER BY clause missing, probably because of presence of ORDER BY clause in OVER subquery. Is this a known bug? And is it possible to bypass this somehow? I need to use whole pageable object with native query with this dense_rank() calling.

**Comment by schauder** [comment]
I suspect this is a bug in the underlying JPA implementation. Spring Data JPA uses `Query.setFirstResult` and `Query.setMaxResult` to create the queries for pagination.

Could you confirm that you seeing this behaviour as well if you use an `EntityManager` directly, as described in https://www.baeldung.com/jpa-pagination

**Comment by Johnczek** [comment]
> I suspect this is a bug in the underlying JPA implementation. Spring Data JPA uses `Query.setFirstResult` and `Query.setMaxResult` to create the queries for pagination.
> 
> Could you confirm that you seeing this behaviour as well if you use an `EntityManager` directly, as described in https://www.baeldung.com/jpa-pagination

Hello, I´ve tried many ways but entity manager did not worked for me cause native query has no option to pass sort into query.

But after some investigation I´ve found a workaround with adding ORDER 1 at the end of query and now It is working fine.
I assume that spring will look for ORDER BY substring and if its found, there is (from his point of view) no need to add another ORDER BY and therefore spring appends just , ordering limiting offsetting. But in this case the ORDER BY clause should be added because the found ORDER BY property is not the one that framework is looking for.

**Comment by TAndronicus** [comment]
I'll try to tackle this issue

**Comment by shu1997** [comment]
Hello I am using postgreSQL also facing the same issue-> in my service layer i have created the pageable object using 
inside @Service:-

              Pageable pageable=PageRequest.Of(Integer page,Integer size,Sort.Direction sortDirection,String sortProperty);
    //Note: I have written the parameter types here along with their names just to explain and not in my actual implementation
              
              Page<ProjectView> projectViewsPage = this.projectRepository.getAllProjects(email, pageable);    

Inside Repository>

@Repository
public interface ProjectRepository extends JpaRepository<ProjectEntry, String> {

    @Query(value = "SELECT id AS id, " +
            "type AS type, name AS name, " +
            "description AS description, source AS source, " +
            "state AS state, schema_version AS schemaVersion, " +
            "modified_at AS modifiedAt, created_at AS createdAt, " +
            "modified_by->>'givenName' AS modifiedBy, created_by->>'givenName' AS createdBy, " +
            "last_access AS lastAccess, visibility AS visibility, " +
            "(SELECT version as latestVersion from packages WHERE owning_project = projects.id " +
            "order by regexp_split_to_array(version, '\\.')\\:\\:int[] desc limit 1), " +
            "dependencies\\:\\:jsonb " +
            "FROM projects WHERE created_by->>'email' =:userEmail OR visibility = 'PUBLIC'",
           countQuery = "SELECT count(*) FROM projects WHERE created_by->>'email' =:userEmail OR visibility = 'PUBLIC'",
            nativeQuery = true)
    Page<ProjectView> getAllProjects(@Param("userEmail") String userEmail, Pageable pageable);

the  resultant  query  in terminal is 
SELECT id AS id, type AS type, name AS name, description AS description, source AS source, state AS state, schema_version AS schemaVersion, modified_at AS modifiedAt, created_at AS createdAt, modified_by->>'givenName' AS modifiedBy, created_by->>'givenName' AS createdBy, last_access AS lastAccess, visibility AS visibility, (SELECT version as latestVersion from packages WHERE owning_project = projects.id order by regexp_split_to_array(version, '\.')::int[] desc limit 1), dependencies::jsonb FROM projects WHERE created_by->>'email' =? OR visibility = 'PUBLIC', last_access desc limit ?
ERROR: syntax error at or near ","  Position: 565 

which is acc to Order by not getting appended at the end  so how do i resolve this issue?

**Comment by TAndronicus** [comment]
I have added a solution where I'm counting the number of occurrences of `order by` and `order by` used in window functions. If the former count is greater than the latter, I'm assuming the order by is already present.
Although this fixes the reported issue, I can think of an example where it won't work - when `order by` is used in nested query (as in @shu1997 comment). Any suggestions are welcome

**Comment by somayaj** [comment]
Hi, can this be worked?

**Comment by 838239178** [comment]
```
Hibernate: select * from resource where MATCH(`name`) against(? IN NATURAL LANGUAGE MODE) limit ?
```
It's 2022 years. I am using spring-boot:2.6.1. No contains `order by`

**Comment by gregturn** [comment]
Thanks @TAndronicus!

**Comment by Persi** [comment]
Hi @TAndronicus, you mentioned a bug concerning alias detection. After upgrading from Spring Boot 2.5.12 to 2.5.13 (which implicitely upgrades spring-data-jpa from 2.5.10 to 2.5.11), some of our JPA queries did not work anymore because of false aliases used in queries. The problem only seem to occur in functions using @Query annotated repository methods, which use generic Sort or Paging mechanics of Spring Data JPA.

Example showing code which works with 2.5.10 of spring-data-jpa, but fails with 2.5.11:
`
	@Query("SELECT r FROM Rolle r where " +
			"(lower(r.name) like concat('%', lower(:name), '%')) AND " +
			"(:deleted is null or r.deleted = :deleted) AND " +
			"(:systemrolle is null or r.systemRolle = :systemrolle) AND " +
			"(COALESCE(:rechtIds, null) is null or (" +
			"select count(r2) from Rolle r2 join r2.rechtIds rIds " +
			"where rIds in (:rechtIds) " +
			"AND r.id = r2.id " +
			"group by r2.id having count(r2.id) = :minNumberOfMatches ) > 0)")
	Page<Rolle> findAllByNameContainsIgnoreCaseAndDeletedAndSystemrolleAndRechtIdsIn(
			@Param("name") @NotNull String name,
			@Param("deleted") Boolean deleted,
			@Param("systemrolle") Boolean systemrolle,
			@Param("rechtIds") Set<RechtId> rechtIds,
			@NotNull Long minNumberOfMatches, Pageable pageable);
`

The occurring error is as follows:
`
...
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: Invalid path: 'r2.name' [SELECT r FROM rechte_rollen.model.Rolle r where (lower(r.name) like concat('%', lower(:name), '%')) AND (:deleted is null or r.deleted = :deleted) AND (:systemrolle is null or r.systemRolle = :systemrolle) AND (COALESCE(:rechtIds, null) is null or (select count(r2) from rechte_rollen.model.Rolle r2 join r2.rechtIds rIds where rIds in (:rechtIds) AND r.id = r2.id group by r2.id having count(r2.id) = :minNumberOfMatches ) > 0) order by r2.name desc]
...
`

As you can see in the error, the generated sql is finalized by "order by r2.name desc", but r2 is the alias used in the subquery, not the alias used for the whole query.

Can you please take a look? I am unsure if we do something wrong, or if this is a new bug introduced with 2.5.11.

With best regards,
Marcus

**Comment by edudar** [comment]
I can confirm, the change in alias detection broke quite a few things:
```
while (matcher.find()) {
  alias = matcher.group(2);
}
```

In my case, I have a field that ends with `From`, alias detection uses `from` as a starting point, and the query alias moves.

```
QueryUtils.detectAlias(
"SELECT e FROM DbEvent e 
WHERE (CAST(:modifiedTo AS date) IS NULL OR e.modificationDate >= :modifiedTo)"
); -> "e"

QueryUtils.detectAlias(
"SELECT e FROM DbEvent e 
WHERE (CAST(:modifiedFrom AS date) IS NULL OR e.modificationDate >= :modifiedFrom)"
); -> "date"
```

**Comment by TAndronicus** [comment]
Thank you @Persi and @edudar for reporting, I will probably have time to take a look next week. Thank you for minimal example @edudar

**Comment by slPerryRhodan** [comment]
> I can confirm, the change in alias detection broke quite a few things:
> 
> ```
> while (matcher.find()) {
>   alias = matcher.group(2);
> }
> ```
> 
> In my case, I have a field that ends with `From`, alias detection uses `from` as a starting point, and the query alias moves.
> 
> ```
> QueryUtils.detectAlias(
> "SELECT e FROM DbEvent e 
> WHERE (CAST(:modifiedTo AS date) IS NULL OR e.modificationDate >= :modifiedTo)"
> ); -> "e"
> 
> QueryUtils.detectAlias(
> "SELECT e FROM DbEvent e 
> WHERE (CAST(:modifiedFrom AS date) IS NULL OR e.modificationDate >= :modifiedFrom)"
> ); -> "date"
> ```

I can confirm this behavior. We have the same error.

**Comment by JNPLZ** [comment]
Hi there, I'm having a similar problem with a query which worked before and broke with the last Spring Boot Update to 2.6.7. It looks like this:

`@Query(value = "SELECT * FROM mytable WHERE nr = :number AND kon = :kon AND datum >= '2019-01-01'", nativeQuery = true)
    Page<KontobewegungDto> getData(Pageable pageable, String number, String kon) throws DataAccessException;`

in an interface extending PagingAndSortingRepository

and now leads to

`ERROR o.h.e.jdbc.spi.SqlExceptionHelper.logExceptions - ERROR: syntax error at or near "WHERE"`

Thanks for looking into it!

**Comment by ruslanys** [comment]
The interesting thing, is that query:

```
SELECT * FROM users_statuses WHERE (user_created_at BETWEEN :fromDate AND :toDate)
```

breaks, and the DB says that the count query was: 

```
select count(WHERE) FROM users_statuses WHERE (user_created_at BETWEEN $1 AND $2)
```


However, the fix of the query is pretty simple, if you put alias right after the table name: 

```
SELECT * FROM users_statuses us WHERE (user_created_at BETWEEN :fromDate AND :toDate)
```
(_Pay attention, I have added_ **us** _alias_)


The count query will look like: `select count(us) FROM users_statuses WHERE (user_created_at BETWEEN $1 AND $2) `.

So, adding an alias to the query is fixing the issue.

**Comment by ruslanys** [comment]
Similar: #2511

**Comment by ruslanys** [comment]
I found out that this commit has bug: https://github.com/spring-projects/spring-data-jpa/commit/3e64d9ad9b7d45fcf1231dbaf207be49cc481e7a

Especially, the line 529: `&& !variable.contains("*");`

**Comment by ruslanys** [comment]
So, I'm not sure this issue is somehow related to the bug, but the origin problem goes from: #2177

**Comment by TAndronicus** [comment]
Yep, this seems to be unrelated to this issue. I don't even know where all those "#metoo" come from

**Comment by darinmanica** [comment]
I have a simple spring boot app which recreates the problem of the incorrect alias.  It's possible to toggle it on/off by changing the version of spring data jpa between 2.6.3 and 2.6.4.  As stated above, it appears to be in the handling of nested aliases in QueryUtils line 438.  The method exits with the last alias, even if it came from within a subselect.

**Comment by darinmanica** [comment]
#2516 fixes the incorrect alias issue described in #2260 and #2500 by removing subqueries from the alias detection.  There are unit tests showing sufficiently nested queries and functions while correctly detecting the alias for the order by clause.

**Comment by edudar** [comment]
@gregturn does not look like #2516 fixes this case: https://github.com/spring-projects/spring-data-jpa/issues/2260#issuecomment-1109105658 as there are no sub-queries yet alias detection is affected by the change in this ticket.

**Comment by darinmanica** [comment]
@edudar this is due to the lack of a zero-width word boundary in a regex that predates #2216; however, it is revealed by the PR.  I've added the word boundary and unit test in a new PR, #2521.

**Comment by gregturn** [comment]
Thanks to everyone else that helped tackle this issue with feedback and links.

**Comment by ronghuiye-agi** [comment]
hi @gregturn, does this issue get fixed? I am using 2.7.1 but still seeing the sorting with wrong table

**Comment by schauder** [comment]
@PAX523 please create a new issue and include a reproducer.

**Comment by darinmanica** [comment]
@PAX523 @ronghuiye-agi There is an issue in #2563 where the alias is incorrectly detected in multi-line queries.  I just submitted #2603  to address this.  Does your query contain EOL characters, such as a java text block?

**Comment by PAX523** [comment]
Yes, that's the case! I cannot inspect the used EOL characters right now, but basically the query consists of Java's multi-line string feature:

```java
 """
  SELECT * FROM ...
   WHERE ...
  """
```

Thank you for working on it. Cheers PAX
