### ISSUE TITLE
LazyInitializer.isUninitialized(object) returns true with object loaded with @EntityGraph untill spring-boot 2.4 (false with 2.3-)

### ISSUE THREAD

**Issue by richub34** [spring-projects/spring-data-jpa#2261]
Hi,

I've got different behaviour with same code when upgrading my app from spring-boot 2.3.12 to spring-boot 2.4.5/2.5.2.
An object loaded with a spring data repository using `@EntityGraph` does:
-  `org.hibernate.proxy.LazyInitializer.isUninitialized(theObject)` returns true on spring-boot 2.4+(tested with spring-boot 2.4.5/2.5.2)
-  `org.hibernate.proxy.LazyInitializer.isUninitialized(theObject)` returns false on spring-boot 2.3- (spring-data-jpa 2.3.9)

As consequence theObject is serialized by jackson as null on spring 2.4+ which is not what I expect.

The same Hibernate 5.4.32.Final is the JPA provider of all spring-boot 2.3.12, 2.4.5 and 2.5.2.

The code is like this:
**`@Repository` code: (interface annotated as `@Transactional(TxType.MANDATORY`)**

```
	@EntityGraph(attributePaths = {"key", "modules", "alc"})
	Optional<AppLc> getById(Long id);
 ```

**`@Service` code (class annotated as `@Transactional`)**

```
	public Optional<AppLc> findById(Long id) {
		return repository.getById(id);
	}
```

**Jackson objectMapper configuration in @Configuration class:**
```
        @Autowired
	private ObjectMapper objectMapper;
	@Override
	public void configureMessageConverters(
			List<HttpMessageConverter<?>> converters) {
		Hibernate5Module hibernateModule = new Hibernate5Module();
		objectMapper.registerModule(hibernateModule);
		converters.add(new MappingJackson2HttpMessageConverter(objectMapper));
	}
```

I did not find anything the net releated to my issue before submitting here. I hope it's a real one :-)
Thanks for providing us such great tools over the years.  

Regards,

**Comment by schauder** [comment]
> Thanks for providing us such great tools other the years.
Glad you like it.

Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

With lazy loading issue even minute details might matter. Therefore we need actually working code to debug this issue.

**Comment by richub34** [comment]
[orm-demo.zip](https://github.com/spring-projects/spring-data-jpa/files/6830755/orm-demo.zip)

Hi,

Thanks for your answer.

Here's a more isolated example of my problem in a maven project.
It illustrates the different behaviours.
Debugging is tricky because of lazzyloading but surely you know that :-)

```
	@Test
	void contextLoads() {
		log.info("LOAD TEST:");
		log.info("java.version={}", System.getProperty("java.version"));
		log.info("hibernate.version={}", org.hibernate.Version.getVersionString());
		log.info("spring.version={}", SpringVersion.getVersion());
		log.info("spring.boot.version={}", SpringBootVersion.getVersion());
		AppLic data = prepareData();

	log.info("DATA CREATED.");

		TransactionTemplate template = new TransactionTemplate(transactionManager);
		template.execute(status -> {
			log.info("LOAD DATA IN NEW TRANSACTION.");
			AppLic loaded = service.getById(data.getId()).get();

			boolean flagIsHibernateProxy = loaded instanceof HibernateProxy;
			log.info("flagIsHibernateProxy={}", flagIsHibernateProxy);
			if (flagIsHibernateProxy) {
				HibernateProxy proxy = (HibernateProxy) loaded;

				boolean flagIsUninitialized = proxy.getHibernateLazyInitializer().isUninitialized();
				log.info("flagIsUninitialized={}", flagIsUninitialized);
			}
			return null;
		});

	}
```


The org.example.orm.demo.DemoApplicationTests junit test class gives the following outputs:
**Output with spring 2.3.12:**
```
2021-07-16 14:39:07.269  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : LOAD TEST:
2021-07-16 14:39:07.269  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : java.version=1.8.0_181
2021-07-16 14:39:07.269  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : hibernate.version=5.4.32.Final
2021-07-16 14:39:07.270  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : spring.version=5.2.15.RELEASE
2021-07-16 14:39:07.270  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : spring.boot.version=2.3.12.RELEASE
2021-07-16 14:39:07.435  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : DATA CREATED.
2021-07-16 14:39:07.436  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : LOAD DATA IN NEW TRANSACTION.
2021-07-16 14:39:07.572  INFO 32024 --- [           main] o.example.orm.demo.DemoApplicationTests  : flagIsHibernateProxy=false

```
**Output with spring 2.5.2:**
```
2021-07-16 14:41:18.117  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : LOAD TEST:
2021-07-16 14:41:18.117  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : java.version=1.8.0_181
2021-07-16 14:41:18.117  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : hibernate.version=5.4.32.Final
2021-07-16 14:41:18.118  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : spring.version=5.3.8
2021-07-16 14:41:18.118  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : spring.boot.version=2.5.2
2021-07-16 14:41:18.281  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : DATA CREATED.
2021-07-16 14:41:18.281  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : LOAD DATA IN NEW TRANSACTION.
2021-07-16 14:41:18.308  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : flagIsHibernateProxy=true
2021-07-16 14:41:18.308  INFO 4908 --- [           main] o.example.orm.demo.DemoApplicationTests  : flagIsUninitialized=true

```
Only the version in the pom.xml has changed between the 2 runs:
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<!-- <version>2.3.12.RELEASE</version> -->
		<version>2.5.2</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
```

**Comment by schauder** [comment]
Sorry, but this sample contains tons of code that doesn't seem to have any relationship with the problem. Please remove all classes, that are not necessary in order to reproduce the problem.

**Comment by richub34** [comment]
[orm-demo-simple.zip](https://github.com/spring-projects/spring-data-jpa/files/6842615/orm-demo-simple.zip)

Hi,
Here's a smaller project. I won't be able to do a smaller one.
Same test class, same output, easier mapping/query.
Regards,

**Comment by richub34** [comment]
Hi,
Here's a smaller project. I won't be able to do a smaller one.
Same test class, same output, easier mapping/query: one entity, one dao, no service, no abstract class, no interface
[orm-demo-simple.zip](https://github.com/spring-projects/spring-data-jpa/files/6843622/orm-demo-simple.zip)
.
Regards,

**Comment by schauder** [comment]
Thanks, that I can work with. 

I'm seeing the general effect, but not exactly as you describe it, if I understood you correctly.
My understanding is that it loads eagerly with 2.3 but not 2.4 or 2.5
But what I'm seeing is that it loads eagerly with 2.3 and 2.4 but not 2.5

Is that also the behaviour you are seeing?

I see the following behaviour for the three version variants:

spring.boot.version=2.3.12.RELEASE

java.version=16.0.1
hibernate.version=5.4.32.Final
spring.version=5.2.15.RELEASE
spring.data.jpa = 2.3.9

initialized true

===========================

spring.boot.version=2.4.5

java.version=16.0.1
hibernate.version=5.4.30.Final
spring.version=5.3.6
spring.data.jpa = 2.4.8

initialized true

===========================

spring.boot.version=2.5.2

java.version=16.0.1
hibernate.version=5.4.32.Final
spring.version=5.3.8
spring.data.jpa = 2.5.2

initialized false
[It is a proxy and not initialized]

**Comment by richub34** [comment]
I do observe as you do : it loads eagerly with 2.3 and 2.4 but not in 2.5. 👍 

Multiple version jumps must have twisted my mind :-)

All my apologies.

**Comment by schauder** [comment]
No need for apologies. I mix up versions all the time.

The effect you are seeing is a side effect of #1697 which renames(*) `JpaRepository.getOne` to `getById` which collides with your chosen method name. 

Therefore it doesn't use the query derivation anymore, but uses a custom implementation, namely a call to `EntityManager.getReference` and does not apply any fetch hints or similar.

You can avoid the name clash by renaming your method to for example `findOneById`.

We'll discuss if we find a different solution, but I currently don't see any.

**Comment by richub34** [comment]
Thanks Jens, I'll rename my methods. Name clash will be on my radar.
Regards,
