### ISSUE TITLE
EntityListerner method gets re-called after repository call

### ISSUE THREAD

**Issue by crystalcase** [spring-projects/spring-data-jpa#2268]
Hello,

I am facing a behavior, which I believe is a bug. Neither anyone of my team nor searching the internet could give me something wo explain this.

Use-case: Getting all entities linked to an edited entity.

I created an `EventListener` and added the annotation to all relevant entities. If an entity gets an update I want to get all their relevant linked entities. Those should get fetched from other repositories. This is where we get to the problem. As soon as I call any repository, the update method in the listener gets called again with the same object as previously. It doesn't matter wether I use `@PostUpdate` or `@PreUpdate`. Everytime the method I am using gets called again. This is ending in an endless loop.

As mentioned I didn't find anything to this, but I don't think this is intentional.

**Comment by schauder** [comment]
This is just the behaviour of JPA and is not a bug of Spring Data. To [quote myself](https://stackoverflow.com/a/67980961/66686):

You are violating the JPA spec by accessing the persistence context in a lifecycle listener.

See the JPA Specification 4.2 Section 3.5.2

> In general, the lifecycle method of a portable application should not invoke EntityManager or query operations, access other entity instances, or modify relationships within the same persistence context. A lifecycle callback method may modify the non-relationship
state of the entity on which it is invoked.

"a portable application should not" is the specification way of saying: Don't do that, anything might happen. Maybe the world ends.
