### ISSUE TITLE
Provide repository fragment for streaming

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-data-jpa#2273]
It's necessary to stream data for batch processing, Spring Data JPA supports return `Stream` type, but it must be called in `@Transactional` methods, and sometimes it failed even `@Transactional` presented, for example:
```java
	@Transactional(readOnly = true)
	public ResponseEntity<StreamingResponseBody> download(@SortDefault(sort = "id") Sort sort) {
		return ResponseEntity.ok(outputStream -> {
			try (Stream<User> all = userRepository.findBy(sort)) {
				// write user to outputStream
			}
		});
	}
```
I fixed it by adding a default method to repository:
```java
	Stream<User> streamAllBy(Sort sort);

	@Transactional(readOnly = true)
	default void forEach(Sort sort, Consumer<User> consumer) {
		// avoid org.springframework.dao.InvalidDataAccessApiUsageException
		// see JpaQueryExecution.StreamExecution::doExecute
		try (Stream<T> all = streamAllBy(sort)) {
			all.forEach(consumer);
		}
	}
```
```java
	public ResponseEntity<StreamingResponseBody> download(@SortDefault(sort = "id") Sort sort) {
		return ResponseEntity.ok(outputStream -> {
				userRepository.forEach(sort, user -> {
					// write user to outputStream
				});
		});
	}
```
I hope Spring Data JPA can provide a repository fragment such as:
```java
import java.util.function.Consumer;
import java.util.stream.Stream;

import org.springframework.data.domain.Sort;
import org.springframework.transaction.annotation.Transactional;

public interface StreamingRepository<T> {

	Stream<T> streamAllBy(Sort sort);

	@Transactional(readOnly = true)
	default void forEach(Consumer<T> consumer) {
		forEach(Sort.unsorted(), consumer);
	}

	@Transactional(readOnly = true)
	default void forEach(Sort sort, Consumer<T> consumer) {
		try (Stream<T> all = streamAllBy(sort)) {
			all.forEach(consumer);
		}
	}
}
```
Reference document should be improved about streaming supports also whether this advice accepted or not.

**Comment by schauder** [comment]
In your first example you are not calling `findBy` within a method annotated by `@Transactional` you are just declaring a closure, which will get executed outside the method you showed.


> Reference document should be improved about streaming supports also whether this advice accepted or not.

Please clarify what kind of improvement you are looking for?

**Comment by quaff** [comment]
> In your first example you are not calling `findBy` within a method annotated by `@Transactional` you are just declaring a closure, which will get executed outside the method you showed.
You are right, that's why `@Transactional` doesn't work here, the error message should describe such scene.

https://github.com/spring-projects/spring-data-jpa/blob/main/src/main/java/org/springframework/data/jpa/repository/query/JpaQueryExecution.java#L347-L348

**Comment by schauder** [comment]
I don't think the Spring Data documentation is the right place to explain the semantics and use of closures. The error message you pointed to says that the method in question needs to run inside a transaction.

**Comment by quaff** [comment]
> I don't think the Spring Data documentation is the right place to explain the semantics and use of closures. The error message you pointed to says that the method in question needs to run inside a transaction.

Closures may be executed in the same thread, but if not it will be failed with that error message, append a short caveat is very helpful to save non-expert's time, please reconsider.

**Comment by schauder** [comment]
> Closures may be executed in the same thread, but if not it will be failed with that error message, append a short caveat is very helpful to save non-expert's time, please reconsider.

Your case doesn't fail because it is executed in a different thread. It fails because it is executed after your annotated method ends. Explaining this an all other scenarios can't be explained in a _short caveat_.

**Comment by quaff** [comment]
> > Closures may be executed in the same thread, but if not it will be failed with that error message, append a short caveat is very helpful to save non-expert's time, please reconsider.
> 
> Your case doesn't fail because it is executed in a different thread. It fails because it is executed after your annotated method ends. Explaining this an all other scenarios can't be explained in a _short caveat_.

What about `Please note it will fails if called in closure which excuted in different thread.`.

**Comment by schauder** [comment]
As I just wrote, this is only one scenario how this might fail, and it isn't even the one relevant for your case.

**Comment by quaff** [comment]
> As I just wrote, this is only one scenario how this might fail, and it isn't even the one relevant for your case.

It's relevant for my case, Spring MVC dispatch `StreamingResponseBody` to async.
https://github.com/spring-projects/spring-framework/blob/b595dc1dfad9db534ca7b9e8f46bb9926b88ab5a/spring-webmvc/src/main/java/org/springframework/web/servlet/mvc/method/annotation/StreamingResponseBodyReturnValueHandler.java#L94

**Comment by schauder** [comment]
After reconsidering the situation we came to the conclusion: The error message in place explains quite correctly the problem: Code that must run in a transaction doesn't. Everything else is the semantics of the JVM and transaction handling of Spring. The use of closures is irrelevant. Therefore a caveat would only prevent on special case of many and therefore would not be a worthwhile improvement.
