### ISSUE TITLE
Add deleteById return a boolean

### ISSUE THREAD

**Issue by wick3ds0ul** [spring-projects/spring-data-jpa#2279]
I am trying to delete a record by ID using `JPARepository`.
The default one in `Repository` is `void deleteById(ID var1);`
Using derived query.
```
@Repository
public interface CustomerRepository extends JpaRepository<Customer, Long> {
      Long deleteById(Long id); // To get deleted record count
      void deleteById(Long id); // To get ignore result
}
```

If it returns a Long, we would have to equate with `1` or a `0`. 

So, adding a method that returns a boolean would be helpful.

This gives less information if my transaction was successful for this use case.
**Repsitory**
```
@Repository
public interface CustomerRepository extends JpaRepository<Customer, Long> {
      boolean deleteCustomerById(Long id);
}
```
**Service**
```
 public boolean delete(Long id) {
        return customerRepository.deleteCustomerById(id);
    }
```
**Controller**
```
@DeleteMapping(path = "/customers/{id}")
public ResponseEntity<?> deleteCustomer(@PathVariable("id") Long id){
    Optional<Customer> foundCustomer= customerService.findById(id);
    return foundCustomer.map(customer -> {
        if (customerService.delete(id)){
            return ResponseEntity.ok().build();
        }else {
            return ResponseEntity.internalServerError().build();
        }
    }).orElse(ResponseEntity.notFound().build());
}
```
**RepositoryTest**
```
@Test
public void deleteCustomerByIdSuccess(){
    boolean result=customerRepository.deleteCustomerById(1L);
    assertTrue(result,"Customer should be deleted successfully");
    Optional<Customer> foundCustomer=customerRepository.findById(1L);
    assertFalse(foundCustomer.isPresent(),"Customer 1 should be deleted and not be found.");
}
```

**Comment by mp911de** [comment]
Care to elaborate what problem you want to solve? According to the code sample, the flow decides based on presence/absence of the query result which status code to return. JPA defers actual database interaction and therefore, a delete method returns the number of entities it found before calling `EntityManager.remove(…)` for each entity.

Your code that deletes entities should be called from a `@Transactional` method to ensure proper locking if you want to avoid concurrency issues to atomically find and delete entities.

**Comment by wick3ds0ul** [comment]
> Care to elaborate what problem you want to solve? According to the code sample, the flow decides based on presence/absence of the query result which status code to return. JPA defers actual database interaction and therefore, a delete method returns the number of entities it found before calling `EntityManager.remove(…)` for each entity.
> 
> Your code that deletes entities should be called from a `@Transactional` method to ensure proper locking if you want to avoid concurrency issues to atomically find and delete entities.

I am using ```@Transactional``` for this method.

But the problem is, the returning value which is a long when calling ```deleteById```.
With the current implementation it returns a long value.```Long:deleteById```. Considering the fact the ```@Id``` are unique.


 ```
   @Transactional
    public Long delete(Long id) {
        return customerRepository.deleteCustomerById(id);
    }
```

```

@DeleteMapping(path = "/customers/{id}")
public ResponseEntity<?> deleteCustomer(@PathVariable("id") Long id){
    Optional<Customer> foundCustomer= customerService.findById(id);
    return foundCustomer.map(customer -> {
        if (customerService.delete(id)>1){
            return ResponseEntity.ok().build();
        }else {
            return ResponseEntity.internalServerError().build();
        }
    }).orElse(ResponseEntity.notFound().build());
}
```


This ```Long``` value bubbles up to the controller method 
 
```
if (customerService.delete(id)>1)
{
 //some code
}
```
and we have to check if the ```Entity``` was deleted. 
What I am trying to do is ```delete``` an entity by ```Id``. It should delete exactly one Entity if that element was found and they are unique.

Changing the return value of ```Long:deleteById``` to ```boolean:deleteById``` would solve the problem i am trying to solve. Instead of comparing how many Entity it deleted. It would return a ```boolean``` if the ```Entity``` was deleted.
`      boolean deleteCustomerById(Long id);`

```
if (customerService.delete(id))
{
  //some code
}
```
Since it is a ```deleteById``` it should return a boolean.
Adding a test would look like.
```
    @Test
    public void deleteCustomerByIdSuccess() {
        boolean isDeleted = customerRepository.deleteCustomerById(1L);
        assertTrue(isDeleted,"Customer should be deleted with id 1.");
        Optional<Customer> foundCustomer = customerRepository.findById(1L);
        assertFalse(foundCustomer.isPresent(), "Customer 1 should not be found.");
    }
```

**Comment by mp911de** [comment]
> It would return a boolean if the Entity was deleted.

That is exactly what it cannot do. JPA defers the actual statement execution until either the next query, transaction commit, or `EntityManager.flush()` call. `EntityManager.remove(…)` returns `void`. The count returned by a delete query method reports how many entities were found to remove, not how many were actually removed.
