### ISSUE TITLE
Sort.Order ignoreCase does not work when query uses selectionAlias

### ISSUE THREAD

**Issue by lonely-development** [spring-projects/spring-data-jpa#2280]
When using `Pageable` containing a `Sort` with ignore case set to true and using a query with _selectionAlias_, lower is never added to resulting query.

1. Pageable with `Sort.Order(...,"name", ...).ignoreCase()`.
2. Query example with _selectionAlias_:
```
    @Query("SELECT customer.id as id, customer.name as name FROM CustomerEntity customer")
    Page<CustomerInfo> findAllActiveTaskInfo(Pageable pageable);
```
3. `org.springframework.data.jpa.repository.query.QueryUtils.java` never reaches `lower` modifier (line 308) because of _selectionAlias_ check (line 293), `getOrderClause()` method.

**Comment by somayaj** [comment]
hi, can this be worked?
