### ISSUE TITLE
Delete @OneToMany entity with cascade = ALL does not work after select with join fetch

### ISSUE THREAD

**Issue by ivan909020** [spring-projects/spring-data-jpa#2281]
<pre>
@Entity
@Table(name = "audiences")
public class Audience {

    @Id
    private Long id;

    @Column
    private Integer number;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "audience")
    private List&lt;Lesson&gt; lessons = new ArrayList&lt;&gt;();

}

@Entity
@Table(name = "groups")
public class Group {

    @Id
    private Long id;

    @Column
    private String name;

    @OneToMany(cascade = CascadeType.ALL, fetch = <b>FetchType.EAGER</b>, mappedBy = "group")
    private List&lt;Lesson&gt; lessons = new ArrayList&lt;&gt;();
    
}

@Entity
@Table(name = "lessons")
public class Lesson {

    @Id
    private Long id;

    @ManyToOne
    @JoinColumn(name = "audience_id")
    private Audience audience;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "group_id")
    private Group group;
    
}

@Repository
public interface AudienceRepository extends JpaRepository&lt;Audience, Long&gt; {

    @Query("SELECT a FROM Audience a " +
            "LEFT JOIN FETCH a.lessons l " +
            <b>"LEFT JOIN FETCH l.group g " + </b>
            "WHERE a.id = :audienceId")
    Audience findByIdWithLessonsAndGroup(Long audienceId);

/*  
    Same exception if we use this query instead of `findByIdWithLessonsAndGroup`

    @Query("SELECT l.group FROM Lesson l " +
            "WHERE l.audience.id = :audienceId")
    List&lt;Group&gt; findAllByAudienceId(Long audienceId);
 */

}
</pre>

---

If there is no `ON DELETE CASCADE` constraint in the database for the audience_id and group_id in the lesson table.
When we try to delete Audience after select with inner eager in child, we have an exception because cascade delete queries have not been executed.

Code to reproduce (the exception appears in any environment):
```
audienceRepository.findByIdWithLessonsAndGroup(1L);
// even if we try explicit delete lessonRepository.deleteAll(audience.getLessons()); it will not work
audienceRepository.deleteById(1L);
```

Exception:
```
delete from audiences where id=? [23503-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement] with root cause

org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "CONSTRAINT_2E: PUBLIC.LESSONS FOREIGN KEY(AUDIENCE_ID) REFERENCES PUBLIC.AUDIENCES(ID) (1)"; SQL statement:
delete from audiences where id=? [23503-200]
```

---

But if the database has `ON DELETE CASCADE` constraint for audience_id and group_id in lesson table.
Then delete query works fine for parent, but after we try to save something another, exception is thrown.

Code to reproduce (the exception appears only if the performer is a controller):
```
audienceRepository.findByIdWithLessonsAndGroup(1L);
// even if we try explicit delete lessonRepository.deleteAll(audience.getLessons()); it will not work
audienceRepository.deleteById(1L);

Audience audience = audienceRepository.findById(2L).get();
audienceRepository.save(audience);
```

Exception:
```
org.hibernate.TransientPropertyValueException: object references an unsaved transient instance - save the transient instance before flushing : com.example.springdemo.domain.Lesson.audience -> com.example.springdemo.domain.Audience
```

---

I found three solutions to resolve this problem:
`set fetch = FetchType.LAZY` for lessons in Group
OR
`@OnDelete(action = OnDeleteAction.CASCADE)` instead of `cascade = CascadeType.ALL`
OR
`entityManager.clear();` before delete Audience

---

Test project:
https://github.com/ivan909020/spring-jpa-test-delete-with-cascade

**Comment by schauder** [comment]
Is there any indication that this is not a problem of the underlying JPA implementation?

**Comment by ivan909020** [comment]
> Is there any indication that this is not a problem of the underlying JPA implementation?

I write test on hibernate. I guess it is.
Tests: https://github.com/vladmihalcea/high-performance-java-persistence/pull/69
