### ISSUE TITLE
FR Support simple limit clause

### ISSUE THREAD

**Issue by robertsearle** [spring-projects/spring-data-jpa#2287]
I would like the ability to write a simple limit query.   E.G. findAllBySomethingAndSomethingElseIsNullAnd _Limit500_

**Comment by schauder** [comment]
`findTop500BySomethingAndSomethingElseIsNullAnd`
or
`findFirst500BySomethingAndSomethingElseIsNullAnd` already work.

You should make sure the query is ordered in most use cases.
See
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.limit-query-result

**Comment by robertsearle** [comment]
Thanks Jens. Last question. I realize I need to limit with a runtime value. How can I pass in a value?  E.g  top 500 or 400?

________________________________

**Comment by schauder** [comment]
The proper place for usage questions ist StackOverflow. Github issues is for, well, issues.

But since you are here: you can pass a Pageable as an additional argument instead of the `top` or `first` name part.
