### ISSUE TITLE
EntityManagerBeanDefinitionRegistrarPostProcessor should set primary flag on EntityManager bean definitions

### ISSUE THREAD

**Issue by schosin** [spring-projects/spring-data-jpa#2288]
When creating multiple `LocalContainerEntityManagerFactoryBean` beans and marking one or more as primary, the created `EntityManager` beans should be marked as primary as well.

This change would make it easier to add another `EntityManager` to an existing application as no further code changes are necessary. Currently Spring fails to autowire `EntityManager` as there is no primary bean available.

This should also fix https://github.com/spring-projects/spring-framework/issues/24097.

**Comment by mp911de** [comment]
See also `AnnotationConfigUtils.processCommonDefinitionAnnotations` for possible missing flags.
