### ISSUE TITLE
Add support for group in ExampleMatcher

### ISSUE THREAD

**Issue by jhonnytuba** [spring-projects/spring-data-jpa#2291]
Currently, using Example with ExampleMatcher, you can only create queries using fields with MatchMode.ALL and MatchMode.ANY, for example:

`field1 = ?0 and field2 = ?1 and field2 = ?2`
`or`
`field1 = ?0 or field2 = ?1 or field2 = ?2`

`ExampleMatcher`
`        .matchingAll()`
`        .withMatcher("field1", GenericPropertyMatcher::exact)`
`        .withMatcher("field2", GenericPropertyMatcher::exact)`
`        .withMatcher("field2", GenericPropertyMatcher::exact)`

The proposal would be to add support for creating queries using groups in ExampleMatcher, for example:

`(firstname = ?0 or lastname = ?1) and age = ?2 and (title = ?3 or description = ?4)`
`or`
`(firstname = ?0 and lastname = ?1) or age = ?2 or (title = ?3 and description = ?4)`

`ExampleMatcher`
`        .matchingAll()`
`        .withMatcher("firstname", matcher -> matcher.exact().groupSpecifier("firstLastname", MatchMode.ANY))`
`        .withMatcher("lastname", matcher -> matcher.exact().groupSpecifier("firstLastname", MatchMode.ANY))`
`        .withMatcher("age", GenericPropertyMatcher::exact)`
`        .withMatcher("title", matcher -> matcher.exact().groupSpecifier("titleDescription", MatchMode.ANY))`
`        .withMatcher("description", matcher -> matcher.exact().groupSpecifier("titleDescription", MatchMode.ANY))`

**Comment by jhonnytuba** [comment]
PR
https://github.com/spring-projects/spring-data-jpa/pull/2292
https://github.com/spring-projects/spring-data-commons/pull/2442

**Comment by schauder** [comment]
We are not going to merge this change. For an explanation why see https://github.com/spring-projects/spring-data-commons/pull/2442#issuecomment-914052573

**Comment by schauder** [comment]
We are not going to merge this change. For an explanation why see https://github.com/spring-projects/spring-data-commons/pull/2442#issuecomment-914052573
