### ISSUE TITLE
Projection class receiving a Set of a @ManyToMany relationship?

### ISSUE THREAD

**Issue by GoncaloAC** [spring-projects/spring-data-jpa#2293]
So i have this entity and this query
`public class TutorialDAO extends AbstractDAO {

    private Boolean visible;

    @ManyToMany(mappedBy = "tutorials", cascade = CascadeType.ALL)
    private Set<TopicDAO> topics;

    @MapKey(name = "id.locale")
    @OneToMany(mappedBy = "tutorial", cascade = CascadeType.ALL, orphanRemoval = true)
    private Map<String, Localization> localizations;

    @MapKey(name = "id.locale")
    @OneToMany(mappedBy = "tutorial", cascade = CascadeType.ALL, orphanRemoval = true)
    private Map<String, JsonData> json;
}
public interface TutorialRepository extends JpaRepository<TutorialDAO, UUID> {

    @Query("select new com.fullstack.dtos.TutorialDTO(t.id, t.createdBy, t.lastModifiedBy, t.created, t.lastModified, t.version, t.visible, l.title, l.description, l.footnote, topics) from tutorials t inner join t.localizations l left join fetch t.topics topics where l.id.locale = :lang and l.title like %:title%")
    Page<TutorialDTO> findAllByTitle(String lang, String title, Pageable pageable);

}
`
Now in the projection im mapping a TopicDAO to the Set basically using Set.of from the set interface. and it works. The problem is says page 1 of 1 because the database only has one item so spring is basically replicating the recipe for as many topics as it has. If i include more info on the prints, it all matches, including the @Id of the recipe meaning is the same. Is there any keywork in JPQL im missing to force this topics to go into a Collection of some sort? I even have SQL queries being logged from hibernate and it does a select * from topics where... multiple times (one for each topic) instead of selecting and returning as a collection
I have also tried with interface based projections the result is the same, it all ends up separated eacly the same way, 10 objects in the page with each topic (basically 10 replicas of the recipe one for each topic).
Now this has some strange behaviour. If in my TutorialDTO constructor (the projection) if the "topics" variable is a TopicDAO it works but returns a page that should have one item (but instead has a copy of that exact item for each topic in the relationship) ,  if i set the "topics" variable to a Set<TopicDAO> as it should it straight up blows up complaining about type diferences. Is this meant to not work or am i missing a JPQL keywork here?

**Comment by schauder** [comment]
This is a limitation of JPQL. Collections are not allowed in constructor expressions.

See Section 4.8 of the JPA Specification or this SO answer: https://stackoverflow.com/a/6004072/66686
