### ISSUE TITLE
Add cross-field validation for countQuery param in @Query with Pagable and nativeQuery=true

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-data-jpa#2306]
Would it be possible to add some kind of check for nativeQuery in use with `Pageable`, that if `nativeQuery = true`, then `countQuery` should **not** be blank?

I was adding a `Pageable` to an existing `@Query(nativeQuery = true)` statement, and search for hours finding that it needs the `countQuery` set explicit.

Instead, the error logged was very unspecific and misleading:
```
2021-09-20 16:01:39,831 WARN o.h.e.j.s.SqlExceptionHelper: SQL Error: 1064, SQLState: 42000
2021-09-20 16:01:39,831 ERROR o.h.e.j.s.SqlExceptionHelper: (conn=173) You have an error in your SQL syntax; check the 
  manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP) FROM person GROUP BY dob' at line 1
```

There is also an old SO question that complained about the same fact (unspecific GROUP syntax error when using Pageable with nativeQuery): https://stackoverflow.com/questions/58092671/spring-boot-native-sql-query-with-pagination-not-working

I know that the docs explicit state that `countQuery` is required. But wouldn't it be great if Spring could detect this error and tell the user to set a count query explicit? Some kind of cross-field validation?

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.at-query.native

`You can, however, use native queries for pagination by specifying the count query yourself, as shown in the following example: `

```
public interface UserRepository extends JpaRepository<User, Long> {

  @Query(value = "SELECT * FROM USERS WHERE LASTNAME = ?1",
    countQuery = "SELECT count(*) FROM USERS WHERE LASTNAME = ?1",
    nativeQuery = true)
  Page<User> findByLastname(String lastname, Pageable pageable);
}
```

**Comment by schauder** [comment]
Unfortunately the parser trying to take the original SQL statement apart in order to construct a correct count query is far from perfect and sometimes fails.

But in general a count query is not required and we therefore won't add a check that claims so.
