### ISSUE TITLE
getById Optional return type ignored

### ISSUE THREAD

**Issue by stephane-dereppe** [spring-projects/spring-data-jpa#2321]
I just migrated to the lastest spring boot version (2.5.5) using Spring Data 2021.0.5.

When I add a method like this on an interface extending CrudRepository;

`Optional<School> getById(String schoolId);`

The `Optional` return type seems to be ignored. If the entity do not exist, I don't get an empty Optional but I get an `EntityNotFoundException`.

It works just fine with Spring boot 2.4.11 (Spring Data 2020.0.13).

Can that be considered as a regression?

**Comment by schauder** [comment]
This is a side effect of renaming `getOne` to `getById` in #1697.

As a workaround you can change the name of your method by introducing an arbitrary phrase between `get` and `By`. For example `getOptionalById`.
