### ISSUE TITLE
Count query removes `distinct` phrase if from part of JPA query contains newline character 

### ISSUE THREAD

**Issue by kaliberr44** [spring-projects/spring-data-jpa#2341]
It seems that there is newline character after the entity alias name in `FROM` part of the query before the `JOIN` the distinct is removed from the count.

Incorrect behavior:
 
```java
@Query("""
    SELECT DISTINCT entity1
    FROM Entity1 entity1 
    LEFT JOIN Entity2 entity2 ON entity1.key = entity2.key""")
```

returns
 
```
select count(entity1) FROM Entity1 entity1
LEFT JOIN Entity2 entity2 ON entity1.key = entity2.key
``` 

Correct behaviour:
```java
@Query("""
    SELECT DISTINCT entity1
    FROM Entity1 entity1 LEFT JOIN Entity2 entity2 ON entity1.key = entity2.key""")
```

returns
 
```
select count(DISTINCT entity1) FROM Entity1 entity1 LEFT JOIN Entity2 entity2 ON entity1.key = entity2.key
``` 

From testing if the `FROM` and `JOIN` are in the same line, and `WHERE` is new line then this incorrect behavior  also occurs.

For now I have solved it with `countProjection = "distinct entity1"`.

**Comment by ruslanys** [comment]
Please have a look https://github.com/spring-projects/spring-data-jpa/issues/2177#issuecomment-1112081785
