### ISSUE TITLE
org.springframework.roo:org.springframework.roo.annotations:pom:1.2.3.RELEASE was not found

### ISSUE THREAD

**Issue by RouxAntoine** [spring-projects/spring-data-jpa#2347]
Hello everybody, 

I have a relatively similar error to https://github.com/spring-projects/spring-data-jpa/issues/2285 

I add `spring-boot-starter-data-jpa` version 2.5.5 to the pom.xml project : 

like this (some exclusion to avoid dependency conflict)

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.google.code.findbugs</groupId>
					<artifactId>annotations</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.google.code.findbugs</groupId>
					<artifactId>jsr305</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.javassist</groupId>
					<artifactId>javassist</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

with maven 3.6.3 : `mvn clean verify -DskipTest=true` give a build success

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

with maven 3.8.2 : `mvn clean vertify -DskipTest=true` give  error

```
org.springframework.roo:org.springframework.roo.annotations:pom:1.2.3.RELEASE was not found in https://repo.spring.io/milestone during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spring-milestones has elapsed or updates are forced
```

Tried workaround : 

- fixed version 2.0.0-RELEASE

```
			<dependency>
				<groupId>org.springframework.roo</groupId>
				<artifactId>org.springframework.roo.annotations</artifactId>
				<version>2.0.0.RELEASE</version>
			</dependency>
```

give following error

```
org.springframework.roo.wrapping:org.springframework.roo.wrapping.inflector:pom:0.7.0.010 was not found in https://repo.spring.io/milestone during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spring-milestones has elapsed or updates are forced
```

- with version 1.3.2-RELEASE 

```
			<dependency>
				<groupId>org.springframework.roo</groupId>
				<artifactId>org.springframework.roo.annotations</artifactId>
				<version>1.3.2.RELEASE</version>
			</dependency>
```

build success again.

- try fixinig querydsl version failed too 

```
			<dependency>
				<groupId>com.querydsl</groupId>
				<artifactId>querydsl-jpa</artifactId>
				<version>5.0.0</version>
				<optional>true</optional>
			</dependency>
```

Always requiring org.springframework.roo.annotations version 1.2.3.RELEASE

```
org.springframework.roo:org.springframework.roo.annotations:pom:1.2.3.RELEASE was not found in https://repo.spring.io/milestone during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of spring-milestones has elapsed or updates are forced
```

maybe due to https://github.com/querydsl/querydsl/issues/3005
and fix with querydsl release 5.0.0 https://github.com/querydsl/querydsl/releases/tag/QUERYDSL_5_0_0
but it seem difficult to find which dependency really include `org.springframework.roo:org.springframework.roo.annotations`

cordially

**Comment by RouxAntoine** [comment]
Spring querydsl always use legacy version of org.springframework.roo.annotations here 

https://github.com/querydsl/querydsl/blob/26f3c89a8a007a9135eb57f095b07e6fc24c516d/querydsl-apt/pom.xml#L58

so overloading repositories into your project cause missing repo :

adding this solve issue

```
  <repositories>
    <!--for org.springframework.roo:org.springframework.roo.annotations -->
    <repository>
      <id>spring roo repository</id>
      <url>https://spring-roo-repository.springsource.org/release</url>
    </repository>
  </repositories>
```

or exclude org.springframework.roo from spring-data-jpa :

```
				<exclusion>
					<groupId>org.springframework.roo</groupId>
					<artifactId>org.springframework.roo.annotations</artifactId>
				</exclusion>
```

**Comment by schauder** [comment]
This is essentially the same as #2285 and just as that it is a problem of Querydsl. 
Thanks for posting the work arounds.

**Comment by RouxAntoine** [comment]
Thanks for fast answering,  Any idea why it work with maven 3.6.3 ?

**Comment by schauder** [comment]
Just a guess, but maybe maven changed the order in which it applies dependencies and repository configurations. You could generate the effective pom for both variants and diff them to get an idea what is going on. Also, `mvn dependency:tree` will tell you where a dependency is coming from.
