### ISSUE TITLE
Add FlushModeType to the Query annotation

### ISSUE THREAD

**Issue by simasch** [spring-projects/spring-data-jpa#2355]
From time to time I need to use `FlushModeType.COMMIT`

But I couldn't find a way to specify this on an interface method using `@Query`.

Did I miss something or is this feature missing?

**Comment by schauder** [comment]
That simple feature rises a surprising amount of questions on our side. Could you clarify your use case? As in why do you want to change the flush mode for a few queries?

**Comment by simasch** [comment]
We have a use case where we don't want to flush the persistence context because the update statements will execute some triggers in the database too early.

**Comment by schauder** [comment]
Since this seems a rather special use case, we are not going to implement this.
