### ISSUE TITLE
Add method `saveAllAndFlushThenClear` to `JpaRepository` for chunked batch insert/update

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-data-jpa#2356]
Here is a typical batch insert example:
```java
	@Transactional
	public void batchInsert() {
		int size = 99999;
		int batchSize = 10; // hibernate.jdbc.batch_size
		List<Customer> batch = new ArrayList<>(batchSize);
		for (int i = 1; i <= size; i++) {
			Customer customer = new Customer();
			batch.add(customer);
			if (i % batchSize == 0) {
				customerRepository.saveAllAndFlush(batch);
				entityManager.clear(); // avoid potential OOM
				batch.clear();
			}
		}
		if (!batch.isEmpty()) {
			customerRepository.saveAllAndFlush(batch);
		}
	}

```
It would be nice if `JpaRepository` have method `saveAllAndFlushThenClear(entities)`, then we can eliminate explicit `entityManager.clear()`.

**Comment by mp911de** [comment]
That's not something we are going to do. You might want to check out Spring Batch specifically for batch-wise processing of data. Other than that, your use-case is overly specific and not so general that it justifies the effort on our side.

**Comment by quaff** [comment]
I think `clear` should be treated as same as `flush`.
