### ISSUE TITLE
Support `TypedParameterValue` of `hibernate-orm`

### ISSUE THREAD

**Issue by heowc** [spring-projects/spring-data-jpa#2366]
`hibernate-orm` supports `TypedParameterValue` for binding parameters. 
Are you thinking of supporting this?

See https://docs.jboss.org/hibernate/orm/5.0/javadocs/org/hibernate/jpa/TypedParameterValue.html

**Comment by heowc** [comment]
I wasn't good at testing, and it was already supported.

However, I thought I would like to use it in a different way. :thinking: 

For example:
1. We usually create a separate interface that inherits from JpaRepository. (ex, AccountRepository)
2. And by writing methods and `@Query`, it works internally as a named query or a native query.
3. Here, there is an issue where the native query does not know the exact type as a result. If null , this type is not clearly known. And this behaves differently depending on the sql-driver. (I found the following issue with hibernate: https://hibernate.atlassian.net/browse/HHH-14778)
4. To solve this, we use `TypedParameterValue` to tell hibernate the type.
5. If we use `spring-data-jpa` and write a method in the interface, we know the parameter, so if we wrap it with `TypedParameterValue` internally, there is no need to do the same thing as in 4.

WDYT?

**Comment by schauder** [comment]
Thanks for confirming that `TypedParameterValue` is properly supported. 

As for the new idea. Could you please create a separate issue for it, so we can have one issue per idea/problem?
