### ISSUE TITLE
Improvements to clarify type using `TypedParameterValue`

### ISSUE THREAD

**Issue by heowc** [spring-projects/spring-data-jpa#2370]
When using a native query, null value binding behaves differently depending on the SQL driver.
(For example, I faced the following issue with hibernate + postgres combination. - https://hibernate.atlassian.net/browse/HHH-14778)

But since we know the type when we write methods in `JpaRepository`, we can use `TypedParameterValue` (or otherwise) to clearly know the type of the parameter.

This issue is derived from #2366.

**Comment by AndreasALoew** [comment]
I'd also like to see this happen very soon if possible, as otherwise we need to work around it large scale... :-(

See https://hibernate.atlassian.net/browse/HHH-14411 for more details...
