### ISSUE TITLE
BindableQuery causes NullPointerException when using proxy over Query

### ISSUE THREAD

**Issue by conservative-dude** [spring-projects/spring-data-jpa#2380]
I use Spring AOP to create proxy over `Query` and this code in `QueryParameterSetter.java` causes me `NullPointerException`:

```java
BindableQuery(QueryMetadata metadata, Query query) {
			super(metadata);
			this.query = query;
			this.unwrapped = Proxy.isProxyClass(query.getClass()) ? query.unwrap(null) : query;
		}
```
[source](https://github.com/spring-projects/spring-data-jpa/blob/main/src/main/java/org/springframework/data/jpa/repository/query/QueryParameterSetter.java#L301)

And `unwrap` in hibernate is implemented as
```java
	@Override
	@SuppressWarnings("unchecked")
	public <T> T unwrap(Class<T> cls) { // <<<< cls is null here
		if ( cls.isInstance( getProducer() ) ) {
			return (T) getProducer();
		}
		if ( cls.isInstance( getParameterMetadata() ) ) {
			return (T) getParameterMetadata();
		}
		if ( cls.isInstance( getQueryParameterBindings() ) ) {
			return (T) getQueryParameterBindings();
		}
		if ( cls.isInstance( this ) ) {
			return (T) this;
		}

		throw new HibernateException( "Could not unwrap this [" + toString() + "] as requested Java type [" + cls.getName() + "]" );
//		throw new IllegalArgumentException( "Could not unwrap this [" + toString() + "] as requested Java type [" + cls.getName() + "]" );
	}
```
[source](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/query/internal/AbstractProducedQuery.java#L1419)

**Comment by schauder** [comment]
That unwrapping was introduced for performance reasons. So it is probably possible to undo it.

But before doing so, we'd like to understand what is your use case here: What is the goal of creating a proxy over a `Query` object?

**Comment by krechun** [comment]
Hi,

I want to track metrics related to execution time and exceptions if there are any.

**Comment by mp911de** [comment]
The assumption that we make in `BindableQuery` is the use of JDK proxies. Neither Hibernate nor Eclipselink are using JDK proxies for this use-case, only [Spring Framework](https://github.com/spring-projects/spring-framework/blob/ce253041c56a0b5f84013e397f767330744bc4d8/spring-orm/src/main/java/org/springframework/orm/jpa/SharedEntityManagerCreator.java#L378-L385) does so in the context of `SharedEntityManagerCreator`. For this use-case we're unproxying the `Query` to avoid performance penalty.

If you're proxying `Query` yourself with a JDK proxy, then your implementation should react to `class` being `null` and either return the proxy object if you want to record metrics or return the underlying `Query` object to gain performance.

**Comment by mp911de** [comment]
Closing as this ticket is not actionable. If you would like us to look at this issue, please provide additional information and we will re-open the issue.
