### ISSUE TITLE
Add annotation which will automatically add join fetch to query.

### ISSUE THREAD

**Issue by mateuszwinnicki** [spring-projects/spring-data-jpa#2382]
Currently, for the 1+n problem, we can only create custom queries with a join fetch (or add something like @Batchsize, which is not a solution, because we still have additional queries).

Consider adding some custom annotation that can be annotated on the method repository which will automatically add join fetch.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mateuszwinnicki** [comment]
Correct, it can be achived by using 
`@NamedEntityGraphs({
        @NamedEntityGraph(
                name = Address.WITH_USER_GRAPH,
                attributeNodes = {
                        @NamedAttributeNode("user")
                }
        )
})`

And then annotate repository method

`
@EntityGraph(Address.WITH_USER_GRAPH)
    List <Address> findByUserId(Long userId);
    `

**Comment by schauder** [comment]
This is what entity graphs are for and as you verified, they work as desired.
I'm therefore closing this issue.
