### ISSUE TITLE
`AbstractMapping.getPersistentEntity(Class<?> type)` fails to lookup the `PersistentEntity` when the provided type is a `HibernateProxy`

### ISSUE THREAD

**Issue by alienisty** [spring-projects/spring-data-jpa#2383]
From my analysis, the regression has been added by commit c866b4202527b3acc64e7cc205a98a8aa754cb59 where "ClassTypeInformation now never unwraps the user type to consistently work with the type originally presented in the lookup..."

The assumption in that comment might be incorrect, I would be surprised if PersistentEntity instances are mapped against an HibernateProxy class.

I believe that at least ClassTypeInformation.from(Class type) should have retained the type unwrapping.

This is a minimal demonstrating project which also shows the impact on Spring Data REST
[demo.zip](https://github.com/spring-projects/spring-data-commons/files/7593104/demo.zip)

**Comment by mp911de** [comment]
I transferred the ticket into the JPA project as we can easily fix the issue here.
