### ISSUE TITLE
Inject Repository into RepositoryCustom

### ISSUE THREAD

**Issue by niroussel** [spring-projects/spring-data-jpa#2384]
Until SpringBoot 2.4.1, it was possible to inject a repository into its custom implementation.

This was really useful to avoid having several repositories for the same Entity.

For example, this doesn't work anymore:

 - <package 'data'>
    - UserRepository.java
    - <packages 'data.custom'>
         - UserRepositoryCustom.java
         - UserRepositoryImpl.java

With :

```java
public class UserRepositoryImpl implements UserRepositoryCustom {

    @Autowired
    private UserRepository repo;

    public List<User> veryComplicatedSearch() {
        ....
        ....
        return repo.findAll(veryComplicatedPredicate);
    }
}
```

This will lead to this exception:

```
      ↓
┌─────┐
|  userRepositoryImpl (field private data.UserRepository data.custom.UserRepositoryImpl.repo)
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```

**Comment by mp911de** [comment]
In short, this isn't possible as repository fragments are required to create the repository instance. You can either work around it by using `@Lazy` or `ObjectProvider` (or look up the repository instance at the time of using it via `ApplicationContext`).

**Comment by RadouaneRoufid** [comment]
What's the correct approach to address this problem without using the workarounds above ?

What if the fragment needs the repository as mentioned by @niroussel ?


```
public class UserRepositoryImpl implements UserRepositoryCustom {

    @Autowired
    private UserRepository userRepository;

    @Override
    public List<User> searchByCriteria(UserSearchCriteria searchCriteria) {
        return userRepository.findAll(UserSpecifications.build(searchCriteria));
    }
}
```

**Comment by sergey-volkov-lm** [comment]
> What's the correct approach to address this problem without using the workarounds above ?

Maybe one of:

- using default methods inside UserRepository interface
- creating UserService/UserSearchService, which hosts additional logic for working with repository

**Comment by samuelpsfung** [comment]
I've this workaround

```java
@Repository
public class UserRepositoryImpl implements UserRepositoryCustom {

    @PersistenceContext
    private EntityManager entityManager;

    private JpaSpecificationExecutor<User, String> executor;

    @PostConstruct
    public void init() {
        executor = new SimpleJpaRepository<User, String>(User.class, entityManager);
    }

    @Override
    public List<User> searchByCriteria(UserSearchCriteria searchCriteria) {
        return executor.findAll(UserSpecifications.build(searchCriteria));
    }
}
```

> creating UserService/UserSearchService, which hosts additional logic for working with repository

i think the query logic should be kept in the repository layer; should not be leaked to the service layer.
