### ISSUE TITLE
@Transactional annotation in spring JPA

### ISSUE THREAD

**Issue by aditya-kapre-shrewsbury** [spring-projects/spring-data-jpa#2387]
Will @Transactional annotation used with timeout do following?

1. Will it close the DB connection after timeout ?
2. Will it release the read locks that might have been on db due to a long running query ?

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.
