### ISSUE TITLE
Add exists method to JpaSpecificationExecutor

### ISSUE THREAD

**Issue by StanislauParuchnik** [spring-projects/spring-data-jpa#2388]
While there is `QueryByExampleExecutor.exists(Example<S> example)` which under the hood builds `Specification` from `Example` to execute exists query, there is no method which accepts `Specification` object to execute exists query.
Implementation is pretty simple and I can provide a PR

**Comment by quaff** [comment]
PR is welcome.

**Comment by schauder** [comment]
@quaff (Regarding deleted comment) please let maintainers decide on these kind of things. Currently this issue is marked as  `waiting-for-triage` for a reason.

**Comment by schauder** [comment]
> I can provide a PR
A PR would be welcome.

**Comment by DiegoKrupitza** [comment]
Can I work on this issue?

**Comment by schauder** [comment]
That's merged. Thanks.
