### ISSUE TITLE
create auto rest api base of entety(for crud)

### ISSUE THREAD

**Issue by loveyandex** [spring-projects/spring-data-jpa#2390]
we did not see a good automation for creating app 

we have to write redundant  code many times 
for updating a field in a enetety

but spring boot must automate this feature 

spring rest data is very pooor 

what should i do now ..

**Comment by schauder** [comment]
Sorry, but this issue tracker is for specific feature requests or bug reports agains Spring Data JPA. We cannot act on vague feature ideas on other projects.
