### ISSUE TITLE
Incorrectly generating count queries for queries starting with whitespaces.

### ISSUE THREAD

**Issue by jaoromi** [spring-projects/spring-data-jpa#2393]
Repository method annotated `@Query`, nativeQuery is true and containing pageable parameter generate incorrectly count query for starting with whitespaces.

For example, above method derived counter query `select count(where) from user where user.age > :age `.
```
@Query("   \n"
+ "select * from user where user.age > :age"
+ "\n    ")
Page<User> findByGreaterThanAge(int age, Pageable pageable);
```
But, If query starting without whitespace, `select count(*) from user where user.age > :age `

I found that org.springframework.data.jpa.repository.query.QueryUtils.COUNT_MATCH regex not matched select query starting whitespace. I think that it should be fix.

**Comment by gregturn** [comment]
While the example code you provided is SQL, not JPQL, I took your suggestion and added support for count queries starting with whitespace.

The query you wrote will only work if you turn on the nativeQuery flag.

**Comment by gregturn** [comment]
And given that handling whitespace before a count prefix isn't really a bug, I've relabeled this issue as an enhancement, and backported it to the previously supported versions.

Thanks for elevating this @jaoromi!
