### ISSUE TITLE
Instant datatype not supported in JPQL queries?

### ISSUE THREAD

**Issue by VanCoding** [spring-projects/spring-data-jpa#2396]
When I have the following JpaRepository:

```
interface OrderJpaRepository : JpaRepository<OrderEntity, Long> {
    @Query(
        """
        SELECT o
        FROM OrderEntity o 
        WHERE :dateFrom is null or o.orderDate >= :dateFrom
        ORDER BY o.orderDate DESC
    """
    )
    fun find(
        dateFrom: Instant?
    ): List<OrderEntity>
}
```

and the order entity is like
```
@Entity
@Table(name = "order", schema = "public")
class OrderEntity(
    //...
    var orderDate: Instant,
    //...
)
```

and I call `repository.find(Instant.now())` I get the error `org.postgresql.util.PSQLException: ERROR: could not determine data type of parameter`

Isn't `Instant` supported for JPQL queries?
I'm a bit confused that this error comes out of the postgres library itself. To me it looks like JPQL thinks everything's good but then postgres isn't.

I'm using org.springframework.boot:spring-boot-starter-data-jpa:2.6.2.

**Comment by schauder** [comment]
This is a pure Postgres / JPA / JPA implementation question unrelated to Spring Data.

You might be intersted in https://stackoverflow.com/questions/49309076/why-jpa-does-not-support-java-time-instant
