### ISSUE TITLE
Make toExpressionRecursively public

### ISSUE THREAD

**Issue by rubasace** [spring-projects/spring-data-jpa#2410]
I'm working on a tool that generates dynamic queries making use of the `CriteriaBuilder` API. My input comes from an UI that sends me which field it wants to query as well as the comparison it wants to do. In order to do so, I need to convert the target fields from something like `field1.field2` to an instance of `Expression` that represents that same field. 

This behaviour is the exact thing that `QueryUtils.toExpressionRecursively()` does but, currently, this is a private method only used by `toOrders()`. 

Given that the logic isn't trivial I'd like to use this method on my code. I'm currently using it via reflection but I was wondering if it would be ok to make the method public as it can be used to build dynamic queries like in my case.

**Comment by schauder** [comment]
`QueryUtils`  is an internal utility. Its methods are only public because they have to be accessible from other packages. We will not make methods public to encourage reuse of this class.

I recommend just copying the required code into your project.
