### ISSUE TITLE
JpaRepository#deleteAllByIdInBatch fails when (compound) IdClass keys are used

### ISSUE THREAD

**Issue by ejl888** [spring-projects/spring-data-jpa#2414]
When using an JpaRepository with an compound IdClass the deleteAllByIdInBatch methods fails with an IllegalArgumentException like:
```
java.lang.IllegalArgumentException: Parameter value element [DeviceGroupDeviceLink.Key(deviceGroupId=8602858a-9ac9-4e70-b381-b2e3163a5b66, deviceId=8cb39b4b-3922-4b65-8150-c5566dc7ffb4)] did not match expected type [java.util.UUID (n/a)],[B@2408dbed,false,2022-01-21 15:08:40.358601)]
```

Below a test I added to org.springframework.data.jpa.repository.RepositoryWithCompositeKeyTests that fails also (on 2.6.x branch).
```

@Autowired EntityManager em;

@Test
void shouldSupportDeleteAllByIdInBatchWithIdClass() throws Exception {

    IdClassExampleDepartment dep = new IdClassExampleDepartment();
    dep.setName("TestDepartment");
    dep.setDepartmentId(-1);
    
    IdClassExampleEmployee emp = new IdClassExampleEmployee();
    emp.setDepartment(dep);
    emp = employeeRepositoryWithIdClass.save(emp);
    
    IdClassExampleEmployeePK key = new IdClassExampleEmployeePK(emp.getEmpId(), dep.getDepartmentId());
    assertThat(employeeRepositoryWithIdClass.findById(key)).isNotEmpty();
    
    employeeRepositoryWithIdClass.deleteAllByIdInBatch(Arrays.asList(key));

    em.flush();
    em.clear();
    
    assertThat(employeeRepositoryWithIdClass.findById(key)).isEmpty();
}

```

Could this be fixed and back ported to the 2.5 branch also? Because we are running Spring Boot 2.5.

**Comment by ejl888** [comment]
The code in deleteAllInBatch uses a different approach to do the deletion. It creates an OR query. Could this be used as solution for this method also?

As a workaround I use the deleteAllInBatch in combination with getById currently, but I think deleteAllByIdInBatch should handle compound IdClass id's also.

**Comment by ejl888** [comment]
Possible fix in SimpleJpaRepository

```
	@Override
	@Transactional
	public void deleteAllByIdInBatch(Iterable<ID> ids) {

		Assert.notNull(ids, "Ids must not be null!");

		if (!ids.iterator().hasNext()) {
			return;
		}

		if (entityInformation.hasCompositeId()) {
			List<T> entities = new ArrayList<>();
			ids.forEach(id -> entities.add(getById(id)));
			deleteAllInBatch(entities);
		} else {
			String queryString = String.format(DELETE_ALL_QUERY_BY_ID_STRING, entityInformation.getEntityName(),
					entityInformation.getIdAttribute().getName());

			Query query = em.createQuery(queryString);
			query.setParameter("ids", ids);

			query.executeUpdate();
		}
	}
```

**Comment by ejl888** [comment]
I created a fork with both test and (quick) fix. But do not know how to create a PR/MR (yet).

**Comment by schauder** [comment]
See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by ejl888** [comment]
I left the original code intact in case of non compound keys, because the generated in query suits the simple case better.

**Comment by ejl888** [comment]
@schauder , I created a PR. Can I ask you to review it or is there another way to ask for review?

**Comment by ejl888** [comment]
Thx @schauder
