### ISSUE TITLE
Deserialization of Java Money with zalando/jackson-datatype-money fails after upgrade to Spring Boot 2.3.5

### ISSUE THREAD

**Issue by darioseidl** [spring-projects/spring-data-jpa#2421]
After the [serialization issue](https://github.com/spring-projects/spring-data-rest/issues/2056) was fixed (thank you!), I tried again to upgrade Spring Boot.

This time, we're having problems with the *De*serialization on PATCH request of Java Money.

There are two problems:

1) The first is apparently caused by https://github.com/spring-projects/spring-data-rest/issues/1743, and very similar to the following reports:
https://github.com/spring-projects/spring-data-rest/issues/1881
https://github.com/spring-projects/spring-data-rest/issues/1911
https://github.com/spring-projects/spring-data-rest/issues/1928

A check was introduced, that if a `JsonNode` doesn't map to a writable property, the `JsonNode` is removed and ignored.
That's a problem whenever the JSON doesn't map directly to a property in the entity, but is converted or parsed in any other way: transient fields with setters, `@JsonSetter`, or custom serializers.

On the original issue there was also the comment 

> We unfortunately need to revisit the fix for this here in the course of fixing DATAREST-1524. I looks like inspecting the persistence configuration regarding updatability is the wrong place to start with as that can be at odds with what's expected to happen at the JSON binding level. For the latter, there actually is e.g. @JsonProperty(access = Access.READ_ONLY). I.e. if you want to prevent the binding to it you actually would need to annotate it that way

but I don't think the fix has been been revisited.

2) The second problem is caused by the [same change in Hibernate](https://hibernate.atlassian.net/browse/HHH-14198) that also caused the serialization issue earlier. A `CompositeUserType` like the Jadira `PersistentMoneyAmountAndCurrency` is now registered in the Hibernate metamodel as an embeddable and the `DomainObjectReader` check with `isEntity` whether a type is managed by Hibernate (IMO, `isEntity` is a bit of a misnomer here, it not only checks for entities, but for any managed type: entities, mapped superclasses and embeddables). So, now a `Money` is treated as an entity with nested properties, instead of passing it as a value object to the `MonetaryAmountDeserializer`. Maybe `isEntity` could return false `CompositeUserTypes`? (I'm not sure how to do that without some Hibernate-specific code and it probably needs to have no knowledge of Hibernate here.)

I have setup a [demo](https://github.com/darioseidl/demo-2102) to reproduce the issues (with some hacky workarounds).

**Comment by odrotbohm** [comment]
Fixes in place in all branches (`2.5.x`, `2.6.x`, `main`, `3.0.x`). The provided sample project builds fine against the `2.5.x` one, but feel free to give the snapshots a try.

**Comment by darioseidl** [comment]
Thank you for the quick fix! I tried with `spring-data-jpa.2.5.9-SNAPSHOT` and it's working. 

I assume the fix for the custom user type being seen as embeddable fixed the whole thing. The other issue, of JsonNodes not mapping to writeable properties might still exist, but doesn't affect us with the Money deserialization now (because the money object is mapped to a writeable property, only the "amount" wasn't).
