### ISSUE TITLE
spring-data-jpa schema validation error with SQL-SERVER(MSSQL)

### ISSUE THREAD

**Issue by todak-sun** [spring-projects/spring-data-jpa#2422]
-----------------------------------------------
Version : spring-boot-starter-data-jpa:2.6.2
-----------------------------------------------

Hi, I'm using on project in my company spring-data-jpa.
Recently, we update spring-boot version 2.5.X to 2.6.2, but met error.

If you validate schema(spring.jpa.hibernate.ddl-auto: validate), query sequneces from [INFORMATION_SCHEMA.SEQUENCES].
Executing query like 'select * from INFORMATION_SCHEMA.SEQUENCES' on 2.5.X, 
but on 2.6.2 (or else then upper version) 
' select convert(bigint, maximum_value) as maximum_value
...
 from INFORMATION_SCHEMA.SEQUENCES
' then application could not load because our some sequences have maxiumu_value grater then MAX_VALUE of 'big int' type.

So I have questions: 

How can we fix this error? We should change our sequneces maximum value? 
or Can we solve this problem with simple way on application setting? 

Regards.

**Comment by schauder** [comment]
The validation is done by Hibernate, so I can only comment as any user of Hibernate could.
And yes it sounds like reducing the maximum value of the sequence should solve the problem.
I assume if you use an older version of Hibernate the error, but not the underlying problem would go away as well.

Of course, you could also disable the validation, but that is probably not in your best interest.

Anyway, this issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jpa`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.
