### ISSUE TITLE
NullPointerException in JpaQueryCreator#complete after updating to 2.6.1

### ISSUE THREAD

**Issue by koh-osug** [spring-projects/spring-data-jpa#2425]
After the update my Unit test fails maybe because of the this [change](https://github.com/spring-projects/spring-data-jpa/compare/2.6.1..2.6.0#diff-088d8b57b29d15a0af76d2342d6e9e7e625f5d826564abc8b2fad8b481dde681L179). `typeToRead` is `null`. Only a specific use case using a projection and a pagination is effected `Page<OrderCodeProjection> findByOrderCreationId(String orderCreationId, Pageable pageable);`. This code is returning a page using a projection just selecting 3 attributes of the order. What could be the reason for this defect?

**Comment by berndwaibel** [comment]
Could you please check if this is the same issues as mentioned in https://github.com/spring-projects/spring-data-jpa/issues/2408?

**Comment by koh-osug** [comment]
Yes, it seem to be a duplicate.
