### ISSUE TITLE
Dose ExampleMatcher  support in operate 

### ISSUE THREAD

**Issue by yadong2000** [spring-projects/spring-data-jpa#2455]
![image](https://user-images.githubusercontent.com/12443375/155668465-15994892-e961-420f-8d60-c4de9515f56f.png)
 
I want query article  with ids ,but i can't find  any in  method  with  ExampleMatcher  ,Dose ExampleMatcher  support in operate .

Maybe use @Query or  use em.createQuery(select * from article where id in (xxxx));

**Comment by mp911de** [comment]
No, there's no support for `IN` queries. This is by design as the `Example` typically matches your domain type and the mentioned `id` property is a singular attribute property, not a collection.

**Comment by yadong2000** [comment]
yeah  i know id is a  a singular attribute property.   ids is a collection ，have some Article id ( primary key in Article).
