### ISSUE TITLE
Could @Repository get more documentation?

### ISSUE THREAD

**Issue by sixcorners** [spring-projects/spring-data-jpa#2456]
The only reference to the Repository annotation is here:
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.namespace

This makes it sound like the difference between an interface with that annotation and one without is that the one with will get it's exceptions translated. Is that correct?

Or.. Is it for making non-spring-data-jpa classes that do get their exceptions translated?

Is there a kind of scanning that would cause a repository to only be picked up if it had the @Repository annotation on it?

**Comment by mp911de** [comment]
[`@Repository`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/stereotype/Repository.html) is a Spring Framework annotation. By registering repositories as beans, Spring Framework itself is going to detect whether it needs to register an AOP component for exception translation. All this is Framework functionality where Spring Data doesn't contribute anything specific.

Activating additional exception translation makes sense in case you're using JPA directly (e.g. using `EntityManager` directly) from a repository fragment and you want that JPA exceptions are being translated into Spring's DAO exceptions. 

Spring Data doesn't consider arbitrary classes annotated with `@Repository` as the annotation isn't related to Spring Data at all.
