### ISSUE TITLE
Broken Javadoc URL for milestone

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-data-jpa#2460]
https://spring.io/projects/spring-data-jpa#learn:

![grafik](https://user-images.githubusercontent.com/5071169/156059853-09966933-9601-4693-b932-0f8d36397bcd.png)

->

![grafik](https://user-images.githubusercontent.com/5071169/156059896-fbd18caf-173d-4a40-86dd-0600cf0eccb1.png)

Javadoc for Spring Data JDBC is also broken ...

**Comment by mp911de** [comment]
That's fixed now. The stylesheet issue for our Javadoc will be fixed with the next milestone.

**Comment by ullenboom** [comment]
Javadoc link in the announcement still broken for M2:

![grafik](https://user-images.githubusercontent.com/5071169/156143846-ea6a9d6d-faa5-43a6-9ad4-3778bd66aefd.png)

**Comment by mp911de** [comment]
Paging @schauder, seems the blog post points to 3.0 M2 but 3.0 M2 isn't released yet.

**Comment by schauder** [comment]
I removed the links since we don't release snapshot JavaDoc.
