### ISSUE TITLE
Is there a way make nullable @Embedded class filed  mark as nullable

### ISSUE THREAD

**Issue by micl9** [spring-projects/spring-data-jpa#2462]
when i add this nullable @Embedded class and it's  field as following:
```kotin
    @Embedded
    var deliveryStation: Station? = null
```
```
@Embeddable
data class Station(

    @Embedded
    var coordinate: Point2D,

    val unitNum: String,

    val roomNum: String,
)

```

then when i enable auto ddl - create

it will set Station unitNum field not null ,but it may be nullable 
```sql
 delivery_station_coordinate_x float not null
```

so Is there any method that can be set nullable

**Comment by schauder** [comment]
Mapping and schema generation is completely handled by your JPA implementation (Hibernate or EclipseLink most likely). Spring Data JPA does not control this behaviour
