### ISSUE TITLE
hibernate.proc.param_null_passing - deprecated

### ISSUE THREAD

**Issue by Drezir** [spring-projects/spring-data-jpa#2465]
Since this parameter is going to be deprecated soon, we have to enable param null pasing - probably through @Param annotation.

```java
    @Procedure(procedureName = "PROCEDURE")
    void updateContractName(@Param("contract") long constractNumber, @Nullable @Param("name") String newName);
```

This will not work when newName is null. Solution could be done using @Nullable or by using special attribute on @Param?

```java
    @Procedure(procedureName = "PROCEDURE")
    void updateContractName(@Param("contract") long constractNumber, @Nullable @Param(value "name", nullable = true) String newName);
```

**Comment by schauder** [comment]
I'm not sure what Spring Data JPA is supposed to do here. Wouldn't that something JPA needs to address? Is there a comment that goes with `hibernate.proc.param_null_passing`?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
