### ISSUE TITLE
H2 2.0.202+ use 1-based enums but JPA assumes 0-based ones

### ISSUE THREAD

**Issue by zapek** [spring-projects/spring-data-jpa#2474]
As reported in https://github.com/h2database/h2database/issues/3465

H2 changed the enums to be 1-based from H2 2.0.202 but JPA assumes 0-based enums.

**Comment by schauder** [comment]
This seems to be a JPA issue, not a Spring Data JPA issue since the mapping is done by the former.

**Comment by zapek** [comment]
Do you have any pointer to where I should report this?

**Comment by schauder** [comment]
Judging from the error message in the referenced issue, you are using Hibernate so that would mean issues should be reported here: https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues
