### ISSUE TITLE
first-level cache

### ISSUE THREAD

**Issue by SleepPerformer** [spring-projects/spring-data-jpa#2478]
JPA version is 2.3.12 and orm is Hibernate
Cache can work when I use findById but doesn't work when I use findByName
How can I use first-level cache for any sql?

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jdbc`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.

In this case the question isn't even about Spring Data JDBC but about JPA/Hibernate, therefore I recommend the tags `jpa` /  `hibernate`.
