### ISSUE TITLE
Subsequent call to a previouly successful request result to a InvalidDataAccessApiUsageException

### ISSUE THREAD

**Issue by fistons** [spring-projects/spring-data-jpa#2479]
Java version: Oracle OpenJDK 17.0.1
Spring Boot version: 2.6.6

I have a very simple repository to list my entities by name starting with a prefix:

```java
package org.example.issue.repository;

import org.example.issue.entity.MyEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MyEntityRepository extends JpaRepository<MyEntity, Long> {

  List<MyEntity> findByNameStartsWith(String namePrefix);
}
```

And a very simple service calling it :

```java
package org.example.issue.service;

import org.example.issue.entity.MyEntity;
import org.example.issue.repository.MyEntityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.stream.Collectors;

@Service
public class MyEntityService {

  private final MyEntityRepository repository;

  @Autowired
  public MyEntityService(MyEntityRepository repository) {
    this.repository = repository;
  }

  public List<String> getSimilarEntitiesName(String prefix) {
    List<MyEntity> similarEntities = this.repository.findByNameStartsWith(prefix);

    return similarEntities.stream()
        .map(MyEntity::getName)
        .collect(Collectors.toList());
  }
}
```

The first call to `getSimilarEntitiesName(String name)` works as expected, but each subsequent calls give me an exception: `org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [\] did not match expected type [java.lang.String (n/a)]` 

Weirdly enough, when I add `@Param` in my repository's method's argument everything works fine:

```java
package org.example.issue.repository;

import org.example.issue.entity.MyEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MyEntityRepository extends JpaRepository<MyEntity, Long> {

  // This works!
  List<MyEntity> findByNameStartsWith(@Param("namePrefix") String namePrefix);
}
```
Here is a complete sample project: [spring-data-jpa-issue.zip](https://github.com/spring-projects/spring-data-jpa/files/8397372/spring-data-jpa-issue.zip)

**Comment by antoniosanct** [comment]
Impressive! The same with 'Containing' keyword.

**Comment by creatorKoo** [comment]
I have same issue. 
OpenJDK 11 with spring boot 2.6.6.
And of course jpa with "startsWith".

I think this is a critical issue. i hope it gets fixed VERY soon.

And thanks @fistons to give me work-around solution!

**Comment by fistons** [comment]
Looks like a duplicate of https://github.com/spring-projects/spring-data-jpa/issues/2472
