### ISSUE TITLE
Feature Request: Optimized "In" Clause for very long lists of arguments

### ISSUE THREAD

**Issue by nightswimmings** [spring-projects/spring-data-jpa#2483]
It would be nice to have some derived suffix for IN clauses of very long lists. There is a limit on most rbdms engines so the query cannot be long.
Something like findByIdInBatch(List<UUID> ids) that does not translate into  SELECT .. IN (a,b,c,d,...) but an underlying optimized query (perhaps creating a temporary table and then a JOIN?)

**Comment by quaff** [comment]
It increase unnecessary complexity from framework perspective, and developer must concern massive memory consumption from application perspective.

**Comment by nightswimmings** [comment]
At least the framework could provide an util or something to iterate batch needs. I know spring-batch is available, but I am just talking about easening a repository.save(list) for list > 1000 elements, for instance
