### ISSUE TITLE
There is a problem with deleting many to many association.

### ISSUE THREAD

**Issue by baggio1103** [spring-projects/spring-data-jpa#2485]
@Entity
@Table(name = "users")
public class User {

    @Id
    private Long id;

    private String name;

    @ManyToMany(cascade = {PERSIST, MERGE})
    @JoinTable(name = "user_following",
            joinColumns = {@JoinColumn(name = "user_id")},
            inverseJoinColumns = {@JoinColumn(name = "user_following_id")})
    private List<User> following;

    @ManyToMany(cascade = {PERSIST, MERGE})
    @JoinTable(name = "user_followers",
            joinColumns = {@JoinColumn(name = "user_id")},
            inverseJoinColumns = {@JoinColumn(name = "user_follower_id")})
    private List<User> followers;
    
    //some other fields, getters and setters

    public void follow(User user) {
        following.add(user);
        user.acceptFollower(this);
    }

    public void acceptFollower(User user) {
        followers.add(user);
    }

}

We have three tables:
- users
- user_following
- user_followers

Imagine having this entity and you are implementing following & followers functionality. 
We have to users - rick & tom.
User rick = new User(1, "rick");
User tom = new User(2, "tom");
rick.follow(tom);

After calling method - rick.follow(tom);
We will populate our tables in the following way

Table - "users"
| id | name |
| 1  |   rick   |
| 2  |   tom   |

Table - "user_following"
|   user_id  |  user_following_id  |
|       1         |              2                  |

Table - "user_followers"
|   user_id  |  user_follower_id  |
|       2        |              1                 |

So far, everything works just great but the problem starts when i try to delete users.

For example:

userRepository.deleteById(1)

JPA gives an error - 
update or delete on table "users" violates foreign key constraint "fk1yg7xqw2kfx6n2196o0gr3obc" on table "user_followers"
  Подробности: Key (id)=(1) is still referenced from table "user_followers".
  
 JPA cannot delete because it generates a wrong sql.

 ```
Hibernate: 
    select
        user0_.id as id1_5_,
        user0_.first_name as first_na5_5_,
    from
        users user0_ 
    where
        user0_.username=?
Hibernate: 
    delete 
    from
        user_followers 
    where
        user_id=?
Hibernate: 
    delete 
    from
        user_following 
    where
        user_id=?
Hibernate: 
    delete 
    from
        users 
    where
        id=?
```

I want to delete user - rick whose id = 1

The error happens due to wrong sql.
When we delete user - 'rick', 
we first delete 'rick' from "user_following" and "user_followers" tables.

Look at the this statement. 

```
Hibernate: 
    delete 
    from
        user_followers 
    where
        user_id=?
```
        
  The error happens due to this statement because the 
  user we are deleting corresponds to the (user_following_id) column of the "user_followers" table, 
  not "user_id" column.
  
  The right sql statement must be:
  
```  
  Hibernate: 
    delete 
    from
        user_followers 
    where
        user_following_id=?
```

Is there a way how to fix this?

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature/improvement requests. 
The problem described is a pure JPA mapping problem. Those should be asked at Stackoverflow and be tagged with `jpa`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.
