### ISSUE TITLE
Grammar mistake in documentation

### ISSUE THREAD

**Issue by bencetb** [spring-projects/spring-data-jpa#2487]
in README.adoc: 
First line: Spring Data JPA, part of the larger Spring Data family, **makes it easy to easily implement** JPA based repositories.
In my opinion **"makes it easy to easily implement"** isn't correct, or if it is grammatically, it isn't used this way. 
The correct usage should be something like: **"makes it easy to implement JPA based repositories"** or **"allows easy implementation of JPA based repositories"** or **"allows developers to easily implement JPA based repositories"**

**Comment by gregturn** [comment]
Thanks @bencetb!
