### ISSUE TITLE
The project takes a long time to start. Watch the log to find the cause. The cause is creating the Repository agent!

### ISSUE THREAD

**Issue by gitaxin** [spring-projects/spring-data-jpa#2489]
My project is a Spring Boot project that uses Spring Data JPA + Hibernate. Recently, I found that the project startup time was getting longer. Later, I found through the log that during the project startup process, all the proxies that inherit the JpaRepository interface were created. Because there are many interfaces, the project takes up to 5 minutes to start. Most of the time is spent creating proxy classes. How do I solve this problem?

**Comment by gitaxin** [comment]
I'll try

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
