### ISSUE TITLE
Release 2.5.12 (2021.0.12)

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-jpa#2495]

**Comment by Axinet** [comment]
Is there any expected release date for this version? 
2.5.9 was in Feb, 2.5.10 was in March and 2.5.11 was in April.
Now there is June already and still no release?

**Comment by mp911de** [comment]
Spring Data JPA 2.5.x support ended in April 2022 after releasing `2.5.11`. See https://spring.io/projects/spring-data-jpa#support for support timelines.

If you want to consume a fix for #2511, please upgrade to the 2.7.x or 2.6.x line.

**Comment by Axinet** [comment]
🤦‍♂️ ok. So I was mislead by existence of this ticket. Maybe it should be close as invalid in that case? 
Thanks for fast answer!
