### ISSUE TITLE
Adding projection support for `JPASpecificationExecutor`

### ISSUE THREAD

**Issue by ratulSharker** [spring-projects/spring-data-jpa#2499]
Hi there,

As per current situation, `JPASpecificationExecutor` does not allow `select` any result other than the entity.

Can we allow projection by adding following methods in the `JPASpecificationExecutor` and their implementation inside `SimpleJpaRepository` ?

```java
public <Q> List<Q> findAll(Specification<T> specification, Class<Q> clazz);

public <Q> List<Q> findAll(Specification<T> specification, Sort sort, Class<Q> clazz);

public <Q> Page<Q> findAll(Specification<T> specification, Pageable pageable,
		Class<Q> clazz);
```

These methods will allow getting different result type other than `T` where T is `JpaSpecificationExecutor<T>`.

**Comment by mp911de** [comment]
That's in place via #2274. We do not want to pollute the API surface with additional overloads that represent all possible combinations of parameter types and operations.

**Comment by ratulSharker** [comment]
@mp911de how can we use projection in 'JPASpecification' ?

**Comment by ratulSharker** [comment]
@mp911de I didn't get it. I can't find any `findBy` method inside the repository extending from `JPARepository<T, ID>` & `JPASpecificationExecutor<T>`. Do i have to introduce one method inside my repository interface ? Elaborate please.

**Comment by schauder** [comment]
That's part of the [`JpaSpecificationExecutor` API](https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/JpaSpecificationExecutor.java#L107) and will be available with the next mile stone for the 3.0 release.

**Comment by ribertojunior** [comment]
> The code would look like along the lines of:
> 
> ```java
> UserRepository repo;
> Specification<User> spec;
> List<UserProjection> result = repo.findBy(spec, q -> q.as(UserProjection.class).all());
> ```

Hello, sorry to jump on this thread. I'm trying to implement this, but It seems that the generated SQL is the same of the regular findAll with specification, what makes the use of the projection meaningless. Is there something missing on this code? I should add that I 'm using pagination as well.

**Comment by mp911de** [comment]
We're attaching a `jakarta.persistence.fetchgraph` Query hint. We provide `AttributeNodes` to the `EntityGraph` and it is up to the JPA provider to consider the fetchgraph.

**Comment by ribertojunior** [comment]
The reason it was not working is that my projection was not correctly designed. So it was a error on my side. Thanks for the help.

**Comment by fernando-1996** [comment]
Hello @ribertojunior 
What did you do to make it work? I have the same problem as you did. I've tried using `project` method also, but it always fetches all the records, triggering many unwanted relationship calls.

**Comment by SchlauFuchs** [comment]
Okay I have difficulties with the syntax in Kotlin. Here is my line, abstracted:
```kotlin
        val result: Page<ItemSearchProjection> = ItemRepository.findBy(searchDefinition.specification) { queryFunction -> queryFunction.`as`(
            ItemSearchProjection::class.java).page(pageRequest) }
```
This fails for me with `Not enough information to infer type variable S`

There is not enough examples in the usual places like Baeldung or StackOverflow to code by example. 

Any help would be appreciated.

**Comment by eduardosouzag** [comment]
Please [ribertojunior](https://github.com/ribertojunior) show you solution.

**Comment by gexge** [comment]
> We're attaching a `jakarta.persistence.fetchgraph` Query hint. We provide `AttributeNodes` to the `EntityGraph` and it is up to the JPA provider to consider the fetchgraph.

How the query hint can be attached to the method ?

Thanks.

**Comment by ribertojunior** [comment]
> Please [ribertojunior](https://github.com/ribertojunior) show you solution.

Sorry for taking so long to answer.
I used Specification.toPredicate(Root, CriteriaQuery, CriteriaBuilder) and did not construct the predicate myself. It worked well, but we shelved this spring boot migration for now, so this version is not well tested.

**Comment by ahmedmagdy512** [comment]
> The code would look like along the lines of:
> 
> ```java
> UserRepository repo;
> Specification<User> spec;
> List<UserProjection> result = repo.findBy(spec, q -> q.as(UserProjection.class).all());
> ```

it gives me error 
java.lang.UnsupportedOperationException: Class-based DTOs are not yet supported.
when using the same as the example you've mentioned 
can you tell me where the problem is ?
I'm using Spring 3, Postgresql driver

**Comment by SP-Soof** [comment]
> > The code would look like along the lines of:
> > ```java
> > UserRepository repo;
> > Specification<User> spec;
> > List<UserProjection> result = repo.findBy(spec, q -> q.as(UserProjection.class).all());
> > ```
> 
> it gives me error java.lang.UnsupportedOperationException: Class-based DTOs are not yet supported. when using the same as the example you've mentioned can you tell me where the problem is ? I'm using Spring 3, Postgresql driver

Checkout: [FetchableFluentQueryBySpecification](https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/FetchableFluentQueryBySpecification.java)

```java
Assert.notNull(resultType, "Projection target type must not be null");
if (!resultType.isInterface()) {
    throw new UnsupportedOperationException("Class-based DTOs are not yet supported.");
    }
```

You are getiing this error because the class in your FetchableFluentQuery must be of type interface.
Changing you UserProjection to an interface should do the trick.

**Comment by mp911de** [comment]
FWIW, support for Class-based projections is going to ship with #2327

**Comment by Gulshan31** [comment]
> > > The code would look like along the lines of:
> > > ```java
> > > UserRepository repo;
> > > Specification<User> spec;
> > > List<UserProjection> result = repo.findBy(spec, q -> q.as(UserProjection.class).all());
> > > ```
> > 
> > 
> > it gives me error java.lang.UnsupportedOperationException: Class-based DTOs are not yet supported. when using the same as the example you've mentioned can you tell me where the problem is ? I'm using Spring 3, Postgresql driver
> 
> Checkout: [FetchableFluentQueryBySpecification](https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/FetchableFluentQueryBySpecification.java)
> 
> ```java
> Assert.notNull(resultType, "Projection target type must not be null");
> if (!resultType.isInterface()) {
>     throw new UnsupportedOperationException("Class-based DTOs are not yet supported.");
>     }
> ```
> 
> You are getiing this error because the class in your FetchableFluentQuery must be of type interface. Changing you UserProjection to an interface should do the trick.

can someone please tell from where findBy is coming? Do we have to define in repository?

**Comment by VariabileAleatoria** [comment]
> FWIW, support for Class-based projections is going to ship with [#2327](https://github.com/spring-projects/spring-data-jpa/issues/2327)

is there any example of usage?

**Comment by datazuul** [comment]
As I did not find an working example of how to use it, I experimented around and found this new way of "findAll" with specification, paging and projection:

```
Page<ItemSearchView> page = jpaRepository.findBy(
                itemSpecification,
                query -> query.as(ItemSearchView.class)
                        .page(pageable)
        );
```

ItemSearchView.class is my projection interface defining relations and fields to be loaded.

**Comment by mp911de** [comment]
I've refined our documentation on our fluent `JpaSpecificationExecutor` interface and the same via https://github.com/spring-projects/spring-data-commons/issues/3419 for the Query by Example variant.
