### ISSUE TITLE
Hibernate Reactive reconsideration

### ISSUE THREAD

**Issue by Sam-Kruglov** [spring-projects/spring-data-jpa#2503]
Hi, last time it was posted a year ago, I thought it wouldn't hurt to take a look at it again. I know the project is not using JPA but posting here as it's most fitting for Hibernate integration work, where to actually put this code is a smaller problem.

Hibernate Reactive is not against introducing R2DBC into their codebase but are not willing to put in the work themselves to do that. However, they added an extension point that allows users to experiment with integrating alternative reactive database drivers. 

This can allow a "motivated contributor" (not me as of now) to integrate R2DBC into Hibernate Reactive which would open up a path for Spring Data to integrate with it.

see https://github.com/hibernate/hibernate-reactive/issues/76#issuecomment-633063114

_Originally posted by @Sam-Kruglov in https://github.com/spring-projects/spring-data-jpa/issues/2211#issuecomment-1107897586_

**Comment by hantsy** [comment]
In fact, I think Hibernate Reactive can reuse some work of the existing Spring Hibernate support and Spring Data JPA, I also filed an issue about this before: https://github.com/spring-projects/spring-data-relational/issues/1178

Hibernate Reactive is based on the Vertx Reactive Drivers which is incompatible with R2dbc, and R2dbc specification is mainly maintained by the Spring guys.

Vertx Reactive Drivers are already adopted in Vertx, Quarkus, Hibernate Reactive and Micronaut SQL module.

**Comment by schauder** [comment]
We still don't have plans (or the resources) to support Hibernate Reactive.

**Comment by aboutZZ** [comment]
Spring reactive has a long way to go, many libiaries and tools I use still not integrate with R2DBC (e.g. hibernate reactive, QueryDSL), this prevent me from migrating to Spring reactive stack（continue to use Spring MVC）😥

**Comment by anaconda875** [comment]
I have created a Spring boot project that integrate Reactive Hibernate and Spring boot/Spring data. More detail [here](https://github.com/anaconda875/reactive-hibernate-spring-boot-starter)
