### ISSUE TITLE
Native @Query methods should allow Sort if Pageable can accept Sort anyway

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-data-jpa#2504]
I can write natives queries like

    @Query( value = "SELECT * FROM Profile WHERE hornlength > ?1 ORDER BY hornlength DESC",
    nativeQuery = true )
    Page<Profile> findProfilesWithHornlengthGreaterThan( short minHornlength, Pageable pageable );
And call with

    findProfilesWithHornlengthGreaterThan( (short) 4, PageRequest.of( 0, 10, Sort.by( "nickname" ) ) );

And the result will be 

    SELECT
        * 
    FROM
        Profile 
    WHERE
        hornlength > ? 
    ORDER BY
        hornlength DESC,
        nickname asc
        limit ?

Good job of integrating `nickname asc`. But if this is possible, then `Sort` should be supported directly and not just indirectly via `Pageable`. However, using

    List<Profile> findProfilesWithHornlengthGreaterThan( short minHornlength, Sort pageable );

leads to

    Reason: Cannot use native queries with dynamic sorting in method public abstract java.util.List com.tutego.boot.jpa.repository.ProfileRepository.findProfilesWithHornlengthGreaterThan(short,org.springframework.data.domain.Sort); 

But writing `PageRequest.of(0, Integer.MAX_VALUE, sort)` would be the same as passing a `Sort` instance directly to the method.

**Comment by gregturn** [comment]
We don't support `Sort` in native queries, because that would require that we support ALL aspects of sorting. And native queries have very limited ability for us to do such. Using `Sort` as a way to slip in pagination is frankly something we are not ready to support at this time.
