### ISSUE TITLE
Setting column length of a Long value with JPA annotations

### ISSUE THREAD

**Issue by charliecat22** [spring-projects/spring-data-jpa#2505]
I'm performing a little database optimisation at the moment and would like to set the column lengths in my table through JPA. So far I have no problem setting the String (varchar) lengths using JPA as follows:
```
@Column(name = "test", length = 19)
private String test;
```
However, when I want to do the same for a column which is of type Long (bigint), it doesn't work. For example, if I write:
```
 @Data
 @Entity
 @Table(name = "test_jpa")
 public class TestEntity implements Serializable {
 private static final long serialVersionUID = 1L;

 @Id
 @GeneratedValue(strategy = GenerationType.AUTO)
 @Column(name = "id",length = 19)
 private Long id;

 @Column(name = "length",precision = 10)
 private Long length;

 @Column(name = "test", length = 19)
 private String test;
 }
```
The column size is still set as the default of 20. 
Log print : ```Hibernate: create table test_jpa (id bigint not null, length bigint, test varchar(19), primary key (id)) engine=InnoDB```
Also,I tried ```@Size,@Length```,all do not work.On mysql.

**Comment by Isro4488** [comment]
How did you complete this?
