### ISSUE TITLE
Update Maven POM meta information

### ISSUE THREAD

**Issue by spliffone** [spring-projects/spring-data-jpa#2506]
Hello together,

some information in the published Maven pom are outdated or missing (see https://repo1.maven.org/maven2/org/springframework/data/spring-data-jpa/2.6.4/spring-data-jpa-2.6.4.pom).

Outdated:
- project.url is "https://projects.spring.io/spring-data-jpa" but should be "https://spring.io/projects/spring-data-jpa"

Missing:
- project.scm.url the references to the source repository
- project.scm.issueManagement.url

Proposal:

```xml
 ...
  <url>https://spring.io/projects/spring-data-jpa</url>
  <scm>
    <connection>scm:git:git://github.com:spring-projects/spring-data-jpa.git</connection>
    <developerConnection>scm:git:git@github.com:spring-projects/spring-data-jpa.git</developerConnection>
    <url>https://github.com/spring-projects/spring-data-jpa</url>    
  </scm>
  <issueManagement>
    <url>https://github.com/spring-projects/spring-data-jpa/issues</url>
  </issueManagement>
```

**Comment by gregturn** [comment]
Thanks @spliffone! Merged to main, backported to 2.7.x, 2.6.x, and 2.5.x.
