### ISSUE TITLE
Methods in SimpleJpaRepository are private that could be used in custom implementation

### ISSUE THREAD

**Issue by maddin79** [spring-projects/spring-data-jpa#2510]
For a custom implementation of the SimpleJpaRepository it would be awesome if methods like:

`applySpecificationToCriteria`
`executeCountQuery`
...

could be protected to reuse them in the custom implementation. Now I have to copy and implement them myself. 
Is there are reason why this methods are private?

Best
Martin

**Comment by schauder** [comment]
We generally try to limit access as far as possible, because anything that can be used from outside of Spring Data must be kept stable or carefully migrated when it has to change.

**Comment by gregturn** [comment]
I second @schauder 's comment that in general we don't wish to expose such inner details.

You can always create and register your own variant of `SimpleJpaRepository` through `JpaRepositoryFactory`, implementing things as you wish. But in general, we can't expose such inner workings.

**Comment by maddin79** [comment]
Sorry, late reply. I understand your point to lower the workload. But what is a library for if I have to invent the wheel over and over again? The code is there as I needed and still I have to program it myself.
