### ISSUE TITLE
count query issue in spring-data-jpa-2.5.11

### ISSUE THREAD

**Issue by lavanya2290** [spring-projects/spring-data-jpa#2511]
When we check our native query an issue comes 
the count uery changes from select count(*) from tablename to select count(order) from tablename.

https://github.com/spring-projects/spring-data-jpa/compare/2.5.9...2.5.11#diff-7d36425745042f8c27507657de795fd7cf1d546da6a740fd00d86add46f81ed4R530

**Comment by lavanya2290** [comment]
<img width="1536" alt="Screenshot 2022-04-27 at 4 30 48 PM" src="https://user-images.githubusercontent.com/13776413/165504460-35cef066-8d00-4b56-9dd2-30247e14bd4b.png">
<img width="1536" alt="Screenshot 2022-04-27 at 4 30 40 PM" src="https://user-images.githubusercontent.com/13776413/165504484-9af88631-a5f0-4c70-948a-76451bb1b268.png">

**Comment by lavanya2290** [comment]
Matcher matcher = COUNT_MATCH.matcher("SELECT * FROM context ORDER BY time");
		String countQuery;

		if (countProjection == null) {

			String variable = matcher.matches() ? matcher.group(VARIABLE_NAME_GROUP_INDEX) : null;
			boolean useVariable = StringUtils.hasText(variable) //
					&& !variable.startsWith(" new") //
					&& !variable.startsWith("count(") //
					&& !variable.contains(",") //
					&& !variable.contains("*");

			String complexCountValue = matcher.matches() && StringUtils.hasText(matcher.group(COMPLEX_COUNT_FIRST_INDEX))
					? COMPLEX_COUNT_VALUE
					: COMPLEX_COUNT_LAST_VALUE;

			String replacement = useVariable ? SIMPLE_COUNT_VALUE : complexCountValue;
			countQuery = matcher.replaceFirst(String.format(COUNT_REPLACEMENT_TEMPLATE, replacement));

**Comment by lavanya2290** [comment]
in 2.5.13 spring boot which uses 2.5.11 issue is there.

**Comment by Axinet** [comment]
#2495 is still open, so the only option as for now is downgrade to spring-data-jpa 2.5.10

**Comment by gregturn** [comment]
Support for `2.5.x` ended back in April. I'm closing this ticket for now. If you are still running into this issue on `2.6.x`+, then please open a new ticket with details.

**Comment by Axinet** [comment]
As mentioned above, support for `2.5.x` line has ended in April. You either have to upgrade to `2.6` line, or if you can't, revert to previous version in `2.5` line without that bug.
Recent `2.6.x` versions don't have this bug any longer.
