### ISSUE TITLE
Update to Hibernate 5.6.9.Final

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-data-jpa#2519]
Hibernate 5.6.9.Final patches https://hibernate.atlassian.net/browse/HHH-15142, which caused anything after Hibernate 5.6.5.Final to break on custom finders that have "startsWith", "endsWith", or "contains" clauses, which used wildcards.

Several issues swirl around this patch, so we need to update as soon as its out.

**Comment by lmorocz** [comment]
Hi @gregturn! Hibernate 5.6.9.Final was released [yesterday](https://in.relation.to/2022/05/16/hibernate-orm-569-and-reactive-115).

**Comment by gregturn** [comment]
Duplicates https://github.com/spring-projects/spring-data-jpa/issues/2583.
