### ISSUE TITLE
QueryRewriter modify query given its name (for named query)

### ISSUE THREAD

**Issue by fawzyj** [spring-projects/spring-data-jpa#2523]
I have a feature suggestion:
When the query is a named query, we may be able to override the query given its name not its text string.

for example, I may define many named queries in my repository with no query value, then define all the queries in QueryRewriter class. This helps in 2 ways:
1- keep my repository file clean and free from text based sql
2- give me the ability to use safe query writers (jooq, queryDSL) to write the query.

I hope you consider it

**Comment by gregturn** [comment]
Can you expound upon what you're interested in?

Because what you're describing (so far), sound like something that can be achieved with Spring Data JPA's support for custom implementations.

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations
