### ISSUE TITLE
Why can't I modify the DDL for the column

### ISSUE THREAD

**Issue by MineYuanlu** [spring-projects/spring-data-jpa#2538]
I want to use `binary(16)` to store UUIDs compactly, but the data length is ignored when defining foreign key types

It looks like `columnDefinition` is not in effect

# Catalogue Table:
![图片](https://user-images.githubusercontent.com/38997444/169463732-a976c114-89bd-4876-a092-f24e61860738.png)

# Img Table:
![图片](https://user-images.githubusercontent.com/38997444/169463137-6a75dd43-38ec-4091-aa5d-643fe2cf28e9.png)

# Database model:
![图片](https://user-images.githubusercontent.com/38997444/169463477-f1e44a62-786f-465f-9e44-9e6f695be20b.png)

**Comment by schauder** [comment]
Schema generation is done by your JPA implementation, not by Spring Data JPA.

**Comment by MineYuanlu** [comment]
I didn't make it clear: the schema in the third figure is obtained from the reverse of the database generated by spring data JPA

But I have found a solution:
```java
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "img", insertable = false, updatable = false)
    Img img;

    @Column(name = "img", columnDefinition = "BINARY(16)")
    UUID imgID;
```
[My Code](https://github.com/mcresweb/Server2/blob/51ae2a988e4cde316397224d865884fb6ed80f9c/src/main/java/com/fei/mcresweb/dao/Catalogue.java#L63)
