### ISSUE TITLE
Annotated query with wildcard-appended named parameter does not handle null in 2.7.0

### ISSUE THREAD

**Issue by jonhakr** [spring-projects/spring-data-jpa#2548]
## Context
We often create queries with optional filtering on parameters (ignore them when null) like so:
```
@Query("""
    select j from Jedi j
    where (:name is null or j.name = :name)
    and (:desc is null or j.description like %:desc%)
  """)
  fun searchContains(
      @Param("name") name: String?,
      @Param("desc") desc: String?,
  ): List<Jedi>
```

As noted in Example 62 in https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.at-query.advanced-like

>  the LIKE delimiter character (%) is recognized, and the query is transformed into a valid JPQL query (removing the %).
> Upon running the query, the parameter passed to the method call gets augmented with the previously recognized LIKE pattern.

This worked fine previously, but after upgrading til 2.7.0 it does not seem to work when such a named parameter is null, which it is intended to be when using that to implement optional filtering like this.

## Problem
When the named parameter is null, the binded value is the literal string `org.hibernate.jpa.TypedParameterValue@<number>` augmented with the wildcard parameter, instead of just null.

I have prepared a demo app that showcases the issue: https://github.com/jonhakr/spring-data-jpa-null-optional-query
The query above is generated as such:
```
select
        jedi0_.id as id1_0_,
        jedi0_.description as descript2_0_,
        jedi0_.name as name3_0_ 
    from
        jedi jedi0_ 
    where
        (
            ? is null 
            or jedi0_.name=?
        ) 
        and (
            ? is null 
            or jedi0_.description like ?
        )
```
When `name` is null it works fine, and the resulting bound parameter values are:
```
binding parameter [1] as [VARCHAR] - [null]
binding parameter [2] as [VARCHAR] - [null]
binding parameter [3] as [VARCHAR] - [%er%]
binding parameter [4] as [VARCHAR] - [%er%]
```
However, if the wildcard appended `desc` is null, the resulting bound parameter values are:
```
binding parameter [1] as [VARCHAR] - [Mace Windu]
binding parameter [2] as [VARCHAR] - [Mace Windu]
binding parameter [3] as [VARCHAR] - [%org.hibernate.jpa.TypedParameterValue@38d895e8%]
binding parameter [4] as [VARCHAR] - [%org.hibernate.jpa.TypedParameterValue@38d895e8%]
```

Simply setting spring-data-jpa to 2.6.4 makes this work fine again

**Comment by jonhakr** [comment]
Possibly related to #2544 ?

**Comment by quaff** [comment]
Possibly related to https://github.com/spring-projects/spring-data-jpa/pull/2461.

**Comment by gregturn** [comment]
Related: #2549

**Comment by mhdb96** [comment]
Having the same problem with spring-data-jpa to 2.7.0

**Comment by pkernevez** [comment]
Is there any plan for this issue ? (and the other related issues)

**Comment by edigu** [comment]
@gregturn seems like the change you made at 3d8b287e0e2129ec827b15613b44f31c19c65c61 addresses the original problem in [3.0.0-M5](https://github.com/spring-projects/spring-data-jpa/releases/tag/3.0.0-M5) release line. However, it is not obvious to me if this issue has to be handled in a different way in 2.7.x or will be backported to 2.7.x automatically during the next release.

I am maintaining an application that is stuck in 2.6.x due to this issue which is closed now, I tried to reproduce with spring-boot 2.7.3 and the issue still persists there. Any feedback regarding 2.7.x would be really helpful for the app maintainers who still use 2.6.x as [noted by quaff here](https://github.com/spring-projects/spring-data-jpa/commit/3d8b287e0e2129ec827b15613b44f31c19c65c61#commitcomment-78731591)

**Comment by dvcer** [comment]
We have the same issue with 2.7.4 and as workaround it helps to use
       `(:name IS NULL or p.name LIKE '%'||:name||'%' )`
 instead of 
      ` (:name IS NULL or p.name LIKE %:name%)`

 @nemezmaksim

**Comment by jonhakr** [comment]
I have updated the example with null data in DB, and can confirm that this still fails for 2.7.5 (also fails for 2.7.0 as before), as stated by @michalkleszcz12, since the injected parameter in the `? is null` comparison is the relevant wildcards instead of null.

**Comment by gregturn** [comment]
@jonhakr Check out the snapshots to see if things are now working as expected.

**Comment by dwursteisen** [comment]
Hi 👋 

For Information, I bump to Spring Boot 2.7.5 yesterday. Some tests failed after the bump.
After investigation, it's the same issue described in this ticket. So I try the `2.7.6-SNAPSHOT` version.
All tests turned green using this snapshot version. So @gregturn fixed our issue, in our case.

Regards

**Comment by jonhakr** [comment]
Can confirm what @dwursteisen is saying. Updated example with spring-data set to that snapshot, and all tests went green

**Comment by gregturn** [comment]
Duplicate of #2653.

**Comment by jonhakr** [comment]
Strictly speaking, #2653 is a duplicate of this

**Comment by meisten** [comment]
Be careful if you use the Spring Native project.

You should create a hint for the `TypedParameterValue` type

```java
@TypeHint(types = org.hibernate.jpa.TypedParameterValue.class)
public class YourNativeHibernateHints implements NativeConfiguration {

}
```

The hint for this type [is missing](https://github.com/spring-attic/spring-native/blob/0.12.2/spring-native-configuration/src/main/java/org/hibernate/HibernateHints.java) from the native configuration for Hibernate.

Without this hint, your binary will use `org.hibernate.jpa.TypedParameterValue`:

```sql
select distinct stationent0_.id as col_0_0_ 
from stations stationent0_ 
where 
    (NULL is null or stationent0_.city_id=NULL) and 
    ('%org.hibernate.jpa.TypedParameterValue@701ac132%' is null or 
        lower(stationent0_.address) like '%org.hibernate.jpa.TypedParameterValue@701ac132%'
    ) 
```

**Comment by ankovi** [comment]
Spring Boot 3.1.4 :

Same problem persists (in my case for a Boolean parameter), but, resolvable as follows :

    @Query("""
            FROM StockEntity s
            WHERE
                      (:#{#species?.size() < 1} = true OR s.objectCode IN :species)
                    AND
                      (:#{#areas?.size() < 1} = true OR s.locationCode IN :areas)
                    AND
                      (:#{#previous?.size() < 1} = true OR s.ancestor.id IN :previous)
                    AND
                      (:#{#multiple == null} = true OR s.multiSpeciesIndicator = :multiple)
            """)
    Page<StockEntity> searchStocks(List<String> species, List<String> areas, List<Long> previous, Boolean multiple, Pageable pageable);

This throws : 

Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = boolean
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.

The problem is with the Boolean multiple parameter.
But, if I use SPeL also for the rest of the (last line) it works fine :  

 AND
                      (:#{#multiple == null} = true OR s.multiSpeciesIndicator = :#{#multiple})
 
NOTE: Testing always worked fine without any problem, so I'd say this was resolved somewhow in Spring Test, but
 not in the Spring Boot JPA.
