### ISSUE TITLE
Error accessing field ... for persistent property after migrating Spring Boot from 2.5 to 2.6 (or 2.7)

### ISSUE THREAD

**Issue by ftsuda-senac** [spring-projects/spring-data-jpa#2552]
After Spring Boot migration from 2.5.14 to 2.6 (or 2.7), this error started to show when i try to save some related entities to database:
```
Caused by: org.springframework.orm.jpa.JpaSystemException: Error accessing field [protected java.lang.Long com.example.datajpaerror.entity.DocumentEntityId.personId] by reflection for persistent property [com.example.datajpaerror.entity.DocumentEntityId#personId] : 1; nested exception is org.hibernate.property.access.spi.PropertyAccessException: Error accessing field [protected java.lang.Long com.example.datajpaerror.entity.DocumentEntityId.personId] by reflection for persistent property [com.example.datajpaerror.entity.DocumentEntityId#personId] : 1
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:331) ~[spring-orm-5.3.20.jar:5.3.20]
...
Caused by: org.hibernate.property.access.spi.PropertyAccessException: Error accessing field [protected java.lang.Long com.example.datajpaerror.entity.DocumentEntityId.personId] by reflection for persistent property [com.example.datajpaerror.entity.DocumentEntityId#personId] : 1
	at org.hibernate.property.access.spi.GetterFieldImpl.get(GetterFieldImpl.java:75) ~[hibernate-core-5.6.9.Final.jar:5.6.9.Final]
...
Caused by: java.lang.IllegalArgumentException: Can not set java.lang.Long field com.example.datajpaerror.entity.DocumentEntityId.personId to java.lang.Long
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:na]
```
Since i'm using a quite complex Entity mapping configuration that involves inheritance and multi-column Primary Keys with EmbeddedId, i've wrote a small application in order to reproduce this error. The application can be found at https://github.com/ftsuda-senac/data-jpa-error

Steps to reproduce the error:

After downloading the application mentioned above, run as `mvn test`

A successful test can be achieved changing the Spring Boot version to 2.5.14 and running the same command `mvn test`

**Comment by schauder** [comment]
This doesn't seem to be a Spring Data, but a Hibernate issue. 

I created a [PR to your demonstrator](https://github.com/ftsuda-senac/data-jpa-error/pull/1) demonstrating it.
You'll need to create an issue with Hibernate. 

Make sure to create a reproducer that does not use Spring, since understandably they don't appreciate to deal with other frameworks when debugging issues.

I'd appreciate it if you could leave a link here to the Hibernate issue, so others can find it more easily.

**Comment by ftsuda-senac** [comment]
@schauder Thanks for reply.
Opened the issue https://hibernate.atlassian.net/browse/HHH-15307 and updated the demo to a pure Hibernate application,

**Comment by BHRother** [comment]
I stopped seeing this error after upgrading to [6.2.6.Final](https://mvnrepository.com/artifact/org.hibernate/hibernate-core/6.2.6.Final).

**Comment by jdeflores127** [comment]
I had the same error in the version 6.4.4.Final and I notice that is a ClassLoader Issue between Hibernate and Spring Dev Tools.

First, I have this code
<img width="548" alt="Captura de Pantalla 2024-02-14 a la(s) 1 44 32" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/511ffb11-4c7b-4f72-b409-4bac8cfecdb6">

And this the SessionFactory
<img width="663" alt="Captura de Pantalla 2024-02-14 a la(s) 1 45 42" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/337b4af9-8dfe-492f-91fa-ae2c7930a98d">

And this is the Entity
<img width="376" alt="Captura de Pantalla 2024-02-14 a la(s) 1 46 47" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/d0c4c9fd-58b9-41b3-ad73-e2df41f8faa0">

This is the Properties
`
hibernate.connection.url=jdbc:h2:mem:bookingdb
hibernate.connection.username=sa
hibernate.connection.password=sa
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true
hibernate.hbm2ddl.auto=create`

In the pom.xml I have the Spring DEV TOOLS
<img width="453" alt="Captura de Pantalla 2024-02-14 a la(s) 1 49 43" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/4ec8e3a3-cfc3-4192-98d6-665a9f009dbc">

When I run the App i get A similar error
<img width="1439" alt="Captura de Pantalla 2024-02-14 a la(s) 1 52 26" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/ab2b56e9-8458-490c-970d-178e6788a66b">

When I debug the App searching the exception I noticed that the Futbolistas object classLoader Is different that Hibernate Field classLoader. Field is generated from Hibernate with the AppClassLoader. The exception is throwed from this code fragment in the line 58. 
<img width="1273" alt="Captura de Pantalla 2024-02-14 a la(s) 1 57 23" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/06234be9-79bc-4196-81b4-32b31c380d9d">

The Futbolistas Class was generated with the dev tool classLoader
<img width="1321" alt="Captura de Pantalla 2024-02-14 a la(s) 2 01 48" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/e98ebe24-f9a2-4517-86ef-c260e8f4ce21">

Reading the dev tool docs I found this
<img width="1237" alt="Captura de Pantalla 2024-02-14 a la(s) 2 05 15" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/b167c8f4-ab07-4fd5-a930-4c529cbd310a">

When I drop the devtools dependency in the pom, making a mvn install, hopefully the app works fine :)
<img width="444" alt="Captura de Pantalla 2024-02-14 a la(s) 2 10 00" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/804931a9-00e5-470a-a930-27661e5f590b">
<img width="1440" alt="Captura de Pantalla 2024-02-14 a la(s) 2 15 16" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/6c75e122-01c4-44bb-b66e-663abd9549da">
<img width="956" alt="Captura de Pantalla 2024-02-14 a la(s) 2 16 04" src="https://github.com/spring-projects/spring-data-jpa/assets/26336133/23cf0976-4474-4dd2-bffe-f53564f12a7c">


So, in my case, the solution was drop the dev tools.

**Comment by LamChiHung** [comment]
> I stopped seeing this error after upgrading to [6.2.6.Final](https://mvnrepository.com/artifact/org.hibernate/hibernate-core/6.2.6.Final).

You save me
