### ISSUE TITLE
JSqlParser fails for modifying queries

### ISSUE THREAD

**Issue by rolfwoll** [spring-projects/spring-data-jpa#2555]
Using Spring Boot 2.7 which uses Spring Data JPA 2.7.0 and I have a problem that occurred after upgrading from Spring Boot 2.3.12.

I have a simple modifying query something like this:

`    
@Modifying(clearAutomatically = true)
 @Query(value = "update userinfo user set user.is_in_treatment = false where user.id = :userId", nativeQuery = true)
 void setNotInTreatment(@Param("userId") int userId);`

We are using JSqlParser for other things in our project, so it is in the classpath, and that parser is therefore used according to the log:

`o.s.d.j.r.q.QueryEnhancerFactory - JSqlParser is in classpath. If applicable JSqlParser will be used.`

At startup the parsing of the above query fails with the following error message:

`Could not create query for public abstract void com.norse.api.repository.UserRepository.setNotInTreatment(int)! Reason: class net.sf.jsqlparser.statement.update.Update cannot be cast to class net.sf.jsqlparser.statement.select.Select `

I'm assume the error is related to the fact that I have a modifying query?

**Comment by DiegoKrupitza** [comment]
Yeah you are right! The current implementation of does not detect if it is a modifying query or not. It assumes that all the queries are "selects".

The problems is here:

```java
private static Select parseSelectStatement(String query) {
  try {
	  return (Select) CCJSqlParserUtil.parse(query);
  } catch (JSQLParserException e) {
	  throw new IllegalArgumentException("The query you provided is not a valid SQL Query!", e);
  }
} 
```

**Comment by DiegoKrupitza** [comment]
When I implemented the `JSqlParserQueryEnhancer` it did not made sense to me that other types of statements (DELETE, UPDATE, ... ) will call this methods. But It seems those call are desired although the results are not used anywhere. The default implementation `QueryUtils` even returns null or "" on all those queries.

**Comment by gregturn** [comment]
@DiegoKrupitza I don't know if modified queries is possible/makes sense, or if (at least) we simply need a more complete error message?

**Comment by gregturn** [comment]
Thanks @DiegoKrupitza.

To be honest, your proposed PR is along the lines of what I was thinking. Sniff out the query "type", and cut out early from any sorting, etc.

**Comment by gregturn** [comment]
Thanks @DiegoKrupitza!

**Comment by gregturn** [comment]
Backported to `2.7.x`.

**Comment by fabriziodelfranco** [comment]
I have the same issue with an insert query, using 2.7.2-SNAPSHOT.
Is there any specific reason for which only UPDATE and DELETE queries have been fixed?

Thanks.

**Comment by DiegoKrupitza** [comment]
> I have the same issue with an insert query, using 2.7.2-SNAPSHOT.
> 
> Is there any specific reason for which only UPDATE and DELETE queries have been fixed?
> 
> 
> 
> Thanks.

@fabriziodelfranco there is an issue (#2593) that covers this problem. I already created a PR that fixes this issue (#2595)

**Comment by fabriziodelfranco** [comment]
Thank you @DiegoKrupitza

**Comment by rolfwoll** [comment]
Thanks @DiegoKrupitza and @gregturn for quick response, followup and fix.
