### ISSUE TITLE
Whether `Class-based Projections` does not support use with `@query`

### ISSUE THREAD

**Issue by immadolf** [spring-projects/spring-data-jpa#2558]
As shown in the figure, it is mentioned in the official document that `Class-based Projections` cannot be used with **native query**, while **native query** is described as `setting the nativeQuery flag to true`.

However, when I mixed `@query` with `Class-based Projections`, I saw an error `org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type`.

Here is my code:
```java
public interface PersonRepository extends Repository<Person, Long> {

    @Query("select p from Person p where p.firstName = ?1")
    PersonDto findByFirstName(String firstName);

}

@Entity
public class Person {
    @Id
    private Long id;
    private String firstName;
    private String lastName;
    @OneToOne(mappedBy = "person")
    private Address address;

   // getter and setter ...
}

public class PersonDto {
    private final String firstName;
    private final String lastName;

    public PersonDto(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public String getFirstName() {
        return firstName;
    }

    public String getLastName() {
        return lastName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PersonDto personDto = (PersonDto) o;
        return Objects.equals(firstName, personDto.firstName) && Objects.equals(lastName, personDto.lastName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(firstName, lastName);
    }
}
```

![图片](https://user-images.githubusercontent.com/12369197/171142450-5fa1c0c8-a48f-4e08-8276-766282ff83fa.png)

![图片](https://user-images.githubusercontent.com/12369197/171142916-34307338-df5a-4285-87c1-bfc2dca17b9c.png)

**Comment by gregturn** [comment]
I understand that the reference documentation implied the code you wrote should work just fine. I updated them to clarify exactly how class-based DTOs work with Spring Data JPA, hopefully giving you the ability to leverage you `PersonDto` within an `@Query` annotation!

**Comment by gregturn** [comment]
Backported to `2.7.x` and `2.6.x`.
