### ISSUE TITLE
Consider removing support for Querydsl project

### ISSUE THREAD

**Issue by mat-mik** [spring-projects/spring-data-jpa#2575]
Querydsl project is not maintained anymore, issues are not solved and pull requests are not reviewed. As you can see from [contributions insight](https://github.com/querydsl/querydsl/graphs/contributors) main maintainer is not involved in project anymore. Current version (5.0.0) contains [connection leak](https://github.com/querydsl/querydsl/issues/3089) we experienced.

One of the reason we decided to use Querydsl for few years back was because of Spring support (like dependency version table).

Original issue: https://github.com/spring-projects/spring-boot/issues/31478

**Comment by mp911de** [comment]
Care to elaborate on how this is helpful to users whose requirements are satisfied with the existing functionality? 

Querydsl is a project maintained by folks in their spare time. They would be more than happy to get help from someone who can provide a stable contribution stream.
