### ISSUE TITLE
how close target targetclass when use Projection

### ISSUE THREAD

**Issue by codersboy** [spring-projects/spring-data-jpa#2579]
i dont need target to show data again
There is no need to display targetClass to json

```
public interface UserInfo {

     String getUsername();

    String getEmail();

    BigDecimal getBalance();

    BigDecimal getAmounts();

    String getLanguage();
}

```
json data from server
```
> data:
amounts: "0.00"
balance: "0.00"
language: "EN"
username: "111@test.com"
target:
      amounts: "0.00"
      balance: "0.00"
      language: "EN"
      username: "111@test.com"
targetClass: "org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap"
```

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by codersboy** [comment]
> If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

`
public class user{
      private String username;
      private Integer amounts;
}

public interface UserDTO {
    public String getUsername();
    public Integer getAmounts();
}
// jpa mapper
public <T> Collection<T> findByUsername(String username, Class<T> type);

UserDTO user = userMapper.findByUsername("admin",UserDTO.class);

System.out.println(user); 
// org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap@51d41b97


to client json formmat
amounts: "0"
username: "admin"
target:     // i dont want show these data,target and targetclass
    amounts: "0"
    username: "admin"
targetClass: "org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap"
`

**Comment by mp911de** [comment]
Depending on the serialization technology you use to serialize the projection proxy into JSON, you need to configure the library you use to use rather property accessors (getters, setters) instead of inspecting the class fields. According to the JSON sample, the JSON serializer is introspecting the projection proxy which renders all internals instead of just the property values.
