### ISSUE TITLE
BindableQuery causes NullPointerException when using proxy over Query

### ISSUE THREAD

**Issue by lfaltran** [spring-projects/spring-data-jpa#2584]
I've a proxy for handle some tenant attributes on current session, and got NullPointerException during unwrap method execution, not sure if I can just ignore or if its an issue that has to be handled on AbstractProducedQuery.

As reported on issue #2380 I'm not sure if it has to be handled on my proxy impl or review this behavior on BindableQuery for "unwrap" method.

```
BindableQuery(QueryMetadata metadata, Query query) {
			super(metadata);
			this.query = query;
			this.unwrapped = Proxy.isProxyClass(query.getClass()) ? query.unwrap(null) : query;
		}
```

```
	@Override
	@SuppressWarnings("unchecked")
	public <T> T unwrap(Class<T> cls) { // <<<< cls is null here
		if ( cls.isInstance( getProducer() ) ) {
			return (T) getProducer();
		}
		if ( cls.isInstance( getParameterMetadata() ) ) {
			return (T) getParameterMetadata();
		}
		if ( cls.isInstance( getQueryParameterBindings() ) ) {
			return (T) getQueryParameterBindings();
		}
		if ( cls.isInstance( this ) ) {
			return (T) this;
		}

		throw new HibernateException( "Could not unwrap this [" + toString() + "] as requested Java type [" + cls.getName() + "]" );
//		throw new IllegalArgumentException( "Could not unwrap this [" + toString() + "] as requested Java type [" + cls.getName() + "]" );
	}
```

As a workaround, I've put an condition if the method called is "unwrap" and just return current "query" received, instead of callind "method.invoke".

Hope to get help with this.

If any extra detail is needed, just let me know.

**Comment by gregturn** [comment]
In the other ticket (https://github.com/spring-projects/spring-data-jpa/issues/2380#issuecomment-988663924), we couldn't get more details on what was going wrong for that user.

As stated, we use JDK proxies for limited purposes. The proxies that Hibernate/EclipseLink use are not. So in your situation, we don't know what you are needing to do and how the proxies are getting in your way.

**Comment by gregturn** [comment]
I'm closing this ticket as it appears identical to the issues popping up in the #2380, which was not actionable on our end. PLUS, that ticket has tips on how to cope with using your own proxy. Let us know if there are more details beyond that.
