### ISSUE TITLE
limit queries of single finders to 2

### ISSUE THREAD

**Issue by tschniewind** [spring-projects/spring-data-jpa#2594]
**Enhancement:**
Given a repositorys find-method returning a single result or an java.util.Optional should **limit** the underlying query to 2.

This would help to get the expected Result in case of multiple rows (IncorrectResultSizeDataAccessException) even if the query leads to huge result set.

(We had a case leading to an out of memory exception cause the query found about 50000 rows. Unfortunately we could not use a UniqueConstraint.)

**Comment by tschniewind** [comment]
In which version will this enhancement be integrated, any idea?

**Comment by schauder** [comment]
This will be part of the next 3.0 milestone and therefore eventually in 3.0 GA.

**Comment by gregturn** [comment]
Backported to `2.7.x`

**Comment by gregturn** [comment]
Backported to `2.6.x`.
