### ISSUE TITLE
findByLoginTimeBefore

### ISSUE THREAD

**Issue by codersboy** [spring-projects/spring-data-jpa#2596]
how get last logintime use great jpa?

database table
id	login_time		                 username
1	2022-07-13 16:15:36.216000	111@test.com
2	2022-07-14 16:20:45.989000	111@test.com
3	2022-07-15 16:21:01.809000	111@test.com

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jpa`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.

When asking on Stackoverflow you might also want to include some more context to help others understand what you want to achieve.
