### ISSUE TITLE
Not in query on empty Collection produce wrong SQL for postgres

### ISSUE THREAD

**Issue by kris2kris** [spring-projects/spring-data-jpa#2602]
Hello,

When doing a `findByMyPropertyNotIn(Set<String> property)` the SQL generated contain effectively a NOT IN but when I put an empty collection as a parameter I expect to retrieve all the lines from my database but I didn't get anything with PostgreSQL.
It seems that query generated is something like `Select * From My_table Where my_property not in (null)`
This query return all the lines on H2 database but nothing on Postgres, I think the query should be adapted when collection is empty.

**Comment by schauder** [comment]
Query generation is done by your JPA implementation, i.e Hibernate most of the time. 

So when the query works for H2 but doesn't for Postgres it's going to be an issue on their side.
