### ISSUE TITLE
contains in query derivation of an ElementCollection creates a proper isMember clause but encloses the argument in % leading to the wrong result.

### ISSUE THREAD

**Issue by schauder** [spring-projects/spring-data-jpa#2607]
When looking at the code `CONTAINING` is obviously intended to work with Strings (and be translated to  `x like %?%`) and for collections where it gets translated to an `isMemberOf`. But in the later case the argument is still wrapped with `%` resulting in the condition yielding the wrong results. In most cases non at all. 

Interesting using a simple property does work.

**Comment by schauder** [comment]
A reproducer is in https://github.com/schauder/stackoverflow/tree/main/jpa/contains

**Comment by gregturn** [comment]
Backported to `2.7.x`
