### ISSUE TITLE
Batch insert on MySQL DB with Generated IDs

### ISSUE THREAD

**Issue by zromano** [spring-projects/spring-data-jpa#2613]
I'm trying to do batch inserts on a MySQL DB where our IDs are auto an incremented Long/BIGINT and having no luck.

By default if you have `@GeneratedValue(strategy = GenerationType.IDENTITY)`, then batching is disabled and you can't do `GenerationType.SEQUENCE` on MySQL. Everywhere I've read has also recommended against doing a `GenerationType.TABLE` and creating a new table is not a viable option in my situation.

I've done many hours of searing and I have had zero luck finding anything that works on this besides hacks to trick JPA/Hibernate. Can someone please provide an example of how to do this and update the docs with an example? I'm fine with not getting the updated entities back like in the `saveAll` method. Just having the number of records updated would be sufficient.

MySQL is an incredibly popular DB and I think it's a big miss to not be able to easily support _fast_ bulk inserts.

Any help on this would be _much appreciated_. Other than this issue, my team has been loving our switch to JPA 🙂

**Comment by schauder** [comment]
This question is about Hibernate, but this is the issue tracker of Spring Data JPA, which just uses Hibernate.

If you are looking for an improvement of Hibernate you should create a ticket on their issue tracker.
If this is about how to achieve your goal with current versions of Hibernate StackOverflow is probably the best resource.
