### ISSUE TITLE
HibernateJpaParametersParameterAccessor throws PersistenceException

### ISSUE THREAD

**Issue by blue-hope** [spring-projects/spring-data-jpa#2614]
Related to #2370.

When executing query, below code is run before create query.

```java
HibernateJpaParametersParameterAccessor(Parameters<?, ?> parameters, Object[] values, EntityManager em) {
  super(parameters, values);

  Session session = em.unwrap(Session.class);
  this.typeHelper = session.getSessionFactory().getTypeHelper();
}
```

Does it properly work on non-transactional query?
As you can see, It uses `invoke()` to unwrap Session but it throws `IllegalStateException` when the query is non transaction.
This is because it uses `ThreadLocal` Internally to get `EntityManager` and the `ThreadLocal` [bindResource](https://github.com/spring-projects/spring-framework/blob/e0f56e7d80a4e1248198e40be99157dbd8f594af/spring-tx/src/main/java/org/springframework/transaction/support/TransactionSynchronizationManager.java#L167-L185)() which set the entityManager is called only when use transaction.
How can I fix it(or is it can be fixed)?

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem. We require more contextual details to find out how you're using JPA.

**Comment by blue-hope** [comment]
Ah, It occurs on spring 2.7.0, and upgrade it to 2.7.2 the error not occurs.
