### ISSUE TITLE
Different revision query handling by spring-data-envers compared to Hibernate Envers AuditReader

### ISSUE THREAD

**Issue by Rokko11** [spring-projects/spring-data-jpa#2616]
Hello,

given I have an audited entity which was modified on revision n.

When I use the Hibernate Envers native AuditReader I get the same behavior when querying for revision n.

```
// Hibernate Envers query. Result is not null
AuditReaderFactory.get(em).find(DummyEntity.class, id, n)

// EnversRevisionRepositoryImpl result is not null
dummyRevisionRepository.findRevision(id, n)
```

When I query the revisions before or after I get different behaviors

```
// Hibernate Envers query result is not null
AuditReaderFactory.get(em).find(DummyEntity.class, id, n + 1)

// EnversRevisionRepositoryImpl result is null
dummyRevisionRepository.findRevision(id, n + 1)
```

Why this inconsistency?

**Comment by mp911de** [comment]
Envers repositories select revisions while you're asking for entity at `<revisionNumber>`. Entity at `<revisionNumber>` is unbounded regarding the target revision number while a `Revision` at `<revisionNumber>` does not exist.
