### ISSUE TITLE
[Query] @NamedQuery name should be prefix by entity name or the entity class name?

### ISSUE THREAD

**Issue by hanct** [spring-projects/spring-data-jpa#2622]
Hi,
    Spring boot version: 2.7.2

  As shown below, i have a class called HeroEntity, and i define the name of entity as Test.
In my @NamedQuery, i give the name "**Test.yyy**", since many online article mentioned prefix with the entity name.  Then in my repository HeroRepos<HeroEntity, Long>, i have a interface method called yyy().   Unfortunately during bootup, error "could not create query for the yyy" is thrown.

However, changed the @NamedQuery's name to **HeroEntity**.yyy, no error occur.

Can I conclude that the name of the @NamedQuery should be {entity class name}.{method name}, not {entity name}.{method name}

```
@Entity(name = "Test")
@NamedQuery(name="Test.yyy", query="select c from Test c")

public class HeroEntity {
```
throw error

```
@Entity(name = "Test")
@NamedQuery(name="HeroEntity.yyy", query="select c from Test c")

public class HeroEntity {
```
Does not throw error

**Comment by schauder** [comment]
> Can I conclude that the name of the @NamedQuery should be {entity class name}.{method name}, not {entity name}.{method name}

Yes, this is correct.

**Comment by hanct** [comment]
> > Can I conclude that the name of the @NamedQuery should be {entity class name}.{method name}, not {entity name}.{method name}
> 
> Yes, this is correct.

Thanks. Hope this is specifically pointed out in the official documentation.
