### ISSUE TITLE
Entity is not being removed from database when using @OneToMany/@ManyToOne

### ISSUE THREAD

**Issue by PeRaVs** [spring-projects/spring-data-jpa#2623]
When I try to delete Entity2, which is connected to Entity1 via 1:N, Entity2 will not being removed from database.

**Full code example with Unit test: https://github.com/PeRaVs/database-sample**

**Entities:**
```
@Entity
@Table(name="entity_1")
public class Entity1 {
    @Id
    @Column(name="id", columnDefinition="char(36)")
    private String id;

    @OneToMany(
            mappedBy="entity1",
            cascade = CascadeType.ALL,
            orphanRemoval = true
    )
    private List<Entity2> entity2 = new ArrayList<>();
}
```
```
@Entity
@Table(name="entity_2")
public class Entity2 {
    @Id
    @Column(columnDefinition = "char(36)")
    private String id;

    @ManyToOne(optional = false)
    @JoinColumn(name="entity1", referencedColumnName = "id")
    private Entity1 entity1;
}
```
**Repositories:**
```
public interface Entity1Repo extends Repository<Entity1, String> {
    List<Entity1> findAll();
    void save(Entity1 entity1);
}

public interface Entity2Repo extends Repository<Entity2, String> {
    void delete(Entity2 entity2);
}
```
**Entity Relationship:**
```
Entity1 e1 = new Entity1().setId("1_1");
Entity2 e2_1 = new Entity2().setId("2_1");
Entity2 e2_2 = new Entity2().setId("2_2");

e1.getEntity2().add(e2_1);
e1.getEntity2().add(e2_2);

e2_1.setEntity1(e1);
e2_2.setEntity1(e1);

entity1Repo.save(e1);
```

**The deletion request that does not arrive in the database:**
```
public void deleteEntity2UsingRepo2() {
    Entity1 e1 = entity1Repo.findAll().get(0);
    Entity2 e2 = e1.getEntity2().get(0);

    entity2Repo.delete(e2);
}
```
Full code example with Unit test: https://github.com/PeRaVs/database-sample

**Comment by schauder** [comment]
That is an interesting finding, but I think it might be a Hibernate issue, not a Spring Data JPA issue.

If I add the following to `MyService` a test using this fails as well and it is completely independent of Spring Data JPA.

```java

    public void deleteEntity2UsingEm() {

        final Entity1 e1 = em.createQuery("select e from Entity1 e", Entity1.class).getResultList().get(0);
        Entity2 e2 = e1.getEntity2().get(0);

        em.remove(e2);
    }
```

I'll create a PR with the changes to your example repo and suggest you create an issue with Hibernate. 
You probably want to use their reproducer template since they aren't to fond of dealing with Spring stuff in their reproducers.

**Comment by PeRaVs** [comment]
Thank you very much for the input! I will introduce this to Hibernate and post the link here as soon as possible :)

**Comment by PeRaVs** [comment]
I have done a little bit more investigation on this and followed your advice to recreate the error using pure Hibernate and the Hibernate ORM testcase template:

Result is: **Hibernate ends with an Exception** thrown to indicate that the deleted object would be re-saved by cascade if it is not removed from the associations. **This exception is invisible when I use JPA.**

```
jakarta.persistence.EntityNotFoundException: deleted object would be re-saved by cascade (remove deleted object from associations): [org.hibernate.bugs.entities.Entity2#2_1                                 ]

	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:133)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:175)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:182)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1426)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:476)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2233)
```

When I change my original example here https://github.com/PeRaVs/database-sample adding the delete statement to remove the Entity2 from the list, the original example works as expected.

The ORM testcase using pure Hibernate can be found here: https://github.com/PeRaVs/hibernate-sample

In my opinion, I would have liked to see the Hibernate exception also pop up when JPA is used.

**Comment by schauder** [comment]
The problem seems to be that while Hibernates `Session` does throw that exception, the `EntityManager` implementation doesn't. 

Only the `EntityManager` is part of the JPA, so Spring Data JPA can only use this.

I have no idea if there is some intention behind this difference in behaviour, or if this is intentional (maybe it would violate the JPA Spec)? Either way, I'm afraid, I can only push this one back towards Hibernate.

I'll send another PR to demonstrate my claim.

**Comment by schauder** [comment]
The PRs for future reference: 
https://github.com/PeRaVs/database-sample/pull/1
https://github.com/PeRaVs/hibernate-sample/pull/1

**Comment by PeRaVs** [comment]
Thanks for your contribution to my code sample. I've raised up a Hibernate Bug: 
https://hibernate.atlassian.net/browse/HHH-15469
