### ISSUE TITLE
 Missing feature related to Class-based Projections.

### ISSUE THREAD

**Issue by ogunodabass** [spring-projects/spring-data-jpa#2635]
Hello Spring Team.

in the document: **no nested projections can be applied**
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections.dtos

I developed the code as application, did some tests and results. It is possible to query dynamically, without specifying the join type, lazy fields can join automatically without using join fetch or EntityGraph. Compared to the normal Entity class (even when querying the same fields), the speed of the select query is much faster.

```java
@Data
public class UserDto1 {
	private Long id;
	private String email;
	private String password;
	private AdressDTO1 adressDTO;

	public UserDto1(Long id, String email, String password, Long adressId, int adressNo, String adressHouse) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.adressDTO = new AdressDTO1(adressId, adressNo, adressHouse);
	}
}
```

```java
@Data
@AllArgsConstructor
public class AdressDTO1 {

	private Long id;
	private int no;
	private String house;
}
```
```java
public interface UserRepository extends JpaRepository<User, Long> {

	public <T> List<T> findBy(Class<T> clazz);
}
```

```java
@Data
@Builder(setterPrefix = "set")
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@AllArgsConstructor
@NoArgsConstructor


@Entity
@Table
public class User {

	@Id
	@SequenceGenerator(name = "user_sequence", sequenceName = "sq_user",allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_sequence")
	private Long id;
	@Column
	private String email;
	@Column
	private String password;

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@ToString.Include(name = "id")
	private Adress adress;
}
```

**Comment by gregturn** [comment]
In light of #2846, have you checked out that this is now valid for `@Query`?

```
select new com.example.Dto(
    e.name,
    e.role,
    new com.example.Address(
        e.address.street,
        e.address.city,
        e.address.zipcode)
    )
from Employee e
join e.address 
```

This is a simple approximation of your query, but nevertheless it's legal in our HQL parser, and so should work with Hibernate, assuming you tune it to your specific DTO types.

**Comment by ogunodabasss** [comment]
Very good. I tried something similar before, I can't remember what result I got.

However, in my benchmark tests, I discovered that DTO based queries are faster than entity and interface based projections. resultSetTransformer() gave the best results, but their performance was very similar. Interface-based projection uses too much System.gc(). If the System.gc problem is solved, it can perform the same as DTO based projection.

Additionally, the execution speed of queries for classes with the return type @ Entity is very slow. 
Can development be done to speed it up?

Benchmark Result: 
[https://github.com/ogunodabass/Spring-JPA-Hibernate-Select-Query-Benchmark/tree/main/008DtoVsObjectVsProjectionVsTupleVsDtoMapper-Lazy-Speed/src/test/java/com/example/demo/benchmark/hot](url)

`
BechhmarkGroupReturnEntity.findAll_User_JPA                                  avgt   20  313996,003 ± 14203,533  us/op
BechhmarkGroupReturnEntity.findBy_UserDto1_dynamic                            avgt   20  114260,209 ±   826,879  us/op
BechhmarkGroupReturnEntity.findUserProjection_UserProjection_JPQL             avgt   20  416818,290 ± 11266,894  us/op
`

Interface Based Projection GC Activity:
[https://github.com/ogunodabass/Spring-JPA-Hibernate-Select-Query-Benchmark/blob/main/008DtoVsObjectVsProjectionVsTupleVsDtoMapper-Lazy-Speed/VisualVm%20Metrics/endpoint-ex22.png](url)

visualVm test images of all the queries I compared in the application:
[https://github.com/ogunodabass/Spring-JPA-Hibernate-Select-Query-Benchmark/blob/main/008DtoVsObjectVsProjectionVsTupleVsDtoMapper-Lazy-Speed/VisualVm%20Metrics/projection%20test-visualvm.png](url)

**Comment by gregturn** [comment]
Given we now have first class support for DTO-based queries in both JPQL as well as HQL, I'm going to close this ticket.

If you wish to open a performance-based ticket, I encourage you to open a new ticket so we can tackle that as a separate effort.

**Comment by gregturn** [comment]
Superseded by #2814.
