### ISSUE TITLE
SqlParserQueryEnhancer errors with Merge statements

### ISSUE THREAD

**Issue by xercasy** [spring-projects/spring-data-jpa#2641]
Hello

similar to #2593

With spring boot >= 2.7, the application failed to start because of merge statement (oracle syntax)

> class net.sf.jsqlparser.statement.merge.Merge cannot be cast to class net.sf.jsqlparser.statement.select.Select (net.sf.jsqlparser.statement.merge.Merge and net.sf.jsqlparser.statement.select.Select are in unnamed module of loader 'app')

for exemple in a JPA repository

```
@Modifying
@Query(value = "merge into ...", nativeQuery = true)
void mergeStatement();
```

`detectParsedType()` in _JSqlParserQueryEnhancer_ appears to neglect the Merge statement which is supported by Jsqlparser

**Comment by gregturn** [comment]
@DiegoKrupitza Is this a scenario you're familiar with?

**Comment by DiegoKrupitza** [comment]
> @DiegoKrupitza Is this a scenario you're familiar with?

I will take a look at this! I have seen that @xercasy has already proposed a PR for this (#2642).

**Comment by DiegoKrupitza** [comment]
@gregturn As realized thanks to the issue #2593 I did not implement all the possible Statements JSqlParser can handle. In #2595 I added support for `INSERT`. Thanks to @xercasy the PR #2642 will fix it with `MERGE`. 

I already reviewed the PR #2642 and as far as I can see it should fix the problem.

**Comment by gregturn** [comment]
Thanks to @xercasy and @DiegoKrupitza, this additional support for native `MERGE` operations is now merged to `main`.

**Comment by xercasy** [comment]
@gregturn Can you backport this issue and https://github.com/spring-projects/spring-data-jpa/issues/2593 to 2.7.x ? Thanks

**Comment by gregturn** [comment]
Backported to `2.7.x`.
