### ISSUE TITLE
Entity json attribute not populated with repository findBy method

### ISSUE THREAD

**Issue by varjoranta** [spring-projects/spring-data-jpa#2643]
I have an entity with id, uuid, some many-to-many mappings, and also a detail field that is using the json type. We are using MySQL database currently. The json field is as follows:

```
@Type(type = "json")
@Column(name = "detail", columnDefinition = "json", length = 1000)
@Getter
private Map<@NotNull @NotBlank @Size(max = 63) String, @Size(max = 255) String> detail = new HashMap<>();
```

I have also a repository method based on findBy method naming convention:

```
    @Transactional(readOnly = true, timeout = 5)
    @Nonnull
    Optional<DbEntity> findByNameAndConnection_Uuid(String name, UUID connectionUuid);
```

This works otherwise, except that the json field in the entity is returned empty, even there is string json data in the database column.

If I keep everything else the same, but just add `@Query` to the findBy method, the json field gets populated correctly from the database, i.e. the following works:

```
    @Transactional(readOnly = true, timeout = 5)
    @Nonnull
    @Query(
            value =
                    "SELECT a FROM DbEntity e "
                            + "LEFT JOIN FETCH a.mappings "
                            + "WHERE e.name = ?1 AND e.connection.uuid = ?2")
    Optional<DbEntity> findByNameAndConnection_Uuid(String name, UUID connectionUuid);
```

**Comment by varjoranta** [comment]
Using Spring versions:
`org.springframework.boot:spring-boot-starter-data-jpa:jar:2.6.11:compile`
`org.springframework.data:spring-data-jpa:jar:2.6.6:compile`

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
