### ISSUE TITLE
Three entity ManyToMany relations, query duplicate result with findById 

### ISSUE THREAD

**Issue by shuanshuan** [spring-projects/spring-data-jpa#2645]
`
//User.java 
{
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
        private String username;
        @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.REFRESH)
	@JoinTable(name = "user_and_role", 
	inverseJoinColumns = @JoinColumn(name = "role_id"), 
	joinColumns = @JoinColumn(name = "user_id"))
	private List<SpringUserRole> userRoles = new ArrayList<>();

.....
}
//
//UserRole.java 
{
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
         private String roleName;
         
       @ManyToMany(mappedBy = "userRoles")
	@JsonProperty(access = Access.WRITE_ONLY)
	private List<User> users = new ArrayList<>();

      	@ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.REFRESH)
	@JoinTable(name = "role_and_permission", 
				inverseJoinColumns = @JoinColumn(name = "permission_id"), 
				joinColumns = @JoinColumn(name = "role_id"))
	private List<RolePermission> permissions = new ArrayList<>();

}
//RolePermission.java
{
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
        
        @ManyToMany(mappedBy = "permissions")
	@JsonProperty(access = Access.WRITE_ONLY)
	private List<UserRole> roles = new ArrayList<>();

}

//working
springUserRepository.findByUsername("admin").get();

//strange result
springUserRepository.findById(1L).get();

//Json
....
"userRoles": [
        {
            "created": null,
            "id": 1,
            "permissions": [
                {
                    "authority": "user_query",
                    "code": "user_query",
                    "id": 1
                },
                {
                    "authority": "role_query",
                    "code": "role_query",
                    "des": "角色查询",
                    "id": 2
                },
                {
                    "authority": "equ_query",
                    "code": "equ_query",
                    "id": 3
                }
            ],
            "role": "admin",
            "roleName": "admin",
            "updated": null
        },
        {
            "created": null,
            "id": 1,
            "permissions": [
                {
                    "authority": "user_query",
                    "code": "user_query",
                    "id": 1
                },
                {
                    "authority": "role_query",
                    "code": "role_query",
                    "id": 2
                },
                {
                    "authority": "equ_query",
                    "code": "equ_query",
                    "id": 3
                }
            ],
            "role": "admin",
            "roleName": "admin",
            "updated": null
        },
        {
            "created": null,
            "id": 1,
            "permissions": [
                {
                    "authority": "user_query",
                    "code": "user_query",
                    "id": 1
                },
                {
                    "authority": "role_query",
                    "code": "role_query",
                    "id": 2
                },
                {
                    "authority": "equ_query",
                    "code": "equ_query",
                    "id": 3
                }
            ],
            "role": "admin",
            "roleName": "admin",
        }
    ],
.....

`

**Comment by shuanshuan** [comment]
JDK:17

**Comment by schauder** [comment]
Crosspost https://stackoverflow.com/questions/73860940/spring-data-jpa-three-entities-manytomany-relations-query-duplicate-result-wit

**Comment by shuanshuan** [comment]
https://github.com/shuanshuan/demo-questions
https://stackoverflow.com/questions/73860940/spring-data-jpa-three-entities-manytomany-relations-query-duplicate-result-wit

@schauder please view this question again,  I still think this is bug
