### ISSUE TITLE
Ambiguous query generation with null-valued parameters in like-queries

### ISSUE THREAD

**Issue by yura2201** [spring-projects/spring-data-jpa#2653]
### **Problem**
-------------------------
Actually the issue [2548](https://github.com/spring-projects/spring-data-jpa/issues/2548) has not been completely resolved! 
`PersistenceProvider#condense(Object)` returns an empty string, so then the query
```@Query(SELECT t FROM My_Table t WHERE (:param is NULL or t.attr LIKE %:param%))```
will transform into ```select my_table.id, ..., my_table.attr as attrN from my_table where '%%' is null or my_table.attr like '%%'``` whereas in spring-data-jpa 2.6.4 or earlier it will transform to ```select my_table.id, ..., my_table.attr as attrN from my_table where NULL is null or my_table.attr like NULL```

**Comment by gregturn** [comment]
@yura2201 Feel free to test out the snapshots.

**Comment by yura2201** [comment]
@gregturn hey! it looks good, but I didn't succeed to find a proper snapshot in a [snapshot-repo](https://repo.spring.io/libs-snapshot) for `2.7.x`

**Comment by gregturn** [comment]
https://repo.spring.io/ui/native/libs-snapshot/org/springframework/data/spring-data-jpa/2.7.6-SNAPSHOT/ was published on 11/9/2022. 

<img width="570" alt="Screen Shot 2022-11-14 at 1 16 09 PM" src="https://user-images.githubusercontent.com/311040/201746304-a1aace71-160a-47fb-9a49-364cce5c69d0.png">
