### ISSUE TITLE
How to use enumerations in @Query

### ISSUE THREAD

**Issue by itlab1024** [spring-projects/spring-data-jpa#2660]
when i use @Query("delete from USER where gender = GENDERENUM.MAN)。 An error occurred，How do I use in @Query? please tell me, thanks

**Comment by itlab1024** [comment]
i do not want to use setParameter function!

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jpa`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.

Whenever you ask about a software error please describe the error: does the wrong thing happen, does an exception get thrown, or anything else. If an exception is involved please provide the full stacktrace.

In this case the question might already be answered:https://stackoverflow.com/questions/43665090/why-do-we-have-to-use-modifying-annotation-for-queries-in-data-jpa
