### ISSUE TITLE
Querying the object containing json before saving other objects will trigger the object to also be saved

### ISSUE THREAD

**Issue by Cooolyu** [spring-projects/spring-data-jpa#2665]
Spring DATA JPA VERSION: 2.7.3
![image](https://user-images.githubusercontent.com/16718459/195570700-098b9c7d-6f09-4096-ad94-7c947bbbe49c.png)
![image](https://user-images.githubusercontent.com/16718459/195571064-4d611501-a51d-4f02-9c14-485438ef32c1.png)
![image](https://user-images.githubusercontent.com/16718459/195570906-b58f815c-95f7-4182-9bdb-4fc424017d3b.png)

**Comment by schauder** [comment]
This is just the way Hibernate works. Spring Data JDBC isn't involved in this. 

If you consider this a bug, please report it to Hibernate.
