### ISSUE TITLE
Not able to detach non entity from persistentContext when dealing with large volume of data's that we were reading as Stream.

### ISSUE THREAD

**Issue by sau3078** [spring-projects/spring-data-jpa#2672]

**Comment by schauder** [comment]
Are you saying what you are trying to do works with `List` as return type for a query method, but not with `Stream`?

And what are you trying to do in the first place? What does "not able to detach" mean?

**Comment by sau3078** [comment]
> Are you saying what you are trying to do works with `List` as return type for a query method, but not with `Stream`?
> 
> And what are you trying to do in the first place? What does "not able to detach" mean?

Please see below example : 

Here T is not standard JPA entity . T is some custom Java Bean.
try (Stream<T> data's = repository.findMyCustomEntity()) {
      data's.forEach(data -> {
        try {
          rabbitMQSender.sendMessage(objectMapper.writeValueAsString(data));
        } catch (JsonProcessingException e) {
          throw new IllegalArgumentException(e.getMessage());
        }
        //releases the object from its persistence context, the JVM can successfully free the memory during the next GC.
        this.entityManager.detach(data);
      });
    }

**Comment by schauder** [comment]
And in what sense are you not able to detach the entity? Do you get an exception?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
