### ISSUE TITLE
Shouldn't JpaRepository extend ListCrudRepository/ListPagingAndSortingRepository?

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-data-jpa#2688]
In Spring Data 3 `JpaRepository` does not extend the new interfaces `ListCrudRepository`/`ListPagingAndSortingRepository` but `MongoRepository` does. Was this forgotten?

Currently, it looks like this:

![grafik](https://user-images.githubusercontent.com/5071169/197994430-6383cda7-0f6b-4f8e-98ee-16a9b870e83d.png)

Both  `JpaRepository` and `MongoRepository` use covariant return types and return `List` anyway.

`JpaRepositoryImplementation `and `SimpleJpaRepository `are also extending `CrudRepository `and `PagingAndSortingRepository `not `List[CrudRepository|PagingAndSortingRepository]`.

I put this issue here in the Commons project because it's related to several projects ...

**Comment by schauder** [comment]
Yes, this was an oversight. Thanks for bringing this up.
