### ISSUE TITLE
Allow sorting of unpaged results

### ISSUE THREAD

**Issue by naihil** [spring-projects/spring-data-jpa#2691]
QuerydslPredicateExecutor provides a method `Page<T> findAll(Predicate predicate, Pageable pageable);`
You can pass Pageable.unpaged() to get all rows in single page, in this case result not sorted.
If you write custom implementation of unpaged() that has some sort and pass it to findAll, this doesnt work because of this code:
https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/Querydsl.java#L117
`

		if (pageable.isUnpaged()) {
			return query;
		}

		query.offset(pageable.getOffset());
		query.limit(pageable.getPageSize());

		return applySorting(pageable.getSort(), query);
`
Sorting applied after isUnpaged() check.

We can change code to:
`

		if (pageable.isPaged()) {
			query.offset(pageable.getOffset());
			query.limit(pageable.getPageSize());
		}

		return applySorting(pageable.getSort(), query);
`
And this code allows sorting of unpaged queries.
Linked with https://github.com/spring-projects/spring-data-commons/issues/1840

**Comment by schauder** [comment]
Could you please clarify why you would want to use sorting with pagination if you actually do not want to page the result?

Instead you could use one of the methods that allow direct supply of sorting.

**Comment by naihil** [comment]
Simple example: frontend with data table and rows-per-page combobox with option "All rows", from request you get pageable, pass it to repository without any additional logic and receive page that can be sorted/unsorted/one from any others or single page with all rows

**Comment by mp911de** [comment]
`Pageable.unpaged()` is a substitute for `null`. Previously, we accepted `null` as parameter for `Pageable`. Following that line of thought, there would not be a `Sort` associated with a `null` `Pageable.`

**Comment by jiayp** [comment]
> 

If we don't accept unpaged with sort Pageable,I think we should add a assert for that.

**Comment by jiayp** [comment]
My understanding is that no unpaged is a special kind of paging, so we should allow him to carry sorting properties.

**Comment by julianschelker** [comment]
I have a similar usecase: Query is quite complex and table has 17 million entries. I want to fetch the first 100 entries that match a criteria sorted by a field. This all works quite fast thanks to indices on field that needs to be sorted in the database. However the findAll with pageable in Spring also executes a query "Select count(...)" to return the total rows which takes subsequently forever.

Why can't I provide the findAll method with the information that I don't need to know the count of all rows, but still provide sort and limit parameters?

That corresponds to the request of providing a Unpaged object with sort and limit.

**Comment by mp911de** [comment]
How about defining a query method returning `Slice`: `Slice<MyObject> findAllByFoo(String foo, Pageable pageable)`?

**Comment by naihil** [comment]
@trohr I use this workaround:
1. In controller get method i have 2 params: Pageable pageable and @RequestParam(value = "unpaged", required = false) Boolean unpaged;
2. This params provided to service method: findService.find(Pageable pageable, Boolean unpaged)
3. In service method i have such code:
`		PageRequest pageRequest;
		if (Boolean.TRUE.equals(unpaged)) {
			long count = workObjectRepository.count(predicate);
			pageRequest = PageRequest.of(0, (int) count, pageable.getSort());
		}
		else {
			pageRequest = PageRequest.of(pageable.getPageNumber(), pageable.getPageSize(), pageable.getSort());
		}

		final Page<WorkType> workObjectPage = workObjectRepository.findAll(predicate, pageRequest);
`

There is +1 query to get rows count with needed predicate, but you dont need multiple methods for paged and unpaged requests
