### ISSUE TITLE
First Level Cache

### ISSUE THREAD

**Issue by liruhui** [spring-projects/spring-data-jpa#2698]
## 1: Problem description
![QQ图片20221113022612](https://user-images.githubusercontent.com/24687986/201489185-73571299-51c0-4360-b96b-63c2b926b6f2.png)

## 2: Other Question
```properties
  when  Query BY  JPQL,QueryByExampleExecutor and JpaSpecificationExecutor , no cache
```
![QQ图片20221113023027](https://user-images.githubusercontent.com/24687986/201489345-875e0cc4-9d92-4271-abc6-e69fb541bd52.png)
![QQ图片20221113023123](https://user-images.githubusercontent.com/24687986/201489381-b46dbde4-793b-4372-94ca-11084b40c0fc.png)

**Comment by schauder** [comment]
This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jpa`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.

But this one isn't even about Spring Data JPA, it is just JPA/Hibernate usage. You might find this answer helpful: https://stackoverflow.com/a/23454195/66686
