### ISSUE TITLE
`EntityManagerBeanDefinitionRegistrarPostProcessor` does not ensure unique `SharedEntityManagerCreator` beans

### ISSUE THREAD

**Issue by imperatorx** [spring-projects/spring-data-jpa#2699]
3.0.0-RC2 (and 1 too)

Given a trivial config:

```xml
<dependencies>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jpa</artifactId>
</dependency>
<dependency>
	<groupId>org.postgresql</groupId>
	<artifactId>postgresql</artifactId>
</dependency>
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>
	<scope>test</scope>
</dependency>
</dependencies>
```

And datasource configured:

```
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=postgres
spring.datasource.password=postgres
```

And a `@Component` `@Autowire`-ing an `EntityManager`, the application fails to start when compiled with `mvnw -Pnative native:compile`, but starts normally when started in java mode from the IDE:

```
No qualifying bean of type 'jakarta.persistence.EntityManager' available: more than one 'primary' bean found among candidates: [org.springframework.orm.jpa.SharedEntityManagerCreator#0, org.springframework.orm.jpa.SharedEntityManagerCreator#1]
```

**Comment by snicoll** [comment]
It looks like `SharedEntityManagerCreator` is created at build-time and taken into account by AOT, and SD JPA is creating it again at runtime. It should rather check if it's there and skip it.

**Comment by mp911de** [comment]
The underlying problem is that multiple runs of `EntityManagerBeanDefinitionRegistrarPostProcessor` result in registering multiple auto-wire candidates of `EntityManager` via `SharedEntityManagerCreator`. We should consider unique bean names to ensure that we end up with a single `EntityManager` for each `EntityManagerFactory` bean even when running `EntityManagerBeanDefinitionRegistrarPostProcessor` multiple times.
