### ISSUE TITLE
Regression in 3.0 when combining 1:n relation, @EntityGraph and Pageable

### ISSUE THREAD

**Issue by steffen-schaefer** [spring-projects/spring-data-jpa#2702]
Hello,

We identified an issue in 3.0.0 snapshots regarding paging under the following circumstances:

- Entity A has a 1:n relation to entity B
- There are A entries having multiple B values
- Using a spring data JPA query with Pageable parameter and Page result
- An @EntityGraph is added to the query which includes loading the collection of B values on A

In this case, the following happens:

- The resulting query includes a left join on B which in combination with paging returns less results than requested via Pageable
- The resulting Page's totalElements is equal to the number of values contained in the page

The described scenario works fine using 2.7.x.

A minimal reproduction scenario is attached
[demo.zip](https://github.com/spring-projects/spring-data-jpa/files/10019232/demo.zip)

Thanks in advance!

**Comment by schauder** [comment]
I turned your demonstrator in a GitHub repository and reproduced the issue using the `EntityManager` directly.

I therefore conclude that this is a Hibernate regression and you'd need to file an issue with them to get it fixed.

**Comment by steffen-schaefer** [comment]
Thank you for the thorough analysis. We filed an issue in Hibernate Jira: https://hibernate.atlassian.net/browse/HHH-15880
