### ISSUE TITLE
spring-data-envers 3.0.0 expects the wrong column type for audit table keys

### ISSUE THREAD

**Issue by donalmurtagh** [spring-projects/spring-data-jpa#2712]
While upgrading a Spring Boot app from v2.7.5 to v3.0.0, I upgraded the spring-data-envers starter to v3.0.0. The relevant section of the Gradle dependency report is shown at the end of this issue.

In my entity classes, the primary keys are UUIDs. The column type for these keys are `varachar(255)`. Prior to the upgrade, these were defined as follows

```java
@Audited
@Entity
@Table(name = "foo")
public class Foo {
    @Id
    @GeneratedValue
    @Type(type = "uuid-char")
    private UUID id;

    // getters, setters, etc. omitted
}
```

In Hibernate 6, the `type` attribute of the `@Type` annotation no longer exists. Initially, I tried just removing this annotation, but this caused an error because Hibernate then expects the primary key column type to be a UUID. In order to inform Hibernate that it should be stored as a `varchar`, I added the `@JdbcType` annotation 

```java
@Audited
@Entity
@Table(name = "foo")
public class Foo {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @JdbcType(VarcharJdbcType.class)
    private UUID id;

    // getters, setters, etc. omitted
}
```

While this fixes the mapping for the `foo` table, I now get a mapping error for the `foo_aud.id` column at startup.

> Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: **wrong column type encountered in column [id] in table [foo_aud]; found [varchar (Types#VARCHAR)], but expecting [uuid (Types#UUID)]**
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateColumnType(AbstractSchemaValidator.java:179) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]

**It seems that Hibernate/JPA is aware of the `@JdbcType` annotation when computing the expected column type, but Envers is not.**

### Post-Migration Gradle Dependency Report
```
+--- org.springframework.data:spring-data-envers -> 3.0.0
|    +--- org.springframework.data:spring-data-jpa:3.0.0 (*)
|    +--- org.hibernate.orm:hibernate-envers:6.1.4.Final -> 6.1.5.Final
|    |    +--- org.hibernate.orm:hibernate-core:6.1.5.Final (*)
|    |    +--- org.jboss.logging:jboss-logging:3.4.3.Final -> 3.5.0.Final
|    |    +--- jakarta.xml.bind:jakarta.xml.bind-api:3.0.1 -> 4.0.0 (*)
|    |    +--- org.glassfish.jaxb:jaxb-runtime:3.0.2 -> 4.0.1 (*)
|    |    +--- org.hibernate.common:hibernate-commons-annotations:6.0.2.Final
```

**Comment by schauder** [comment]
This seems to be a Hibernate/Envers problem. I don't think there is much the Spring Data team can do about this.

**Comment by donalmurtagh** [comment]
I've [reported the issue](https://hibernate.atlassian.net/browse/HHH-15777) to Hibernate
