### ISSUE TITLE
Exact projection field names should not matter

### ISSUE THREAD

**Issue by wiktoor** [spring-projects/spring-data-jpa#2715]
Let's say I have a simple table in MySQL database
```
create table users (
  id bigint primary key,
  first_name char(10),
  last_name char(10),
  registration_date timestamp(3)
);
```

and corresponding class:

```
@Entity
@Table(name = "users")
public class UserEntity {
  @Id 
  Long id;
  @Column(name = "first_name")
  String firstName;
  @Column(name = "last_name")
  String lastName;
  @Column(name = "registration_date")
  LocalDateTime registrationDate;
}
```

and I want to get `first_name` and `second_name` field in a query. 

```
@Repository
public interface UsersRepository extends CrudRepository<User, Void> {
  @Query(value = "select u.first_name, u.second_name from users where u.first_name = :firstName", nativeQuery = true)
  List<NameProjection> findUsersByFirstName(@Param("firstName") String firstName);
}
```

then if my `NameProjection` interface looks like this:

```
public interface NameProjection {
  String getFirstName();
  String getLastName();
}
```

then the method always returns null. The solution is to rename methods in the interface to `getfirst_name()` and `getlast_name()`, which makes the code much more ugly.

I understand that detecting this is not, by any means, a must have, but it would be cool if it was implemented, especially if it's already done in other spring libraries.

**Comment by schauder** [comment]
Alternatively you may provide aliases with the columns in the select.

**Comment by wiktoor** [comment]
You are right. Can I somehow achieve this without `nativeQuery`?

**Comment by schauder** [comment]
```
select u.firstName, u.secondName from UserEntity  u where u.firstName = :firstName
```

should work.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.
