### ISSUE TITLE
Kotlin sub data class override field is null on Spring Boot/Data jpa 3.0.0

### ISSUE THREAD

**Issue by ZedG2** [spring-projects/spring-data-jpa#2729]
I have a super class and multiple subclasses, all subclasses map to single tabel.
When I use JPA to query data, I can't access super class's properties.

example:

```kotiln
@Entity
@@Inheritance
abstract class Order( @Id open val oid: String)

@Entity
data class PlaneOrder(
    val foo: String,
    @Id
    override val oid: String,
): Order(oid)
```

I only can access `planeOrder.foo`, If I call `planeOrder.oid` the result is null.
In intellij debugger view, It's seem like.

```
order = {PlaneOrder@hashcode}
+ foo = "bar"
+ oid = null
+ Order.oid = "ididid"
---

The same code is worked on Spring-Boot 2.X, so any workaround or advice?

**Comment by schauder** [comment]
The classes you show do not have a inheritance relationship, but I guess that is just a typo?

Anyway, what you describe sounds more like an issue of the JPA implementation you are using.

If you think this is indeed a Spring Data JPA issue, please provide a reproducer that demonstrates the issue and also demonstrates that it does not occur when you are using JPA directly, i.e. load and persist entities using the `EntityManager` directly.

**Comment by ZedG2** [comment]
> The classes you show do not have a inheritance relationship, but I guess that is just a typo?
> 

Sorry it's typo






> Anyway, what you describe sounds more like an issue of the JPA implementation you are using.
> 
> If you think this is indeed a Spring Data JPA issue, please provide a reproducer that demonstrates the issue and also demonstrates that it does not occur when you are using JPA directly, i.e. load and persist entities using the `EntityManager` directly.

You're probably right, sorry I didn't verify this first, I'll verify later if it's a JPA implementation issue.

**Comment by ZedG2** [comment]
I've basically been able to confirm that it's hibernate issue.
So I close this issue, sorry guys.
