### ISSUE TITLE
Shared `EntityManager` is `synthetic`, preventing bean post processing

### ISSUE THREAD

**Issue by kzander91** [spring-projects/spring-data-jpa#2730]
The `EntityManager` registered in `JpaRepositoryConfigExtension` is `synthetic` (which is new as of 3.0). Synthetic beans are not post-processed by Spring, in particular it is therefore no longer possible to apply AOP interceptors to it.

See https://github.com/spring-projects/spring-boot/issues/33510 and https://github.com/spring-projects/spring-data-jpa/commit/1bfc3595ce2e14cdc03decfe350f20e139e3c877#r82897830 for details.

**Comment by schauder** [comment]
@christophstrobl Could you take a look? Especially at the referenced comment? That was on an AOT related change.

**Comment by christophstrobl** [comment]
@schauder will, do. might take some time though.

**Comment by christophstrobl** [comment]
I gave it a quick try without the `synthetic` flag wich seems to be fine also in AOT/native mode. But I need to do some further investigation. Changes are good this is a leftover that should have been removed. Things changed quite a bit since July. 
Thanks for reporting @kzander91 !

**Comment by quaff** [comment]
Any update?

**Comment by quaff** [comment]
@gregturn It's a regression block upgrading, could you resolve it ASAP?

**Comment by quaff** [comment]
@christophstrobl Would you take a look?

**Comment by quaff** [comment]
What's the decision?

**Comment by christophstrobl** [comment]
Removing `entityManager.setSynthetic(true)` from `JpaRepositoryConfigExtension` worked for the aot/native smoke test.

**Comment by quaff** [comment]
Then it's safe to merge https://github.com/spring-projects/spring-data-jpa/pull/2866.

**Comment by gregturn** [comment]
Merged to `main`, backported to `3.1.x` and `3.0.x`.
