### ISSUE TITLE
Limit results of an entity in a join

### ISSUE THREAD

**Issue by hks1** [spring-projects/spring-data-jpa#2734]
I have a data model wherein classA has a one-to-many relationship with classB.
When I query classA by ID, I want to limit the classB results in the response.

e.g. lets say classA is a Customer class and classB is an Order class and I want to pull only last 6 (configurable) orders or so instead of lets say the whole history of last 5 years, or whatever is stored.

Right now I get the whole list. I am using v 2.7.2

**Comment by schauder** [comment]
That would be a risky thing to do with JPA. 
If you change classA in anyway it would be considered dirty and gets persisted, along with its relationship which now doesn't contain the `Order` entities older than 6 months.


Instead use a separate query to load the `Order` entities you want.

**Comment by hks1** [comment]
> 

Thanks @schauder , that makes sense.
