### ISSUE TITLE
"Could not safely identify store assignment" messages with multiple Spring Data modules (JPA / MongoDB)

### ISSUE THREAD

**Issue by sebastianhaberey** [spring-projects/spring-data-jpa#2740]
Spring Data version: 2.6.0

I am getting the following errors on application start:

```
2022-12-22 11:54:44.370  INFO 10552 --- [    Test worker] .RepositoryConfigurationExtensionSupport : Spring Data JPA - Could not safely identify store assignment for repository candidate interface org.example.mongodb.MyMongoDbRepository. If you want this repository to be a JPA repository, consider annotating your entities with one of these annotations: javax.persistence.Entity, javax.persistence.MappedSuperclass (preferred), or consider extending one of the following types with your repository: org.springframework.data.jpa.repository.JpaRepository.
...
2022-12-22 11:54:44.784  INFO 10552 --- [    Test worker] .RepositoryConfigurationExtensionSupport : Spring Data MongoDB - Could not safely identify store assignment for repository candidate interface org.example.jpa.MyJpaRepository. If you want this repository to be a MongoDB repository, consider annotating your entities with one of these annotations: org.springframework.data.mongodb.core.mapping.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.mongodb.repository.MongoRepository.
```

This makes sense because `MyMongoDbRepository` is not a JPA repository and `MyJpaRepository` is not a MongoDB repository. But it's still unnerving to see this message for each repository on startup. The only way to get rid of it is

```
@EnableJpaRepositories("org.example.jpa")
@EnableMongoRepositories("org.example.mongodb")
```

somewhere in the Spring configuration. My question is, is that the expected behaviour?

**Comment by mp911de** [comment]
It is the intended behavior. Spring Data has no means to determine what store module should implement a repository definition unless you annotate entity classes, subclass a store-specific repository interface or provide a base package/filters in your `@Enable…Repositories` declaration. Check out the reference docs on [Using Repositories with Multiple Spring Data Modules](https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#repositories.multiple-modules).

**Comment by sebastianhaberey** [comment]
What I meant to say is that both classes are proper subclasses of their respective module classes `MongoRepository` and `JpaRepository`. So Spring Data should be able to associate them with their module, and there shouldn't be an error message. Or am I mistaken?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by sebastianhaberey** [comment]
Yes, sorry, the project is completed and I don't have access to the code any more. If I come across this again I'll file a new issue with a minimal example included.

**Comment by jruijgers** [comment]
@mp911de Not sure if you are still working on this, but here is a repo with 2 Data Repositories that give this warning for each other: [jruijgers/spring-data-multiple-implementations](https://github.com/jruijgers/spring-data-multiple-implementations)

**Comment by alturkovic** [comment]
> [@mp911de](https://github.com/mp911de) Not sure if you are still working on this, but here is a repo with 2 Data Repositories that give this warning for each other: [jruijgers/spring-data-multiple-implementations](https://github.com/jruijgers/spring-data-multiple-implementations)

Have you found a solution for this? Still happening for me in `4.1.0-M2`.

I have JPA and ElasticSearch Data modules with the following definition examples:

```
interface CommentRepository : JpaRepositoryImplementation<CommentEntity, UUID>
interface LogRepository : ElasticsearchRepository<LogDocument, UUID>
```

And when I start my application, I can see the following in the logs:

```
Spring Data Elasticsearch - Could not safely identify store assignment for repository candidate interface app.example.db.CommentRepository; If you want this repository to be a Elasticsearch repository, consider annotating your entities with one of these annotations: org.springframework.data.elasticsearch.annotations.Document (preferred), or consider extending one of the following types with your repository: org.springframework.data.elasticsearch.repository.ElasticsearchRepository

...

Spring Data JPA - Could not safely identify store assignment for repository candidate interface app.example.es.LogRepository; If you want this repository to be a JPA repository, consider annotating your entities with one of these annotations: jakarta.persistence.Entity, jakarta.persistence.MappedSuperclass (preferred), or consider extending one of the following types with your repository: org.springframework.data.jpa.repository.JpaRepository
```

It seems like Spring should be able to recognize that `CommentRepository` is JPA backed and `LogRepository` is ES backed and I would not expect these log statements.

**Comment by mp911de** [comment]
The underlying issue to sort the log messages is to determine whether a repository candidate is being picked up by a different store module. We would have to introduce API and verify against all other store modules.

**Comment by alturkovic** [comment]
Thanks for the quick update! Is that planned for future?
Is raising the logging level to WARN the best way to mute these messages for now?

**Comment by mp911de** [comment]
Currently, we don't have bandwidth to work on this. Feel free to give it a spin if you like.
