### ISSUE TITLE
Javax.persistence is not longer available in 3.x

### ISSUE THREAD

**Issue by Dragamaster** [spring-projects/spring-data-jpa#2751]
Hi, i'm migrating from 2.7.5 to 3.0.1 and i realice that not longer add deoendencies to javax.persistence, this is correct?? i'm searching in your documentation and not found anything about that change.

Is this an issue or with this version we need to add de dependency

**Comment by schauder** [comment]
With recent versions of JPA `javax.persistence` got replaced with `jakarta.persistence`. You'll need to change the imports in your code.
