### ISSUE TITLE
In kotlin, when @Column(nullable = false) is marked, the queried entity must always be written "!!"

### ISSUE THREAD

**Issue by ddxl123** [spring-projects/spring-data-jpa#2752]
In kotlin,
When writing entity classes, the default values of attributes are null,
The annotation of the attribute is `@Column(nullable = false)`, which indicates that it cannot be empty.
For example, the following `username`:
```
@Entity
class Users {
    @Column(nullable = false)
    var username: String? = null
}
```

When querying, `findById` returns the following result:
 `val user = Users(username:"MyName")`

When calling `user. username!!` I have to bring `!!`,
because the annotation is `@Column(nullable = false)`.

This creates a problem:
When I get the `username`, I always have to check whether the `@Column` annotation of `username` is marked as empty or not, and then I can judge whether I should write `!!` or not.
This is very troublesome, and I always write what should not be written on `!!` carelessly.

What can I do to prevent the IDEA compiler from reporting errors when I mark `@Column(nullable = false)` and do not write `!!`?

If it is written like this (give the attribute a default value):
```
    @Column(nullable = false)
    var username: String = "default"
```
When using `findById` to query, I must bring `withIgnorePaths`, which is more troublesome:
```
val matcher = ExampleMatcher.matching().withIgnorePaths("username", ...))
Example.of(Users(username:""),matcher)
```

**Comment by schauder** [comment]
I don't think this is anything Spring Data JPA has any control over. 

This seems to be a mixture of Kotlin and IntelliJ IDEA behaviour.
I'd recommend asking such a question on Stackoverflow
