### ISSUE TITLE
Wrong result obtained from db with version 3.0.1 (also tested with 2.7.7)

### ISSUE THREAD

**Issue by disk91** [spring-projects/spring-data-jpa#2755]
Not sure where is the problem but I get wrong result from Database on a really simple query (rest of my SQL call seems to be correct)

DB SQL statement and result
```
SELECT * from tenant_user where user_id='23e008f4-49e1-4378-b2fc-fff9fc444f3e' and is_admin=true; 

tenant_id    	user_id	...
d1c01b19-df66-4b82-8640-2530d4330784	23e008f4-49e1-4378-b2fc-fff9fc444f3e
dedf8328-779d-4df3-96e5-7f4216925e4b	23e008f4-49e1-4378-b2fc-fff9fc444f3e
b814a45c-e8dc-4765-b874-89d7c0af4e52	23e008f4-49e1-4378-b2fc-fff9fc444f3e	
````
We have 3 lines with 3 different tenant_id for a single user

When executing the same query with spring JPA
```
@Query(value = "SELECT * from tenant_user where user_id='23e008f4-49e1-4378-b2fc-fff9fc444f3e' and is_admin=true;", nativeQuery = true)
    public List<UserTenant> findUserTenantByUserIdAndIsAdmin(
            UUID userId,
            boolean isAdmin
    );

Result:
23e008f4-49e1-4378-b2fc-fff9fc444f3e - get - d1c01b19-df66-4b82-8640-2530d4330784
23e008f4-49e1-4378-b2fc-fff9fc444f3e - get - d1c01b19-df66-4b82-8640-2530d4330784
23e008f4-49e1-4378-b2fc-fff9fc444f3e - get - d1c01b19-df66-4b82-8640-2530d4330784
```

We get 3 time the same record, number of record is ok, content of record is wrong.

I get exactly the same result with
```
 public List<UserTenant> findUserTenantByUserIdAndIsAdmin(
            UUID userId,
            boolean isAdmin
 );
```

Java code to display  this is:
```


List<UserTenant> uts = userTenantRepository.findUserTenantByUserIdAndIsAdmin(
                    UUID.fromString(userId),
                    true
);
for ( UserTenant ut : uts ) {
    log.info(ut.getUserId + " - get - "+ ut.getTenantId());
}
```

I don't really see what kind of stupid thing I could do to have this behavior, so any idea welcome, this is making me crazy

**Comment by schauder** [comment]
Please check if you get the same behaviour when you execute the query using an `EntityManager` directly.

If you get the same wrong result, then this is a Hibernate issue (or whatever JPA implementation you are using). Please raise an issue with them.

Otherwise we would need a reproducer, preferably as a GitHub repository, with the database included. Either as an in memory database when you can reproduce the issue with that, alternatively with the database included via Testcontainers.

**Comment by disk91** [comment]
Confirmed, EntityManager returns the same result.

**Comment by schauder** [comment]
Please leave a link here to any related issue you create with the JPA implementation.

**Comment by disk91** [comment]
The problem is fixed : this was related to composite IDs, the table has 2 IDs, I declared a single one. this is a Hybernate "Normal" behavior to make s***t in such situation even if the query result are good.
basically the solution has been ( for people having the same problem in the future )

```
...
@IdClass(UserTenantId.class)
...
public class UserTenant {
    @Id
    ...
    private UUID userId;

    @Id
    ...
    private UUID tenantId;

```
and create a class for managing the composite Id

```
public class UserTenantId implements Serializable {

    private static final long serialVersionUID = 0L;
    private UUID userId;
    private UUID tenantId;

    public UUID getUserId()...
    public void setUserId(UUID userId)...
    public UUID getTenantId()...
    public void setTenantId(UUID tenantId)...
}
```
