### ISSUE TITLE
Page result returns different values than the generated SQL

### ISSUE THREAD

**Issue by AlanRoblesDLT** [spring-projects/spring-data-jpa#2772]
After upgrading to spring-data-jpa 3.0.0 a JPQL query that uses Pageable is returning less elements than expected.
I executed the generated SQL from the console and that returns the correct number of elements.
I don't see a count SQL query being generated when using spring-data-jpa 3.0.0

JPQL Query:
    @Query(value = "select fsd from FeeScheduleDrugEntity fsd "
        + "left join DrugNdcEntity ndc on fsd.drug.id = ndc.drug.id and fsd.drug.noc = true "
        + "left join FeeScheduleSourceEntity fsse on fsse.id = fsd.drugFeeScheduleSource.id "
        + "where fsd.feeSchedule.id = :feeScheduleId ")

Generated SQL:
select f1_0.fee_schedule_drug_id,
       f1_0.allowable_per_billing_unit,
       f1_0.fee_schedule_drug_source,
       f1_0.created_at,
       f1_0.created_by,
       f1_0.drug_id,
       f1_0.fee_schedule_item_source_id,
       f1_0.fee_schedule_id,
       f1_0.modified_at,
       f1_0.modified_by
from core.fee_schedule_drug f1_0
         join core.drug d2_0 on d2_0.drug_id = f1_0.drug_id
         left join core.drug_ndc d1_0 on f1_0.drug_id = d1_0.drug_id and d2_0.is_noc = true
         left join core.fee_schedule_item_source f2_0
                   on f2_0.fee_schedule_item_source_id = f1_0.fee_schedule_item_source_id
where f1_0.fee_schedule_id=?
order by d1_0.ndc asc
offset ? rows fetch first ? rows only

**Comment by schauder** [comment]
This is a cross post from Stackoverflow: https://stackoverflow.com/questions/75177032/page-result-returns-different-values-than-the-generated-sql

Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

As mentioned on Stackoverflow this is likely a Hibernate bug.
If you don't think so please make sure to include equivalent, but working code based on the `EntityManager` directly to demonstrate this is actually a Spring Data issue.

**Comment by AlanRoblesDLT** [comment]
Seems to be a Hibernate issue https://hibernate.atlassian.net/browse/HHH-15964
