### ISSUE TITLE
DataIntegrityViolationException when creating a bi-directional many-to-many relationship

### ISSUE THREAD

**Issue by ThomHurks** [spring-projects/spring-data-jpa#2776]
I have a Spring Boot project using Spring Data JPA and Hibernate, we're using version 2.7.8 (latest of the 2.x series as of writing). I replicated exactly the code from Vlad Mihalcea's blog https://vladmihalcea.com/the-best-way-to-map-a-many-to-many-association-with-extra-columns-when-using-jpa-and-hibernate/ It's about creating a many-to-many relationship with extra attributes, and it uses an `@EmbeddedId` on the many-to-many table entity.

The problem I'm having is that Spring Data JPA throws an exception with this code. I can't spot anything obviously wrong, and the author of the code is a contributor to the Hibernate project so the code must've worked at some point at least. The code also seems consistent with everything I could find about this topic on StackOverflow, the documentation, other blogs, etc, so I'm assuming that this may be a bug with Spring Data JPA.

If you run the test contained in my reproduction project it will throw the following error:

`org.springframework.dao.DataIntegrityViolationException: A different object with the same identifier value was already associated with the session : [com.example.demo.entities.PostTag#com.example.demo.entities.PostTagId@3e2]; nested exception is javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [com.example.demo.entities.PostTag#com.example.demo.entities.PostTagId@3e2]
        at com.example.demo.services.PostServiceTest.testAddTagToPost(PostServiceTest.java:21)
Caused by: javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [com.example.demo.entities.PostTag#com.example.demo.entities.PostTagId@3e2]
        at com.example.demo.services.PostServiceTest.testAddTagToPost(PostServiceTest.java:21)
`

A workaround I found is that if you remove one side of the many-to-many relationship, for example by removing it from the `Tag` entity, making the relationship unidirectional, then it works fine. It's when it's bi-directional that it throws.

The reproduction project is here: https://github.com/ThomHurks/spring-data-jpa-many-to-many-with-attrs-issue

Thanks for the good work on this project by the way :heart:

**Comment by schauder** [comment]
What is happening is you have:
`Post` has a list of `PostTag`.
So does `Tag`.

Within a single transaction you load a `Post` and a `Tag`, create a new `PostTag` referencing both and add that to the lists of both `Tag` and `Post`.

You then call `save` on the `PostRepository`, which essentially does an `EntityManager.merge` on the `Post`.

The `merge` creates a new `PostTag` instance which is now in the persistence context (aka 1st level cache).
But the original `PostTage` is still referenced by the `Tag` instance, which gets flushed at the end of the transaction, resulting in the exception you are seeing.

Not sure what to do about it. 
I'm not sure we can convince the Hibernate team that it is a bug.
I also don't think it is a Spring Data JPA bug. 
So I'd say it is just one of these weird corner cases of JPA that you need to avoid.

From a Spring Data / DDD perspective you should avoid bidirectional relationships.
Alternatively you can remove the `save` call and rely on JPAs dirty checking to do a flush for you.

**Comment by ThomHurks** [comment]
Ah, many thanks for your explanation!

I tried all kinds of different things to get the code working, but I don't think I tried removing the `save()` to let the dirty checking flush the changes when the transaction commits. I should have, though, so a good lesson.

I have been using Spring/JPA/Hibernate for quite some time but indeed I've never really had to use a bidirectional many-to-many relation, so I hadn't encountered this corner case before. It was definitely non-intuitive. Is it possible that the documentation may be improved so this is more clear? For example, the Spring Data JPA documentation has a fairly similar code snippet in section 5.1.7. Transactionality, example 118:

`
@Transactional
  public void addRoleToAllUsers(String roleName) {

    Role role = roleRepository.findByName(roleName);

    for (User user : userRepository.findAll()) {
      user.addRole(role);
      userRepository.save(user);
    }
  }
`
The example then continues to explain that:
> Note that the call to save is not strictly necessary from a JPA point of view, but should still be there in order to stay consistent to the repository abstraction offered by Spring Data.

It may be good to explain somewhere that sometimes you need to avoid a manual call of `save()` because that can cause the problems that you described. This may only be the case with bidirectional many-to-many, but since JPA supports that it may be good to mention this in the Spring Data JPA docs. Will definitely save people some time :)

I also added a commit to my reproduction repo which shows the non-working code and a working version without the save, and it includes the explanation that you gave; if someone has the same problem and searches on the web, hopefully they'll find my repo too and save some time.

**Comment by ThomHurks** [comment]
Yeah, I can see your viewpoint. The decision is yours either way. I'll close this issue then. Thanks for helping!
