### ISSUE TITLE
Continue: SimpleJPARepository: Methods accessing metadata.getComment() without Null-Check produce NPE

### ISSUE THREAD

**Issue by dickerpulli** [spring-projects/spring-data-jpa#2778]
According to #2716 

@gregturn Unfortunately the commits https://github.com/spring-projects/spring-data-jpa/commit/f40b39c3ec1039c36f4545ee9a5f74c6451d850a and https://github.com/spring-projects/spring-data-jpa/commit/b0aa2b67546698fefc4218393ea9eebc01524c69 has not been pushed to the 3.0.x branch, so they were not a part of the 3.0.1 release. Could you please add them to the 3.0.x branch, so that they are at least included in next release 3.0.2?

Thanks.

**Comment by gregturn** [comment]
Resolved via 7dce3d119fa1e8a01d0e29fca1b790dbf6b19383 and 4a7126a21afc468f43f592e3139d34410c2f8b2c.

**Comment by dickerpulli** [comment]
Thanks
