### ISSUE TITLE
AbstractEntityInformation uses methods without "get" prefix as ID accessor for primitive id fields

### ISSUE THREAD

**Issue by igorbunova** [spring-projects/spring-data-jpa#2784]
I'm currently working on upgrading spring-boot from 2.3
There is the entity example I have
```
@Entity
@Table(name = "groups")
public class Group {
    @javax.persistence.Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "group_id")
    private long id;

    //... other fields
    
    @Version
    @Column(name = "version", nullable = false)
    private int version;
    
    public Id id() {
        return Id.fromNumber(id, IdType.GROUP);
    }
    //... other fields getters and setters

    public int getVersion() {
        return version;
    }
}
```
IdType is just an enum and Id is my custom type to convert internal database id to a value I can expose on the frontend. Basically instead of such implementation there can be
```
   public String id() {
       return "test";
   }
```
for testing.
Starting from spring-boot 2.4.0 I have
```
java.lang.IllegalStateException: Failed to load ApplicationContext
...
Caused by: org.springframework.dao.InvalidDataAccessApiUsageException: Unsupported primitive id type long!
...
Caused by: java.lang.IllegalArgumentException: Unsupported primitive id type long!
	at org.springframework.data.repository.core.support.AbstractEntityInformation.isNew(AbstractEntityInformation.java:57)
	at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.isNew(JpaMetamodelEntityInformation.java:246)
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:556)
```
when try creating the entity with jpa repository.
The reason is that 
`ID id = getId(entity);` in `AbstractEntityInformation.isNew` retrieves the `long id` field using the `Id id()` method, when idType is retrieved as long.
So finally it goes to the 
`throw new IllegalArgumentException(String.format("Unsupported primitive id type %s!", idType));` line in `AbstractEntityInformation.isNew`
I found a number of workarounds 
1) add `public long getId()` method
2) rename `private long id`
3) not use primitive type
4) rename `Id id()`
however, I have hundreds of such classes, so it would be great to fix on the framework side.
I suppose this is a bug in `CachedIntrospectionResults.isPlainAccessor`, because my `Group.id()` method is added as the property descriptor for `Groupd.id` property in `CachedIntrospectionResults.introspectPlainAccessors`

```
private boolean isPlainAccessor(Method method) {
        ...
        try {
	        // Accessor method referring to instance field of same name?
	        method.getDeclaringClass().getDeclaredField(method.getName());
	        return true;
        }
        catch (Exception ex) {
	        return false;
        }
}
```
it actually checks that the class has any field named the same way as the method, without proper type checking
I've checked the history of changes for this file and it looks like starting from 2.4 all spring-boot 2 minor versions still have this problem.

**Comment by quaff** [comment]
You should use `private Long id;` instead of `private long id;`
