### ISSUE TITLE
YesNoConverter from Hibernate does not seem to work with @Query

### ISSUE THREAD

**Issue by instagibb** [spring-projects/spring-data-jpa#2785]
I have encountered an issue with  when updating to Spring Boot 3 (and subsequently Hibernate 6)

We have entities with something like the following
```
@Entity
public class Test
{
	@Convert(converter = YesNoConverter.class)
	@Column(nullable = false, length = 1)
	@ColumnDefault("N")
	private boolean isPublic;
}
```

Before the upgrade the `@Convert(converter = YesNoConverter.class)` annotation was `@Type("yes_no")` but following the [migration guide](https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc#basic-types) we updated as recommended. But now, when using an `@Query("SELECT t FROM Test t WHERE t.isPublic = 'Y'")` annotation like so we encounter the following error

```
org.hibernate.sql.ast.SqlTreeCreationException: QueryLiteral type [`class java.lang.String`] did not match domain Java-type [`java.lang.Boolean`] nor JDBC Java-type [`java.lang.Character`]
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitLiteral(BaseSqmToSqlAstConverter.java:4702)
BaseSqmToSqlAstConverter.java:4702
	at org.hibernate.query.sqm.sql.BaseSqmToSqlAstConverter.visitLiteral(BaseSqmToSqlAstConverter.java:416)
BaseSqmToSqlAstConverter.java:416
	at org.hibernate.query.sqm.tree.expression.SqmLiteral.accept(SqmLiteral.java:64)
```
It seemingly tries to parse the `'Y'` as a `String` instead of a `char`

Which I am assuming is a Hibernate error/bug but thought I'd ask here as well

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.
