### ISSUE TITLE
Add delete(Predicate predicate) to QuerydslJpaPredicateExecutor (and QuerydslPredicateExecutor)

### ISSUE THREAD

**Issue by ddcruver** [spring-projects/spring-data-jpa#2786]
We build application-specific query objects to make it easier for our users that we resolve to QueryDSL predicates.  we would like to also reuse the same predicates to perform a delete on the database. Could a function void delete(Predicate predicate) be added to the `org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor` and the interface `org.springframework.data.querydsl.QuerydslPredicateExecutor`

**Comment by mp911de** [comment]
Closing as duplicate of spring-projects/spring-data-commons#1022
