### ISSUE TITLE
Two Eager Loading properties with back references does not work

### ISSUE THREAD

**Issue by de313e** [spring-projects/spring-data-jpa#2788]
After upgrading to Spring Boot 3.0 we have issues with two `@OneToOne` relationships that the first one can not be loaded when set to `FetchType.LAZY`.

Scenario is that a Parent Entity, i.e. `User` has `UserSettings` and `UserTermsOfUse`:

    @Entity
    @Data
    @Table(name = "user_model")
    public class User {
    
        @Id
        @GeneratedValue(generator = "system-uuid")
        @GenericGenerator(name = "system-uuid", strategy = "uuid")
        private String id;
    
        /**
         * IMPORTENT: Here it will be set to EAGER, as after migrating to Spring Boot 3.0
         * User Settings is not loaded and therefore. This leads to Impossible User delete
         * as a User Settings still exists within DB.
         */
        @OneToOne(fetch = FetchType.LAZY, mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
        private UserSettings userSettings;
    
        @OneToOne(fetch = FetchType.LAZY, mappedBy = "user", cascade = CascadeType.ALL, orphanRemoval = true)
        private UserTermsOfUse userTermsOfUse;
    }

Each `UserSettings` UserTermsOfUse` have a backreference to User:

    @Entity
    @Data
    public class UserSettings {
    
        @Id
        @GeneratedValue(generator = "system-uuid")
        @GenericGenerator(name = "system-uuid", strategy = "uuid")
        private String id;
    
        @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
        @JoinColumn(name = "user_id", referencedColumnName = "id")
        @ToString.Exclude
        private User user;
    
        private String language;
    
        private String lastActiveClientId;
    
    }

and

    @Entity
    @Table(name = "user_termsofuse")
    @Data
    public class UserTermsOfUse {
    
        @Id
        @GeneratedValue(generator = "system-uuid")
        @GenericGenerator(name = "system-uuid", strategy = "uuid")
        private String id;
    
        @OneToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
        @JoinColumn(name = "user_id", referencedColumnName = "id")
        @ToString.Exclude
        private User user;
    
        @Column(name = "accepted_termsofuse")
        private String acceptedTermsOfUse;
    
    }

When writing a test with to load a saved `User` the `UserSettings` is always null. My Test is:

    @Test
    @Order(1)
    void firstTest() {
        //given
        System.out.println("- 1st TEST ");
        User user = new User();

        UserSettings userSettings = new UserSettings();
        userSettings.setUser(user);
        user.setUserSettings(userSettings);

        UserTermsOfUse userTermsOfUse = new UserTermsOfUse();
        userTermsOfUse.setUser(user);
        user.setUserTermsOfUse(userTermsOfUse);

        //when
        userRepository.save(user);
        // then
        assertEquals(1, userRepository.findAll().size());
        assertEquals(1, userTermsOfUseRepository.findAll().size());
        assertEquals(1, userSettingsRepository.findAll().size());

        System.out.println("------------------------");
        System.out.println("User.ID: " + user.getId());
        System.out.println("User.userSettings.ID: " + user.getUserSettings().getId());
        System.out.println("User.userTermsOfUse.ID: " + user.getUserTermsOfUse().getId());
        System.out.println("------------------------");
    }

    @Test
    @Order(2)
    void secondTest() {
        System.out.println("- 2nd TEST ");
        List<User> all = userRepository.findAll();

        assertEquals(1, all.size());
        User user = all.get(0);
        System.out.println("------------------------");
        System.out.println("User.ID: " + user.getId());
        System.out.println("User.userSettings.ID: " + user.getUserSettings().getId()); // Null Pointer da user settings nicht da
        System.out.println("User.userTermsOfUse.ID: " + user.getUserTermsOfUse().getId());
        System.out.println("------------------------");

    }

At the above mentioned code I get an `NullPointerException` even though I saved a `UserSettings` before.

Only when I remove the backreference from `UserSettings` and `UserTermsOfUse` the test works OR when I set the property `userSettings` to `FetchType.EAGER`:

I provided also a small Application to demonstrate the failure:

https://github.com/de313e/SpringEagerLoadingIssue

**Comment by schauder** [comment]
I have to admit I don't understand 100% what is going on.

I created a PR demonstrating that the problem goes away when the tests are annotated with proper transactions. 
It also demonstrates that without transactions you get the same problem when basing the test on the `EntityManager`.

I therefore think this is a Hibernate issue and you should raise the issue with them.

On the other hand there are a couple of things I don't understand:
- Why does it work in Spring 2.7.8?
- Why do we get a NPE instead of a `LazyLoadingException`?
- I tried to use `userRepository.deleteAll()` to clean up the database between tests. This didn't work, because it didn't find any entities to delete although the second test always complained that there are now two users in the database ????

If you agree that this is a Hibernate issue, and create an issue with them, please leave a link. 
If you don't agree let us know why not.

**Comment by de313e** [comment]
As I asked the question also at Stackoverflow, someone opend a ticket already at Hibernate. Here ist he link
https://hibernate.atlassian.net/browse/HHH-16135 
Also thx for your feedback and time.
