### ISSUE TITLE
Methods with @Query and receiving a Sort object with field of type other than String and ignoreCase enabled do not work

### ISSUE THREAD

**Issue by arielcarrera** [spring-projects/spring-data-jpa#2789]
### Description:
An error occurs when a repository method using the @Query annotation and with a given sort parameter includes a non-string column type and the ignoreCase flag is enabled.

### Error Message:
Caused by: org.hibernate.QueryException: Parameter 1 of function lower() has type STRING, but argument is of type java.lang.Long

### Feasible solutions:
- Modify QueryUtils.class to allow the detection of the field type before the generation of the SORT sentence including lower(...) and avoid the usage of lower() for numeric / non string types.
- Alternatively, the QueryUtils.class can be modified adding the function str() like the following example: lower(str(...))
- Other

#### Requirements:
- Java JDK 17
- Docker
- Spring Boot 3.0.2
- Hibernate 6.X
- Testcontainers + Junit + MySQL container

**Comment by mp911de** [comment]
Determining sort fields in a query derivation arrangement is possible as we have all the contextual details to determine the actual property types. `@Query` requires query parsing, which we don't want to expand too much into. While there are good cases for simple property types, there are also a lot of cases where we would need to unwind unions, inner joins, virtual tables, and so on. We want to avoid getting into that business.

Please avoid setting `ignoreCase` in the first place for properties that do not carry character data.
