### ISSUE TITLE
@PostUpdate method is called after @DomainEvents method

### ISSUE THREAD

**Issue by konstantinyayloyan** [spring-projects/spring-data-jpa#2790]
```
public class MyClass extends AbstractAggregateRoot<MyClass> {

    @Id
    @Column(name = "INSTANCE_ID")
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "HIBERNATE_SEQUENCE")
    @SequenceGenerator(name = "HIBERNATE_SEQUENCE", sequenceName = "HIBERNATE_SEQUENCE", allocationSize = 1)
    private Long id;

    @Version
    @Column(name = "VERSION")
    private Long version;

    @PostUpdate
    public void beforeUpdate() {
        registerEvent(new MyClassModifyEvent(this));
    }
}

```

I have MyClass in which I want to registerEvent in @PostUpdate method. Then I have this handler:

```
@Component
@RequiredArgsConstructor
@Slf4j
public class MyClassModifyEventHandler {


    @TransactionalEventListener(phase = TransactionPhase.BEFORE_COMMIT)
    public void handle(final MyClassModifyEvent persistenceEvent) {
        log.info("MyClassModify handler");
    }
}
```

So this is not working, because domainEvents in AbstractAggregateRoot is called before registerEvent of MyClass, so my event is not being registered. Any solutions?

**Comment by mp911de** [comment]
`@DomainEvents` isn't intended to be used that way. The intended usage is to hand in an object to `save(…)` that contains already your domain events. `@PostUpdate` is being called by the entity manager/transaction management after interacting with the `EntityManager`

as per § 3.5.3 of the JPA spec:

> The PreUpdate and PostUpdate callbacks occur before and after the database update operations to
> entity data respectively. These database operations may occur at the time the entity state is updated or
> they may occur at the time state is flushed to the database (which may be at the end of the transaction). 

`@DomainEvents` are handled by an interceptor in the repository proxy instance.

**Comment by konstantinyayloyan** [comment]
hi @mp911de. It was working for spring boot 2. After updating spring boot 2 to 3 it stopped working. How should I understand that updating spring boot will cause this issue?

**Comment by konstantinyayloyan** [comment]
any news @mp911de?
