### ISSUE TITLE
findById with lowercase returns lowercase, but database' id is uppercase

### ISSUE THREAD

**Issue by kylooh** [spring-projects/spring-data-jpa#2797]
Hi, everyone. I have a problem about `JpaRepository`'s `findById` method. I try to use lowercase id query parameter (my database is MySQL, which is not case sensitive), which returns a entity with lowercase id field. But, database's value is actual a uppercase value. 

## Environment
MacOS: Ventura (M1 chip)
MySQL: 5.7.34
Spring Data JPA: 2.7.3

## Codes

Database:
| code | 
| CODE1 |

Data and repo define:
```Java
@Data
@Entity
@Table("testing_table")
class MyEntity {
    @Id private String code;
}

@Repository
interface MyRepository extends JpaRepository<MyEntity, String> {

    Optional<MyEntity> findByCode(String code);
}
```

Business code:
```Java
@Autowired private MyRepository repository

public void testing {
    MyEntity entity1 = repository.findById("code1").get(); 
    //which returns a entity with LOWERCASE code
    //MyEntity(code="code1")
    MyEntity entity2 = repository.findByCode("code2").get();
    //which returns a entity with UPPERCASE code
    //MyEntity(code="CODE1")
}
```

> Yes. The behavior of `findById` function's result is not same as `findByCode`, but they are same field.
> I did some search, seems like the JPA-proxied method `findByCode` using naming mapping to generate sql query. But `@Id` field using `EntityManager` with local cache. So, does this means it is a Spring Data JPA's bug?

Thx for reading.

**Comment by quaff** [comment]
Please provide actual sql generated.

**Comment by schauder** [comment]
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by kylooh** [comment]
> Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

https://github.com/kylooh/RE-SpringJPAfindById

 In this repo's code `com/example/MainApplicationKtTest.kt:38` did no return same answer with `com/example/MainApplicationKtTest.kt:35` with MySQL database.

Also, sorry there is no database included, or I don't know what is the correct way do that. And for now, this problems not work on H2 database. Because both line above returns empty, and I don't know how to make H2 case insensitive .

Hope that helps.

**Comment by gregturn** [comment]
Using Testcontainers and MySQL, I was able to craft this test case:

```
@Transactional
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = MainApplicationTest.TestConfig.class)
public class MainApplicationTest {

    @Autowired
    TestRepository repository;

    @Test
    void findByIdReturnsDifferentResultsBetweenFindByCode() {

        var codeL = "code_lowercase";
        var codeU = "CODE_UPPERCASE";
        var codeC = "Code_CamelWithUnderline";

        repository.save(new TestEntity(codeL));
        repository.save(new TestEntity(codeU));
        repository.save(new TestEntity(codeC));

        var data = repository.findAll();

        assertThat(data).hasSize(3);
        assertThat(data).flatExtracting(TestEntity::getCode).containsExactlyInAnyOrder(codeL, codeU, codeC);

        var codeLFindByCode = repository.findByCode(codeL);
        var codeLToLowerFindByCode = repository.findByCode(codeL.toLowerCase());
        var codeLToUpperFindByCode = repository.findByCode(codeL.toUpperCase());
        var codeLFindById = repository.findById(codeL);
        var codeLToLowerFindById = repository.findById(codeL.toLowerCase());
        var codeLToUpperFindById = repository.findById(codeL.toUpperCase());

        var codeLFindByCodeValue = codeLFindByCode.getCode();

        assertThat(codeLFindByCodeValue).isEqualToIgnoringCase(codeLToLowerFindByCode.getCode());
        assertThat(codeLFindByCodeValue).isEqualToIgnoringCase(codeLToUpperFindByCode.getCode());
        assertThat(codeLFindByCodeValue).isEqualToIgnoringCase(codeLFindById.get().getCode());
        assertThat(codeLFindByCodeValue).isEqualToIgnoringCase(codeLToLowerFindById.get().getCode());
        assertThat(codeLFindByCodeValue).isEqualToIgnoringCase(codeLToUpperFindById.get().getCode());
    }

    @EnableJpaRepositories( //
            considerNestedRepositories = true, //
            basePackageClasses = TestConfig.class, //
            includeFilters = @ComponentScan.Filter(type = FilterType.ASSIGNABLE_TYPE, classes = TestRepository.class))
    @EnableTransactionManagement
    static class TestConfig {

        @Bean(initMethod = "start", destroyMethod = "stop")
        public MySQLContainer<?> container() {

            return new MySQLContainer<>("mysql:8.0.24") //
                    .withUsername("test") //
                    .withPassword("test") //
                    .withConfigurationOverride("");
        }

        @Bean
        public DataSource dataSource(MySQLContainer<?> container) {

            MysqlDataSource dataSource = new MysqlDataSource();
            dataSource.setUrl(container.getJdbcUrl());
            dataSource.setUser(container.getUsername());
            dataSource.setPassword(container.getPassword());
            return dataSource;
        }

        @Bean
        public AbstractEntityManagerFactoryBean entityManagerFactory(DataSource dataSource) {

            LocalContainerEntityManagerFactoryBean factoryBean = new LocalContainerEntityManagerFactoryBean();
            factoryBean.setDataSource(dataSource);
            factoryBean.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
            factoryBean.setPackagesToScan(this.getClass().getPackage().getName());

            Properties properties = new Properties();
            properties.setProperty("hibernate.hbm2ddl.auto", "create");
            properties.setProperty("hibernate.dialect", MySQL8Dialect.class.getCanonicalName());
            factoryBean.setJpaProperties(properties);

            return factoryBean;
        }

        @Bean
        PlatformTransactionManager transactionManager(EntityManagerFactory entityManagerFactory) {
            return new JpaTransactionManager(entityManagerFactory);
        }
    }
}
```

This test case passes,  but only because the assertions switch to `isEqualToIgnoringCase`. Clearly, as documented, MySQL can operate in a case-insensitive manner. Now it is quirky that in several situations, you get back the precise value put in, but it is strange that `repository.findById(codeL.toUpperCase());` will actually hand you back what was original a lowercase string in uppercase format. 

However, since this is the risk of using case insensitive systems, I'm not sure that this is really Spring Data JPA or Hibernate's responsibility. Instead, you have to deal with the risk that stuff going in and stuff coming out could vary and handle accordingly, because Java by default is case sensitive.

Or you must track down the settings that would configure your MySQL database to operate in a case sensitive fashion.

Either of these factors appear to be out of band for JPA as well as Spring Data JPA.
