### ISSUE TITLE
Table with @Inheritance(strategy = InheritanceType.JOINED)  strategy fetching wrong column of Jsonb type

### ISSUE THREAD

**Issue by amit88265** [spring-projects/spring-data-jpa#2805]
Problem 
I have created three entities with the strategy InheritanceType.JOINED. 
Parent entity looks like this:
```

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public class A<E extends AJsonContent>  extends AbstractDomainJsonEntity<E, String> {

  @Id
  @GeneratedValue(generator = "uuid2")
  @GenericGenerator(name = "uuid2", strategy = "org.hibernate.id.UUIDGenerator")
  @NotNull(groups = OnUpdate.class)
  @Null(groups = OnCreate.class)
  @Column(name = "a_id", columnDefinition = "VARCHAR(255)")
  @JsonProperty("aId")
  @Schema(description = "This attribute indicates unique id of OriginationJsonApplication")
  private String id;

  private String aAttribute;
}
```
First child is:
```
@Entity
public class B extends A<BAttribute> {

  private String bAttribute;
}
```
Second child is:

```
@Entity
public class C extends A<CAttribute> {

  private String cAttribute;
}
```
Here parent has a column of jsonb type whose type is being passed by child entities using generics argument  A<E extends AJsonContent> and argument should of subtype  AJsonContent.

Now, when bRepository.findById() is called, it returns an instance of B with jsonb column  CAttribute instead of BAttribute.

When I removed C entity completely, then it is working fine. But when it B and C are both together it fetches the wrong jsonb column for B entity.

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.

**Comment by amit88265** [comment]
@schauder which repo is the proper place to open this issue?

**Comment by schauder** [comment]
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues
