### ISSUE TITLE
How to use spring data jpa to query with recursive?

### ISSUE THREAD

**Issue by ddxl123** [spring-projects/spring-data-jpa#2808]

**Comment by schauder** [comment]
Please provide a description what you are trying to do.

**Comment by ddxl123** [comment]
> 

How to use WITH RECURSIVE in spring data jpa?
Can I only use @Query(nativeQuery: true)?

**Comment by ddxl123** [comment]
> Please provide a description what you are trying to do.

How to use WITH RECURSIVE in spring data jpa?
Can I only use @query(nativeQuery: true)?

**Comment by schauder** [comment]
Yes, you'd use `@Query(nativeQuery= true)` for that.

This issue tracker is for bug reports and feature/improvement requests. 
This question is more of a usage questions. Those should be asked at Stackoverflow and be tagged with `spring-data-jpa`.
By using Stackoverflow, the community can assist and the questions and their answers can more easily be found using the search engine of your choice.
