### ISSUE TITLE
NPE in version 3.0.2 when using DELETE native queries

### ISSUE THREAD

**Issue by The-Arne** [spring-projects/spring-data-jpa#2812]
Commit 64b5a22a24b42e8660f441897b001e4b594fff1c introduced a null pointer exception in line 620 of QueryUtils. If a native query is not a select, but, for example, a delete, "variable" will be null, leading to said exception.

Example code in repository:
```
	@Modifying
	@Query(value = "delete from some_table where id in :ids", nativeQuery = true)
	void deleteStuffFromSomeTable(@Param("ids") Collection<UUID> ids);
```

Relevant part of the trace:
```
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "variable" is null
	at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:620)
	at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49)
	at org.springframework.data.jpa.repository.query.StringQuery.deriveCountQuery(StringQuery.java:111)
	at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.<init>(AbstractStringBasedJpaQuery.java:82)
	at org.springframework.data.jpa.repository.query.NativeJpaQuery.<init>(NativeJpaQuery.java:58)
	at org.springframework.data.jpa.repository.query.JpaQueryFactory.fromMethodWithQueryString(JpaQueryFactory.java:53)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$DeclaredQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:170)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:252)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:95)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:111)
	... 79 more
```

**Comment by ayrtonnadgel** [comment]
In my case, the NPE occurs querying a sequence value. 

```java
@Query(value = "SELECT nexval('public.my_sequence')", nativeQuery = true)
Integer getNextvalMySequence();
```

**Comment by gideruette** [comment]
Same here, with non CRUD native query
```java
@Query(value = """
select count(1) as totalItems,
sum(case when myField is null then 0 else 1 end) as notNullItems
from myClass
""", nativeQuery = true)
```

Found a workaround by adding a fictive `countQuery`

```java
@Query(value = """
select count(1) as totalItems,
sum(case when myField is null then 0 else 1 end) as notNullItems
from myClass
""", countQuery = "select 1", nativeQuery = true)
```

**Comment by gmbeneva** [comment]
Same with an UPDATE query:
``` SQL
  @Modifying
  @Query(nativeQuery = true, value = "UPDATE seq_mgmt SET seq_no = :value WHERE seq_id = :key")
  int setNextValue(@Param("key") String key, @Param("value") Long value);
```

**Comment by gregturn** [comment]
This has been patched in `main` (`3.1.0-SNAPSHOT`) and backported to `3.0.x` and `2.7.x`).

**Comment by therealaleko** [comment]
> 
Is this warranting a release of SDJPA asap, or is it still within your release cadence? If not re-releasing, when is the next release? I'm not aware of the cadence this project follows. Thanks!

**Comment by ChristianCiach** [comment]
Workaround for people using Gradle if you don't want to downgrade Spring Boot altogether:

```groovy
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.name == 'spring-data-jpa' && details.requested.version == '3.0.2') {
            details.useVersion '3.0.1'
            details.because 'https://github.com/spring-projects/spring-data-jpa/issues/2812'
        }
    }
}
```

**Comment by kris2kris** [comment]
Another workaround, if you have only a few native queries, is to add a count query and everything is working

**Comment by mp911de** [comment]
The next round of releases is scheduled for in 4 weeks, see https://calendar.spring.io/.

As suggested above, we recommend downgrading to Spring Data JPA 3.0.1 as the 3.0.2 release shipped with a few changes only.

**Comment by cmuchinsky** [comment]
> The next round of releases is scheduled for in 4 weeks, see https://calendar.spring.io/.
> 
> As suggested above, we recommend downgrading to Spring Data JPA 3.0.1 as the 3.0.2 release shipped with a few changes only.

Unfortunately this is easier said than done when using a bom that wraps around the spring-boot one because there is no way to declare the downgrade in the bom itself. Instead every consumer would have to explicitly downgrade using a custom gradle resolution strategy which is error prone and not practical when you have a large number of consumers.

**Comment by eu-rlarsen** [comment]
> > The next round of releases is scheduled for in 4 weeks, see https://calendar.spring.io/.
> > As suggested above, we recommend downgrading to Spring Data JPA 3.0.1 as the 3.0.2 release shipped with a few changes only.
> 
> Unfortunately this is easier said than done when using a bom that wraps around the spring-boot one because there is no way to declare the downgrade in the bom itself. Instead every consumer would have to explicitly downgrade using a custom gradle resolution strategy which is error prone and not practical when you have a large number of consumers.

We just skip this release for both Spring Boot 2.7.9 and 3.0.3 - the work it takes "fixing" the NPE for us is not worth it.

**Comment by SabareeshGC** [comment]
I am surprised there was no test that could have caught this.

**Comment by ChristianCiach** [comment]
@SabareeshGC I usually don't find these kinds of discussion very productive and refrain to comment on them. But I agree that it is fair to be a bit surprised that a project of this size did not contain a single unit test that just happens to execute a mutating native query. But, well, now there is one :) 

This also once again shows the importance of static code analysis. Eclipse (with my rather strict compiler settings) immediate marked the buggy line as a potential NPE, and tools like NullAway would surely do the same. Seeing that there a nullable annotations in `org.springframework.lang`, maybe cases like these could be prevented in the future by utilizing static code analysis.

**Comment by SabareeshGC** [comment]
@ChristianCiach  please dont take it wrong we love spring and community behind it. This just caught us off guard which never affected us before in this manner. When i meant i was surprised it just expressed the feeling nothing more than that.

**Comment by jchellojchello** [comment]
what is the solution for that ?

**Comment by aschufft** [comment]
We have the same NPE since 2.7.9 - all versions before (tested 2.7.3 - 2.7.8) are working:

@Query(value = "SELECT nexval('{h-schema}my_sequence')", nativeQuery = true)

Rolling back to 2.7.8

**Comment by jase52476** [comment]
I'm having the same issue.  Thanks @cigaly for pointing me here.

https://github.com/spring-projects/spring-data-jpa/issues/2408#issuecomment-1449292206

> I'm getting this after upgrading spring-boot-starter-parent 2.7.8 -> 2.7.9, it's pulling spring-data-jpa 2.7.8 from 2.7.7 and my 
> repository that was working previously now is having a NPE :
> 
> Caused by: java.lang.NullPointerException: null at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607) at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49) at org.springframework.data.jpa.repository.query.StringQuery.deriveCountQuery(StringQuery.java:119)
> 
> on line 594, this string is created and it defaults to null if there's no match:
> 
> String variable = matcher.matches() ? matcher.group(VARIABLE_NAME_GROUP_INDEX) : null;
> 
> But the null is not handled on line 607:
> 
> if (nativeQuery && (variable.contains(",") || "*".equals(variable))) {
> 				replacement = "1";	
...
> 
> If I switch back to spring-boot 2.7.8 and do a mvn clean install it starts up just fine with no modification of my repository.

**Comment by otavioprado** [comment]
> This has been patched in `main` (`3.1.0-SNAPSHOT`) and backported to `3.0.x` and `2.7.x`).

I'm still experiencing this issue in version 3.0.4-SNAPSHOT, 3.1.0-SNAPSHOT and 2.7.10-SNAPSHOT. Is there anything else I should do or check to resolve this using the SNAPSHOT version?

**Comment by mp911de** [comment]
@otavioprado we released just today versions `2.7.9` and `3.0.3`. Please file a new ticket along with a stack trace and a way to reproduce your issue.

**Comment by otavioprado** [comment]
> @otavioprado we released just today versions `2.7.9` and `3.0.3`. Please file a new ticket along with a stack trace and a way to reproduce your issue.

My issue is the same of the topic:
`Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'policyRepository' defined in repositories.PolicyRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Could not create query for public abstract void repositories.PolicyRepository.removeAllPoliciesFromUser(java.lang.String,java.lang.String); Reason: Cannot invoke "String.contains(java.lang.CharSequence)" because "variable" is null`
I tried with the versions 3.0.3, 3.0.4-SNAPSHOT, 3.1.0-SNAPSHOT, 2.7.9 and 2.7.10-SNAPSHOT. The only version that works is 2.7.8 and older.
My query is as bellow
`   
@Repository
public interface PolicyRepository extends JpaRepository<Policy, String> {
    @Modifying
    @Transactional
    @Query(value = "DELETE FROM t_user_policies " +
            "WHERE fk_tenant_id = :tenantId " +
            "AND username = :username ", nativeQuery = true)
    void removeAllPoliciesFromUser(@Param("tenantId") String tenantId, @Param("username") String username);
}
`

**Comment by mp911de** [comment]
I'm not able to reproduce the issue with 3.0.3 anymore.

**Comment by breun** [comment]
If you use Spring Boot 2.7.9: Spring Data BOM 2021.2.9 has been released, with Spring Data 2.7.9. This will be included in Spring Boot 2.7.10 (scheduled for March 23), but you can temporarily override `spring-data-bom.version` to 2021.2.9 for now.

**Comment by otavioprado** [comment]
> If you use Spring Boot 2.7.9: Spring Data BOM 2021.2.9 has been released, with Spring Data 2.7.9. This will be included in Spring Boot 2.7.10 (scheduled for March 23), but you can temporarily override `spring-data-bom.version` to 2021.2.9 for now.

Thanks @breun 
It works
```
	...
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.9</version>
		<relativePath/>
	</parent>
	...
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.data</groupId>
				<artifactId>spring-data-bom</artifactId>
				<version>2021.2.9</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>
	...
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-data-jpa</artifactId>
	</dependency>
	...
```
For use 3.0.3 I need to upgrade the bom to [2022.0.3](https://github.com/spring-projects/spring-data-bom/releases/tag/2022.0.3) ?

**Comment by breun** [comment]
@otavioprado You don’t even need that full import, this should be enough:

```
<properties>
  <spring-data-bom.version>2021.2.9</spring-data-bom.version><!-- Temporary override until Spring Boot 2.7.10 -->
</properties>
```

If you’re on Spring Boot 3, you can upgrade to Spring Boot 3.0.4, which was just released.

**Comment by breun** [comment]
@pfuerholz Are you referring to Spring Boot 2.7.9 or Spring Data JPA 2.7.9? This bug should have been fixed in the latter.

**Comment by sergmain** [comment]
> @pfuerholz Are you referring to Spring Boot 2.7.9 or Spring Data JPA 2.7.9? This bug should have been fixed in the latter.

it's the same - SpringBoot 2.7.9 is using 
```
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-jpa</artifactId>
        <version>2.7.9</version>
      </dependency>
```

**Comment by pfuerholz** [comment]
When I use version 2.7.9 throughout Spring Boot.

**Comment by javadev-jef** [comment]
Works on `2.7.10`. Thank you all!
