### ISSUE TITLE
Problem to create count query with version 2.7.8

### ISSUE THREAD

**Issue by kris2kris** [spring-projects/spring-data-jpa#2816]
The method createCountQueryFor of QueryUtils has been changed in this [commit](https://github.com/spring-projects/spring-data-jpa/commit/a851022dad5e0b81794613e70e575f8ee0ebe431#diff-7d36425745042f8c27507657de795fd7cf1d546da6a740fd00d86add46f81ed4).
My repository with native query cannot be created because variable is null when doing `variable.contains(",").`
A simple query like this produce the problem 
`@Query(nativeQuery=true, value="Select * FROM MY_TABLE")`

**Comment by mp911de** [comment]
It is indeed a duplicate. Apologies for the inconvenience.
