### ISSUE TITLE
NPE in QueryUtils

### ISSUE THREAD

**Issue by edreyer** [spring-projects/spring-data-jpa#2832]
Spring boot v2.7.9
Spring data JPA 2.7.8
Class: `org.springframework.data.jpa.repository.query.QueryUtils`
Line: 607

It's possible that `nativeQuery` is true and `variable` is null. 
In this case, an NPE occurs at `variable.contains(",")`

```java
if (nativeQuery && (variable.contains(",") || "*".equals(variable))) {
```
<img width="471" alt="curbee-backend_–_QueryUtils_java__Maven__org_springframework_data_spring-data-jpa_2_7_8_" src="https://user-images.githubusercontent.com/1228222/222242073-e50a8b77-9f42-4078-86d7-76244d2d3b7b.png">

**Comment by gregturn** [comment]
Duplicates #2812.
