### ISSUE TITLE
Allow to use Kotlin value classes directly as JpaRepository Id type

### ISSUE THREAD

**Issue by igorwojda** [spring-projects/spring-data-jpa#2840]
Consider this entity

```kotlin
@Entity
@Table(name = "project")
class ProjectJpa(

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    val id: ProjectId,

    @Column(name = "name", nullable = false)
    val name: String,
)

```

The `id` is defined as Kotlin value class that is just a wrapper for the `UUID`:

```
value class ProjectId(val id: UUID)
```

Define repo with `ProjectId` as id

```kotlin
@Repository
interface ProjectJpaRepository : JpaRepository<ProjectJpa, ProjectId>
```

With the above code  project can be saved to database:

```kotlin
projectJpaRepository.save(project.toJpa())
```

**Problem**
Retrieving project using `findById`...

```kotlin
projectJpaRepository.findById(ProjectId(UUID.fromString("1ec87062-89dd-4f75-a7a2-be7631332bbb")))
```

... results in 'org.springframework.dao.InvalidDataAccessApiUsageException' exception.:
```
Provided id of the wrong type for class com.mango.persistence.entity.ProjectJpa. Expected: 
class java.util.UUID, got class com.mango.business.model.value.ProjectId
```

**Comment by igorwojda** [comment]
Here it is
[sample-2840.zip](https://github.com/spring-projects/spring-data-jpa/files/11198506/sample-2840.zip)

**Comment by mp911de** [comment]
Kotlin compiles `ProjectJpa` to:

```java

class ProjectJpa {

UUID id; // Kotlin: ProjectId
}
```

while the repository declaration remains at `ProjectJpaRepository extends JpaRepository<ProjectJpa, ProjectId>`. This difference between the declarations causes the identifier mismatch. You could switch the repository declaration to `JpaRepository<ProjectJpa, UUID>`.

There's not much we can do here. Kotlin aims to provide a lot of value at the code frontend at the price of compatibility between components.
