### ISSUE TITLE
The dialect support for different databases is spring data jpa

### ISSUE THREAD

**Issue by yangmeng66** [spring-projects/spring-data-jpa#2841]
Hello, for ORM, spring data jpa is an excellent integration framework, which can connect different types of databases, such as mysql, oracle, etc Of course, our own self-developed database(http://doc.yashandb.com/), we also want to adapt to spring data jpa, but the question is, if we have adapted hibernate (such as... Dialect), must it be compatible with spring data jpa? Because I didn't find code similar to MySQL Dialect in the spring data jpa code

**Comment by mp911de** [comment]
Spring Data JPA builds on top of JPA providers and doesn't rely on any database-specific features. All dialect business in handled by the underlying JPA implementation.
