### ISSUE TITLE
JpaRepository.getReferenceById sometime return an entity with null value

### ISSUE THREAD

**Issue by minhtran-q** [spring-projects/spring-data-jpa#2842]
## Issue: 
I'm having trouble trying to get an entity via method `getReferenceById` when using Spring Data JPA.

I have two entities like this:

![image](https://user-images.githubusercontent.com/26593630/223143164-91bc2fd3-594e-420d-8cb1-df31413ec898.png)

In my Database I have only one record in file `file_metadata` and I am trying to get this record with method `JpaRepository.getReferenceById` and set to a `FileRawData` entity object (not exist in Database) that I will use in `handle(FileRawData fileRawData)` method.

And in the `handle(FileRawData fileRawData)` method. Some time I can't get the value of the `FileMetadata` entity, even though the value it already exists under DB. 

```
  public void handle(FileRawData fileRawData) {
    FileMetadata fileMetadata = fileRawData.getFileMetadata();
    if (fileMetadata.getNumberOfLines() == null) {
      log.info("NumberOfLines is null");
      log.info("{}", fileRawData.getFileMetadata().getId());
      log.info("{}", fileRawData.getFileMetadata().getFileName());
      log.info("{}", fileRawData.getFileMetadata().getNumberOfLines());
    }
```
_All my methods are in the `@Transactional`_

```
2023-03-06 21:35:03.897  INFO 19424 --- [onverter-exec-4] c.t.d.m.e.PlanConvertTaskExecutor        : NumberOfLines is null
2023-03-06 21:35:03.898  INFO 19424 --- [onverter-exec-4] c.t.d.m.e.PlanConvertTaskExecutor        : 96fd27d1-61d6-40cf-b9f9-941664952763
2023-03-06 21:35:03.898  INFO 19424 --- [onverter-exec-4] c.t.d.m.e.PlanConvertTaskExecutor        : \tmp\2023-03-06T14_34_27\tmp_file.csv
2023-03-06 21:35:03.898  INFO 19424 --- [onverter-exec-4] c.t.d.m.e.PlanConvertTaskExecutor        : 40
```
_console log_

## Version:
spring-boot-starter-parent: 2.7.8
spring-boot-starter-data-jpa: 2.7.8
hibernate-core: 5.6.14.Final

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
