### ISSUE TITLE
Documentation: Recommend Records instead of Lombok for class based projections

### ISSUE THREAD

**Issue by grubeninspekteur** [spring-projects/spring-data-jpa#2843]
The documentation section on [Class-based Projections (DTOs)](https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections.dtos) recommends Lombok's `@Value` annotation to reduce boilerplate of DTOs. With the Java 17 baseline of Spring 6, it would be better to just replace the example with a record, mention that DTOs can be arbitrary classes with a constructor, and remove the mention of Lombok.

**Comment by mp911de** [comment]
Good point. Records are ideal to be used for projections.

**Comment by grubeninspekteur** [comment]
Closing in favor of https://github.com/spring-projects/spring-data-commons/issues/2793 as the documentation for projections resides in Spring Data Commons.
