### ISSUE TITLE
MySQL 5.7 "like" escaping characters differently in SpringBoot 3.0.4 than in SpringBoot 3.0.2

### ISSUE THREAD

**Issue by zromano** [spring-projects/spring-data-jpa#2853]
Hi team,

I noticed the following breaking change between SpringBoot versions `3.0.2` and `3.0.4` when escaping characters in a `like`:

In`3.0.2`, we were escaping wildcard characters like so: 
```sql
where u3_0.emailAddress like '%user\\_1\\%%'
```

In`3.0.4`, we were escaping wildcard characters like so: 
```sql
where u3_0.emailAddress like replace('%user\\_1\\%%', '\\', '\\\\')
```
 which doesn't yield the same results.

---

As a side note: we ideally want `where u3_0.emailAddress like '%user\_1\%%'` to be executed in the MySQL, but it doesn't appear possible to do that. It always adds an extra `\`.

In code we are saying:
```java
String searchBy = "user\_1\%";
Predicate nameSearchBy = criteriaBuilder.like(emailAddress, "%" + searchBy + "%");
```
in either version results in the query executed on MySql 5.7 being:  `'%user\\_1\\%%'` instead of the desired `'%user\_1\%%'`

**Comment by zromano** [comment]
This might be a hibernate issue, but since it happens between the two different SB versions, I thought I'd bring up here first.

Thanks for any help 👍

**Comment by mp911de** [comment]
This is a Hibernate issue since `CriteriaBuilder` is not a Spring Data type.
