### ISSUE TITLE
NoClassDefFoundError  TypedParameterValue when using eclipselink

### ISSUE THREAD

**Issue by haube** [spring-projects/spring-data-jpa#2857]
Hi there, 

we followed this guide (https://www.baeldung.com/spring-eclipselink) to use eclipselink instead of hibernate. 
So we have following exclusion in the pom file.
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-entitymanager</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.hibernate</groupId>
					<artifactId>hibernate-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```
Upgrading spring-boot form 2.7.7 to 2.7.8 i get the following error in one of our tests.
```
java.lang.NoClassDefFoundError: org/hibernate/jpa/TypedParameterValue
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$NamedOrIndexedQueryParameterSetter.setParameter(QueryParameterSetter.java:95)
```
i guess the reason is this older issue https://github.com/spring-projects/spring-data-jpa/issues/2544
which makes use of a hibernate dependency.

Removing the exclusion for `hibernate-core` makes the code run. 

But i am unsure about side effects. Is it just excluded to safe some space in the artifact or does it enable some maybe unwanted spring magic by default.

**Comment by gregturn** [comment]
This should also be candidate for backporting to `3.0.x` since it involves HIbernate 6.
