### ISSUE TITLE
Support sorting by aliased columns

### ISSUE THREAD

**Issue by gregturn** [spring-projects/spring-data-jpa#2863]
For queries where a column is an alias:

```
select AVG(p.points) as avg
from Player p
```

...when we have a `Sort.by("avg")`, it should NOT append `order by p.avg` but instead simply have `order by avg`.

Essentially, anywhere we have an aliased column or value, that should be supported in the `order by` operations.

**Comment by SharkFourSix** [comment]
Anyway to do this in version 2? I think releasing this fix in SB3 forces people to deal with the migration hell (refactoring thousands of import from javax.* to jarkata,*, etc) to SB3. Not a very good look :/
