### ISSUE TITLE
Issue with native query when returning to an Entity with ManyToOne mapping after upgrading to spring data 3

### ISSUE THREAD

**Issue by FranciscoPDNeto** [spring-projects/spring-data-jpa#2879]
I have a specific situation here that a native query, which worked fine on the 2.7.x versions, started to display an error that a specific column from this lazy mapping attribute does not exists. I'm not returning any fields of this mapping, that's why I think it could be throwing this sql error, but this mapping is lazy and it was working on that previous version. 

It was being used the native query because of the operator ILIKE, which is not a standard one. I've tested after with HQL instead, keeping the ILIKE operator and it worked too, checking the SQL generated with show_sql translating correctly this OPERATOR, considering it's not standard. So for now I think we could make this workaround, but it would be great to understand why this started to happen after updating to version 3, I didn't find any migration guide which specifies some breaking change for this behavior.

Thanks in advance!

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.

**Comment by FranciscoPDNeto** [comment]
Thank you for the answer! I was just with a doubt if it's a spring data or hibernate because when I run the same query not using native query it works as expected. I will try to find some moment here to try a reproducer to identify better the issue, if it's spring data or hibernate related. I saw as well on the Hibernate bugs it has an open one https://hibernate.atlassian.net/browse/HHH-16272 related to oneToMany mappings, maybe it could be related to, anyway, thank you!
