### ISSUE TITLE
Using deprecated '-debug' fallback for parameter name resolution

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-data-jpa#2893]
Hi

We've migrated from Spring Boot 2.7.x to Spring Boot 3.0.5 and observed a lot of warning messages in the console:

`22:38:33.661 WARN  - Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: demo.UserRepository`

This warning is printed for some Spring Data repository interfaces (but not for all). It seems this issue was already fixed in Spring 6.0.4 - https://github.com/spring-projects/spring-framework/issues/29612

We're using Spring 6.0.7 now but issue still reproduces.

**Comment by sergey-morenets** [comment]
Hi 

@schauder 

Thank you for the quick response. No, I don't use any Spring Boot or JVM arguments.

**Comment by schauder** [comment]
If you are using Spring Boot you shouldn't need any special configuration. 
If you are using Spring Boot please provide a reproducer.

Without Spring Boot you need to use that flag. 
See https://stackoverflow.com/a/31846371/66686

**Comment by vishalsingh2972** [comment]
@schauder  @sergey-morenets Getting similar warning after trying everything....any resolution?

`Apr 14, 2023 1:09:54 AM org.springframework.core.LocalVariableTableParameterNameDiscoverer inspectClass
WARNING: Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: demo.LoggingAspect`

I am currently using Spring 6.0.7

**Comment by sergey-morenets** [comment]
Hi @vishalsingh2972 

Unfortunately I have no solution. I see this warning even if run my application using Spring Boot plugin.

**Comment by schauder** [comment]
If the problem persists I recommend creating a reproducer and filing an issue against [Spring Framework](https://github.com/spring-projects/spring-framework/issues) or [Spring Boot](https://github.com/spring-projects/spring-boot/issues)
