### ISSUE TITLE
Spring Boot 3 Migration Issue with Custom Query and JPARepository

### ISSUE THREAD

**Issue by ariefmirza** [spring-projects/spring-data-jpa#2896]
We tried to migrate to Spring 3.0.4 from Spring 2.7.3 and currently we are facing an issue with our existing query. When we tried to pass a parameter of List of UUID to any source, destination, customer, or supplier, we got an error of 
```java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.UUID (java.util.ArrayList and java.util.UUID are in module java.base of loader 'bootstrap').```
but when null is passed, the query is working fine.

When passing a single value, sometimes it works, but it's not consistent on which parameter.
On the first app run, it may work on the source, but not on the rest. Next run it can work on the rest but not on source.

We couldn't pinpoint where the issue is coming from because the exact same query was working well on Spring 2.7.3.

The following is the Repository class with our custom query.
``` java
import com.edison.entity.InventoryShipment;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

@Repository
public interface InventoryShipmentRepository extends JpaRepository<InventoryShipment, UUID> {

    @Query(value = "SELECT i FROM InventoryShipment i " +
            "WHERE i.startDate BETWEEN :from AND :to" +
            "AND ((:source) IS NULL OR CAST(i.sourceCountry.id AS org.hibernate.type.UUIDCharType) IN (:source)) " +
            "AND ((:destination) IS NULL OR CAST(i.destinationCountry.id AS org.hibernate.type.UUIDCharType) IN (:destination)) " +
            "AND ((:customer) IS NULL OR CAST(i.carrierCustomer.id AS org.hibernate.type.UUIDCharType) IN (:customer)) " +
            "AND ((:supplier) IS NULL OR CAST(i.carrierSupplier.id AS org.hibernate.type.UUIDCharType) IN (:supplier))")
    List<InventoryShipment> findInventoryFilter(@Param("from")LocalDate dateFrom, 
                                                @Param("to")LocalDate dateTo, 
                                                @Param("source") List<UUID> sourceList, 
                                                @Param("destination") List<UUID> destinationList, 
                                                @Param("customer") List<UUID> customerList, 
                                                @Param("supplier") List<UUID> supplierList);
}
```

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.
You might also want to check https://github.com/spring-projects/spring-data-jpa/issues?q=label%3A%22for%3A+external-project%22+is%3Aclosed if this was reported before

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.

**Comment by ariefmirza** [comment]
@schauder thanks for the info.

I tried an implementation using `EntityManager` directly and it does seem that it's a Hibernate issue.

**Comment by schauder** [comment]
Thanks for the confirmation. If you have a link to the Hibernate issue please add it as a comment so others have a better chance to find it.
