### ISSUE TITLE
SimpleJPARepository: existsById() throws NPE if metadata is null

### ISSUE THREAD

**Issue by patdlanger** [spring-projects/spring-data-jpa#2897]
Hi there, 
I guess this is somewhat related to https://github.com/spring-projects/spring-data-jpa/issues/2716

In existsById() there is no null-check so it can produce NPEs when trying to access metadata.getComment()

**Comment by schauder** [comment]
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by patdlanger** [comment]
@schauder Hi I uploaded a simple example here https://github.com/patdlanger/existsbyid
