### ISSUE TITLE
Upgrade to Hibernate 6.2.0

### ISSUE THREAD

**Issue by Eng-Fouad** [spring-projects/spring-data-jpa#2899]
cc @odrotbohm

**Comment by odrotbohm** [comment]
Thanks for the contribution. Note that dependency updates are usually something we have to do ourselves, as we have to coordinate with the downstream portfolio regarding their plans to upgrade, too.

For reference for others: also note that you can already use Hibernate 6.2 with an existing boot application by simply configuring `hibernate.version` to `6.2.0.Final`. What's suggested here is upgrading Spring Data's *build* to Hibernate 6.2, which, given we primarily target JPA in our production code, is more of a testing topic than a "can Spring Data JPA work with Hibernate 6.2".

**Comment by odrotbohm** [comment]
We're not done yet. There are a couple of tests failing after the upgrade. Investigating.

**Comment by odrotbohm** [comment]
This is blocked as we cannot get the test case checking that our identifier access code does not initialize Hibernate proxies to run reliably. It works locally, it doesn't on CI. It looks like Hibernate under some circumstances optimizes the proxies away (likely nice for users) but we unfortunately reliably need to get one to perform the test. I've reached out to the Hibernate team for advice.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-data-jpa/issues/2917.
