### ISSUE TITLE
Join fetch strategy with Embeddable does not work since Spring Boot 3.0.0

### ISSUE THREAD

**Issue by GwennaelLonvert** [spring-projects/spring-data-jpa#2910]
I'm facing an issue since upgrading Spring boot 2.7.10 to 3.0.0 (problem still occurs in 3.0.5). I first thought the problem was on `Hibernate` side but everything works when I'm just using `EntityManager`, but the problems occurs when using `CrudRepository`.

I have two entities with a bidirectionnal @OneToMany relationship. The @ManyToOne is in a Embeddable class. My queries are with "join fetch" strategy to load the association directly and avoid a N+1 select.

Before upgrading, everything was ok, but now the association is not loaded and I got an exception when I try to access on this association with my result entity.

**Important : the problem happens only if the @ManyToOne is in a Embeddable class.**

Here is a simplified part of my entities :

```java
@Table(name = "sellers")
@Entity
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SellerEntity implements Serializable {
    @EmbeddedId
    private SellerEntityPK pk;

    @Column
    private String name;

    public String getId() {
        return pk.getId();
    }

    public CompanyEntity getCompany() {
        return pk.getCompany();
    }
}
```

```java
@Getter
@Builder
@Embeddable
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class SellerEntityPK implements Serializable {

    @ManyToOne(fetch = FetchType.LAZY)
    private CompanyEntity company;

    private String id;

    @Override
    public String toString() {
        return company.getName() + "+" + id;
    }
}
```

```java
@Table(name = "company")
@Entity
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CompanyEntity implements Serializable {

    @Id
    @Column
    private String name;

    @Column
    private String country;

    @OneToMany(cascade = CascadeType.ALL, mappedBy = "pk.company")
    @Default
    private Set<SellerEntity> sellers = new java.util.HashSet<>(0);

}
```
The query : 
```java
@Query("""
            select distinct s from SellerEntity s
            join fetch s.pk.company c
            where c.name = :companyName
            """)
    Optional<SellerEntity> findSellersWithCompany(String companyName);
```

Runtime code : 
```java
Optional<SellerEntity> postFound = sellerRepository.findSellersWithCompany("My first company");
String country = postFound.get().getCompany().getCountry();
```

The SQL does not contain the "join" on the table "company" : 
```sql
select distinct s1_0.company_name,s1_0.id,s1_0.name from sellers s1_0 where s1_0.company_name=?
```
but before upgrading, the sql request was doing the join and everything worked fine
```sql
select distinct sellerenti0_.company_name as company_3_6_0_, sellerenti0_.id as id1_6_0_, companyent1_.name as name1_0_1_, sellerenti0_.name as name2_6_0_, companyent1_.country as country2_0_1_ from sellers sellerenti0_ inner join company companyent1_ on sellerenti0_.company_name=companyent1_.name where companyent1_.name=?
```

Error : 

```java
org.hibernate.LazyInitializationException: could not initialize proxy [com.example.jpajoinfetch.seller.CompanyEntity#My first company] - no Session
```

I have done a little reproducer, with two modules : one in 2.7.10 version and one in 3.0.5 version. There is one test to show the problem.
[join-fetch-issue.zip](https://github.com/spring-projects/spring-data-jpa/files/11200562/join-fetch-issue.zip)

Could you tell me if it's a bug ? Is there any workaround ?

**Comment by gregturn** [comment]
This is looking very much like a Hibernate issue. Using your reproducer, I was able to glean the following from your reproducer:

* Simply dropping "fetch" from the `findSellersWithCompany` query causes the test case to fail all the same.
* I verified this fails on Spring Boot 3.0.5, 3.1.0-M2, and 3.0.6-SNAPSHOT. All of these versions use Hibernate 6.1, which certainly has some wrinkles.
* Changing `@ManyToOne(fetch = FetchType.LAZY)` on `SellerEntityPK` to `EAGER` makes the test go green.
* Adding `spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true` makes the test go green.

I realize that the last two options are not optimal. They are even deemed anti-patterns in some areas. Forcing all lazy fetching to one solution can be a tad brute force.

But all this points to some change in Hibernate and lazy loading configuration, and that it's clearly NOT a drop-in upgrade migrating to Hibernate 6.1.

**Comment by GwennaelLonvert** [comment]
Thanks for your reply. 

Indeed, we cannot go for the two last options. 

I thought it was an Hibernate issue. So I tried to reproduce the problem with their "test-template", where I use only an `EntityManager` and everything works fine. I use the exact same entities, the only difference 
```java
entityManager.createQuery("select distinct s from SellerEntity s join fetch s.pk.company c where c.name = 'My first company'").getResultList()
```
instead of using a `Repository`. 
I attach the small project : 
[hibernate-orm-6.zip](https://github.com/spring-projects/spring-data-jpa/files/11219629/hibernate-orm-6.zip)
You can check if you want, with the `JPAUnitTestCase`. I'm not saying it's on their side or on yours, just trying to figure out :)

**Comment by GwennaelLonvert** [comment]
@gregturn Did you have time to look at my response and my Hibernate reproducer ?

**Comment by gregturn** [comment]
I just downloaded and ran your test case. I saw this:

```
Hibernate: 
    select
        distinct s1_0.company_name,
        s1_0.id,
        s1_0.name 
    from
        sellers s1_0 
    where
        s1_0.company_name='My first company'

```

And it ran GREEN. So it works, as in no proxy issues, but it definitely has altered the query. I decided to try out Hibernate's recent `6.2.1.Final` version, since Spring Data JPA just upgrade do that last Friday. And this is what I got running the exact same code:

```
Hibernate: 
    select
        distinct s1_0.company_name,
        c1_0.name,
        c1_0.country,
        s1_0.id,
        s1_0.name 
    from
        sellers s1_0 
    join
        company c1_0 
            on c1_0.name=s1_0.company_name 
    where
        s1_0.company_name='My first company'
```

**Comment by gregturn** [comment]
First of all, running your Spring Boot 3 reproducer against Spring Boot `3.1.0-SNAPSHOT` definitely works. The test case passes just fine. That's the version that brings in Hibernate ORM 6.2. A little more digging, and it appears that Hibernate ORM 6.1 is the real culprit.

If you can jump to Spring Boot 3.1, then that's great. `3.1.0-RC1` whose release is in flight, should work just fine. You can also find it at `3.1.0-SNAPSHOT`, that too will pick up Spring Data JPA's adoption of Hibernate ORM 6.2.

However, if you can't and want to use the latest stable release of Spring Boot (`3.0.6`), then you can do THIS to get there:

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-jpa</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.hibernate.orm</groupId>
    <artifactId>hibernate-core</artifactId>
    <version>6.2.1.Final</version>
    <optional>true</optional>
    <exclusions>
        <exclusion>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

That should pull your Spring Boot 3.0 application up to Hibernate ORM 6.2 (the latest stable version while I write this).  Do that, and everything looks GREEN from my end.

<img width="1587" alt="Screen Shot 2023-04-20 at 12 13 38 PM" src="https://user-images.githubusercontent.com/311040/233439843-39cae016-35cd-435b-9696-ce6b9779f686.png">

That being said, on the original reproducer I don't see `fetch` clause just like I don't see it on the Hibernate example you recently linked to. I don't know how right or wrong that query is without the `fetch`. But it gets you over the session management issue we saw initially. The `fetch` thing may be a SEPARATE Hibernate issue.

**Comment by gregturn** [comment]
@GwennaelLonvert Please let me know if any of these alterations makes a difference.

**Comment by GwennaelLonvert** [comment]
Thanks for your investigation. I'll try those alterations today and I get back to you as soon as possible.

**Comment by GwennaelLonvert** [comment]
Sorry for the delay.

Both solutions (`3.1.0-RC1` or `3.0.6` + force Hibernate version) seem to solve the issue, thanks a lot. I prefer the solution with `3.1.0-RC1`, so I will have to wait for the `3.1.0` release, because I must use a stable version. Do you have an idea when it should be released approximately ?

So for this problem, you think the problem was on Hibernate side ? I checked the release notes on their side and I did not find something related to this, but anyway, it works now with Hibernate 6.2...

**Comment by GwennaelLonvert** [comment]
FYI, I just found the related issue on Hibernate side, and the fix is indeed in Hibernate 6.2. That makes sense now

https://hibernate.atlassian.net/browse/HHH-15875

**Comment by schauder** [comment]
Thanks for the confirmation.

**Comment by odrotbohm** [comment]
@GwennaelLonvert – According to our [release calendar](https://calendar.spring.io/), the Spring Boot 3.1 GA release is scheduled for May 18th.
