### ISSUE TITLE
Select before updates, is it possible turn off this check?

### ISSUE THREAD

**Issue by miltonhit** [spring-projects/spring-data-jpa#2958]
For example, I have this repository interface:

```
public interface AreaLogadaRepository extends CrudRepository<AreaLogadaRepository.Document, String> {
}
```

When I call this method:
myRepository.save(obj)

The spring executes:
1. select .... where id = ?;
2. update .....

I'm looking for a solution where I don't need to handle the EntityManager directly.
It is possible?

**Comment by schauder** [comment]
How would you do this when handling the `EntityManager` directly? I'm pretty sure this is standard behaviour of Hibernate, although it might depend on the presence of id and version attributes and their mapping.

**Comment by schauder** [comment]
Have you seen the stackoverflow questions about this? https://stackoverflow.com/questions/45635827/how-do-i-stop-spring-data-jpa-from-doing-a-select-before-a-save https://stackoverflow.com/questions/16303691/hibernate-select-before-update

**Comment by miltonhit** [comment]
Greetings @schauder,

 Yes I have thoroughly reviewed various references.... However it was not clear to me if this could be configured by Spring Data. I tried to put this annotation on my entity too, but it didn't work:
 
 ```
@SelectBeforeUpdate(value=false)
```


But if this really is Hibernate's responsibility, you can close this issue.
Thank you for the awnser.
