### ISSUE TITLE
 java.lang.ClassCastException while using spring with eclipselink

### ISSUE THREAD

**Issue by sanju450** [spring-projects/spring-data-jpa#2963]
Hi Team,

i am getting a strange error while using spring with eclipselink

```
org.eclipse.persistence.exceptions.DescriptorException
Exception Description: The class, [MigriertAttributeTransformer] cannot be used as an AttributeTransformer.
Internal Exception: java.lang.ClassCastException: class MigriertAttributeTransformer cannot be cast to class org.eclipse.persistence.mappings.transformers.Attrib
uteTransformer (MigriertAttributeTransformer is in unnamed module of loader org.springframework.instrument.classloading.SimpleThrowawayClassLoader @6cc86152; org .eclipse.persistence.mappings.transformers.AttributeTransformer is in unnamed module of loader 'app')
```

I got answers from eclipselink forum saying its something to do with spring classloader but didnot find anything useful.

Could you please help me out 

Iam using spring 5.2.7 version with eclipselink 2.7.6

These are my properties in persistence.xml

```xml
 <properties>
                        <property name="javax.persistence.jdbc.driver" value="oracle.jdbc.driver.OracleDriver" />
                        <property name="javax.persistence.jdbc.url" value="" />
                        <property name="javax.persistence.jdbc.user" value="" />
                        <property name="javax.persistence.jdbc.password" value="" />
                        
                    <property name="eclipselink.ddl-generation" value="create-tables" />
                    <property name="eclipselink.ddl-generation.output-mode" value="database" />
                        <property name="eclipselink.logging.level" value="ALL" />
                        <property name="eclipselink.logging.parameters" value="true" />
                        <!-- from iau-maris-opa -->
                        <property name="eclipselink.jdbc.bind-paramaters" value="true" />
                        <property name="eclipselink.target-database" value="Oracle" />
                        <property name="eclipselink.target-server" value="None"/>
                        <property name="eclipselink.persistence-context.flush-mode" value="commit" />
                        <property name="eclipselink.persistence-context.reference-mode" value="WEAK" />
                    <property name="eclipselink.weaving" value="static" />
                    <property name="eclipselink.weaving.eager" value="true" />
                     <property name="eclipselink.jdbc.exclusive-connection.mode" value="Always"/>
                     <property name="eclipselink.sessions-xml" value="Testsessions.xml"/>
                     <property name="eclipselink.session-name" value="default_test"/>
                      <property name="eclipselink.orm.validate.schema" value="boTLDescriptor.xml"/>
                    <!--  <property name="eclipselink.target-server" value=""/>-->

                </properties>
```

And spring-context.xml looks like this

```xml
<bean id="entityManagerFactory" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean">

        <property name="persistenceXmlLocation" value="classpath:persistence.xml" />
     <!-- <property name="dataSource" ref="dataSource" />-->
        <property name="persistenceUnitName" value="persistenceUnit_test" />
        <property name="jpaVendorAdapter">
            <bean class="org.springframework.orm.jpa.vendor.EclipseLinkJpaVendorAdapter">
                <property name="showSql" value="true"/>
                <property name="generateDdl" value="true"/>
               <property name="databasePlatform" value="org.eclipse.persistence.platform.database.Oracle12Platform"/>
            </bean>
        </property>
        <property name="jpaDialect">
            <bean class="org.springframework.orm.jpa.vendor.EclipseLinkJpaDialect" />
        </property>
    <property name="jpaPropertyMap">
        <props>
            <prop key="eclipselink.weaving">false</prop>
<!--            <prop key="eclipselink.weaving.lazy">true</prop>-->
<!--            <prop key="eclipselink.weaving.internal">true</prop>-->
        </props>
        </property>

    <!-- <property name="loadTimeWeaver">
     <bean class="org.springframework.instrument.classloading.ReflectiveLoadTimeWeaver" />
     </property>-->
      <property name="loadTimeWeaver">
         <bean class=
                       "org.springframework.instrument.classloading.InstrumentationLoadTimeWeaver">

         </bean>
     </property>
    </bean>
```

StackTrace: 

Target Invocation Exception: Exception [EclipseLink-183] (Eclipse Persistence Services - 2.7.6.v20200131-b7c997804f): org.eclipse.persistence.exceptions.DescriptorException Exception Description: The class, [MigriertAttributeTransformer] cannot be used as an AttributeTransformer. Internal Exception: java.lang.ClassCastException: class MigriertAttributeTransformer cannot be cast to class org.eclipse.persistence.mappings.transformers.Attrib uteTransformer (de.bund.bamf.InGe.bo.MigriertAttributeTransformer is in unnamed module of loader org.springframework.instrument.classloading.SimpleThrowawayClassLoader @6cc86152; org .eclipse.persistence.mappings.transformers.AttributeTransformer is in unnamed module of loader 'app') Mapping: org.eclipse.persistence.oxm.mappings.XMLDirectMapping[attributeTransformerClass-->attribute-transformer/text()] Descriptor: XMLDescriptor(org.eclipse.persistence.mappings.foundation.AbstractTransformationMapping --> [DatabaseTable(attribute-mapping)]) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1109) at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) at org.springframework.test.AbstractSingleSpringContextTests.createApplicationContext(AbstractSingleSpringContextTests.java:213) at org.springframework.test.AbstractSingleSpringContextTests.loadContextLocations(AbstractSingleSpringContextTests.java:189) at org.springframework.test.AbstractSingleSpringContextTests.loadContext(AbstractSingleSpringContextTests.java:169) at org.springframework.test.AbstractSpringContextTests.getContext(AbstractSpringContextTests.java:140) at org.springframework.test.AbstractSingleSpringContextTests.setUp(AbstractSingleSpringContextTests.java:98) at junit.framework.TestCase.runBare(TestCase.java:140) at org.springframework.test.ConditionalTestCase.runBare(ConditionalTestCase.java:76) at junit.framework.TestResult$1.protect(TestResult.java:122) at junit.framework.TestResult.runProtected(TestResult.java:142) at junit.framework.TestResult.run(TestResult.java:125) at junit.framework.TestCase.run(TestCase.java:130) at junit.framework.TestSuite.runTest(TestSuite.java:241) at junit.framework.TestSuite.run(TestSuite.java:236) at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90) at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.6.v20200131-b7c997804f): org.eclipse.persistence.exceptions.Entit yManagerSetupException Exception Description: Predeployment of PersistenceUnit [persistenceUnit_test] failed. Internal Exception: Exception [EclipseLink-9005] (Eclipse Persistence Services - 2.7.6.v20200131-b7c997804f): org.eclipse.persistence.exceptions.SessionLoaderException Exception Description: An exception was thrown while loading the project-xml file [META-INF/de.bund.bamf.InGe.boTLDescriptor.xml]. Internal Exception: Exception [EclipseLink-106] (Eclipse Persistence Services - 2.7.6.v20200131-b7c997804f): org.eclipse.persistence.exceptions.DescriptorException Exception Description: The method [setAttributeTransformerClass] on the object is throwing an exception. Argument: [class MigriertAttributeTransformer] Internal Exception: java.lang.reflect.InvocationTargetException Target Invocation Exception: Exception [EclipseLink-183] (Eclipse Persistence Services - 2.7.6.v20200131-b7c997804f): org.eclipse.persistence.exceptions.DescriptorException Exception Description: The class, [MigriertAttributeTransformer] cannot be used as an AttributeTransformer. Internal Exception: java.lang.ClassCastException: class MigriertAttributeTransformer cannot be cast to class org.eclipse.persistence.mappings.transformers.Attrib uteTransformer (MigriertAttributeTransformer is in unnamed module of loader

**Comment by sanju450** [comment]
yes ,spring data is not involved. i am using eclipselink jpa with spring context and below are dependency information.

eclipselink.version>2.7.6</eclipselink.version>
<spring.version>5.2.7.RELEASE</spring.version>
   
<dependencies>  
  <dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
  </dependency>
  <dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.3.0</version>
  </dependency>
  <dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.3.0</version>
  </dependency>
  
  <dependency>
    <groupId>javax.xml.ws</groupId>
    <artifactId>jaxws-api</artifactId>
    <version>2.3.1</version>
  </dependency>

  <dependency>
    <groupId>com.oracle.ojdbc</groupId>
    <artifactId>ojdbc8</artifactId>
    <version>${ojdbc.version}</version>
    
  </dependency>
   
  <dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-tx</artifactId>
    <version>${spring.version}</version>
  </dependency>

  <dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-orm</artifactId>
    <version>${spring.version}</version>
  </dependency>
  <dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-test</artifactId>
    <version>2.5.6</version>
  </dependency>
   
  <dependency>
    <groupId>junit</groupId>
    <artifactId>junit</artifactId>
    <version>4.13.1</version>
    <scope>compile</scope>
  </dependency>
  <dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>eclipselink</artifactId>
    <version>${eclipselink.version}</version>
    <exclusions>

      <exclusion>
        <groupId>org.eclipse.persistence</groupId>
        <artifactId>commonj.sdo</artifactId>
      </exclusion>
      
    </exclusions>
  </dependency>
</dependencies>

**Comment by mp911de** [comment]
Please file a ticket at https://github.com/spring-projects/spring-framework/issues as Spring Data isn't involved.
