### ISSUE TITLE
BadJpqlGrammarException: Line 1:236 token recognition error at: '!';

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-data-jpa#2970]
Hi

We tried to upgrade our Spring Boot project and used Spring Data JPA 3.1 (previously we had 3.0.x).
And we received a lot of errors in our JPQL (@Query) queries, for example, if we used "!=" operator then we received the following exception trying to execute this query:

`Caused by: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:236 token recognition error at: '!'; Bad JPQL grammar.`

We are aware that JPA officially supports "<>" operator but "!=" also worked before 3.1. 
We understood that this issue is caused by new HQL parser in Spring Data JPA however we couldn't find any information about these breaking changes in WIKI: https://github.com/spring-projects/spring-data-commons/wiki/Spring-Data-2023.0-%28Ullman%29-Release-Notes

So what we suggest:
1) Add information about breaking changes in WIKI/documentation
2) Currently this error happens during query execution. But if query is invalid then this error should be fired on application startup (like any other query validation errors).

**Comment by gregturn** [comment]
I can also confirm that Hibernate's own query parser has:

```
NOT_EQUAL : '!=' | '^=' | '<>';
```

**Comment by gregturn** [comment]
Merged to `main` and backported to `3.1.x`.

**Comment by gpolet** [comment]
> Merged to `main` and backported to `3.1.x`.

Looks like this one didn't make into 3.1.1
