### ISSUE TITLE
Order by NULLS FIRST/LAST no longer supported

### ISSUE THREAD

**Issue by rvullriede** [spring-projects/spring-data-jpa#2976]
After upgrading to Spring Boot 3.1.0 (which pulls Spring Data JPA 3.1 via Spring Data 2023.0) I've encountered the following exception:
` org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:56 mismatched input 'NULLS' expecting {<EOF>, ',', EXCEPT, FETCH, INTERSECT, LIMIT, OFFSET, UNION}; Bad JPQL grammar [SELECT a FROM AppRelease a ORDER BY a.dateReleased DESC NULLS LAST]`

Since this worked before I suspect this is due to the new JQL/HQL query parser introduced in #2814 .

While such a query is not (yet, see https://github.com/jakartaee/persistence/issues/76) part of the JPA standard, it's supported by Hibernate (not sure about other implementations) and its a regression compared to other versions.

**Comment by mp911de** [comment]
That's a duplicate of #2962

**Comment by rvullriede** [comment]
Ah, sorry for the noise. Must have missed that.
