### ISSUE TITLE
Incorrect version of Spring Data JPA reference documentation

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-data-jpa#2978]
Hi

Official documentation states that current version is 3.1.0: https://spring.io/projects/spring-data-jpa#learn

However the link goes to the 3.0.5 reference documentation: https://docs.spring.io/spring-data/jpa/docs/current/reference/html/

```
 Oliver Gierke Thomas Darimont Christoph Strobl Mark Paluch Jay Bryant Greg Turnquist 
version 3.0.5, 
2023-04-14 
```

And I don't even see 3.1.0 folder in the versions list here: 
https://docs.spring.io/spring-data/jpa/docs/

**Comment by christophstrobl** [comment]
Thanks for the heads up - docs are now deployed.
https://docs.spring.io/spring-data/jpa/docs/3.1.0/reference/html/
