### ISSUE TITLE
`existsById(…)` fails with `NullPointerException` when metadata does not exist

### ISSUE THREAD

**Issue by TheOezzi** [spring-projects/spring-data-jpa#2991]
Hey all,
After migrating to spring-data-jpa v3.1 I'm currently facing an issue with [this check](https://github.com/spring-projects/spring-data-jpa/blob/97255cfabb05c2f92dbcbff048dc15dc5b2a7d61/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#LL376C2-L376C2) in the existsById Query.

It will not work, as metadata.getComment() will throw a NPE if the metadata is already null.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by quaff** [comment]
> If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

It's an obvious missing null check, I've created https://github.com/spring-projects/spring-data-jpa/pull/2995.

**Comment by TheOezzi** [comment]
Thanks !
