### ISSUE TITLE
in version 3.1.0, some entity fields will be always altered when program startups

### ISSUE THREAD

**Issue by macauyeah** [spring-projects/spring-data-jpa#3004]
in  spring-boot-starter-data-jpa 3.1.0, when setting properties 

```
spring.jpa.hibernate.ddl-auto=update
```

some entity fields, which are not mapping to default data type, will be always recreated when program startups.

for example, default data type for 
- mapping BigInteger to mysql is DECIMAL(38, 0)
- mapping String to mysql is VARCHAR(255)

when I change the definition like below
```java
	@Column(columnDefinition = "DECIMAL(37, 0)")
	private BigInteger bigId;
	@Column(columnDefinition = "VARCHAR(512)")
	private String str512;
```
they will always be altered when program startups.

And more, ***java.utils.Date*** will always be altered even if I do not specified column definition.
```java
	private Date utilDate;
```

I am not sure the problem is caused by spring-data-jpa 3.1.0 or hibernate-core 6.2.2.

my demo project which fork from spring-guides, ***Accessing data with MySQL 3.1.0***

## branch ddl310 ##
- [pom.xml](https://github.com/macauyeah/gs-accessing-data-mysql/blob/ddl310/complete/pom.xml)
- [User.java](https://github.com/macauyeah/gs-accessing-data-mysql/blob/ddl310/complete/src/main/java/com/example/accessingdatamysql/User.java)

debug output will show that
```
Hibernate: alter table user modify column big_id  DECIMAL(37, 0)
Hibernate: alter table user modify column str512  VARCHAR(512)
Hibernate: alter table user modify column util_date  datetime(6)
```

## branch ddl307 ##
downgrade to 3.0.7, the problem gone.
- [pom.xml](https://github.com/macauyeah/gs-accessing-data-mysql/blob/ddl307/complete/pom.xml)
- [User.java](https://github.com/macauyeah/gs-accessing-data-mysql/blob/ddl307/complete/src/main/java/com/example/accessingdatamysql/User.java)

I also tested 3.1.0 with mircosoft sql server. The behavior still exits.

**Comment by mp911de** [comment]
Spring Data doesn't generate SQL nor DDL to create/alter tables. Please reach out to the Hibernate team.
