### ISSUE TITLE
InsertQuery used to `Projections DTO`

### ISSUE THREAD

**Issue by seonghoo1217** [spring-projects/spring-data-jpa#3008]
I recently saw a post saying that if you look up DTO without looking up the entity directly when you look up the entity, you may not look up unnecessary columns, so you can get an advantage.

However, like the code in the example, isn't it better to look up the entity directly if you want to make the DTO a new entity through the inquiry result? And when creating an entity that is related, why is it possible to create it with just a PK value?

**example select query**
```java
List<MusicRoomMemberDTO> mrmDTOList = jpaQueryFactory
				.select(Projections.fields(MusicRoomMemberDTO.class,
						mrm.musicRoomMemberSeq,
						mrm.ownerSeq.as("ownerSeq"),
						mrm.member.memberSeq.as("memberSeq"))
				)
				.from(mrm)
				.where(mrm.ownerSeq.eq(member.getMemberSeq()))
				.fetch();
```

**Comment by mp911de** [comment]
> isn't it better to look up the entity directly if you want to make the DTO a new entity through the inquiry result? 

Care to elaborate? What are you asking for? Also, you're referring to a primary key value, while the code snippet shows some Querydsl code with three columns that do not seem to be the primary key.
