### ISSUE TITLE
spring boot 3.1.0 jpa @BatchSize(size = 10)

### ISSUE THREAD

**Issue by audgks5551** [spring-projects/spring-data-jpa#3009]
```java
@Entity
@NoArgsConstructor
@AllArgsConstructor
@BatchSize(size = 10)
@Table(name = "tag_boards")
public class TagBoard {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = LAZY)
    private Tag tag;

    private int p;
}
```
```
tagBoardRepository.findById(id);
```
When tagBoardRespository.findById(id); is called, an in-section query is generated as shown below.
It occurs when spring boot 3.1.0 is operated now, and in clause does not occur when spring boot 3.0.7.
Is this a bug? Or is it intended?
```
select
        t1_0.id,
        t1_0.p,
        t1_0.tag_id      
    from
        tag_boards t1_0      
    where
        array_contains('ar0: ARRAY [CAST(1 AS BIGINT), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL]',t1_0.id)
```
Is there a way to solve it?

**Comment by quaff** [comment]
I think it's changed at hibernate side, you can use hibernate 6.1 instead of 6.2 to verify, if it is, you should report to hibernate team.

**Comment by quaff** [comment]
I've created https://hibernate.atlassian.net/browse/HHH-16779.
