### ISSUE TITLE
Proposal of an annotation to write the full name of a pojo in the hql requests

### ISSUE THREAD

**Issue by meilleureVie** [spring-projects/spring-data-jpa#3026]
so far when we want to use a pojo in hql selection query, we need to define the full qualified name of the pojo even if we are using a query from method query.
for instance, assume we have a bean named **StudentDto**  with properties name and firstname and located in the package **com.mydomaine.myproject.mysubmodule**. In order to use this bean in a query from a method query, we will do something like this :

```
@Query("select new com.mydomaine.myproject.mysubmodule.StudentDto(u.name, u.firstname) from Student u")
List<StudentDto> fetchStudents();
```

This approach is not the best cause it not helps to take advantage of the typesafe

I would like to suggest something i found in mapstruct project. We can add a new annotation for that. Let call it imports. So we can rewrite the query  like this :

```
import com.mydomaine.myproject.mysubmodule.StudentDto;

@Imports(value = StudentDto.class)
@Query("select new StudentDto(u.name, u.firstname) from Student u")
List<StudentDto> fetchStudents();
```

or We can also add an attribute to the query annotation to achieve that goal; something like this :

```
@Query(imports = StudentDto.class, value = "select new StudentDto(u.name, u.firstname) from Student u")
List<StudentDto> fetchStudents();
```
And after that, spring data had to turn the hql query generated into  : 
`select new com.mydomaine.myproject.mysubmodule.StudentDto(u.name, u.firstname) from Student u"`

I think this will be helpful
thanks

**Comment by gregturn** [comment]
So this proposal would involve doing an additional Spring Data JPA transformation where `StudentDto` is transformed into `com.mydomaine.myproject.mysubmodule.StudentDto` before being handed off to the entity manager as long at the DTO type can be accessed by some sort of annotation?

This raises questions that must be answered before we can consider it. Look at the following usage of this proposed new API:

```java
@Imports(value = StudentDto.class)
@Query("select new com.example.StudentDto(u.name, u.firstname) from Student u")
List<StudentDto> fetchStudents();
```

In this scenario, that annotation is applied, but the query already has a spelled out FQDN. Do we:
* Ignore the annotation?
* Compare the package paths of `StudentDto` and the HQL. If they match, no transform needed. If they differ, throw an exception?

Is this Hibernate only? On principle, we are trying to have one API for all, being Hibernate, EclipseLink, as well as any other JPA provider. Currently, JPQL doesn't support `new StudentDto(...)` without a FQDN, but Hibernate does.

**Comment by quaff** [comment]
IMO it's not worthy to increase complexity for such trivial feature.

**Comment by gregturn** [comment]
Based on evaluation and feedback, we have decided to not adopt this request.
