### ISSUE TITLE
Proposal of non domain repository

### ISSUE THREAD

**Issue by meilleureVie** [spring-projects/spring-data-jpa#3027]
So far, each repository has to specify a domain class and a domain id to work. That's fine, but sometimes we just need a read-only repository that will only contain queries written with the @query annotation. This need arises when we are done with crud operations and we are faced with application statistics queries. And these statistical queries can grow rapidly. And in these situations, in order to maintain a good pattern for our application, we need to set the repository on demand since the create and update operations are no longer performed.

So I'm wondering if it's possible to have some sort of repository for these cases in the future?
thanks

**Comment by mp911de** [comment]
Repositories are conceptually bound to domain-driven design. Running reports isn't something that fits into the space. While Spring Data repositories can be used for these operations (with `@Query` you can basically do whatever you want), we do not plan on exploring that direction. @gregturn provided you already with an approach to expose as little methods as possible.
