### ISSUE TITLE
There is a timezone bug in OffsetDateTime in Spring Boot 3.1.0.

### ISSUE THREAD

**Issue by ac-saro** [spring-projects/spring-data-jpa#3035]
My working environment is as follows:
DB: 10.6.11-MariaDB
Timezone: +09:00 (system, db both)

You can reproduce the issue using the following steps:

```
@Entity
@Table(name = "forum_topic")
class Topic(
...
  @Column(nullable = false)
  var regDt: OffsetDateTime = OffsetDateTime.now(),
  
  @Column(nullable = false)
  var updDt: OffsetDateTime = OffsetDateTime.now(),
)

boardTopicRepository.save(Topic());
```
Starting from Spring boot 3.0.7 version, it is stored in the following format in the DB.
![image](https://github.com/spring-projects/spring-data-jpa/assets/15857631/a29ef6fd-a3ae-44f5-b46c-6fae3735b943)
The data is stored in the DB as a properly formatted value with the applied timezone of +09:00.

However, starting from Spring Boot 3.1.0, it is stored as UTC-based value with a -9-hour offset.
When converted to OffsetDateTime in the DB, it does not apply the timezone, resulting in a output of -9 hours.
![image](https://github.com/spring-projects/spring-data-jpa/assets/15857631/1fec11e2-695b-4b72-bb53-f8f973deacf0)

Both the server and the DB are configured with the +09:00 timezone.

**Comment by mp911de** [comment]
Have you tried downgrading Hibernate to version 6.1?

**Comment by ac-saro** [comment]
@mp911de 
```
id("org.springframework.boot") version "3.1.0"
...
implementation("org.hibernate.orm:hibernate-core:6.1.7.Final")
```

I confirmed that it works fine after downgrading Hibernate to 6.1.7.

It seems to be a bug in Hibernate 6.2.

**Comment by bright-k** [comment]
https://docs.jboss.org/hibernate/orm/6.2/migration-guide/migration-guide.html#ddl-offset-time

The default setting for OffsetDateTime has been changed since Hibernate 6.2.x.
Have you tried using the setting in the mentioned document?

**Comment by ac-saro** [comment]
@bright-k 
Thank you
It can be confusing that the default value has been changed, but it has been resolved with the NORMALIZE option.

If others need documentation, please refer to the following address:
https://thorben-janssen.com/hibernate-6-offsetdatetime-and-zoneddatetime/

**Comment by slankka** [comment]
Using Hibernate 5.4.32 with  MariaDb-10.0.38 
mariadb-java-client 2.7.11

jdbcUrl :
```
jdbc:mariadb://a.b.c.d:3306/e?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&timezone=auto&useFractionalSeconds=true
``` 

JPA entity type Instant field with `record.getCreateTime().getEpochSecond() ` returns wrong timestamp (db+8)

```
db: 2024-03-13T17:48:30 (1710323310)
DataGrip: 2024-03-13T17:48:30 (1710323310)
JPA: 2024-03-14T06:48:30 (1710370110)
```

```
    @Column(name = "create_time", insertable = false, updatable = false)
    private Instant createTime;
``

after setting this property help , and epochSecond correct
```
spring.jpa.properties.hibernate.jdbc.time_zone=GMT+8
```
