### ISSUE TITLE
Lazily fetched associations being set to null depending on max_fetch_depth parameter

### ISSUE THREAD

**Issue by philiplowney** [spring-projects/spring-data-jpa#3043]
We use Spring Data JPA with Hibernate. We have recently upgraded to the following versions:
```
<spring.version>6.0.10</spring.version>
<spring-data-jpa.version>3.1.1</spring-data-jpa.version>
<hibernate.version>6.2.5.Final</hibernate.version>
```

After updating, we noted two issues related to the Hibernate max_fetch_depth parameter:

- Depending on the value of max_fetch_depth, entity relationships defined on fetched entities as @ManyToOne and @OneToMany were being set to null rather than initialised with a proxy. This appears to be a bug to us because there is no way to now distinguish between absent data and data that should be lazily loaded.

- Different values for max_fetch_depth are producing incompletely populated results, as expected, but the way the results are populated does not seem consistent as the value for max_fetch_depth changes. That is, an entity that is returned when max_fetch_depth=1 is not returned when max_fetch_depth=2.

A detailed example of this bug along with test cases has been created here: https://github.com/philiplowney/spring-jpa-hibernate-max-fetch-depth-bug

**Comment by mp911de** [comment]
The tests in `AbstractHibernateTestCase` succeed only because you're using the attached entity. Once the session cache is cleared (by calling `entityManager.clear()` or using individual `EntityManager` instances for each test step), you get the same behavior as with Spring. 

Therefore this report doesn't qualify as Spring Data issue.

**Comment by philiplowney** [comment]
Thank you for looking into this, I will raise a ticket with the Hibernate team instead.
