### ISSUE TITLE
Spring boot >= 3.0.1 changes outer to inner join when @EntityGraph and @Id

### ISSUE THREAD

**Issue by bioc-wajskonr** [spring-projects/spring-data-jpa#3050]
I'm using @EntityGraph to eagerly load some attributes. 
However, something broke after updating from 2.6.x to 3.x.

Suppose we have a human who can have multiple houses:
```
public class Human {
    @Id
    @Column(name = "ID", nullable = false, updatable = false, precision = 20)
    @GeneratedValue
    private BigInteger id;

    @EqualsAndHashCode.Exclude
    @ToString.Exclude
    @OneToMany(mappedBy = "human", cascade = CascadeType.ALL)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Collection<House> houses;
}
```

When searching for a human, by ID, EntityGraph can eagerly load some attributes:

```
@EntityGraph(attributePaths = { "houses.address" })
@Query ("SELECT h FROM Human h WHERE h.id = ?1")
Human findByIdEagerHouseAddresses(Integer id);
```
This will create SQL with left (outer by default) joins:
```
select h1_0.id, h2_0.human_fk, h2_0.address_fk, a1_0.id 
from human h1_0 
left join house h2_0 on h1_0.id = h2_0.human_fk
left join address a1_0 on a1_0.id = h2_0.address_fk where h1_0.id in (?)
```

This is acceptable because I will get the human even if they don't have a house.
However, if the address field in the house has the @Id annotation, the outer join will change to "inner":
```
@Entity
public class House {
    @Id
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "human_fk", nullable = false, updatable = false)
    private Human human;

    @Id  // THIS ANNOTATION WAS ADDED
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "address_fk", nullable = false, updatable = false)
    private Address address;
}
```
```
select h1_0.id, h2_0.human_fk, h2_0.address_fk, a1_0.id 
from human h1_0 
left join house h2_0 on h1_0.id = h2_0.human_fk 
join address a1_0 on a1_0.id = h2_0.address_fk where h1_0.id in (?)
```
If a human does not have a house, the query returns nothing due to the inner join, which seems like a bug.

**Comment by bioc-wajskonr** [comment]
Test case -> [https://github.com/bioc-wajskonr/JpaJoinBug](https://github.com/bioc-wajskonr/JpaJoinBug)

**Comment by mp911de** [comment]
Have you verified this issue against Hibernate 5.6 vs. 6.2 directly? We see an increased number of similar reports that is caused by Hibernate itself.

**Comment by mp911de** [comment]
Thanks a lot for the investigation. I was referring more to plain Hibernate usage without having anything Spring-related in the mix.

Between 3.0.0 and 3.0.1, we introduced a fix to retain subgraphs via https://github.com/spring-projects/spring-data-jpa/commit/24dccbec2f437f0faee3efb49a53b912d7cfdb11

Likely this is the effect you're seeing.

**Comment by bioc-wajskonr** [comment]
ok, sorry I was wrong. The change you have pointed out is ok.

I had been testing and modifying the versions of Hibernate (org.hibernate:hibernate-core), not Hibernate ORM (org.hibernate.orm:hibernate-core) which is utilized by Spring Boot.

Indeed, the bug emerges when upgrading hibernate-core from version 6.1.5.Final to 6.1.6.Final. Spring Boot 3.0.0 was employing 6.1.5.Final, however, Spring Boot 3.0.1 switched to using 6.1.6.Final, which has a bug. 
Thats why I thought it's 3.0.1 fault.

**Comment by bioc-wajskonr** [comment]
And this bug is neither fixed in latest 6.1.7.Final nor in 6.2.6.Final

**Comment by bioc-wajskonr** [comment]
It seems to be hibernate bug, so I'll close the ticket.

**Comment by bioc-wajskonr** [comment]
@mp911de Why label "for: external-project"? Isn't it spring-data fault, that implementation of @EntityGraph creates inner join instead of outer?

**Comment by mp911de** [comment]
Spring Data isn't in charge of fixing Hibernate issues. I'm able to reproduce the same query with using the Hibernate API directly:

```
EntityGraph<?> entityGraph = entityManager.createEntityGraph(Human.class);
entityGraph.addSubgraph("houses").addAttributeNodes("address");

entityManager.createQuery("SELECT h FROM Human h WHERE h.id = ?1")
		.setParameter(1, 1234)
		.setHint(EntityGraphType.FETCH.getKey(), entityGraph)
		.getResultList();
```
