### ISSUE TITLE
Using operator '!=' throws BadJpqlGrammarException in spring data jpa 3.1.1

### ISSUE THREAD

**Issue by gpolet** [spring-projects/spring-data-jpa#3061]
It seems that the `!=` operator is not supported in spring-data-jpa 3.1.1 (See issue https://github.com/spring-projects/spring-data-jpa/issues/2970). I (mis?)understood it would be fixed in 3.1.1.

The following query below fails with BadJpqlGrammarException 
```
public interface EmployeeRepository extends JpaRepository<Employee, Long> {

    @Query("select e from Employee e where e.firstName != :name")
    List<Employee> failingQuery(@Param("name") String name);

}

```

**Comment by gpolet** [comment]
Hi @gregturn . Indeed, we're using EclipseLink.
I confirm that this kind of query worked without issues before Spring Data JPA 3.1.

**Comment by gregturn** [comment]
I'll mark this is a regression and will move to patch the JPQL parser to handle this.
