### ISSUE TITLE
Multiple datasource setup - injected jpa properties depend on load order

### ISSUE THREAD

**Issue by 1dEraNCeSIv0** [spring-projects/spring-data-jpa#3088]
### Description

We have a setup where our spring boot app is connected to 2 separate datasources, primary and secondary. These datasources use different schemas. Also we try to reuse our spring properties as much as possible to avoid duplicating common properties.

Together this can cause an issue where hibernate schema validation fails due to `secondary_schema.primary_schema_table` not existing on the primary db. Otherwise the app exceptions at the latest once it starts using `secondary_schema.primary_table` because those tables do not exist.

I've traced the issue and it seems that if 
1. the secondary datasource's `LocalContainerEntityManagerFactoryBean` is instantiated first, and
2. we use the primary jpa properties to copy common values over for reuse in the secondary datasource's jpa properties
then the primary jpa properties are changed to the secondary's values by the time they are injected into the primary `LocalContainerEntityManagerFactoryBean`.

This should probably not happen.

### How to reproduce

1. Download and import [this example project](https://github.com/spring-projects/spring-data-jpa/files/12207155/multiple-datasource-injection-issue.zip) as gradle project in your IDE
2. Execute the tests in `DemoApplicationTest`

Expected: 
Tests work (no assert)

Actual behavior:
`primaryRepository.save(new PrimaryEntity())` throws an exception because `secondary_schema` is not found for the sql statement `insert into secondary_schema.primary_entity ...`

### Further details

When adding a breakpoint to `PrimaryDatabaseConfig.entityManagerFactory`, `SecondaryDatabaseConfig.entityManagerFactory` and `SecondaryDatabaseConfig.jpaProperties` I can confirm, that
1. the `defaultJpaProperties` autowired into `SecondaryDatabaseConfig.jpaProperties` hold the correct default schema in their `defaultJpaProperties.properties` map
2. the `secondaryJpaProperties` autowired into `SecondaryDatabaseConfig.entityManagerFactory` are a different object that holds the correct values
3. the `jpaProperties` autowired into `PrimaryDatabaseConfig.entityManagerFactory` are the same object as the `defaultJpaProperties` autowired in step 1, only their `properties` field now hold a map with the default schema `secondary_schema`

So it seems to me that injecting the primary jpa properties into the secondary jpa property bean definition mutates the primary jpa properties. I believe this should not happen.

The behavior even persists when introducing an additional layer of indirection. Defining a class
```java
@Component
public class JpaPropertiesContainer {

    private Map<String, String> properties;

    public JpaPropertiesContainer(JpaProperties jpaProperties) {
        this.properties = jpaProperties.getProperties();
    }

    public Map<String, String> getProperties() {
        return properties;
    }
}
```
and autowiring this class into `SecondaryDatabaseConfig.jpaProperties` causes the same behavior, so the primary jpa properties get mutated even when they are not autowired directly into the secondary jpa properties as a parameter. Autowiring _nothing_ into `SecondaryDatabaseConfig.jpaProperties` solves the issue, however. Why? I have no idea...

**Comment by 1dEraNCeSIv0** [comment]
Would it help if I provided more info or tried to summarize the issue better?

**Comment by mp911de** [comment]
Thanks for reaching out. Spring Boot is creating entity manager factory beans so please file this ticket at https://github.com/spring-projects/spring-boot/issues please.
