### ISSUE TITLE
Javadoc: Add @since for the new methods in Specification

### ISSUE THREAD

**Issue by ullenboom** [spring-projects/spring-data-jpa#3089]
`org.springframework.data.jpa.domain.Specification` has some new methods since 3.0 -- addAll(...)/anyOf(...) -- the `@since` Javadoc tag is missing.

**Comment by gregturn** [comment]
Pull request welcome!

**Comment by rukins** [comment]
@gregturn, It is done :)

**Comment by gregturn** [comment]
Thanks @rukins!

**Comment by gregturn** [comment]
Backported to `3.1.x` and `3.0.x`.
