### ISSUE TITLE
Cannot compile SELECT with DISTINCT with pagination

### ISSUE THREAD

**Issue by ujhazib** [spring-projects/spring-data-jpa#3098]
Since spring boot 3.1.0 (so spring data jpa 3.1.0 as well), if I have a _SELECT_ with a _DISTINCT_ keyword and it uses _pagination_, the query fails to compile during startup. I am currently trying to upgrade to 3.1.2 though. The issue is with the generated count query

First of all, the exception I get:

```
Caused by: org.hibernate.query.sqm.ParsingException: line 1:30 no viable alternative at input 'SELECTcount(DISTINCTname'
	at app//org.hibernate.query.hql.internal.StandardHqlTranslator$1.syntaxError(StandardHqlTranslator.java:46)
	at app//org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at app//org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
	at app//org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at app//org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at app//org.hibernate.grammars.hql.HqlParser.queryExpression(HqlParser.java:1780)
	at app//org.hibernate.grammars.hql.HqlParser.selectStatement(HqlParser.java:400)
	at app//org.hibernate.grammars.hql.HqlParser.statement(HqlParser.java:331)
	at app//org.hibernate.query.hql.internal.StandardHqlTranslator.parseHql(StandardHqlTranslator.java:116)
	... 225 more
```

A broken down simple example inside a repository interface (extends JpaRepository) which could you write and trigger the issue:

```
@Query("SELECT DISTINCT loc.name AS name, loc.lat AS latitude, loc,lon AS longitude FROM LocalityEntity loc")
Page<LocalityProjection> getLocalityPositions(Pageable p)
```

As far as I could debug it back, the difference between using spring boot 3.0.9 and this was that, in the background, the older one uses spring data jpa's QueryUtils to create the count query, but in case of the new version we go into JpaQueryParserSupport's createCountQuery (and going into JpqlQueryTransformer) and from that point was no easy for me to follow it anyways.

For reference and to see the root cause, the difference between the two generated count queries are that the old one uses `count(DISTINCT loc)` inside the query, while the new one is using `count(DISTINCT loc.name AS name, loc.lat AS latitude, loc,lon AS longitude)`. Valid SQL will not accept something like that, and I believe the HQL to SQL transition will just try to place the proper aliases and leave the body of the count alone, ending up having multiple items inside count.

**Comment by gregturn** [comment]
We're doing this in part to support backward compatibility. However, it looks like we have been supporting something that was faulty for awhile. With the new parser, it became increasingly simply to hold onto the projection and slide into the transformed query.

However, in a derived COUNT query built on top of a DISTINCT, that assumption was clearly faulty and required a little extra care. So I'm drafting a PR that I'd like some feedback from @schauder and/or @mp911de.

**Comment by gregturn** [comment]
Additionally, what happens if you need to "count the number of distinct names in a table"?

e.g. `select count(distinct e.name) from Employee e`

This sort of query would NEED to fetch all the names, apply a DISTINCT (can't remember if some databases require ordering), and then counting the results. If such a query were rewritten into `select count(distinct e) from Employee e` then it would be wrong.

Hence, I don't think making guesses like "replacing the projection with the primary alias" is guaranteed to work.

In essence, mixing DISTINCT with COUNT almost certainly should be done by hand to ensure the results are correct. We can "help" if we take a "select distinct e from ..." and move stuff around such that it becomes "select count(distinct e) from ...", but anything more is at risk of being flat out wrong.

**Comment by ujhazib** [comment]
> Additionally, what happens if you need to "count the number of distinct names in a table"?
> 
> e.g. `select count(distinct e.name) from Employee e`
> 
> This sort of query would NEED to fetch all the names, apply a DISTINCT (can't remember if some databases require ordering), and then counting the results. If such a query were rewritten into `select count(distinct e) from Employee e` then it would be wrong.
> 
> Hence, I don't think making guesses like "replacing the projection with the primary alias" is guaranteed to work.
> 
> In essence, mixing DISTINCT with COUNT almost certainly should be done by hand to ensure the results are correct. We can "help" if we take a "select distinct e from ..." and move stuff around such that it becomes "select count(distinct e) from ...", but anything more is at risk of being flat out wrong. (Which is what we're presently doing.)
> 
> My initial thought that there was something faulty we could fix is wrong. And frankly, when you use DISTINCT, it may be best to go ahead and hand-write the `countQuery` for the `@Query` annotation as well.

Understandable, and I also suspected that this is not correct. Can it be done with an inner select though?

`SELECT COUNT(*) FROM (<original query>) AS result;`

I had another issue where I wanted to generate the count query myself but especially after 3.1.x some hibernate apis became closed to achive it easily (to convert the JPQL to SQL). I wanted to also limit the above kind of select to speed up count when we have too many elements, that is also not a supported feature in any of these frameworks.

I'd have to fill out parameters and also think about SpEL in my queries as well if I'm succeeded with the transformation. I have a code with the actual HQL SQL conversion now taken from a repo which was done by one of the hibernate maintainers, but that is already huge. And to make the fill out and the spel conversion as well, would be a tedious code work to be inside our own solution rather than being done in Spring Data JPA in my opinion. I'm not afraid of do such work, but it would be much better to centralize the "default" count there with this approach. Maybe I am unaware of some other special cases where the above doesn't work.

**Comment by gregturn** [comment]
We certainly can't have the solution be "for a count query on a distinct operation, inject an inner select". At least, not without gobs and gobs of test cases. Whereas that solution DOES work in many scenarios, it's not something I can see being correct ALL the time.

The truth is, in my experience of writing hundreds of production queries, DISTINCT queries REALLY require extra analysis to ensure they are correct against the applied data set. It's VERY hard to generalize that into framework code.

Now we are trying to afford you top-level support by allowing you to leverage SpEL expressions and we've updated parameter binding so that you can inject arguments into your `@Query` annotations, but it's really best to write those queries (and the countQuery) directly to ensure it's really DISTINCT.

**Comment by ujhazib** [comment]
Thanks for your support so far and looking into this. I will see then how we wil move forward.

**Comment by greazleay** [comment]
I just came across this and I am not sure what the proposed solution is reading through the thread. Though I did eventually get the query to compile in my own case which has a WHERE clause but the values were duplicated even with writing a separate count query and handling the pagination manually. I am using Spring Boot 3.2.4 with a PostgreSQL database

**Comment by ujhazib** [comment]
> I just came across this and I am not sure what the proposed solution is reading through the thread. Though I did eventually get the query to compile in my own case which has a WHERE clause but the values were duplicated even with writing a separate count query and handling the pagination manually. I am using Spring Boot 3.2.4 with a PostgreSQL database

In short, the original generated count query was wrong itself. I agree. They didn't reproduce that, just throw an error on our case. You have to carefully check out your case and find a way to rewrite in a way that you have a count query as well which is ok for paginating your main query, or you check if it is still makes sense in your logic to have only one column in the distinct.
