### ISSUE TITLE
spring-data-jpa:3.1.2 findAll(Specification<T> spec, Pageable pageable) generates invalid query

### ISSUE THREAD

**Issue by kpentchev** [spring-projects/spring-data-jpa#3104]
In a very specific scenario involving an entity class extending another entity class and using `@Inheritance(strategy = InheritanceType.JOINED)` and when querying via the repository method `findAll(Specification<T> spec, Pageable pageable)` with a specification that adding a predicate filtering for both an inherited property/column and a property/column from a related entity/table an invalid SQL count query is generated, because the joined table is not considered.

I have prepared a minimal implementation reproducing the issue at https://github.com/kpentchev/spring-data-jpa-bug. You should run the test class `ChildClassRepositoryTest`.

**Comment by kpentchev** [comment]
I was able to test with a previous version 3.0.8 which did not experience the issue.

**Comment by mp911de** [comment]
The main difference between `3.1.2` and `3.0.8` is (when used via Spring Boot), the Hibernate version (6.2 vs. 6.1). Switching to Hibernate 6.1 fixes the issue. Hibernate 6.3.0.CR1 suffers from the same problem so I recommend reaching out to the Hibernate team and filing a bug there.
