### ISSUE TITLE
Problem with generate exists query from query method names in data jpa

### ISSUE THREAD

**Issue by sami355-24** [spring-projects/spring-data-jpa#3122]
I had to implement a logic that returns True only when all the list values ​​exist in the DB. I wrote the method according to data jpa's method naming convention as follows.

```java
Boolean existsAllByIdIn(List<Long> ids);
```
Afterwards, I tested to see if the logic worked correctly, but found something strange.

The logic I want is to return `true` when all the values ​​given as arguments must exist in the DB, but in actual operation, `true` is returned if there is even one value.

In other words, the problem was found that it was operated like `or` rather than `and`.

To check a more accurate query, I checked the query going to the DB through the p6spy library. As a result, a completely different query came out than I expected.

expected query
```java
SELECT CASE WHEN EXISTS (
    SELECT 1
    FROM expense_document
    WHERE expense_document_id IN (1,2,3)
    HAVING COUNT(DISTINCT expense_document_id) = 3
) THEN 'Yes' ELSE 'No' END AS result;
```
Query that actually went out
```java
select
        e1_0.expense_document_id
    from
        expense_document e1_0
    where
        e1_0.expense_document_id in (1,2,3) fetch first 1 rows only
```

I  don't know why these queries are being written. Any help would be appreciated.

Curious about why it works like this, I looked into the source code of data jpa, but I only found `QueryUtils.java`, a class in charge of writing `find`, `exists`, `delete`, and `select` queries, and a method with the all keyword. I couldn't find the class involved in generating the dynamic query for .

**Comment by schauder** [comment]
There is no `existsAll` keyword in query derivation. There is only `exists`, so the `All` part of your method name is just ignored.

If you are looking for the code doing the parsing and eventually query generation look for classes with the name part `PartTree`
