### ISSUE TITLE
How to limit the return results in a non-declarative query?

### ISSUE THREAD

**Issue by Mpp1486356697** [spring-projects/spring-data-jpa#3124]
I want to be the same “
  <T> Collection<T> findByLastname(String lastname, Class<T> type);
”
，But it failed.
public interface PersonDao extends JpaRepository<Person,Long>, JpaSpecificationExecutor<Person>
        ,QuerydslPredicateExecutor<Person> {

    <C> Page<C> findAll(Specification<Person> spec, Pageable pageable,Class<C> c);
    <C> Page<C>  findAll(Predicate predicate, Pageable pageable,Class<C> c);
}
Using Querydsl to construct conditions is very convenient, but it does not allow limiting the return results - I don't want to use it “new JPAQueryFactory(em).select(QPerson.person.name).where(....,

**Comment by Mpp1486356697** [comment]
Yes, you are correct.
Why doesn't findBy behave like findAllByName? “select p1_0.name ”
But instead "p1_0.id,p1_0.age,p1_0.name,p1_0.phone_id "  
Or rather, what should I do then?

`    personDao.findBy(Example.of(new Person("lrb",null,null)),
                x -> x.as(PersonOnlyName.class).page(PageRequest.of(1, 1)));
//        Hibernate: select p1_0.id,p1_0.age,p1_0.name,p1_0.phone_id from person p1_0 where p1_0.name=? limit ?,?
//        Hibernate: select p1_0.id,p1_0.name from phone p1_0 where p1_0.id=?
//        Hibernate: select count(p1_0.id) from person p1_0 where p1_0.name=?
       personDao.findBy(Example.of(new Person("lrb",null,null)),
                x -> x.project("name").page(PageRequest.of(1, 1)));
//        Hibernate: select p1_0.id,p1_0.age,p1_0.name,p1_0.phone_id from person p1_0 where p1_0.name=? limit ?,?
//        Hibernate: select count(p1_0.id) from person p1_0 where p1_0.name=?
        Page<PersonOnlyName> lrb = personDao.findAllByName("lrb", PageRequest.of(1, 1), PersonOnlyName.class);
//        Hibernate: select p1_0.name from person p1_0 where p1_0.name=? limit ?,?
//        Hibernate: select count(p1_0.id) from person p1_0 where p1_0.name=?

`

**Comment by Mpp1486356697** [comment]
> Have you seen the `findBy` method that allows limiting?
> 
> ```java
> List<User> results = repo.findBy(predicate, query -> query.limit(10).all());
> ```
> 
> Generally, `Pageable` allows limit results to one page if you're looking for a simpler API.

Yes, you are correct.
Why doesn't findBy behave like findAllByName? “select p1_0.name ”
But instead "p1_0.id,p1_0.age,p1_0.name,p1_0.phone_id "
Or rather, what should I do then?

` personDao.findBy(Example.of(new Person("lrb",null,null)),
x -> x.as(PersonOnlyName.class).page(PageRequest.of(1, 1)));
// Hibernate: select p1_0.id,p1_0.age,p1_0.name,p1_0.phone_id from person p1_0 where p1_0.name=? limit ?,?
// Hibernate: select p1_0.id,p1_0.name from phone p1_0 where p1_0.id=?
// Hibernate: select count(p1_0.id) from person p1_0 where p1_0.name=?
personDao.findBy(Example.of(new Person("lrb",null,null)),
x -> x.project("name").page(PageRequest.of(1, 1)));
// Hibernate: select p1_0.id,p1_0.age,p1_0.name,p1_0.phone_id from person p1_0 where p1_0.name=? limit ?,?
// Hibernate: select count(p1_0.id) from person p1_0 where p1_0.name=?
Page lrb = personDao.findAllByName("lrb", PageRequest.of(1, 1), PersonOnlyName.class);
// Hibernate: select p1_0.name from person p1_0 where p1_0.name=? limit ?,?
// Hibernate: select count(p1_0.id) from person p1_0 where p1_0.name=?

**Comment by mp911de** [comment]
`findBy` projections use fetch graphs instead of tuple queries. I think that is something we can improve on, see also #2600.
