### ISSUE TITLE
Update JPQL and HQL parsers with newly introduced JPA 3.2 keywords

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-jpa#3136]
See https://deploy-preview-652--jakartaee-specifications.netlify.app/specifications/persistence/3.2/

* Adds `union`, `intersect`, `except`, `cast`, `left`, `right`, and `replace` for Jakarta Persistence QL and criteria queries
* Adds `||` string concatenation operator to Jakarta Persistence QL
* Adds support for specifying null precedence when ordering Jakarta Persistence QL and criteria queries

**Comment by Nendanfito** [comment]
Does null precedence work on Page requests? Because its not working for me with version 3.2.1

`
Sort.Order sort = switch (direction != null ? direction : "") {
            case "asc" -> Sort.Order.asc(sortBy);
            case "desc" -> Sort.Order.desc(sortBy).nullsLast();
            default -> Sort.Order.asc("code");
        };

PageRequest pageRequest = PageRequest.of(
                alarmPageableFilter.getPageNumber(),
                alarmPageableFilter.getPageSize(),
                Sort.by(sort));
`

**Comment by mp911de** [comment]
No, it's not working with 3.2.1 because the JPA spec level is at 3.1. Starting with JPA 3.2, the API will specify null precedence (see https://projects.eclipse.org/projects/ee4j.jpa/releases/3.2)

**Comment by ducanh2110** [comment]
I have the same issue too. Dont understand why it's happen

**Comment by joseardaiz** [comment]
@mp911de and @christophstrobl - would you guys know when the issue that @Nendanfito explained here will be fixed?

**Comment by Nendanfito** [comment]
@emaranga I configured it  for spring in general in the application.yaml:
```
spring:
  jpa:
    properties:
      hibernate:
        order_by:
          default_null_ordering: last
```
With that solution all the querys made by jpa will return nulls last, in case you don't want it you have to made a nativeQuery.
