### ISSUE TITLE
Is 'tinytext' now the default field type for @Lob?

### ISSUE THREAD

**Issue by HengCC** [spring-projects/spring-data-jpa#3139]
after upgrading from 2.x to 3.x, regarding fields annotated with @Lob, the default database type used to be 'longtext,' but after the upgrade to 3.x, it changed to 'tinytext.' This caused my application to perform database field updates during startup, leading to data truncation. Even though it's a development environment, I find this change quite unreasonable."

Even though this field already existed in the database beforehand, it still got updated to 'tinytext

<img width="352" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/6167532/e62bdd9e-8491-4040-86fb-7c86fc438e04">

**Comment by mp911de** [comment]
Since Spring Data JPA isn't implementing any LOB nor DDL support, you should point this question at your JPA implementation vendor.

**Comment by kylooh** [comment]
Hi, I've met the same problem too. I am wondering did you solve this problem already? I've trying to use `@Column(columnDefinition = "LONGTEXT")` on the field of data structure. But it didn't work. Glad to see you guys disscusing about it.

**Comment by HengCC** [comment]
@kylooh  The issue was finally resolved by using version 3.0.9. and I have not yet tried a more recent update/version.

**Comment by kylooh** [comment]
> @kylooh The issue was finally resolved by using version 3.0.9. and I have not yet tried a more recent update/version.

My spring boot version is `3.2.1`, and it seems releasing at Dec 2023, after `3.0.9`'s Jul 2023. And this problem still exists. Maybe it is something else soloved your problem. But I solved my problem by remove `Lob` annotation, replacing it with `Column(columnDefinition="LONGTEXT")`
