### ISSUE TITLE
JPQL parser can't handle an attribute named "power"

### ISSUE THREAD

**Issue by sdusart** [spring-projects/spring-data-jpa#3143]
Similar (I think) to #3028, a query using an attribute named _power_ fails with this error : 

`BadJpqlGrammarException: Line 1:18 no viable alternative at input 'e.power'; Bad JPQL grammar [select distinct e.power.id from MyEntity e] `

Environment : 
- springboot:3.1.3
- JDK 17.0.8-zulu
- Debian GNU/Linux 12

**Comment by sdusart** [comment]
IIRC, having _power_ in a package name triggers an error too.

**Comment by gregturn** [comment]
Thanks @sdusart! That's fixed, merged to `main`, and backported to `3.1.x`.
