### ISSUE TITLE
Add `@NativeQuery` annotation as alias for `@Query(nativeQuery=true)`

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-jpa#3155]
The intent is to create a place where we can specify strategies to rewrite SQL queries. Right now, JSQLParser is used when it is there and we fall back to regex if it isn't there. We want to create a place where we could specify a `SqlRewriterStragtegyFactory` to decide how much JSQLParser we want to take into account (or bypass the rewrite for certain queries).

**Comment by fatihdogmus** [comment]
Hello, can I pick this issue? I'm new to contributing to open source, so this issue seems easy enough to do for a first timer 🙂

**Comment by danvandeee** [comment]
Hi as it seemed no one had picked this up yet i thought of picking it up.
Created a pr for it https://github.com/spring-projects/spring-data-jpa/pull/3353
