### ISSUE TITLE
Add Projections to QuerydslPredicateExecutor

### ISSUE THREAD

**Issue by membersound** [spring-projects/spring-data-jpa#3159]
It would be great if the `findBy()` method of `QuerydslPredicateExecutor` could support projection interfaces.

The method currently only works with the real `@Entity`, like:
```
intercace MyEntityRepository extends JpaRepository<MyEntity, Long>, QuerydslPredicateExecutor<MyEntity> {
}
```

Usage:
```
Stream<MyEntity> stream = dao.findBy(predicate, FluentQuery.FetchableFluentQuery::stream);
```

But not this:

```
Stream<MyEntityView> stream = dao.findBy(predicate, FluentQuery.FetchableFluentQuery::stream)
interface MyEntityView {
     String getMyField1();
     String getMyField4();
}
```

**Comment by mp911de** [comment]
Have you seen that `findBy` accepts a functional callback that lets you specify the target type? 

`dao.findBy(predicate, q -> q.as(MyEntityView.class).stream())`

**Comment by membersound** [comment]
I see, yes that's what I was looking for. Maybe this could be added to the docs? I could not find such an example.

**Comment by mp911de** [comment]
Take a look here: https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example.fluent

**Comment by membersound** [comment]
So as my ticket is about how to use projections, I think this is answered sufficient.

Anyways there seems to be a performance issue with this approach, for which I created a new issue for better tracking:
https://github.com/spring-projects/spring-data-jpa/issues/3160
