### ISSUE TITLE
KeysetScrollPosition.isInitial always returns false

### ISSUE THREAD

**Issue by wsaca** [spring-projects/spring-data-jpa#3180]
Hello, I have a problem trying to check if my query is in the first position:
```java
Window<Role> findAllBy(ScrollPosition position);
```

When calling it, it returns 2 records:
```java
Window<Role> window = roleRepository.findAllBy(ScrollPosition.keyset());
```
but `window.positionAt(0).isInitial()` always returns `false`

The reason apparently lies in the `JpaMetamodelEntityInformation.getKeyset` method which always returns at least one key set:
https://github.com/spring-projects/spring-data-jpa/blob/1b50d23b9fa180b70c4ff167875085bd1e1394a0/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/JpaMetamodelEntityInformation.java#L233

`getKeyset` is used in `ScrollDelegate.createWindow`:
https://github.com/spring-projects/spring-data-jpa/blob/1b50d23b9fa180b70c4ff167875085bd1e1394a0/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/ScrollDelegate.java#L89

and by calling `window.positionAt(0).isInitial()`, the `KeysetScrollPosition.isInitial` method checks the loaded keys where it always finds at least one and returns `false`:
https://github.com/spring-projects/spring-data-commons/blob/30dcacc8c1ef11d70580f7f79927122590a71ac7/src/main/java/org/springframework/data/domain/KeysetScrollPosition.java#L140

**Comment by quaff** [comment]
The javadoc of `ScrollPosition.isInitial()` states:
> Returns whether the current scroll position is the initial one.

The javadoc of `Window.positionAt()` states:
> Returns the {@link ScrollPosition} at {@code index}.


It doesn't state position at zero must be initial one, I don't think it's a bug.
Could you share your actual use case to check `ScrollPosition.isInitial()` ?

**Comment by mp911de** [comment]
What @quaff said. Conceptually, the initial position starts before index zero as it describes the position before the first element. 

Regardless of keyset or offset mechanisms, if you request the next `Window` as of `previous.positionAt(0)` then the next window starts after the first element of the initial window of data.
