### ISSUE TITLE
Spring boot starter data jpa does not respect @BatchSize

### ISSUE THREAD

**Issue by anaconda875** [spring-projects/spring-data-jpa#3186]
=================================================================
Source code of this question can be found [HERE][1]

Spring boot version: 2.7.16

Mariadb version: 10.7.8

=================================================================

I'm develop a simple app. I have an entity named Category that have self reference to itself (list of child):

    @Entity
    @Table(name = "tbl_category")
    @Data
    @NamedEntityGraph(
      name = "test",
      attributeNodes = {
        @NamedAttributeNode(value="children",subgraph="children"),
      },
      subgraphs = {
        @NamedSubgraph(
          name = "children",
          attributeNodes = {
            @NamedAttributeNode("children")
          }
        )
      })
    @BatchSize(size = 10)
    public class Category {
    
      @Id
      @GeneratedValue
      private Long id;
    
      @Basic(optional = false)
      private String name;
    
      @ManyToOne
      @ToString.Exclude
      private Category parent;
    
      @OneToMany(mappedBy = "parent", cascade = { CascadeType.PERSIST, CascadeType.MERGE })
      @ToString.Exclude
      @BatchSize(size = 10)
      private List<Category> children;
    
      @OneToMany(mappedBy = "category")
      @ToString.Exclude
      private List<Product> products;
    
    }

I want to load a Category by id (and its children of type Category too) without N+1 issue. 
I searched on Google and found this [article][2].

But no luck, N+1 still shown up. Seems that Hibernate (or Spring) ignored my `@BatchSize`

Below is some related code snipe:

    @Service
    @RequiredArgsConstructor
    public class DefaultCategoryService implements CategoryService {
    
      private final CategoryRepository repository;
    
      @Override
      public CategoryResponse save(CategoryRequest request) {
        Category entity = toEntity(request);
        entity = repository.save(entity);
    
        return new CategoryResponse(entity);
      }
    
      @Override
      public CategoryResponse findById(Long id) {
        return repository.findById(id).map(this::toResponse)
          .orElseThrow(() -> new ResourceNotFoundException(String.format("Category with id [%d] is not found", id)));
      }
    
      private CategoryResponse toResponse(Category category) {
        return new CategoryResponse(category);
      }
    
      private Category toEntity(CategoryRequest request) {
        Category entity = new Category();
        entity.setName(request.getName());
        List<Category> children = Optional.ofNullable(request.getChildren())
          .orElseGet(Collections::emptyList)
          .stream()
          .map(cr -> {
            Category child = toEntity(cr);
            child.setParent(entity);
    
            return child;
          })
          .collect(Collectors.toList());
        entity.setChildren(children);
    
    
        return entity;
      }
    
    }

    @Data
    @NoArgsConstructor
    public class CategoryResponse {
    
      private Long id;
      private String name;
      private List<CategoryResponse> children;
    
      public CategoryResponse(Category entity) {
        this.id = entity.getId();
        this.name = entity.getName();
        this.children = Optional.ofNullable(entity.getChildren())
          .orElseGet(Collections::emptyList)
          .stream()
          .map(CategoryResponse::new).collect(Collectors.toList());
      }
    }

    @Data
    public class CategoryRequest {
    
      private String name;
      private List<CategoryRequest> children;
    
    }

Please help!! Why spring boot does not respect my @BatchSize?

  [1]: https://github.com/anaconda875/product/tree/n-plus-1
  [2]: https://jivimberg.io/blog/2018/08/04/recursive-queries-on-rdbms-with-jpa/

**Comment by mp911de** [comment]
Any annotations on the entity are subject to be handled by your persistence provider. Spring Data isn't involved in evaluating JPA annotations.
