### ISSUE TITLE
Unable to use deleteInBatch due to cascade issue

### ISSUE THREAD

**Issue by BalachandranM** [spring-projects/spring-data-jpa#3198]
I have entity A and B.

A is binded to B in a one-to-one relationship while the owning side is B in the relation(i.e, a_id is in B).

The issue that I faced is, when I try to delete a collection of A objects using `repo.delete` method, respective elements of B is deleted and then A is deleted, which is fine. **But, when I try to delete the same collection of A objects using `repo.deleteInBatch` method, elements of B are not pushed for delete and the ORM is directly trying to delete the records of A because of which I get into exceptions.**. It appears to be an issue with the cascade.

This seems to be a bug with deleteInBatch method since the same is working for regular deletes.

I am using Spring Boot 2.7.3
JDK: 1.8
DB: Postgresql

**Comment by quaff** [comment]
No, It's not a bug, it's used for bulk delete with one single query. Here is the Javadoc of `deleteInBatch()`:
> Deletes the given entities in a batch which means it will create a single query. This kind of operation leaves JPAs first level cache and the database out of sync.

I think the javadoc need be improved to clarify that cascade and events are ignored in this case, It's contrary to https://github.com/spring-projects/spring-data-jpa/issues/3177

**Comment by schauder** [comment]
@quaff is right on the spot, including that the documentation could use some improvement, which I did with https://github.com/spring-projects/spring-data-jpa/commit/685107d4e16f34800a5c78b92dd33a24b36f4ef1

**Comment by BalachandranM** [comment]
Thanks guys for the quick response 👍  :)
