### ISSUE TITLE
Session.getNamedNativeQuery(...) has been deprecated - alternatives needed?

### ISSUE THREAD

**Issue by stefan-schilling** [spring-projects/spring-data-jpa#3203]
Hello,

Our Postgres prod DB allows to run queries using Json, while our H2 test DB does not allow it. I can therefore not end-to-end test the queries by adding data to the DB and test, if the queries work. All I can do is to verify the working queries remain unchanged.
That is why I obtain the native query from the Session and the compare the String against the expected one in the test.

Sadly, method Session.getNamedNativeQuery(String) has been deprecated with Hibernate 6.2.6.Final (coming with Spring Boot 3.1.x). 

Since the JavaDoc does not mention an alternative, I'm asking here: is there any other way to cover the scenario described above? E.g. by using another method to get the named native query or by using a completely different approach.

Thanks.
Stefan

**Comment by schauder** [comment]
You would need to ask that the Hibernate team. This is the Spring Data JPA issue tracker. Spring Data JPA is relying on JPA which is implemented by Hibernate, but it is not Hibernate.

That said: You should use Testcontainers to test your database interactions, not an in-memory database when in production you use Postgres.
