### ISSUE TITLE
KeySetScrollPosition.initialize() in reference doc example is package-private. 

### ISSUE THREAD

**Issue by pro0331** [spring-projects/spring-data-jpa#3204]
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.scrolling.keyset
https://docs.spring.io/spring-data/commons/reference/repositories/scrolling.html

Both JPA and commons docs use KeySetScrollPosition.initialize() in examples, and they explain no other ways for keyset based scrolling. 
But the example code is not working, because KeySetScrollPosition.initialize() is a package private method.

**Comment by quaff** [comment]
It belongs to `spring-data-commons`, I've created https://github.com/spring-projects/spring-data-commons/pull/2963.

**Comment by pro0331** [comment]
Oh, I thought I was creating the issue on spring-data-commons :$
Thanks for the updates.
