### ISSUE TITLE
Add feature allow CrudRepository entity with same name @Table targets different database

### ISSUE THREAD

**Issue by CarlosOnline** [spring-projects/spring-data-jpa#3207]
Please add a feature that allows entity repositories with same class name, targeting different databases on same server.  Its awkward having to create different class names for the same table name when targeting multiple databases.  Could you please implement this feature?

**Desired**
```
@Table(catalog = "Students", name="Person")
@Entity
public class Student

@Table(catalog = "Teachers", name="Person")
@Entity
public class Student
```

**Actual**
```
@Table(catalog = "Students", name="Person")
@Entity
public class TeachersDatabaseStudent

@Table(catalog = "Teachers", name="Person")
@Entity
public class StudentDatabaseStudent
```

**Comment by mp911de** [comment]
Spring Data JPA isn't handling any database access at all, your JPA provider handles these aspects. Depending on your JPA provider there are various strategies available. We have examples for Hibernate at https://github.com/spring-projects/spring-data-examples/tree/main/jpa/multitenant.
