### ISSUE TITLE
Seconds being truncated: bug or common behavior

### ISSUE THREAD

**Issue by GuilhermeSerra** [spring-projects/spring-data-jpa#3208]
Hi,

I have in my Oracle Database, columns named: "PAOR_DATE_CREATION" and "PAOR_DATE_EXPEC_DATE" (among others) that stores DATE Oracle type in "PAYMENT_ORDER" table.

**Entity**
```
@Entity
@Table(name = "PAYMENT_ORDER")
class PaymentOrder {

/* properties */

    @Column(name = "PAOR_DATE_CREATION", nullable = false)
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    var creationDate: LocalDateTime? = LocalDateTime.now()

    @Column(name = "PAOR_DATE_EXPEC_DATE", nullable = false)
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    var expectedPaymentDate: LocalDateTime? = LocalDateTime.now()

/* properties */

}
```

The code below is a test to get all rows and print

```
paymentOrderService.findAll().map {
        println(it)
}
```

When I run the code, it returns:

```
{"creationDate":"2023-05-07T14:21:47", "expectedPaymentDate":"2023-05-08T00:00"}
{"creationDate":"2023-06-12T12:39:47", "expectedPaymentDate":"2023-06-14T00:00:01"}
```

"creationDate" (2023-05-07T14:21:47) is **correct** as stored in database but "expectedPaymentDate" (2023-05-08T00:00) (**first line**) has **seconds truncated**, is **different** from database.
For a second test, I changed manually another record adding 1 second and now it returns correctly (2023-06-14T00:00:01) (**second line**)

Why it happens? is it a bug? or just some configuration issue?
Sorry for do not give too much details and thanks for looking into it!

**Comment by mp911de** [comment]
Spring Data JPA isn't involved in value to database mapping, your JPA provider is handling these aspects.
