### ISSUE TITLE
JpaRepositroy unable to be proxied

### ISSUE THREAD

**Issue by lixx174** [spring-projects/spring-data-jpa#3211]
When I defined an inner interface and extends JpaRepositroy ,there is no proxy object in spring.

So I got an error that:
 Parameter 0 of constructor in com.security.infra.repository.DefaultOauth2ClientRepository required a bean of type 'com.security.infra.repository.DefaultOauth2ClientRepository$Oauth2ClientJpaRepository' that could not be found.

here is the source code:
![image](https://github.com/spring-projects/spring-data-jpa/assets/135929345/bb4694ce-7a2a-4a77-aaaf-3667817a819e)

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by lixx174** [comment]
@mp911de  I'm sorry that didn't describe it clearly.

this is the step to reproduce at spring boot 3.1.5:

1. gradle depency : `implementation 'org.springframework.boot:spring-boot-starter-data-jpa'`
2. the core code : `@Component
@RequiredArgsConstructor
public class OuterRepository {

    // Autowired by constructor with lombok
    private final InnerJpaRepository repo;

    @Repository
    public interface InnerJpaRepository extends JpaRepository<Object, Integer> {

    }
}`

In this case, when I start tomcat, the `InnerJpaRepository ` can't be Autowired and will get an error.
I konw that if I don't define  `InnerJpaRepository ` as an inner class, it's all ok.

**Comment by mp911de** [comment]
Thanks for the detail. By default, nested repository definitions are ignored. Please add `@EnableJpaRepositories(considerNestedRepositories = true)` to your configuration to enable scanning for nested repository interfaces.

**Comment by lixx174** [comment]
Thanks a lot
