### ISSUE TITLE
Visibility of `SimpleJpaRepository.ExampleSpecification`

### ISSUE THREAD

**Issue by dabico** [spring-projects/spring-data-jpa#3213]
Would it be possible to increase the visibility of `SimpleJpaRepository.ExampleSpecification` from `private` to `protected`?
I'm developing a custom repository that extends `SimpleJpaRepository`, and would like to reuse this inner class as opposed to copying it from the parent. The class in question:

https://github.com/spring-projects/spring-data-jpa/blob/018c2acd86d0a901353036dcdf44eda0bc625bca/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#L953-L987

**Comment by gregturn** [comment]
Fundamentally speaking, `ExampleSpecification` is an implementation detail to provide support for Query by Example.

I'd really to understand the use case you are attempting to solve that begs you to make changes and alterations to `ExampleSpecification`.

**Comment by mp911de** [comment]
Have you seen that you have all of this flexibility if you use the fluent `findBy(Specification, q -> q.stream())` or `findBy(Example, q -> q.stream())` API?

**Comment by dabico** [comment]
> Have you seen that you have all of this flexibility if you use the fluent `findBy(Specification, q -> q.stream())` or `findBy(Example, q -> q.stream())` API?

HI @mp911de 

I was not aware of this API, when was it introduced? I'm still on SB 2.7, and I don't think our organization will migrate to 3.X in the near future.

**Comment by mp911de** [comment]
It has been introduced with version 3.0. Spring Data JPA 2.7 has reached its OSS EOL by now (Nov 2023) and we will ship only one final OSS release.
We generally avoid updates to API that has been released as changes to API that is available for quite a while asks for trouble.

Given that update, I'm closing the ticket.
