### ISSUE TITLE
SpringDataJpa3.1.5 auto append "escape '\' " to the generated sql  for findAllByXXXContaining

### ISSUE THREAD

**Issue by tarepanda1024** [spring-projects/spring-data-jpa#3216]
When I using findAllByXXXContaining() , jpa generate sql , and append  "escape '\' ", this makes sql exec failed.Is this a bug or feature ? How can I avoid this？

<img width="1448" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/23069203/e5c511dd-2150-4d55-9dc1-511c5aa59bf2">

SpringBootVersion: 3.1.5
SpringDataJpaVersion: 3.1.5
JDK：jdk21
mysql:8.0

**Comment by quaff** [comment]
You should turn off [NO_BACKSLASH_ESCAPES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_backslash_escapes) at mysql server side.

**Comment by tarepanda1024** [comment]
> You should turn off [NO_BACKSLASH_ESCAPES](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_backslash_escapes) at mysql server side.

Oh , It works ! Thanks ! Is there any config to turn off this feature in JPA not in mysql?

**Comment by quaff** [comment]
With my test with MySQL Server 5.7.44, no matter `NO_BACKSLASH_ESCAPES` enabled or not, spring-data-jpa/hibernate will works fine.
`NO_BACKSLASH_ESCAPES` enabled then `escape '\'` will be used.
`NO_BACKSLASH_ESCAPES` disabled then `escape '\\'` will be used.

I assume your database is not real mysql but some other database use mysql protocol, If I'm correct you should report bug to its team.

**Comment by tarepanda1024** [comment]
> With my test with MySQL Server 5.7.44, no matter `NO_BACKSLASH_ESCAPES` enabled or not, spring-data-jpa/hibernate will works fine. `NO_BACKSLASH_ESCAPES` enabled then `escape '\'` will be used. `NO_BACKSLASH_ESCAPES` disabled then `escape '\\'` will be used.
> 
> I assume your database is not real mysql but some other database use mysql protocol, If I'm correct you should report bug to its team.

I start mysql process in docker.It's real mysql.

![image](https://github.com/spring-projects/spring-data-jpa/assets/23069203/1cea77a6-b7db-4e89-ab40-3aa2d0472ba6)


![image](https://github.com/spring-projects/spring-data-jpa/assets/23069203/fd7dc12b-cd03-4560-92a9-6188359b5439)

**Comment by quaff** [comment]
You can test `escape '\'` with `NO_BACKSLASH_ESCAPES` mode via mysql cli.

**Comment by tarepanda1024** [comment]
> You can test `escape '\'` with `NO_BACKSLASH_ESCAPES` mode via mysql cli.

It's failed.

![image](https://github.com/spring-projects/spring-data-jpa/assets/23069203/731b676e-7859-4da6-a9b5-d1a5eb25a256)

**Comment by mp911de** [comment]
`LIKE` with `ESCAPE` is a feature to control escaping with `Starts`/`Ends`/`Contains` queries to avoid injection of control characters that would be able to change the nature of the query.

As @quaff already pointed out, this is a configuration setting outside of Spring Data.

**Comment by gowrishankarjhcbb** [comment]
> `LIKE` with `ESCAPE` is a feature to control escaping with `Starts`/`Ends`/`Contains` queries to avoid injection of control characters that would be able to change the nature of the query.
> 
> As [@quaff](https://github.com/quaff) already pointed out, this is a configuration setting outside of Spring Data.

how about oracle any specific confifguration ?
