### ISSUE TITLE
Spring 3.1 EntitySpecification + Pageable + EntityGraph Pages In-Memory

### ISSUE THREAD

**Issue by thejeff77** [spring-projects/spring-data-jpa#3223]
This is mostly a follow up for this https://github.com/spring-projects/spring-data-jpa/issues/3206 since it was closed without really engaging in discussion, and I have feedback / follow up for this. I'm guessing I have to issue a new issue for follow ups when its immediately closed in cases like this... since its not my intention of going away just yet. Sorry to be annoying.

To quote my [reply](https://github.com/spring-projects/spring-data-jpa/issues/3206):

=========
@mp911de I guess I'm wondering why spring data won't use setMaxResults alone when the page request is for page number 0 (I.E. the first page), and not page in-memory for this case.

This would allow a limit to be set to a query that isn't technically paging yet, as page isn't > 0.

I'm pretty sure its not possible to set a queryhint dynamically in spring data, is it?. If not, setting setMaxResults on this dynamically clearly isn't possible, but I could possibly do it with a static hard coded value that is in the annotation. Am I right or am I missing anything?

It seems like this might be better as a bug report / optimization feature request to allow limit queries dynamically in these cases where a page request represents a limit query and not a paging query (I.E. Page number = 0)

Am I making sense or am I missing something?

**Comment by mp911de** [comment]
Thanks for reaching out. Let's continue the discussion in the original ticket. Closing a ticket isn't a termination of the discussion, rather, that the ticket isn't actionable in its current form. Adding more details can change its state. Therefore, to not create duplicate threads, I'm closing this one and respond to your comment at https://github.com/spring-projects/spring-data-jpa/issues/3206#issuecomment-1802264638.
