### ISSUE TITLE
Unable to use Java 21

### ISSUE THREAD

**Issue by arkadiusz97** [spring-projects/spring-data-jpa#3233]
I want to create a new Spring Boot project which utilizes the newest Spring Data JPA by creating it in start.spring.io with a settings as below:
![Zrzut ekranu 2023-11-19 141028](https://github.com/spring-projects/spring-data-jpa/assets/32438274/3c941f05-dbd9-45c2-bcad-94d7567adc79)
![Zrzut ekranu 2023-11-19 143317](https://github.com/spring-projects/spring-data-jpa/assets/32438274/b1852fce-90e3-425d-8e18-1df99d6d85f7)
I didn't change anything in the project and, when I'm trying to run it, I have following error:
```

Unsupported Java. 
Your build is currently configured to use Java 21.0.1 and Gradle 8.4.

Possible solution:
 - Use Java 20 as Gradle JVM: Open Gradle settings 
 - Open Gradle wrapper settings, change `distributionUrl` property to use compatible Gradle version and reload the project
```

Remove dependency 'org.springframework.boot:spring-boot-starter-data-jpa' resolves this problem and project compiles and runs. Also after downgrade Java version from 21 to 17 this problem went away. Is Java 21 supported in JPA for a Spring Boot 3.2.0?

**Comment by mp911de** [comment]
`start.spring.io` is setting up your build environment. Please file the ticket at https://github.com/spring-io/initializr/issues.
