### ISSUE TITLE
Redundant parameter in the Limit query

### ISSUE THREAD

**Issue by sergey-morenets** [spring-projects/spring-data-jpa#3242]
Hi

Spring Data JPA introduced new Limit functionality to provide dynamic limiting. So if earlier we wrote the following query:

```
	List<Product> findTop3By();
	
	List<Product> findFirst3By();
```

and now we can use new approach:

`	List<Product> findBy(Limit limit);`

But I noticed that resulting SQL in the first two queries was :

`SELECT * from Product p1_0 fetch first ? rows only`

And now it's:

`SELECT * from Product p1_0 offset ? rows fetch first ? rows only`

So why do we need additional parameter offset? I guess it's redundant and not needed here.

**Comment by mp911de** [comment]
This is because we convert by default `Limit` into `Pageable(0, limit)` and set the `Query.setFirstResult(…)` value implicitly.

Actually, Hibernate could omit that value as not setting the offset and setting offset zero should yield the same result.

**Comment by quaff** [comment]
I will try to fix it at hibernate side.

**Comment by quaff** [comment]
I've created https://github.com/hibernate/hibernate-orm/pull/7579 to fix this.

**Comment by sergey-morenets** [comment]
> I've created [hibernate/hibernate-orm#7579](https://github.com/hibernate/hibernate-orm/pull/7579) to fix this.

Thank you, @quaff

**Comment by quaff** [comment]
> > I've created [hibernate/hibernate-orm#7579](https://github.com/hibernate/hibernate-orm/pull/7579) to fix this.
> 
> Thank you, @quaff

FYI, Hibernate team decline that.
