### ISSUE TITLE
vesion 3.0.10

### ISSUE THREAD

**Issue by HXinPeng** [spring-projects/spring-data-jpa#3243]
I have identified the problem in more detail: When using Spring Data JPA, after adding the @OneToMany annotation to the entity, the address of the List parameter in the retrieved entity becomes PersistentBag. unable to resolve the issue with using Dubbo in collaboration .Is there any way to resolve this?

errMsg：Decode rpc result failed: org.apache.dubbo.common.serialize.SerializationException: com.alibaba.fastjson2.JSONException: autoType not support input org.hibernate.collection.spi.PersistentBag,

**Comment by christophstrobl** [comment]
How is Spring Data JPA involved here? 
This looks like the [fastjson2#2032](https://github.com/alibaba/fastjson2/issues/2032) problem you already reported.
