### ISSUE TITLE
Page<T> findAll Method, Why run a data query first?

### ISSUE THREAD

**Issue by CHOICORE** [spring-projects/spring-data-jpa#3251]
Dear Spring Developers,

I'm asking because I can't find any related data. I'm sorry.

It's a shameful question.

why does return type Page<T>  run a data query first?

by executing the count query first,

It can determine the total number of records that match the criteria. 

If the count is zero, it may prevent the unnecessary execution of the data retrieval query, optimizing database resources 
and response time.

==========================================================================================
After asking the question, I thought about it more, but if the maxResults is less than the requested number, is it advantageous to calculate it yourself and send less count queries?

**Comment by schauder** [comment]
> After asking the question, I thought about it more, but if the maxResults is less than the requested number, is it advantageous to calculate it yourself and send less count queries?

This is what we do.
