### ISSUE TITLE
SELECT ... WHERE ... IN no longer working as of JPA 3.2.x

### ISSUE THREAD

**Issue by thecatwhisperer** [spring-projects/spring-data-jpa#3256]
In Spring 3.1.5 (and prior) the following query resulted in expected data:
```
@Query("select distinct s from Staff s where upper(s.name) in " +
            "(select distinct upper(t.manager) from Staff t where t.manager <> null)")
```

The query should return a certain number of results depending on the data submitted.  For pre 3.2.0 it returns say.. 7.. after.. 0.

**UPDATED**

3.1.5 generated query:
```
select distinct s1_0.id,s1_0.department,s1_0.division,s1_0.email_address,s1_0.location,s1_0.manager,s1_0.manager_email_address,s1_0.name,s1_0.senior_manager,s1_0.senior_manager_email_address,s1_0.start_date,s1_0.status,s1_0.title from staff s1_0 where upper(s1_0.name) in(select distinct upper(s2_0.manager) from staff s2_0 where s2_0.manager is not null)
```

3.2.0 generated query:
```
select distinct s1_0.id,s1_0.department,s1_0.division,s1_0.email_address,s1_0.location,s1_0.manager,s1_0.manager_email_address,s1_0.name,s1_0.senior_manager,s1_0.senior_manager_email_address,s1_0.start_date,s1_0.status,s1_0.title from staff s1_0 where upper(s1_0.name) in (select distinct upper(s2_0.manager) from staff s2_0 where s2_0.manager!=null)
```

The genrate SQL is slightly different...

As of 3.2.0, the query now shows no results.  There is no error that I can see (enabled debug logging at `org.springframework.data`)

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by thecatwhisperer** [comment]
@mp911de -- updated teh generated SQL.. as you can see there is a difference between the two.. in the last part it switched from `is not null` to `!=null`

**Comment by mp911de** [comment]
Thanks a lot. Spring Data JPA is not in the business of generating SQL queries, Hibernate is.

It could well be that our JPQL parser interferes `<>` with `!=` vs. `IS NOT`.

What happens if you downgrade to Hibernate 6.2?

**Comment by thecatwhisperer** [comment]
Hi @mp911de -- downgrading Hibernate to `6.2.13.Final` (the version in Spring 3.1.5) solves the issue, but is not ideal?  Obviously we don't want to stay on a n older version of hibernate.  Should I raise a bug with Hibernate?

**Comment by thecatwhisperer** [comment]
I also tried upgrading Hibernate ORM to `6.3.2.Final` but that has the same issue.

**Comment by mp911de** [comment]
> Should I raise a bug with Hibernate?

Yes, please.

**Comment by thecatwhisperer** [comment]
@mp911de -- created https://hibernate.atlassian.net/browse/HHH-17513
