### ISSUE TITLE
EmbeddedId query sql change

### ISSUE THREAD

**Issue by skyfour** [spring-projects/spring-data-jpa#3261]
i upgrade spring boot from 2.7.5 to 3.1.5,now i have a issue.i use jpa CrudRepository function findById.now query sql change,
from equals to in.
entity id use EmbeddedId

`select
        applicatio0_.unique_type as unique_t1_8_0_,
        applicatio0_.unique_value as unique_v2_8_0_,
        applicatio0_.entity_id as entity_i3_8_0_ 
    from
        app applicatio0_ 
    where
        applicatio0_.unique_type=? 
        and applicatio0_.unique_value=?`

`select
        a1_0.unique_type,
        a1_0.unique_value,
        a1_0.entity_id 
    from
        app a1_0 
    where
        (
            a1_0.unique_type,a1_0.unique_value
        ) in ((?,?))`
i want konw why?

**Comment by mp911de** [comment]
Hibernate is in the business of generating SQL. Have you tried running the same query via the EntityManager to inspect the SQL between Hibernate 5.6 and 6.2?

**Comment by skyfour** [comment]
> Hibernate is in the business of generating SQL. Have you tried running the same query via the EntityManager to inspect the SQL between Hibernate 5.6 and 6.2?
![image](https://github.com/spring-projects/spring-data-jpa/assets/25677237/056a55c2-2113-4ec9-9028-93cb4b7ed48b)

i use the same code, select sql still the same as above.
this is 6.2

**Comment by schauder** [comment]
So this is a change the Hibernate team introduced. I don't think the Spring Data team can do anything about this. Please ask the Hibernate team for clarification. If you create a ticket with them a link to that ticket here would be appreciated
