### ISSUE TITLE
JPA Query misinterpreted for concat and substring functions

### ISSUE THREAD

**Issue by hbellahc** [spring-projects/spring-data-jpa#3265]
I have two simple entities :  

```
@Entity
public class AccountGroup {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private Integer customerId;
}
```
And 

```
@Entity 
public class Account {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String complementaryKey;
    private Integer company;
    private Integer customerId;
}
```

For conception reason (old tables and used every where), I need to implement a request like this in my AccountGroupRepository interface : 

```
  @Query("select ag " +
            "from AccountGroup ag join Account a on ag.customerId = a.customerId " +
            "where ag.name like ?1 " +
            "and  concat(a.company, concat('.', substring(a.complementaryKey, 1,2) ) ) in (?2) ")
    List<AccountGroup> search(String name, List<String> agencies);
```

With h2 as a database it's OK 
With db2 as a database it's KO since SpringBoot 3.1

When it's KO, here is the Error message : 

> ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper-150] [SQL0104] Elément syntaxique CODEUNITS32 n'est pas correct. Eléments possibles : OCTETS

The sql displayed it looks like this 

```
select distinct ag.id, ag.name
from AccountGroup ag join account a on ag.customerId =a.customerId  
where upper(ag.name) like upper(cast(cast(? as varchar(32672))||'%' as varchar(32672)))
and cast(cast(a.company as varchar(32672))||cast('.'||substring(a.complementaryKey,1,2,codeunits32) as varchar(32672)) as varchar(32672)) in (?,?,?,?,?)
```

**Comment by mp911de** [comment]
Which Spring Data JPA version are you using? We no longer use the `CONCAT` mechanism since Spring Data JPA 3.1.4.

**Comment by hbellahc** [comment]
@mp911de I'm using SpringBoot 3.2.0

**Comment by mp911de** [comment]
Your previous comment says Boot 3.1 and specifically the bugfix version is relevant

> With db2 as a database it's KO since SpringBoot 3.1

In any case, Spring Data isn't in the business of generating SQL. Please check whether running the query via `EntityManager` behaves the same. If so, please file a ticket at the Hibernate issue tracker.
