### ISSUE TITLE
Count query derivation from DISTINCT queries seems to be broken

### ISSUE THREAD

**Issue by da-z** [spring-projects/spring-data-jpa#3269]
I have a large chunk of JPA code that was working fine in Spring Boot 2.x but not in Spring Boot 3.x (Hibernate 6 on Oracle and H2 in Oracle mode in tests):

Sample JPQL query:
```sql
SELECT DISTINCT abc AS x FROM T -- (note the AS alias)
```

In SB 3.x I am getting the error: `At 1:n and token 'AS', no viable alternative at input 'SELECT count(DISTINCT abc *AS x`

And indeed, that's not a valid SQL query because aliases are not allowed in that scenario.

My take on this is: either strip the alias, or derive the Count query like this, which means you don't need to mess with the original query:

```sql
SELECT COUNT(*) FROM ({original_sql}) -- I assume this is how it is working in SB 2.x
```

**Comment by christophstrobl** [comment]
Thanks for reporting, sounds like you already have a test that you could share to help us diagnose the issue. Would you mind taking the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem?

**Comment by da-z** [comment]
Sure: https://github.com/da-z/spring-data-jpa-issue-3269 (just run the test)

**Comment by gtiburcio** [comment]
I'm having the same problem here.

**Comment by christophstrobl** [comment]
We're working on a solution. Early snapshots (branch builds) should be available soon.

**Comment by da-z** [comment]
Hello. Will this fix be merged into main?

**Comment by THD-Thomas-Lang** [comment]
I have the same problem and i could it solve by using a dedicated `countQuery()` in addition to your `@Query()`. So kind of this way:`@Query("SELECT DISTINCT abc AS x FROM T", countQuery="select count(*) FROM T")`

**Comment by da-z** [comment]
@THD-Thomas-Lang The regression has already been fixed. All we need is more upvoters for this PR to be merged.

**Comment by THD-Thomas-Lang** [comment]
Didn´t know that there is an upvote function? Thank you!

**Comment by da-z** [comment]
There is no upvote function but you can leave a comment or react to one of the existing comments.
