### ISSUE TITLE
3.2.0 Bug or feature? BeanCreationException JpaRepository findBy id extended Serializable exception

### ISSUE THREAD

**Issue by Mrakobec** [spring-projects/spring-data-jpa#3272]
If I have Entity extended from org.springframework.data.jpa.domain.AbstractPersistable<PK extends Serializable> and realize that entity like 
`
@Entity
@Table
public class ExampleEntity extends AbstractPersistable<UUID>{}`
then create interface repository 

```
public interface ExampleEntity Repository extends JpaRepository<ExampleEntity , UUID> {
    ExampleEntity findAllById(UUID entityId);
}
```

i will get BeanCreationException.  Cannot compare left expression of type 'java.io.Serializable' with right expression of type 'java.util.UUID'
I can fix it with chane UUID to Serializable like that
```
public interface ExampleEntity Repository extends JpaRepository<ExampleEntity , UUID> {
    ExampleEntity findAllById(Serializable entityId);
}
```
But when i create request with pagination everything is ok
```
public interface ExampleEntity Repository extends JpaRepository<ExampleEntity , UUID> {
    Page<ExampleEntity> findAllById(PageRequest pageRequest, UUID entityId);
}
```
On version 3.1.1 I don't have any problems with that. I start migration and got that exceptions. Is that normal behavior now?

**Comment by Mrakobec** [comment]
I founded it on methods with id of param Entities like
` @Entity @Table public class ExampleEntity1 extends AbstractPersistable<UUID>{}`
` @Entity @Table public class ExampleEntity2 extends AbstractPersistable<UUID>{ @ManyToOne ExampleEntity1 exampleEntity1}`

and repo like
```
public interface ExampleEntity2 Repository extends JpaRepository<ExampleEntity , UUID> {
    List<ExampleEntity2> findAllByExampleEntity1_Id(UUID entityId);
}
```

**Comment by quaff** [comment]
You should prepare [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) instead of code snippet.

**Comment by Mrakobec** [comment]
What? That is example and all what do u needed. Here is 1 or 2 Entitys and 1 repository, what do u need?
springframework.boot - 3.2.0
dependencies - org.springframework.boot:spring-boot-starter-data-jpa

**Comment by Mrakobec** [comment]
Idk why do u need it, but here it is [example.zip](https://github.com/spring-projects/spring-data-jpa/files/13727496/example.zip)

**Comment by christophstrobl** [comment]
@Mrakobec thank you for the reproducer - we'll have a look.

**Comment by quaff** [comment]
I confirm it works fine with Spring Boot 3.2.1-SNAPSHOT, I believe it's fixed by https://github.com/spring-projects/spring-data-jpa/commit/94da1837d45dc86064fd10c220d04a09952fbb32.
