### ISSUE TITLE
Spring Data JPA 3.x.x bug after migration from 2.8.x

### ISSUE THREAD

**Issue by mikebgrep** [spring-projects/spring-data-jpa#3292]
I am concerned that there is a bug in Spring Data JPA 3.2.x. I migrate from 2.8.x and I am encounter problems with one of the repositories for Users of my application. When I call JPA, the repository save() method with entity email and password are not written into the database.

I have the following test that fails with custom exception: ```com.intuitionlabs.app.exception.ResourceNotFoundException: Customer with that email test@email.com does not exists```. The case is there are no exceptions when I test it manual, just the data is not saved into the database.

```
@Test
    void verifyFindByEmail() {
        Customer customer = Customer.builder().email("test@email.com").build();
        Customer expected = repository.save(customer);
        Customer actual = service.findByEmail("test@email.com");

        assertEquals(expected.getId(), actual.getId());
        assertEquals(expected.getEmail(), actual.getEmail());
    }
```

Version of Spring boot is:
```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.2.1</version>
		<relativePath/>
	</parent>
```

Repository :
```
@Repository
public interface CustomerRepository extends JpaRepository <Customer, Long> {

    Optional<Customer> findByEmail(String email);

}
```
Service:
```
public interface CustomerService {

    Customer save(Customer customer);
}
```

Service Implementation:
```
@Service
public class CustomerServiceImpl implements CustomerService {

    private final CustomerRepository repository;

    public CustomerServiceImpl(CustomerRepository repository) {
        this.repository = repository;
    }

    @Override
    public Customer save(Customer customer) {
        return repository.save(customer);
    }
```

https://github.com/mikebgrep/simple-spring-boot-application-reproduction

This is a reproduction demo project that  reproduces the issue you can use and H2 databse.
You can run the tests and see that the repository didn't save the entity username and password. 
Is not reproducible with entity that does not extend the base abstract User class.
Regards.

**Comment by christophstrobl** [comment]
Thank you for reporting and the sample project. The issue does not seem to be related to the `select` but happens earlier on `insert`.

The log files clearly show that the email column is not populated with the value used in the test.
```
Hibernate: select next value for user_seq
Hibernate: insert into customers (email,password,role,created_at,first_name,last_name,updated_at,id) values (?,?,?,?,?,?,?,?)
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (1:VARCHAR) <- [null]
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (2:VARCHAR) <- [null]
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (3:TINYINT) <- [null]
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (4:TIMESTAMP) <- [null]
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (5:VARCHAR) <- [null]
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (6:VARCHAR) <- [null]
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (7:TIMESTAMP) <- [null]
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (8:BIGINT) <- [1]
``` 
The select itself appears to be as expected
```
Hibernate: select c1_0.id,c1_0.email,c1_0.password,c1_0.role,c1_0.created_at,c1_0.first_name,c1_0.last_name,c1_0.updated_at from customers c1_0 where c1_0.email=?
TRACE 95758 --- [main] org.hibernate.orm.jdbc.bind: binding parameter (1:VARCHAR) <- [test@email.com]
```

The same behaviour can be reproduced with plain hibernate and the criteria API which makes me think this should be better reported with the hibernate team.

**Comment by mp911de** [comment]
Check out https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/?filter=allissues
