### ISSUE TITLE
I have a question contributing

### ISSUE THREAD

**Issue by sami355-24** [spring-projects/spring-data-jpa#3298]
Hello, in the past, I posted an issue because I had a question about the exists + all keyword.
Below are the relevant issues.
https://github.com/spring-projects/spring-data-jpa/issues/3122

At that time, after learning that the features I wanted were not provided, I implemented the logic I wanted with JPQL. But after time, I suddenly remembered the past and wanted to implement features like existAll.

So, I want to implement the functions I want to do a contributing myself, is that okay?
The contributing guide says to talk first through issues or discursions, so I post the issue like this.

**Comment by sami355-24** [comment]
Thank you for your help.
Perhaps I don't have any practical experience yet, so I've raised the issue without knowing the usefulness of the function.

**Comment by mp911de** [comment]
No worries, we're here to provide guidance. As your question is now answered, I'm closing the ticket.
