### ISSUE TITLE
Allow Supertypes Specifications in JpaSpecificationExecutor 

### ISSUE THREAD

**Issue by aykborstelmann** [spring-projects/spring-data-jpa#3300]
See the following commit: https://github.com/spring-projects/spring-data-jpa/commit/4c4512578ebe6333cc7c388e8533e11c7e0a396f
I added a test in your codebase which is exactly the same as I am going to describe. 

Suppose we have an abstract `@MappedSupperclass` `AbstractMappedType` and a concrete entity `ConcreteType1` extending `AbstractMappedType`. 

Then we also have `MappedTypeRepository` which is a `@NoRepositoryBean` but does extend `JpaSpecificationExecutor` and must therefore look like this: 

```java
@NoRepositoryBean
public interface MappedTypeRepository<T extends AbstractMappedType> extends JpaRepository<T, Long>, JpaSpecificationExecutor<T> {
}
``` 

However when using this repository in its abstract form, we face some issues. 

```java 
@Autowired
@Qualifier("concreteRepository1")
private MappedTypeRepository<?> mappedTypeRepository;

@Test
void testUseMappedTypeRepository() {
  concreteRepository1.save(new ConcreteType1("Test"));

  List<? extends AbstractMappedType> findings = mappedTypeRepository.findAll(
      where(mappedTypeAttribute1Equals("Test")));
  assertThat(findings).isNotEmpty();
}

private static Specification<AbstractMappedType> mappedTypeAttribute1Equals(String attribute1) {
  return (root, query, criteriaBuilder) -> criteriaBuilder.equal(root.get(AbstractMappedType_.ATTRIBUTE1), attribute1);
}
```

This does not work because `Specification<AbstractMappedType>` cannot be applied as first parameter for 
`List<T> findAll(Specification<T> spec);` of `JpaSpecificationExecutor<T>`.

IMO, the method `JpaSpecificationExecutor#findAll` should be defined as follows, accepting also specifications of supertypes of `T`. 
```java
List<T> findAll(Specification<? super T> spec); 
``` 

In fact, I have already implemented change, and you can have a look at #3301

**Comment by christophstrobl** [comment]
@aykborstelmann thank you for getting in touch. Let me take this to the team.

**Comment by aykborstelmann** [comment]
@christophstrobl Thanks for taking care. Any updates on this ?

**Comment by aykborstelmann** [comment]
Hi, once again, any updates on it ? 
I already provided you an PR (#3301) which implements the change :)

**Comment by mp911de** [comment]
For the time being, this looks like a wall of changes without providing an immediate benefit. As we don't have much bandwidth, this isn't something we will incorporate soon. We might revisit your proposal next year or so.

**Comment by aykborstelmann** [comment]
Alright, thank you for the answer! 

I hope I could motivate the benefits enough with the given example and test, if not please let me know !
Currently any usage of `JpaSpecificationExecutor` in a generic repository have to be faced with hacky solutions such as wildcards in returns types and unchecked castings. I have faced this issue in many projects until now. 
Hopefully the passing tests can somehow ensure you valid working state of the PR. 

I am looking forward to a diskussion then :)

**Comment by mp911de** [comment]
We discussed the issue within our team and we don't want to update our code to consider type hierarchy changes across specifications.
