### ISSUE TITLE
Docs for 2.7.18 missing (404)

### ISSUE THREAD

**Issue by eidottermihi** [spring-projects/spring-data-jpa#3302]
<https://docs.spring.io/spring-data/jpa/docs/2.7.18/reference/html/> gives a 404 Not Found.

This link is used on <https://spring.io/projects/spring-data-jpa/#learn> :
![grafik](https://github.com/spring-projects/spring-data-jpa/assets/2780736/191eeb35-e7f8-419e-bbac-ba7b183ae110)

**Comment by mp911de** [comment]
Thanks for letting us know. That's fixed now.
