### ISSUE TITLE
Inject Repository into Custom Repository instance cause circular reference

### ISSUE THREAD

**Issue by devholic22** [spring-projects/spring-data-jpa#3320]
First, I checked about two issue: #2384 , and [this](https://github.com/spring-projects/spring-data-commons/issues/2319).

but I solve this problem by another way, I don't know why this way solved problem.

could I know Spring data JPA internal principle?

this is my example code.

* <package 'domain'>
  * Board.java
  * BoardRepository.java
* <package 'infrastructure'>
  * BoardJpaRepository.java
  * BoardJpaRepositoryImpl.java

With:
```java
public interface BoardRepository {

    Long save(final Board board);
    ...
}
```
```java
public interface BoardJpaRepository extends JpaRepository<Board, Long> {
}
```
```java
@Repository
@RequiredArgsConstructor
public class BoardJpaRepositoryImpl implements BoardRepository {

    private final BoardJpaRepository boardJpaRepository;

    @Override
    public Long save(final Board board) {
        boardJpaRepository.save(board);
        ...
    }
}
```

Error:
```java
┌─────┐
|  boardJpaRepositoryImpl defined in file [..../board/infrastructure/BoardJpaRepositoryImpl.class]
└─────┘
```

My Solution:
Instead use `boardJpaRepositoryImpl`, use `boardRepositoryImpl` (or `jpaBoardRepositoryImpl`). it worked to solve problem. 

(I wanted to create repository implementations, both with and without using JPA. That's why I didn't use the name BoardRepositoryImpl. Instead, I intended to use BoardJpaRepositoryImpl to signify an implementation using JPA. I'm curious if there are any rules against using the combination of a Spring Data JPA interface and its corresponding `impl` class in situations like this.)

additionally, I tried to search spring data jpa documentation, and I knew about `repositoryImplementationPostfix`. Is there any connection with this?

thanks to check this issue, and I apologize if this problem too much similar previous issues.

**Comment by mp911de** [comment]
You cannot inject a repository facade into its own repository fragment as this creates a circular dependency. You could make the repository `@Lazy` or inject an `ObjectProvider< BoardJpaRepository>` to defer object resolution to a time after the objects are constructed.
