### ISSUE TITLE
Using native basic sql queries for pagination is slow, and automatic count query generation for a basic native SQL query is failing.

### ISSUE THREAD

**Issue by pranav-hsg** [spring-projects/spring-data-jpa#3324]
### Problem Definition

If the countQuery is not provided in the @Query annotation for a basic native SQL query, the generated count query in Spring Data JPA is incorrect. This issue adversely affects paginated queries, where the accurate count query is essential for calculating total results. Currently, the count query is not being generated correctly, leading to significant performance problems. Execution times surpass 20 seconds for datasets with over 600,000 rows.

### Investigation Results

Upon enabling hibernate.show_sql for investigation, it becomes evident that the count query is not being generated correctly. The issue is illustrated in the image below, where the 'select *' query is executed, contributing to the problem.

<img width="494" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/65011770/40969d94-af30-492d-9e73-4abbd9ddb6b0">

### Environment 
Java : 21
Spring Data JPA version: 3.2.2 
Database: MySQL

### Steps to Reproduce

1. Use a basic native SQL query in a Spring Data JPA repository, for example:
``` java
   @Query(value = "select * from users", nativeQuery = true)
   Page<Object> getAllUsers(Pageable pageable);
```

**Comment by christophstrobl** [comment]
@pranav-hsg thanks for reporting an the PR. We'll look into it.

**Comment by pranav-hsg** [comment]
Thanks for the reply, This is happening especially when the alias is not provided in the SQL query. Happy to contribute!
