### ISSUE TITLE
A signed numeric literal in JPQL, a space will be inserted between the sign and the numeric literal after parsing

### ISSUE THREAD

**Issue by hgwr** [spring-projects/spring-data-jpa#3342]
If you use a signed numeric literal in JPQL, a space will be inserted between the sign and the numeric literal after parsing, resulting in a syntax error.

## Reproduction environment

````
$ java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
````

````
dependencies {
   implementation 'org.springframework.data:spring-data-jpa:3.2.3-SNAPSHOT'
}
````

## How to reproduce

You can reproduce it by running the Spring Boot web application from the https://github.com/hgwr/try-negative-one repository.

The JPQL query `SELECT m FROM Memo m WHERE m.categoryId = -1` is used in the application. If you call it like `curl "http://127.0.0.1:8080/memo/category/negative-one"`, you will get the following exception.

````
ERROR 86400 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.dao.InvalidDataAccessApiUsageException: An exception occurred while creating a query in EntityManager: 
Exception Description: Syntax error parsing [SELECT m FROM Memo m WHERE m.categoryId = - 1]. 
[27, 45] The expression is not a valid conditional expression.] with root cause

org.eclipse.persistence.exceptions.JPQLException: 
Exception Description: Syntax error parsing [SELECT m FROM Memo m WHERE m.categoryId = - 1]. 
[27, 45] The expression is not a valid conditional expression.
        at org.eclipse.persistence.internal.jpa.jpql.HermesParser.buildException(HermesParser.java:159) ~[org.eclipse.persistence.core-4.0.2.jar!/:na]
````

As shown in the exception error message, `WHERE m.categoryId = -1` is parsed to include a space between the sign and the numeric literal, such as `WHERE m.categoryId = - 1` .

## Suggestions for solutions

Pull Request https://github.com/spring-projects/spring-data-jpa/pull/3343

In the process of adding the sign token below, we suggest suppressing the addition of spaces by setting false to the second argument of the constructor JpaQueryParsingToken.

https://github.com/spring-projects/spring-data-jpa/blob/57d0b11a34c084bac95b238fbefd0af56a4a7d7f/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/HqlQueryRenderer.java#L1292

**Comment by christophstrobl** [comment]
@hgwr thanks for raising the issue and taking the time to craft the PR!

**Comment by christophstrobl** [comment]
The problem is also present for signed expressions like `-count(u)`. We'll fix that as well.
