### ISSUE TITLE
JPA Save do not return updated Object when the primary Id is not Auto Generated

### ISSUE THREAD

**Issue by assemble-code** [spring-projects/spring-data-jpa#3344]
When `jpaRepositoyr.Save(someObject)` is called and `someObject` contains an `Id` that is not auto generate/manually provided  then the the object returned  by `Save()` does not reflect the auto generated database column value.

#### Minimum reproducible code.
- Entity
```kotlin

@Entity
@Table(name = "reset_password")
data class ResetPasswordDAO(
    @Id val emailId: String,
    val resetToken: String,
    @Column(insertable = false, updatable = false) var createdAt:Instant=Instant.MIN ,
)
```
- service method

``` kotlin

fun resetPassword(restPasswordRequest: ResetPasswordRequest) {
            val token = //random token
            val resetPasswordDAO =
                ResetPasswordDAO(
                    restPasswordRequest.emailId,
                    token)
                

        val savedObject      resetPasswordRepository.save(resetPasswordDAO)

        logger.info("reset token created for customer {} at {}", restPasswordRequest.emailId,  savedObject.createdAt))

        val fetchedObject =  resetPasswordRepository.getResetPasswordDAOByEmailId(restPasswordRequest.emailId)

          
        logger.info("reset token created for customer {} at {}", restPasswordRequest.emailId,  fetchedObject.createdAt)
     }
```
here the `createdAt` is autogenerated in the database, as per the documentation if my understanding is correct then the object returned by `save()` should contain value from database, but it contains the default value of `Instant`.

Even when I tried fetching the object after the save the object do not contain the value form the database.

**Comment by quaff** [comment]
I don't think `entityManager.persist(entity)` will know that field is generated by database.


> Even when I tried fetching the object after the save the object do not contain the value form the database.

You should call `entityManager.detach(entity)` or `entityManager.refresh(entity)` first.

**Comment by assemble-code** [comment]
1. shouldn't the data be flushed after the `save` is called as it is in transactional block.
2. I tried `entityManager.detach(savedEntity)`  and it worked,
3.  but one thing i am not able to wrap head around is that even if the `save` is transactional, `findBy..` called after save returns older data and it was suppose to be read committed  as per my current understanding .


Sorry if questions are naive @quaff

**Comment by quaff** [comment]
> 1. I tried `entityManager.detach(savedEntity)`  and it worked,
> 2. but one thing i am not able to wrap head around is that even if the `save` is transactional  and entity is committed then the `entity` in `entityManager` is detached   , then `findBy..` should not return older data as it shows selecte query being fired so it should get the new value as per my current understanding .
> 3. if the save or any method that can modify the value of db is called, shouldn't data be fetched from the database rather than using the persistent cache, As Save might have caused some fields to modified as result of db trigger or auto generated column, etc.
> 
> Sorry if questions are naive @quaff

If your `findBy...` and `save` are in the same transaction, it will try to load entity from persistent context not database, if they are not in the same transaction but second level cache is enabled, it will try to load entity from cache not database.

**Comment by mp911de** [comment]
Closing this one as the save method behaves as designed along with JPA attached entity semantics. Any specifics that concern database-generated activity, flushing are out of our control as we use `EntityManager.persist(…)` in the regular case.
