### ISSUE TITLE
Example in docs missing @NonNullApi annotation

### ISSUE THREAD

**Issue by robin-a-meade** [spring-projects/spring-data-jpa#3345]
The code block labeled _Using different nullability constraints_ on https://docs.spring.io/spring-data/jpa/reference/repositories/null-handling.html should have a `@NonNullApi` annotation directly above the package declaration.

Otherwise, the descriptions of the callouts don't make sense, and the use of the two `@Nullable` annotations are superfluous because nullable is the default behavior.

**Comment by mp911de** [comment]
`@NonNullApi` is applied on the package level via `package-info.java` (see also `@Target({ElementType.PACKAGE})`). Adding `@NonNullApi` to each Java file in a package would create redundancy otherwise and wouldn't be a clean programming model.
