### ISSUE TITLE
Limit selection of nested properties

### ISSUE THREAD

**Issue by scordio** [spring-projects/spring-data-jpa#3352]
I'm not sure if I should report this in `spring-data-jpa` or `spring-data-commons`. I apologize in advance if this isn't the right place.

I experienced the following issue on Spring Data JPA with Hibernate, initially with Spring Boot 2.7.14 and Db2 for z/OS, but also reproduced with the latest Spring Boot (both GA and snapshot) and H2.

In the _Interface-based Projections_ section of both the [Spring Data JPA](https://docs.spring.io/spring-data/jpa/reference/repositories/projections.html#projections.interfaces) and [Spring Data Commons](https://docs.spring.io/spring-data/commons/reference/repositories/projections.html#projections.interfaces) reference guides, there is an example on how to use such projections recursively:

```java
interface PersonSummary {

  String getFirstname();
  String getLastname();
  AddressSummary getAddress();

  interface AddressSummary {
    String getCity();
  }
}
```

If I use this interface in a repository, like:

```java
interface PersonRepository extends Repository<Person, UUID> {

  Collection<PersonSummary> findPersonSummaryByLastname(String lastname);
}
```

The following query is executed:

```sql
select p1_0.firstname,p1_0.lastname,p1_0.city,p1_0.street,p1_0.zip_code from person p1_0 where p1_0.lastname=?
```

where `street` and `zip_code` are also selected although they are not required.

This seems to contradict what is mentioned in the _Closed Projections_ section:

> If you use a closed projection, Spring Data can optimize the query execution, because we know about all the attributes that are needed to back the projection proxy.

As a workaround, if I remove the nested interface in `PersonSummary` and concatenate the property names:

```java
interface PersonSummaryNoNested {

  String getFirstname();

  String getLastname();

  String getAddressCity();
}
```

the following query is executed:

```sql
select p1_0.firstname,p1_0.lastname,p1_0.city from person p1_0 where p1_0.lastname=?
```

Reproducer: [PersonRepositoryTest](https://github.com/scordio/spring-boot-playground/blob/spring-data-jpa-3352-reproducer/src/test/java/io/github/scordio/playground/PersonRepositoryTest.java)

---

Is this a bug or is it by design?

In case the example with the nested interface is not meant to be considered as a closed projection, would it make sense to highlight this detail in the documentation?

**Comment by mp911de** [comment]
Currently, this behavior is by design as we use top-level properties for the selection. We could introspect the projection for nested projections to limit the selection.

For the time being, using inlined, concatenated properties makes sense. We can revisit this enhancement somewhere in the future.

**Comment by scordio** [comment]
Thank you for the feedback, @mp911de! Would you accept a small addition to the docs about it?

Talking with colleagues, I realized this wasn't clear to many of them when looking at the `PersonSummary` example.

**Comment by christian-schlueter** [comment]
Would love to see this revisited in the future - if the nested entity has relationships themselves that are not part of the projection, they will also get queried in separate queries, so this can result in a lot of wasted DB resources.

**Comment by mp911de** [comment]
FWIW, I updated docs with #2757 to explain property limitations.

**Comment by scordio** [comment]
> FWIW, I updated docs with #2757 to explain property limitations.

https://github.com/spring-projects/spring-data-jpa/blob/7f13a04c414ad210e30ef647fda75590e28526cb/src/main/antora/modules/ROOT/pages/repositories/projections.adoc?plain=1#L26-L27

Looks perfect to me. Thanks a lot!

**Comment by mp911de** [comment]
I explored nested element projections. The good news is, that it works for interface projections quite well. There are a few caveats:

* We cannot select a tuple in a multi-select as hibernate forbids that. So we need another carrier for nested object data. 
* So far, I've been successful with using the entity itself as the carrier and populate properties using nested aliases. That works also nicely across multiple hierarchy levels.
* We have to resort to constructor expressions while the instantiated type is populated via properties. I think that's not intended usage, yet it works.
* Partially populating entities is a dangerous path, we've seen with Kotlin that we quickly hit  limits as Kotlin types are properly designed when they are immutable and limit nullability. I do not have an answer to that issue.
* DTO's might be the final boss. We do not control DTO constructors and JPA doesn't have model metadata about a DTO.

That being said, it seems that there might be a way for nested properties decomposition using various roundtrips. I'm just not sure that things will work in all sorts of arrangements.

Given the complexity and uncertainty, I need to consult the team how we want to proceed.

**Comment by scordio** [comment]
> That being said, we decided not to follow up on that topic as we have other features that we want to ship and don't really have the bandwidth (and energy) to convince the Hibernate team that such an endeavor requires.

I totally get it. Even if I were to try, I don't feel like I have the expertise to convince them.

Still, many thanks for looking into it!
