### ISSUE TITLE
Punctuation affects parameter mapping

### ISSUE THREAD

**Issue by qinxi** [spring-projects/spring-data-jpa#3354]
Versions:
spring-data-jpa: 3.2.2

```
@Query(
    value = """
      SELECT oh.*
      FROM orders_history oh
      WHERE oh.user_id = :userId
        AND oh.status = 'PAID'
        AND oh.id != :id
      ORDER BY oh.created_at DESC
      LIMIT :previousCount;
    """,
    nativeQuery = true
  )
```
In this case `previousCount;` is considered as a whole and causes an error.

> Could not locate named parameter [previousCount], expecting one of [previousCount;, id, userId]

**Comment by mp911de** [comment]
Can you provide a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem?
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

We require additional details and it would be good if you'd attach the stack trace as well.

**Comment by qinxi** [comment]
@mp911de  Yeah. Here is the repository key commit: https://github.com/qinxi/jpa-parameter-demo

and the key commit is: https://github.com/qinxi/jpa-parameter-demo/commit/782d255d6779d9bd438bef7b3b9be53070eef53f

**Comment by christophstrobl** [comment]
Thank you very much @qinxi for the reproducer. This seems to be an issue with the persistence provider which considers `;` part of the identifier used for the named parameter. This can be reproduced like this:

```kotlin
val nativeQueryString = """
  SELECT u.*
  FROM users u
  WHERE u.name = :name
  ORDER BY u.id DESC
  LIMIT :previousCount;
"""
val query = entityManager.createNativeQuery(nativeQueryString)
query.setParameter("name", "John");
query.setParameter("previousCount", 2); // use .setParameter("previousCount;", 2); and it will work
```

You may consider reporting this with the hibernate team. It would be great if you'd leave a comment on this ticket with the reference to the hibernate issue.

**Comment by christophstrobl** [comment]
We've also tried to reproduce the issue with other persistence providers and the binding works as expected/fine using EclipseLink.

**Comment by qinxi** [comment]
@christophstrobl Hey, thank you for replay. 
I create a PR to hibernate to fix that. 
https://github.com/hibernate/hibernate-orm/pull/7807
