### ISSUE TITLE
Weird Error about Hibernate Proxy Class Cast Exception

### ISSUE THREAD

**Issue by gunb0s** [spring-projects/spring-data-jpa#3362]
I found some weird behavior of hibernate proxy, when casting.

when using findById of jpa repository,
some time `hibernate proxy` returns and sometime `real entity` returns.

i'm using
```
hibernate-core:6.4.1.Final
spring-data-jpa:3.2.2
```

My entity setting is like below
```java
@Entity
@Table(name = "users")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "dtype")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
public abstract class User {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "user_id")
	private Long id;

	private String name;

	@Column(updatable = false, insertable = false)
	private String dtype;

	public User(String name) {
		this.name = name;
	}
}

@Entity
@Getter
@DiscriminatorValue("S")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class Student extends User {
	@Builder
	public Student(String name) {
		super(name);
	}
}
```

And i did find query
```java
Post post = postRepository.findPostWithLecture(createCommentDto.getPostId()).orElseThrow();
Lecture lecture = post.getBoard().getLecture();
User user = userRepository.findById(createCommentDto.getUserId()).orElseThrow();

if (user.getDtype().equals("E")) {
	lectureRepository.findByIdAndEducator(lecture.getId(), (Educator) user).orElseThrow();
} else {
	enrollmentRepository.findByStudentAndLecture((Student) user, lecture).orElseThrow();
}
```
in above case `userRepository.findById` returns `User$HibernateProxy$byHBV0qu`
but when `useRepository.findById` is executed at the beginning of function, it returns just `User`.

`postRepository.findPostWithLecture` uses JPQL and i guess this is a root cause of weird return of `findById`
this function`s implementation is like below
```java
@Query("select p from Post p join fetch p.board where p.id = :postId")
Optional<Post> findPostWithLecture(Long postId);
```

is this weird return a normal behavior? or bug??

**Comment by mp911de** [comment]
Please provide a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem along with the exception stack trace.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by gunb0s** [comment]
> Please provide a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem along with the exception stack trace. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

i made a test in my repository to reproduce error

https://github.com/gunb0s/improved-eureka/blob/bug/hibernate-proxy/src/test/java/gunb0s/toy/ciazza/test/WeirdProxyBehaviorTest.java

**Comment by christophstrobl** [comment]
Thank you very much for providing the reproducer project. Unfortunately there's not much we can do from a spring data perspective as the issue stems from the underlying persistence provider and can be reproduced with plain JPA as outlined below (using the provided sample for reference). 

```java
Query query = em.createQuery("select p from Post p join fetch p.board where p.id = :postId", Post.class);
query.setParameter("postId", postId);
query.getSingleResult();

User user = em.find(User.class, studentId, Collections.emptyMap()); // <-- class ....user.entity.User$HibernateProxy$ouTchvQE
```

You may want to report the problem to the hibernate team. We'd appreciate it if you could leave a comment with a link to the new issue here.

**Comment by gunb0s** [comment]
> Thank you very much for providing the reproducer project. Unfortunately there's not much we can do from a spring data perspective as the issue stems from the underlying persistence provider and can be reproduced with plain JPA as outlined below (using the provided sample for reference).
> 
> ```java
> Query query = em.createQuery("select p from Post p join fetch p.board where p.id = :postId", Post.class);
> query.setParameter("postId", postId);
> query.getSingleResult();
> 
> User user = em.find(User.class, studentId, Collections.emptyMap()); // <-- class ....user.entity.User$HibernateProxy$ouTchvQE
> ```
> 
> You may want to report the problem to the hibernate team. We'd appreciate it if you could leave a comment with a link to the new issue here.

thank you for sugges pure jpa example, i made a question to zulip of hibernate orm ( hibernate orm github doesn't have issue tab)
https://github.com/spring-projects/spring-data-jpa/issues/3362#issuecomment-1938793833
