### ISSUE TITLE
BUG: from 3.x data-jpa doesn't use lookupQuery() method check @Query when starting

### ISSUE THREAD

**Issue by FULaBUla** [spring-projects/spring-data-jpa#3364]
> This is a correct and valid error message as the args of `BookDto` are `String, String, String, int` while Hibernate wants `int, java.lang.String, java.lang.String, int`.
> Anyways, this is a Hibernate exception message and as this is your schema/your query there's nothing we can do here. You can change the constructor argument, however, to `int`.

_Originally posted by @mp911de in https://github.com/spring-projects/spring-data-jpa/issues/3336#issuecomment-1929733575_
           

But from 2.x you valid it and throw exception about the same code in #3336 when i start the application, and from 3.x you valid this when i use it, or because of different spring-data-jpa code implementation i cannot get this exception when i start the application. The design and logical consistency of the code have changed. I want to know if there are any errors when I start, not test them as I use them.

the lookupQuery method in 2.x can achive it.

**Comment by FULaBUla** [comment]
```java
	/**
	 * Validates the given query for syntactical correctness.
	 *
	 * @param query
	 * @param errorMessage
	 */
	private void validateQuery(String query, String errorMessage, Object... arguments) {

		if (getQueryMethod().isProcedureQuery()) {
			return;
		}

		EntityManager validatingEm = null;

		try {
			validatingEm = getEntityManager().getEntityManagerFactory().createEntityManager();
			validatingEm.createQuery(query);

		} catch (RuntimeException e) {

			// Needed as there's ambiguities in how an invalid query string shall be expressed by the persistence provider
			// https://java.net/projects/jpa-spec/lists/jsr338-experts/archive/2012-07/message/17
			throw new IllegalArgumentException(String.format(errorMessage, arguments), e);

		} finally {

			if (validatingEm != null) {
				validatingEm.close();
			}
		}
	}
```

`validatingEm.createQuery(query); ` this code throws exception in 2.7.18 rather than 3.x when my args' type is not correct.

**Comment by christophstrobl** [comment]
Thank you for filing the issue. The query validation code is still invoked on spring data side. The behaviour change seems to stemm from the underlying JPA implementation which considers the provided query valid when creating it.
The issue can be reproduced with plain JPA. It also does not make a difference if the target domain type is provided to the `createQuery` method. I recommend bringing this topic up with the maintainers of the persistence provider in use.
