### ISSUE TITLE
Jakarta 11: Jakarta Data support

### ISSUE THREAD

**Issue by vbazhmin** [spring-projects/spring-data-jpa#3372]
Greetings !

Recently Jakarta introduced new specification Jakarta Data https://jakarta.ee/specifications/data/1.0/ and it is said to be available in Jakarta 11. 

1) What do you think about it ? 
2) Are there any plans to support it or integrate with it ? For example Spring supports other Jakarta specifications like Jakarta Servlet.

Regards,
Vladimir

**Comment by mp911de** [comment]
We've been in touch with the project and contributed several suggestions to align Jakarta Data with Spring Data's concepts as the initial specification goal was to standardize what people use for many years.

The project's direction has unfortunately turned into a direction that goes against established design practices in Spring Data with several conflicting concepts and we're no longer interested in adopting the current specification state. Strong voices argue for a more annotation-driven declaration of query methods that are not compatible with how Spring Data works.

That being said, I do not see us adopting that specification. Also, it is currently not clear to us what tangible benefit such a standard provides if it deviates from standardizing what's out there for years.
