### ISSUE TITLE
org.hibernate.query.SemanticException - hibernate 6.3 - spring boot 3.2

### ISSUE THREAD

**Issue by amirensit** [spring-projects/spring-data-jpa#3376]
Hello.
I am migrating to latest version of spring boot (3.2).
As I know it is supposed to support hibernate 6.3.

I am getting this error with a native jpa query.
`Caused by: org.hibernate.query.SemanticException: Cannot compare left expression of type 'first type' with right expression of type 'second type`.

I think it is fixed in hibernate 6.4.

I tried  forcing hibernate 6.4 with spring boot 3.2,
I tried also fallback to spring boot 3.1.8 and hibernate 6.1, but none did work.

Any suggestion please ?

**Comment by christophstrobl** [comment]
Spring Boot `3.2.2` uses hibernate `6.4.1.Final`.

If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by amirensit** [comment]
^^
Of course, just i am using my phone.
I will give some code examples.

**Comment by amirensit** [comment]
Here is code snippets
```
@Query("SELECT" +
        " indemniteDota " +
        "FROM IndemniteDota AS indemniteDota " +
        "WHERE indemniteDota.avisId = :avisId " + // <<< the error 
        "AND NOT EXISTS ( " +
        other_query_here
        ") ")
    List<IndemniteDota> findAllIndemnitesDotaThatDoesNotHaveLimiteResponsabiliteContestation(@Param("avisId") Long avisId);
```

```
@Entity
@Table(name = "t_indemnites_dota_ido")
@PrimaryKeyJoinColumn(name = "id")
@Getter
@SuperBuilder(toBuilder = true)
@AllArgsConstructor
@NoArgsConstructor
public class IndemniteDota extends Indemnite implements Serializable {
...
}
```

```
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@Table(name = "t_indemnites_ind")
@SuperBuilder(toBuilder = true)
@Getter
@AllArgsConstructor
@NoArgsConstructor
public class Indemnite implements Serializable {

    @Id
    @Column(name = "id", nullable = false)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequenceIndemnite")
    @SequenceGenerator(name = "sequenceIndemnite", sequenceName = "t_indemnites_ind_id_seq")
    private long id;
    ....
    }
```

@christophstrobl  Is that sufficient to reproduce ?

**Comment by Herzenkin** [comment]
hi @christophstrobl!

Seems like its is related to SpringBoot/SpringData + Hibernate integration issue:
https://hibernate.atlassian.net/browse/HHH-17595

I face the very similar problem when started upgrading to SB 3.2.2 from 2.7.5

**Comment by amirensit** [comment]
Solved [here](https://stackoverflow.com/questions/78026045/spring-data-jpa-3-1-4-hibernate-6-1-6-final-validation-failed-for-query-for).

**Comment by christophstrobl** [comment]
@amirensit sorry, but no. Could you please provide a complete sample. Thank you.
