### ISSUE TITLE
Page's content  type isn't correct

### ISSUE THREAD

**Issue by FULaBUla** [spring-projects/spring-data-jpa#3379]
```java
@Query("select .....")
Page<LinkedHashMap<String, Object> query(Pageable pageable);
```

I wish spring-data-jpa return `Page<LinkedHashMap<String, Object>>` but you return `Page<Object[]>`. The content type isn't `LinkedHashMap<String, Object>`, it is `Object[]`.

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve.

**Comment by FULaBUla** [comment]
> If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. Right now, we struggle to understand what you want to achieve.

According to the method I defined, the return value type I should get from `Page.getContent()` is `LinkedHashMap<String, Object>`. But actually, I get `Object[]` from `Page.getContent()`.

**Comment by mp911de** [comment]
We do not support `Map` as query method return type, see https://docs.spring.io/spring-data/data-jpa/reference/repositories/query-return-types-reference.html.

**Comment by FULaBUla** [comment]
> We do not support `Map` as query method return type, see https://docs.spring.io/spring-data/data-jpa/reference/repositories/query-return-types-reference.html.

@mp911de The documentation doesn't specify what type of T is available in `Page<T>`. And when I use `Page<List<Object>>`,   The type i get from `Page.getContent()` is also Object[] instead of List<Object>.
