### ISSUE TITLE
Spring Boot 3.2.3 + Native Image Compile broken with JPA/Hibernate

### ISSUE THREAD

**Issue by goafabric** [spring-projects/spring-data-jpa#3380]
Compiling Native Images with Spring Boot 3.2.3 + Spring Data JPA,
is unfortunately DOA.

gradle(w) nativeCompile results ins:

`Error: Could not find target method: public static org.hibernate.bytecode.spi.BytecodeProvider org.springframework.orm.jpa.vendor.Target_BytecodeProviderInitiator.buildBytecodeProvider(java.lang.String)`

Please See the simple Demo app attached, generated from Start.Spring.IO

I already tried to set Reflection Hints for this, but to no avail.

[demo.zip](https://github.com/spring-projects/spring-data-jpa/files/14383321/demo.zip)

**Comment by christophstrobl** [comment]
Please see: spring-projects/spring-framework#32311 for details.
