### ISSUE TITLE
API with Pagination giving error after spring-boot-starter-jpa version upgrade.

### ISSUE THREAD

**Issue by rswain90** [spring-projects/spring-data-jpa#3383]
We were initially using Java8 & spring-boot-starter-data-jpa:2.1.3.RELEASE.
When we are trying to fetch data with page value greater than total page number, we used to get [] response & logs like _{"entityType":"org.springframework.data.domain.PageImpl","message":"Page 2 of 1 containing UNKNOWN instances"_. But after **version upgrade to 2.7.8** we are getting SQL error _SqlExceptionHelper   : Incorrect syntax near ','._

Could you please help me to know, what changes happened  after data-jpa:2.2 related to  pagination response & what fix has to apply. 

Below is the code. 
`Page<MaterialResource> findByModifiedTimeAndType(@Param("type") String type,
                                             @Param("fromTime") LocalDateTime fromTime,
                                             @Param("toTime") LocalDateTime toTime,
                                             Pageable pageable);`
                                             
 **Response with Java8 & spring-boot-starter-data-jpa:2.1.3.RELEASE.** 
 Request : parameter=pageable, value=Page request [number: 1, size 20, sort: UNSORTED] (Total page is 1 but requesting index 1)
 `{
    "timestamp": "2024-02-26T16:32:25.973592",
    "requestId": "eb1dc2ee613826cd",
    "resource": [],
    "page": {
        "size": 20,
        "totalElements": 7,
        "totalPages": 1,
        "number": 1
    },
    "_links": {
        "first": {
            "href": "http://localhost:8080/materials/search?toTime=2024-02-23T07:22:27.612Z&fromTime=2024-02-06T06:43:30.550Z&type=fabric&projection=costing&size=20&page=0"
        },
        "prev": {
            "href": "http://localhost:8080/materials/search?toTime=2024-02-23T07:22:27.612Z&fromTime=2024-02-06T06:43:30.550Z&type=fabric&projection=costing&size=20&page=0"
        },
        "self": {
            "href": "http://localhost:8080/materials/search?toTime=2024-02-23T07:22:27.612Z&fromTime=2024-02-06T06:43:30.550Z&type=fabric&projection=costing&size=20&page=1"
        },
        "last": {
            "href": "http://localhost:8080/materials/search?toTime=2024-02-23T07:22:27.612Z&fromTime=2024-02-06T06:43:30.550Z&type=fabric&projection=costing&size=20&page=0"
        }
    }
}`                                             

**Response with Java11 & spring-boot-starter-data-jpa:2.5.7.**         
Request : parameter=pageable, value=Page request [number: 1, size 20, sort: UNSORTED]  
`"error": {
        "code": "500",
        "message": "SQLServerException: Incorrect syntax near ','."
    }`

**Comment by mp911de** [comment]
Spring Data JPA isn't in the business of generating SQL statements.

Please enable Hibernate SQL logging and attach a stack trace. While I am afraid that this is a Hibernate issue, we still want to make sure that Spring isn't the one that causes the issue.

**Comment by rswain90** [comment]
Thanks for looking my issue. I just attached logs which is before & after Spring upgrade. I am surprised why its failing after just spring upgrade without any code changes. Please let me know if you need any more details.  
[BeforeSpringUpgradeLog.txt](https://github.com/spring-projects/spring-data-jpa/files/14407555/BeforeSpringUpgradeLog.txt)
[AfterSpringUpgradeLog.txt](https://github.com/spring-projects/spring-data-jpa/files/14407556/AfterSpringUpgradeLog.txt)

**Comment by mp911de** [comment]
The main difference is `count(distinct productsou0_.id) as col_0_0_` vs. 

```
        count(distinct productsou0_.attr_id,
        productsou0_.id,
        productsou0_.map_key) as col_0_0_
```

Can you please provide a minimal reproducer that contains the entity model and the affected repository query method?

**Comment by rswain90** [comment]
@mp911de I tried to analysis more & found that after spring boot upgrade its taking primary key(composite) of er_material table & before it was taking primary key of ed_material for getting count. As its taking composite primary key, query is failing for Count(Col1,col2,col3). 
**Old Query**
from
            er_material productsou0_
        inner join
            ed_material material1_
                on productsou0_.id=material1_.id
                
As a resolution we changed our query like below & it starting picking  primary key of ed_material.
                from
            ed_material material1_
        inner join
            er_material productsou0_
                on productsou0_.id=material1_.id

Thanks you so much for looking my issue.
