### ISSUE TITLE
potentiallyWrapWithWildcards usage is wrong in StringQuery

### ISSUE THREAD

**Issue by sahinyanlik** [spring-projects/spring-data-jpa#3395]
For oracle we can not have three parameter for CONCAT

https://docs.oracle.com/cd/B13789_01/server.101/b10759/functions022.htm

Changes can be seen from below:

https://github.com/spring-projects/spring-data-jpa/blob/b7bc17f2df6cb41c90634a91c873d17d3d23aea1/src/main/java/org/springframework/data/jpa/repository/query/StringQuery.java#L387

There is problem for version > 2.7.12

**Comment by christophstrobl** [comment]
Thank you @sahinyanlik for getting in touch. Unfortunately [support](https://spring.io/projects/spring-data-jpa#support) for the `2.7.x` line already ended in late 2023.
A fix is present in more recent versions of spring-data-jpa.
