### ISSUE TITLE
Cannot run/debug tests with IntelliJ IDEA

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-data-jpa#3404]
It works fine until 3.2 GA
3.2.1 will report `java: java.lang.NoClassDefFoundError: jakarta/persistence/Entity`
3.2.3 will report `java: java.lang.NoSuchMethodError: 'void org.hibernate.jpa.internal.MutableJpaComplianceImpl.<init>(java.util.Map)'`

![1](https://github.com/spring-projects/spring-data-jpa/assets/143040/c605d2c6-57f9-401e-867c-d225ce6aa07c)

IntelliJ IDEA 2023.3.5 (Community Edition)

**Comment by schauder** [comment]
Sorry, we don't have the bandwidth to help with IDE issues. All I can offer the confirmation: We are using IntelliJ all the time and it works fine with our code base. My first try would be to reimport the Maven project.
