### ISSUE TITLE
Calling Postgres Function From Spring data jpa repository

### ISSUE THREAD

**Issue by pratt8084** [spring-projects/spring-data-jpa#3407]
Hi All, I am facing issue in calling the postgres function from spring data jpa repository
Please help

Function:
CREATE OR REPLACE FUNCTION user.userbase()
 RETURNS json
 LANGUAGE plpgsql
AS $function$

BEGIN

 RETURN (SELECT array_to_json(array_agg(t)) from

 ( 
.....

Repository :
@Query(value = "SELECT  user.userbase()", nativeQuery = true) 
String callYourFunction(); 

getting below errror again and again.
org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111

**Comment by christophstrobl** [comment]
Closing this one as it's an hibernate issue. Maybe try casting the json return value to text.
