### ISSUE TITLE
Problem with Spring Data JPA with projections, specifications and SPEL

### ISSUE THREAD

**Issue by z8manu8z** [spring-projects/spring-data-jpa#3410]
I'm having a problem using a bean in a SPEL `@Value` expression by combining Projections and Specifications.

Example project : [spring-jpa-projections-specs.zip](https://github.com/spring-projects/spring-data-jpa/files/14759947/spring-jpa-projections-specs.zip)

In the attached project, a projection returned by a `@Query` works correctly, while a projection returned by JpaSpecificationExecutor.findBy(Specification spec) returns an error during http serialization.

CityProjection : 

`@Value("#{@projectionHelper.fullName(target.name, target.country)}")
String getFullName();`

In CityServiceImpl line 79 : 

`CityProjection = this.cityRepository.findByNameAndCountry(name, country);` => works well

`CityProjection = this.cityRepository.findBy(new Specification<City>() {
			@Override
			public Predicate toPredicate(Root<City> root, CriteriaQuery<?> query, CriteriaBuilder criteriaBuilder) {
				return null;
			}
		}, q -> q.as(CityProjection.class).firstValue());`
		
=> fails with message : 

Resolved [org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: EL1057E: No bean resolver registered in the context to resolve access to bean 'projectionHelper']

How can I solve this ?

**Comment by christophstrobl** [comment]
The fix unfortunately requires quite a few changes in the current implementation, so I'm afraid there's no easy work around for this at the moment.

**Comment by z8manu8z** [comment]
@christophstrobl Ok thanks for your investigations !
I can adapt my implementation, no worry about that.
Can you show me how I can do ?
