### ISSUE TITLE
Suboptimal specification queries for object arrays

### ISSUE THREAD

**Issue by markusheiden** [spring-projects/spring-data-jpa#3412]
When using code to filter by an SQL array containing a given element, the `null` handling in the generated SQL breaks the check.

[arrayfunction.zip](https://github.com/spring-projects/spring-data-jpa/files/14809016/arrayfunction.zip)

SQL generated for PostgreSQL (shortened):
```sql
SELECT ... FROM ... WHERE CASE WHEN longs IS NOT NULL THEN COALESCE(array_position(longs, 2), 0) END IS NOT NULL
```

The generated SQL has two flaws:
- `longs` is not nullable, so the `null` check is not needed.
- Due to the unexpected `COALESCE` the result is always `NOT NULL` what breaks the intended check for existing elements.

```java
@Entity
public class MyEntity {
    // This automatically maps to an SQL array.
    @Column(name = "longs", nullable = false)
    private List<Long> longs;
    ...
}

public interface MyRepository extends Repository<MyEntity, Long> {
    List<MyEntity> findAll(Specification<MyEntity> spec);
}

public class Test
    void test() {
        ...
        var found = repository.findAll(Specification.where(hasAnyLong(2L)));
    }

    private Specification<MyEntity> hasAnyLong(Long l) {
        return (entity, cq, cb) -> {
            Path<MyEntity> longs = entity.get("longs");
            var position = cb.function("array_position", Integer.class, longs, cb.literal(l));
            return cb.isNotNull(position);
         };
    }
}

```

**Comment by quaff** [comment]
>> Returns the 1-based position of an element in the array. Returns 0 if the element is not found and `null` if the array is `null`.

You should use `cb.ge(position, 1)` instead of `cb.isNotNull(position)`.


BTW, It's handled by Hibernate not Spring Data JPA.

**Comment by markusheiden** [comment]
Sorry for misjudging this. The workaround works. Thanks for that. I used `cb.gt(position, 0)` though.

**Comment by quaff** [comment]
https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#hql-array-position-functions

The function `array_position` is hql function provided by Hibernate, It will overlay native sql function.

**Comment by markusheiden** [comment]
Thanks for pointing me to the docs. I thought these function calls were calls of native functions of the database before.

Then it might be another Hibernate bug because it worked before when using user types to map to SQL arrays. In that case `array_position` was called directly with no adaption needed to provide the documented behavior.

**Comment by quaff** [comment]
> Then it might be another Hibernate bug because it worked before when using user types to map to SQL arrays. In that case `array_position` was called directly with no adaption needed to provide the documented behavior.

I guess that works before `array_position` added, it's introduced since 6.4.0, see https://hibernate.atlassian.net/issues/HHH-17335
