### ISSUE TITLE
Native query is not working when an entity attribute entity attribute is annotated with @NotFound

### ISSUE THREAD

**Issue by mukeshkumar0322** [spring-projects/spring-data-jpa#3443]

**Comment by christophstrobl** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it. 
`@NotFound` is part of hibernate which indicates the problem might be better reported with them.

**Comment by mukeshkumar0322** [comment]
Hi Spring-Projects/Spring-Data-Jpa

This issue is resolved now
 Problem was with bean naming.

Thanks ,
Mukesh
