### ISSUE TITLE
hibernate6.5 fix @Query doesn't check constructor field type issue

### ISSUE THREAD

**Issue by FULaBUla** [spring-projects/spring-data-jpa#3450]
#3364 #3336 https://hibernate.atlassian.net/browse/HHH-17729
These two issues are fixed after the hibernate6.5 official version is upgraded. Can spring-Date-jPA 3.2 be upgraded to hibernate6.5?

**Comment by christophstrobl** [comment]
Thanks for getting in touch, we prefer to use GitHub issues only for bugs and enhancements. 
Nevertheless, following our upgrade policy the `data-jpa 3.2.x` line will remain on hibernate `6.4` applying only patch level updates. You may override the dependency and upgrade already on your own. Please watch out if you're using GraalVM native image as hibernate 6.5 comes with additional reflection hint requirements.
Other than that, `data-jpa:3.3.0` will be out in a few weeks.
