### ISSUE TITLE
JPQL and HQL parser issue with class projection when FQDN includes "exp"

### ISSUE THREAD

**Issue by jgooley-sh** [spring-projects/spring-data-jpa#3451]
Version: Latest 3.1.x

It appears that when using class based projection we can't have `exp` in our package name.

```
select new com.company.exp.thing.stuff.ClassName(
  e.id,
  cast(round(coalesce(SUM(e.amount), 0),2) as decimal) as amountTotal
)
from Experience e
group by e.id
```

Antlr output:
> line 1:22 mismatched input '.' expecting '('
> line 1:32 mismatched input '.' expecting {<EOF>, ',', EXCEPT, FROM, GROUP, INTERSECT, ORDER, UNION, WHERE}

**Comment by christophstrobl** [comment]
@jgooley-sh thanks for reporting - we'll look into this.
