### ISSUE TITLE
entity basePackages in third-party jars

### ISSUE THREAD

**Issue by en-o** [spring-projects/spring-data-jpa#3461]
There exists JPA operations in a custom third-party JAR. If @EntityScan is used, it fails to load entities from the third-party JAR, resulting in a "Not a managed type" error. However, if @EntityScan is not used, JPA scanning in the business project will be ineffective. Upon debugging, I found that this is overridden in org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration#getPackagesToScan(). Currently, I need to append instead of override the entity scanning. I'm unsure if this is a bug or a design principle. My current approach to handling this is as follows:

# Override the original class override method
```java
protected String[] getPackagesToScan() {
List<String> packages = EntityScanPackages.get(this.beanFactory).getPackageNames();
if (packages.isEmpty() && AutoConfigurationPackages.has(this.beanFactory)) {
	packages = AutoConfigurationPackages.get(this.beanFactory);
	packages.add("cn.jdevelops.config.standalone.model");
}
return StringUtils.toStringArray(packages);
}
```
![image](https://github.com/spring-projects/spring-data-jpa/assets/45027672/eef955a6-e093-4290-a6c3-b5b4df22a5e0)

**Comment by odrotbohm** [comment]
This is a [known issue](https://github.com/spring-projects/spring-boot/issues/19024) with Spring Boot. Prefer to use `@AutoConfigurationPackage` to add multiple packages to the default entity scanning.

**Comment by en-o** [comment]
> This is a [known issue](https://github.com/spring-projects/spring-boot/issues/19024) with Spring Boot. Prefer to use `@AutoConfigurationPackage` to add multiple packages to the default entity scanning.

thanks
