### ISSUE TITLE
Error found: java.lang.NoSuchMethodError: "_persistence_checkFetchedForSet(java.lang.String)  with spring data JPA 3.3.0

### ISSUE THREAD

**Issue by AnupamKT** [spring-projects/spring-data-jpa#3490]
We upgraded the following spring  jars

- Spring framework jars from 6.1.5 to 6.18
- Spring boot from 3.2.4 to 3.3.0
- Spring data JPA from 3.2.4 to 3.3.0
- Spring data commons to 3.2.4 to 3.3.0

we observed the following runtime error:java.lang.NoSuchMethodError: "_persistence_checkFetchedForSet(java.lang.String)
We are using the Eclipselink version 4.0.2.

When we upgrade only Spring boot and spring framework jars, there are no errors seen. This error is seen only when we upgrade spring data JPA and spring data commons. We even tried upgrading eclipselink to its latest version 4.0.3 but no luck.
Please suggest what we need to do.

**Comment by christophstrobl** [comment]
Thank you for getting in touch. This sounds a bit like a dependency problem. data-jpa builds fine against both eclipse link 4.0.2 and 4.0.3. 
Maybe you can take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem and provides a little more context in which the error occurs.
