### ISSUE TITLE
jpa custom

### ISSUE THREAD

**Issue by 3066097899** [spring-projects/spring-data-jpa#3498]
<img width="599" alt="1" src="https://github.com/spring-projects/spring-data-jpa/assets/141490759/5e9b8fd9-3f22-48f6-ac59-fa673fa0acea">
<img width="148" alt="2" src="https://github.com/spring-projects/spring-data-jpa/assets/141490759/986de51e-81d1-4db6-a706-453c23b2b2e8">
**Why does the "Insert unexpected" issue occur during the insert operation when I configure the custom operation database method in JPA? SQL statements, regardless of capitalization, cannot solve it**

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by 3066097899** [comment]
[study_jpa_query.zip](https://github.com/user-attachments/files/15585911/study_jpa_query.zip)
In this project, I am learning to use a custom sql method in the JPA operating database. When I define an "INSERT" method, the "INSERT unexpected" problem occurs. I use the "@ Query annotation" where the problem occurs. After I use mybaties, I call the @ Insert annotation in mybaties to solve the problem. How can I solve the problem without using mybaties

In this project, I am learning to use a custom sql method in the JPA operating database. When I define an "INSERT" method, the "INSERT unexpected" problem occurs. I use the "@ Query annotation" where the problem occurs. After I use mybaties, I call the @ Insert annotation in mybaties to solve the problem. How can I solve the problem without using mybaties

**Comment by mp911de** [comment]
The code is a pretty wild mix of annotations. Generally speaking, Spring Data isn't raising any IDE errors, that's the responsibility of IDE plugin authors. For any modifying queries, please add `@Modifying` to indicate that the query is running insert/update/delete statements. Also, the `@Query("INSERT INTO …`) query is missing `nativeQuery = true`.
