### ISSUE TITLE
Missing `@Transactional` on `SimpleJpaRepository.delete(spec)`

### ISSUE THREAD

**Issue by gbrehmer** [spring-projects/spring-data-jpa#3499]
Is there a reason that this delete method variant has no predefined `@Transactional` marker?

https://github.com/spring-projects/spring-data-jpa/blob/4387a31069f8b2b4b3b6a51d60e13b0ebcacbb05/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/SimpleJpaRepository.java#L479

Currently this breaks support (or needs additional boilerplate code) for the best practice of adding `@Transactional(readOnly=true)` at repository class level

**Comment by mp911de** [comment]
That's an oversight on our end, the method should be marked `@Transactional`.

**Comment by quaff** [comment]
@mp911de  Please see https://github.com/spring-projects/spring-data-jpa/pull/3194 to decide if we need a test case to prevent such oversight.
