### ISSUE TITLE
[Bug] StaleObjectStateException when search in EntityListener @PostRemove method

### ISSUE THREAD

**Issue by Farley-Chen** [spring-projects/spring-data-jpa#3501]
When there is more then one row  in the table.

If you remove one entity, and then search in the entity listener in `@PostRemove` method if will fail on StaleObjectStateException.

The code sample is here.

[issue.zip](https://github.com/user-attachments/files/15739193/issue.zip)

**Comment by schauder** [comment]
JPAs  behaviour is undefined when accessing the  `EntityManager` in life cycle methods:

> In general, the lifecycle method of a portable application should not invoke EntityManager or query operations, access other entity instances, or modify relationships within the same persistence context.

See: https://jakarta.ee/specifications/persistence/3.0/jakarta-persistence-spec-3.0#lifecycle-callback-methods

The behaviour depends on the underlying JPA implementation not on Spring Data.
