### ISSUE TITLE
weird vscode HQL syntax error in Spring Boot

### ISSUE THREAD

**Issue by jackytank** [spring-projects/spring-data-jpa#3520]
I had installed Spring Boot Extension Pack in VSCode and I detect and weird JPQL/HQL syntax error present in my repository

![image](https://github.com/spring-projects/spring-data-jpa/assets/52403567/1141555a-26a1-4688-8735-e7d54485ba95)

although the code work fine without any runtime error, but VSCode still showing that weird syntax error make me want to become a dictator and destroy the world

**Comment by christophstrobl** [comment]
The VSCode extension is not part of data-jpa but the tools support. Please report the issue [there](https://github.com/spring-projects/sts4).
