### ISSUE TITLE
Interface-based projection does not work for queries with declared fields when returned interface is implemented by the entity

### ISSUE THREAD

**Issue by vitos23** [spring-projects/spring-data-jpa#3537]
Interface-based projection does not work properly when querying for not the whole entity but specified fields and returned interface is implemented by the entity.

Suppose we have:
```kotlin
interface UserInfo {
    val name: String
    val age: Int
}

@Entity
@Table(name = "users")
class User(
    @Column(name = "name")
    override var name: String,
    @Column(name = "age")
    override var age: Int,
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    var id: Long? = null,
) : UserInfo

interface UserRepository : JpaRepository<User, String> {

    @Query("select name, age from users", nativeQuery = true)
    fun findAllInfos(): List<UserInfo>

}
```

Let's put some data in the `users` table: `userRepository.save(User("user", 123))`.
And if we execute `findAllInfos` we will get the following error:
```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object[]] to type [@org.springframework.data.jpa.repository.Query com.example.projectiondemo.UserInfo] for value [{...}]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
...
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [@org.springframework.data.jpa.repository.Query com.example.projectiondemo.UserInfo]
...
```

The full example is [here](https://github.com/user-attachments/files/16115840/projection-demo.zip).

The root of the problem is on the 139th line of the `ResultProcessor` class (spring-data-commons), in the method `processResult`:
```java
if (source == null || type.isInstance(source) || !type.isProjecting()) {
	return (T) source;
}
```

`type.isProjecting()` returns `false` but `source` is just `Object` with queried fields, not the entity. Therefore, projection is not created.

**Comment by odrotbohm** [comment]
Projection interfaces must not be implemented by the aggregate which the repository manages. If it implements the interface we cannot distinguish between a lookup for the full entity behind the interface or just the reduced set of properties. A simple workaround would be to create an additional, empty projection interface that extends `UserInfo` to make clear what you're tying to do.

**Comment by vitos23** [comment]
Thanks for the workaround. It would be nice to see such limitations covered in the documentation.
