### ISSUE TITLE
Invalid stackoverflow links on the Overview tab

### ISSUE THREAD

**Issue by arefbehboudi** [spring-projects/spring-data-jpa#3554]
Hi,

The overview tab of Spring Data JPA page contains a link to stackoverflow. The link is invalid and has not been tagged with `spring-data-jpa`. 
The link is :

https://stackoverflow.com/questions/tagged/

I think the correct link should be like below:

https://stackoverflow.com/questions/tagged/spring-data-jpa

**Comment by mp911de** [comment]
Thanks for letting us know. That's fixed now.
