### ISSUE TITLE
two entities with the same table name - merged table

### ISSUE THREAD

**Issue by cloner1998** [spring-projects/spring-data-jpa#3556]
Hello,
I accidentally had two entities with the same table name (actually one without explicit Table annotation) and jpa without warning created a table that emerged from merging all columns of both entities (and unusable as it's firing wrong insert queries with fewer arguments than required - so it's not a merge)

I don't know if this is expected behavior or not but I was expecting a fail-fast behavior

 here is my example:

```kotlin
@Entity
@Table(name = "a")
class A(
    @Id
    val a: Int,
    val c: Int,
    val aa: Int
)

@Entity
@Table(name = "a")
class B(
    @Id
    val b: Int,
    val c: Int,
    val bb: Int
)
```

which result in 
```sql
create table public.a (
  a integer not null,
  aa integer not null,
  b integer primary key not null,
  bb integer not null,
  c integer not null
);
```

thanks in advance

**Comment by quaff** [comment]
I think it's reasonable, it's a valid use case to map the same table to different entities (full and brief).
BTW, It's not handled by Spring Data JPA but JPA implementation such as Hibernate and EclipseLink.

**Comment by schauder** [comment]
As @quaff correctly noted this issue is in the realm of the JPA implementation, and not of Spring Data.

**Comment by cloner1998** [comment]
thank you for correcting me 
have a good day
