### ISSUE TITLE
Data JPA starter dependency causing Micrometer traceId and spanId to disappear from logs MDC

### ISSUE THREAD

**Issue by a7md0** [spring-projects/spring-data-jpa#3557]
Adding `org.springframework.boot:spring-boot-starter-data-jpa` dependency is causing the `traceId` & `spanId` of Micrometer to disappear from the MDC for some reason, thus the logs are missing these identifiers 

Once Data JPA dependency is removed the `traceId` & `spanId` are available in the MDC & logs.

Am I missing something here? Why JPA is breaking the Micrometer for non-HTTP projects? (e.g., worker node)

Spring Boot 3.3.2 with 
`org.springframework.boot:spring-boot-starter-actuator` 
`io.micrometer:micrometer-tracing-bridge-otel`

**Comment by mp911de** [comment]
I'm not sure I follow. In a HTTP context, `ServerHttpObservationFilter` adds observation capabilities. If you just run a `Runnable`, then you need to attach observation yourself.

Please elaborate or provide a minimal reproduce to follow up here.
