### ISSUE TITLE
Execute error after packaging using SpringNative

### ISSUE THREAD

**Issue by iloveuaa** [spring-projects/spring-data-jpa#3560]
resloved .spring change to 3.0.8

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

**Comment by iloveuaa** [comment]
> If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem. You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

I run everything normally locally, but it fails after I package it into a binary file through the command.

`mvn -Pnative clean native:compile -DskipTests`

Thanks for your time

```sql
CREATE TABLE `gz_app` (
  `appid` bigint(20) NOT NULL,
  `appkey` char(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `status` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `exp_date` date DEFAULT NULL,
  `node_num` smallint(6) DEFAULT NULL,
  `username` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `password` char(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`appid`) USING BTREE,
  KEY `IDX_STATUS` (`status`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC;
```
[Gezi-Core.zip](https://github.com/user-attachments/files/16507108/Gezi-Core.zip)

**Comment by iloveuaa** [comment]
spring change to 3.0.8
