### ISSUE TITLE
findLastChangeRevision doesn't return last revision if two revisions with exactly the same timestamp exist

### ISSUE THREAD

**Issue by flauschtrud** [spring-projects/spring-data-jpa#3579]
While running automated tests I ran into an issue with RevisionRepository.findLastChangeRevision.

If two revisions with exactly the same timestamp exist findLastChangeRevision does not necessarily return the revision with the highest revision number (which is what I would expect).

If my revinfo table has the following content findLastChangeRevision for the associated audited entity actually returns the revision with id 1 and not the one with id 2.

id,timestamp
1,2024-08-13 08:49:48.501000
2,2024-08-13 08:49:48.501000

In the implementation the revisions are ordered based on revisionProperty("timestamp") and the ID is not taken into account. https://github.com/spring-projects/spring-data-jpa/blob/a44bca82c6d939aa3a43d60d008b2dc750b51f27/spring-data-envers/src/main/java/org/springframework/data/envers/repository/support/EnversRevisionRepositoryImpl.java#L96

I am aware that this is an edge case and that it's way more likely to run into it in artificial scenarios but it's also not impossible to cause issues for production code.

**Comment by mp911de** [comment]
Actually, shouldn't the retrieval sort by `AuditEntity.revisionNumber().desc()`?

**Comment by schauder** [comment]
Hibernates documentation isn't overly clear of the semantics of the two properties. 
But in the javadoc to  `@RevisionNumber` I found `Values of this property should form a strictly-increasing sequence of numbers.`
And there is also this old discussion in the Hibernate forum.
https://discourse.hibernate.org/t/order-of-revision-number-in-envers/2399

So it does indeed seem that the `revisionNumber` should be used.

I'll fix that.

**Comment by wacker** [comment]
We have a regression here, as revision numbers are in fact not always sequential (at least not in a multi-node environment), because of the pre-allocation of Hibernate sequence numbers. The 'order by' should probably be composed of timestamp AND rev in order to handle the issue of exactly the same timestamps.
