### ISSUE TITLE
Remove Quotes from PostgreSQL Integer Array Type in SQL Generation

### ISSUE THREAD

**Issue by HollisMeynell** [spring-projects/spring-data-jpa#3614]
How to remove the quotation marks generated by `@Column(columnDefinition = "integer[]") `in the SQL creation statement? These quotation marks cause a PostgreSQL error via JDBC: `ERROR: type "integer[]" does not exist.`

**Comment by HollisMeynell** [comment]
```
@Entity(name = "table_1")
class MaiChartLite(
    @Id
    var id: Int,

    @Type(IntArrayType::class)
    @Column(columnDefinition = "integer[]")
    var notes:IntArray,
)
```

error:
```
Error executing DDL "create table "table_1" ("id" integer not null, "notes" "integer[]", primary key ("id"))" via JDBC [ERROR: type "integer[]" does not exist
```
The correct result should be 
```
create table "table_1" ("id" integer not null, "notes" integer[], primary key ("id"))
```
===================================================^ not quotes

**Comment by schauder** [comment]
Schema generation for JPA is done by your JPA implementation, not by Spring Data. Please consult with them to solve this problem.
