### ISSUE TITLE
Allow returning Map from the repository methods

### ISSUE THREAD

**Issue by mipo256** [spring-projects/spring-data-jpa#3636]
I've not found any similar issue, so I'm creating a new one.

**Problem:**

The problem is that sometimes native queries are quite complicated, and it is possible that they would return unknown at declaration time number of columns. I'm not saying it is a great way of doing things, but that's just what we have in our case, for instance. 

And in this case we cannot really return any kind of projection, since we do not know anything about the structure of the result set being returned at compile time.

**Solution (Proposal)**:

I think it makes sense to consider allowing returning the `Map` from the repository query method, like:

```
@Query(value = "...", nativeQuery=true)
Map<String, Object> findSomethingComplex();
```

In this case, the key is supposed to be the column name, and the value is just a raw column value.

**Comment by christophstrobl** [comment]
Thank you for getting in touch. 
Repository finder methods in data-jpa using `Map` or `List<Map>` as return type will give you something called a `TupleBackedMap` delegating calls to an underlying `jakarta.persistence.Tuple`. So actually the outlined code from above should already work as expected. 

I had a look at our reference documentation but could not spot anything mentioning this behaviour. So, unless I'm missing something here, this seems to be a documentation issue.

**Comment by mipo256** [comment]
Hey @christophstrobl!
Would it also work for the methods where we expect a single result from the database? Like single `Map`, not a `List`.

**Comment by christophstrobl** [comment]
Yes, you could have something like:
```
@Query(value = "SELECT * from book", nativeQuery=true)
List<Map<String, Object>> findSomething();

@Query(value = "SELECT * from book WHERE id = 1", nativeQuery=true)
Map<String, Object> findSomethingSingle();
```

I'll update the documentation.
