### ISSUE TITLE
Support of Inline View with Pageable 

### ISSUE THREAD

**Issue by gogoadl** [spring-projects/spring-data-jpa#3662]
I found a bug that did not produce a normal count query when using Page with InlineView.

It would be good to test it by referring to the [example repository](https://github.com/gogoadl/spring-jpa).

I'm attaching a simple example first.

Count queries generated when requesting JPQL queries as below are as follows.

#### Sample Query
```
    @Query("SELECT T.id as id,T.name as name,T.address as address FROM (SELECT T2.id as id, T2.name as name,T2.address as address FROM Member T2) T")
    Page<TestInterface> pageRequestWithoutJoin(@Param("id") Long id, PageRequest pageRequest);
```

#### HQL Count Query

HQL cannot interpret this query and an error occurs.

```
    SELECT count(T) FROM (SELECT T2.id as id, T2.name as name, T2.address as address FROM Member T2 ) T
```

#### Error Log

```
org.hibernate.query.SemanticException: The derived SqmFrom[id, name, address] can not be used in a context where the expression needs to be expanded to identifying parts, because a derived model part does not have identifying parts. Replace uses of the root with paths instead e.g. `derivedRoot.get("alias1")` or `derivedRoot.alias1`
```

The example repository also provides example queries, including inserting example data into the H2 database, so it would be good to use them.

Thank you.

**Comment by mp911de** [comment]
`SemanticException` is a Hibernate exception as consequence of using inline views. We can only derive count queries from the specified `FROM` part of your query.

If the derived query doesn't work for you, then please specify a `countQuery` through `@Query(countQuery=…)`.

**Comment by gogoadl** [comment]
@mp911de Thank you for your response, any additional support for this is not in the plan?

**Comment by mp911de** [comment]
You can do all sorts of things in a subselect (even a series of nested subselects) so we cannot figure out your intent. Therefore there's nothing we can do here except letting you define your intent with a query declaration so that you override our assumption.
