### ISSUE TITLE
PagingAndSortingRepository.findAll(Pageable) ignores an unpaged Pageable with a sorted Sort

### ISSUE THREAD

**Issue by demonfiddler** [spring-projects/spring-data-jpa#3676]
Passing an unpaged Pageable containing a sorted Sort to the PagingAndSortingRepository.findAll(Pageable) method ignores the Pageable's Sort, generating an SQL SELECT statement that is missing the requisite ORDER BY clause. The following code fragment illustrates the problem:

```
List<Order> orders = List.of(Order.asc("sortProperty"));
Sort sort = Sort.by(orders);
Pageable pageable = Pageable.unpaged(sort);
ListPagingAndSortingRepository<T, ID> repository = ...;
Page<T> unsortedPage = repository.findAll(pageable);
List<T> sortedContent = repository.findAll(sort);
assert unsortedPage.getContent().equals(sortedContent) : "The findAll(Pageable) overload does not sort the content";
```

**Comment by mp911de** [comment]
No worries. It could be that the issue affects other modules as well. Closing this one and moving it to JPA.
