### ISSUE TITLE
HQL parser rejects `INSERT … ON CONFLICT` clause

### ISSUE THREAD

**Issue by jdupont22** [spring-projects/spring-data-jpa#3689]
Migrating from Spring Boot 3.3.5 to 3.4 lead to this error

The error

> Caused by: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 4:8 mismatched input 'ON' expecting {<EOF>, ','}; Bad JPQL grammar [
        INSERT INTO AggregationPrice(range, price, type) 
        VALUES (:range, :price, :priceType) 
        ON CONFLICT (range) DO UPDATE 
        SET price = :price, type = :priceType 
        ]

The code

  ```
@Modifying
@Query(
    """
      INSERT INTO AggregationPrice(range, price, type) 
      VALUES (:range, :price, :priceType) 
      ON CONFLICT (range) DO UPDATE 
      SET price = :price, type = :priceType 
    """
)
fun save(range: Range<LocalDateTime>, price: Double, priceType: AggregationPriceType)
  ```

**Comment by mp911de** [comment]
This is a regression. Specifically, the issue that we do not consider the conflict clause is becoming visible by eagerly parsing statements.
