### ISSUE TITLE
Support for Auto-Updating Database Constraints for Enum Changes in Hibernate

### ISSUE THREAD

**Issue by mojtabaJ** [spring-projects/spring-data-jpa#3699]
I am working on a Spring Boot application that uses Hibernate for ORM and PostgreSQL as the database. One of my entities, BlockItemEntity, uses an enum, ContactTypeConstant, with the `@Enumerated(EnumType.STRING)` annotation. Here's a simplified version of the entity and enum:
```java
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "block_item", schema = "public")
public class BlockItemEntity implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    @Column(length = 256)
    private String title;

    @Enumerated(EnumType.STRING)
    private ContactTypeConstant contactType;
}

@RequiredArgsConstructor
@Getter
public enum ContactTypeConstant {
    EMAIL(10, "email"),
    PHONE(20, "phone");

    private final long id;
    private final String title;
}

```

Initially, a database CHECK constraint was created for the contact_type column to ensure it matches one of the existing enum values:

```sql
ALTER TABLE block_item
ADD CONSTRAINT block_item_contact_type_check
CHECK ((contact_type)::text = ANY
       ((ARRAY ['EMAIL'::character varying, 'PHONE'::character varying])::text[]));

```
Later, I added new enum values, MOBILE and SMS, to the ContactTypeConstant enum. However, when trying to save a new BlockItemEntity with these values, I encountered the following error:

`ERROR: new row for relation "block_item" violates check constraint "block_item_contact_type_check"
`

**Problem:**

Hibernate does not appear to update the `CHECK `constraint in the database when new enum values are added. As a result, the database remains out of sync with the application’s updated model, leading to constraint violations.
**Request:**

1. Hibernate does not appear to update the `CHECK `constraint in the database when new enum values are added. As a result, the database remains out of sync with the application’s updated model, leading to constraint violations. are modified?
2. Enhancement Proposal: If such a feature does not exist, could it be added to ensure smoother schema evolution?
3. Best Practices: If the above is not feasible, what is the recommended approach for managing enum-related `CHECK `constraints in production environments, particularly when working with Hibernate and PostgreSQL?

Currently, I manually drop and recreate the `CHECK `constraint to accommodate new enum values. While this works, it is manual, error-prone, and disruptive. Having Hibernate handle this process automatically or providing clearer guidance would greatly enhance productivity.

I am unsure if this capability already exists, and I may have overlooked it in the documentation. Any clarification or direction would be highly appreciated.

**Comment by mp911de** [comment]
This is a Hibernate issue as your JPA provider provides schema creation functionality. Spring Data isn't involved into that. Generally, we recommend using a proper database change management library such as Flyway or Liquibase.
