### ISSUE TITLE
Transaction commit fails with `TransientObjectException: persistent instance references an unsaved transient instance `

### ISSUE THREAD

**Issue by tcordel** [spring-projects/spring-data-jpa#3712]
Hi,

## Overview

We met an unexpected error upgrading to spring-boot 3.4.0

I'm not sure this bug deals with spring-data, but i have not been able to reproduce the default using hibernate directly ; maybe you may provide new directions of investigations...

Here is a sample project representing the default with the minimal configuration needed to reproduce it : https://github.com/tcordel/jpa-named-query/tree/main

```
org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.TransientObjectException: persistent instance references an unsaved transient instance of 'com.example.demo.entities.UserNotifEntity' (save the transient instance before flushing)
   	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:368)
   	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:246)
   	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
```

## Details

This issue appears **only** if the optional fetch is done here : [NotificationService](https://github.com/tcordel/jpa-named-query/blob/main/src/main/java/com/example/demo/services/NotificationService.java?plain=1#L46)

### Entities
```mermaid
classDiagram
    class ApplicationEntity {
          
    }
    class UserEntity {

    }
    class TypeNotificationEntity{

    }
    class UserNotifEntity {
        +UserEntity User
        +TypeNotificationEntity typeNotif
    }
    class UserNotifAppliEntity {
        +UserNotifEntity UserNotif
        +ApplicationEntity application
    }
```
### Tests
List of the tests present in [DemoApplicationTests](https://github.com/tcordel/jpa-named-query/blob/main/src/test/java/com/example/demo/DemoApplicationTests.java) :
* [buggyWithTransactionalUsingNamedQueryForDeletion](https://github.com/tcordel/jpa-named-query/blob/main/src/test/java/com/example/demo/DemoApplicationTests.java#L60) : This test presents the bug
* [workingWithoutTransactional](https://github.com/tcordel/jpa-named-query/blob/main/src/test/java/com/example/demo/DemoApplicationTests.java#L85) : condition of bug but removing @Transactional annotation on service makes it pass
* [workingRequiringNewTransactionForDeletion](https://github.com/tcordel/jpa-named-query/blob/main/src/test/java/com/example/demo/DemoApplicationTests.java#L92) : condition of bug but requiring new transaction before calling named query makes it pass
* [workingInSameConditionWithJpqlForDeletion](https://github.com/tcordel/jpa-named-query/blob/main/src/test/java/com/example/demo/DemoApplicationTests.java#L70) : condition of bug but using jpql for deletion makes it pass
* [workingInSameConditionWithCriteriaForDeletion](https://github.com/tcordel/jpa-named-query/blob/main/src/test/java/com/example/demo/DemoApplicationTests.java#L78): consition of bug but using criteria for deletion make it pass

Thanks for your time :)

**Comment by quaff** [comment]
I'm pretty sure it caused by bug fix https://github.com/hibernate/hibernate-orm/commit/055570c8af7c8455d6ae318d589c47441c55850c, I'm not sure you are using in correct way, I didn't dig too much because the code is a bit hard to read.

**Comment by mp911de** [comment]
I can reproduce the issue with using the EntityManager:

```java
CriteriaBuilder cb = entityManager.getCriteriaBuilder();
CriteriaQuery<UserNotifEntity> criteriaDelete = cb.createQuery(UserNotifEntity.class);
Root<UserNotifEntity> from = criteriaDelete.from(UserNotifEntity.class);
criteriaDelete.where(cb.equal(from.get("user"), user), cb.equal(from.get("typeNotif"), typeNotif));
Query query = entityManager.createQuery(criteriaDelete);
List resultList = query.getResultList();
for (Object o : resultList) {
	entityManager.remove(o);
}
```

On the flip side, using a `CriteriaDelete` or a JPQL delete query doesn't show this behavior. That being said, I consider the issue a Hibernate problem and there is nothing we can do about.

**Comment by palhoye** [comment]
This issue was introduced with Hibernate 6.6. 
Hibernate 5.3 does not have this issue. 
Short term work-around is to specify Hibernate dependency as 6.5.3.Final.

**Comment by tcordel** [comment]
For anyone interested the
Issue has been reported to hibernate team :
https://hibernate.atlassian.net/browse/HHH-18936

Downgrading is not possible for us due to another hibernate issue (
https://hibernate.atlassian.net/browse/HHH-18400). But thanks for the tips.

**Comment by dennisvang** [comment]
possibly related: https://discourse.hibernate.org/t/transientobjectexception-when-mixing-entitymanager-delete-with-delete-statements-in-6-6-x/10621
