### ISSUE TITLE
Paged findAll(…) with Specification does not work with join fetch [DATAJPA-105]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#532]
**[Andrew Geery](https://jira.spring.io/secure/ViewProfile.jspa?name=ageery)** opened **[DATAJPA-105](https://jira.spring.io/browse/DATAJPA-105?redirect=false)** and commented

The method `Page<T> findAll(Specification<T>, Pageable)` in the `JpaSpecificationExecutor` interface throws an exception if the `Specification` uses a join fetch.  The problem is that in order to do the pagination, the library has to first perform a count query, but when the count query is performed, the join fetches are not eliminated or changed to regular joins.

The error is:

org.hibernate.QueryException: query specified join fetching, but the owner of the fetched association was not present in the select list

The attached zip file is a simple Maven project which demonstrates this problem (mvn test).

---

**Affects:** 1.0 GA, 1.0.1

**Attachments:**
- [test.zip](https://jira.spring.io/secure/attachment/18795/test.zip) (_6.81 kB_)

14 votes, 11 watchers

**Comment by xerZV** [comment]
any updates on that?

**Comment by beherren2019** [comment]
Hello @schauder Is there any update on this?

**Comment by burakturker** [comment]
is there any update

**Comment by lehaiquantb** [comment]
2024 => any update ?

**Comment by sanderino666** [comment]
When using Kotlin you could use an extension function to get rid of the if statement in the specification.

For example:
```
fun <X : Any, Y : Any> Root<X>.joinOrFetch(
    cq: CriteriaQuery<*>,
    attributeName: String,
    jt: JoinType,
): FetchParent<X, Y> {
    // https://github.com/spring-projects/spring-data-jpa/issues/532
    return if (cq.resultType.name == "java.lang.Long") {
        this.join(attributeName, jt)
    } else {
        this.fetch(attributeName, jt)
    }
}
```

**Comment by anaconda875** [comment]
Hi @schauder, any update on it?

**Comment by rishiraj88** [comment]
@anaconda875 , this issue appears as "closed" already!
