### ISSUE TITLE
Add option so that CrudRepository.findOne throws an unchecked exception if entity is not found [DATAJPA-118]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#544]
**[Adrian](https://jira.spring.io/secure/ViewProfile.jspa?name=nitegate)** opened **[DATAJPA-118](https://jira.spring.io/browse/DATAJPA-118?redirect=false)** and commented

For a clean design it would be great if I could set an option (maybe on the jpa:repository tag) that will throw a javax.persistence.EntityNotFoundException (or some other unchecked exception) instead of returning null if CrudRepository.findOne does not find the entity.

---

**Issue Links:**
- [DATAJPA-301](https://jira.spring.io/browse/DATAJPA-301) Add CrudRepository#findExpected(ID)
 (_**"is duplicated by"**_)

14 votes, 25 watchers

**Comment by Azahe** [comment]
(can I comment on closed issues?)
A word to people missing exception based api (like me):

Optional or null based results force repository user to check *something*. 

To give an example:
```java
Entity findByName(name); 
```
Will force user of repository to repeat `result == null` check (and then doing something).
```java
Optional<Entity> findByName(name); 
```
Will force user of repository to repeat `result.isEmpty()` (or do something clever like `result.map(...)` or `result.stream()` - still multiple times in the code, *check* or *flow branching* will be duplicated).

Now, advantage of exception based apis is possibility to create exception handlers working in an aspect-like manner (and just *not care* about empty results).
What I mean by this is we can have something in code:
```java
handleDbException(BaseDbException ex) {
  // logic like reporting it to error tracker, maybe returning specific error code, maybe mapping to some other exception
}
```
Now by the above I don't necessarily mean controller-level (infrastructure) exception handler - you might want something like this in your domain (making a decision to couple with aspect library or being very careful with using some base class). While having an option to have unchecked exception as a result of repository call would make things simpler (especially with some convention like `getEntity` throwing on missing and `findEntity` not - personally I always thought of *finding* as not implying success) - you might achieve it with *after returning aspect* that does mapping of null or empty optional (I would recommend null as optional needs to be unwrapped and it kinda breaks the point) to your desired exception  

Please note that using this approach we can free domain logic from empty-result handling concern. Imho it can tremendously improve readability retaining design security that `Optional` introduces - exception will propagate to somewhere. Such approach is extremely useful when failing is *just ok* and there is no backup strategy like repeating or changing flow of the code (which, to me, seems to major case in code). 
It will not work where you want to do something specific with missing result (like try another source).
