### ISSUE TITLE
Improve handling of null query method parameter values [DATAJPA-209]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#622]
**[Matthew T. Adams](https://jira.spring.io/secure/ViewProfile.jspa?name=matthewadams)** opened **[DATAJPA-209](https://jira.spring.io/browse/DATAJPA-209?redirect=false)** and commented

In 1.1.0.RC1 and prior, query methods expect non-null values.  If a null value is passed in to a query method, the JPQL generated includes an "= NULL" condition, which is always false.

SD JPA supports query method keyword `IsNull`, which allows for testing explicitly whether a value is `null`.  This is ok, but fails to meet our requirement of using null parameter values to indicate that that parameter should be ignored and not included in the query.

Here's an example.  Suppose I have a `Foo` that references a `Bar` and a `Goo`, and I want to create a query that finds me any `Foo` instances that reference a given `Bar` and/or `Goo`.  The query method would look like this:

```java
public interface FooRepository extends JpaRepository<Foo> {

  List<Foo> findByBarAndGoo(Bar bar, Goo goo);
}
```

If this method is called with a non-null values for both parameters, everything works fine.  However, if you pass null for either parameter, no `Foo` instances are found because `= NULL` is always `false`.  One alternative is for the author to write custom, boilerplate method implementations that handle `null` instances as desired.  Another alternative is to write a collection of methods representing all of the permutations of the nullable parameters, which doesn't really scale well past two or three parameters:

```java
public interface FooRepository extends JpaRepository<Foo> {

  List<Foo> findByBarAndGoo(Bar bar, Goo goo);
  List<Foo> findByBar(Bar bar);
  List<Foo> findByGoo(Goo goo);
}
```

This issue represents a request to improve this situation.

Consider a new enum & annotation:

```java
public enum NullBehavior {
	EQUALS, IS, IGNORED
}

@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.PARAMETER})
public @interface NullMeans {
	NullBehavior value() default NullBehavior.EQUALS;
}
```

With this annotation, SD JPA would let the author decide how to behave when `null` parameters are encountered.  In the absence of the annotation, the current default behavior (`= NULL`) would apply.  If the author uses `@NullMeans(IS)`, then SD JPA will produce an `IS NULL` clause.  If they use `@NullMeans(IGNORED)`, then SD JPA does not include a clause for the given parameter.

Now, reconsider the `Foo` example.  I now have a flexible way of specifying the queries I want.

```java
public interface FooRepository extends JpaRepository<Foo> {

  List<Foo> findByBarAndGoo(@NullMeans(IGNORED) Bar bar, @NullMeans(IGNORED) Goo goo);
}
```

This also scales well:

```java
public interface BlazRepository extends JpaRepository<Blaz> {

  @NullMeans(IGNORED) // applies to all parameters unless overriden by @NullMeans on parameter(s)
  List<Blaz> findByFooAndGooAndHooAndKooAndLoo(Foo foo, Goo goo, Hoo hoo, Koo koo, @NullMeans(IS) Loo loo);
}
```

I've also allowed `@NullMeans` to be placed on the interface as well, which would provide a default for all parameters on all query methods defined in the interface.  I would imagine that many folks would use `@NullMeans`(IGNORED) at the interface level since it's so practical

---

**Affects:** 1.1 RC1

**Issue Links:**
- [DATACMNS-1319](https://jira.spring.io/browse/DATACMNS-1319) Suggestion: change interpretation of Optionals as parameters in Spring Data JPA repositories interfaces
 (_**"is duplicated by"**_)
- [DATAJPA-121](https://jira.spring.io/browse/DATAJPA-121) Query parameter is null,it still use equals(=) to compare

- [DATACMNS-490](https://jira.spring.io/browse/DATACMNS-490) Add support for optional query method parameters

77 votes, 72 watchers

**Comment by dellasavia** [comment]
> **[timguy](https://jira.spring.io/secure/ViewProfile.jspa?name=timguy)** commented
> 
> please keep also in mind all the **findByIn** (e.g.: `findByFooIn(List<..)` cases.
> 
> Because all the described statements like `(property = :parameter or (:parameter is null and property is null))` would not apply here. At least when I use `@Query` with `(:partnerIds is null` the list expand to: `(:partnerIds_0, :partnerIds_1 is null` which is not a valid query

this is not performatic in big tables...

**Comment by joeykay9** [comment]
Is the suggested @NullMeans annotation still under consideration. I believe it will be super helpful for multiple condition derived query statements.

**Comment by Curtaingit** [comment]
Is this plan still being updated? I also encountered this problem. Multiple parameters may be NULL but what I want is to ignore this parameter instead of generating IS NULL.

**Comment by meilleureVie** [comment]
when this feature "@NullMeans" will be implemented or it exists yet

**Comment by gregturn** [comment]
If you need to optionally exclude certain fields from a query based upon that entry being `null` (like a filter box on a web page), why not use Query by Example?

https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#query-by-example

Query by Example, by default, will ignore any fields that are `null` and EXCLUDE them from the query. This avoids having to deal with `Optional` fields, distinguishing between `IS NULL` scenarios. To top it off, we even have special handlers that if they see `null` entered into a field, switch to `IS NULL` in the generated JPQL.

**Comment by gregturn** [comment]
Due to the complexity of dealing with `null` being a signal to exclude a field from a query, we have decided not to implement this feature.

**Comment by Hollerweger** [comment]
Would Query by Example also work for lists?

e.g.: All parameters are optional ( can be null) + logical AND

- parameter name needs a contains ignore-case match and can be null
- parameter types provides a list of types that should match ( SQL IN )
  - In case the parameter is null or the list is empty I could just pass all types instead
- third parameter is just a Boolean that can be null

I couldn't find how I can do a SQL IN match with Query by Example which easily works with method names. eg: findByTypeIn

Full query with method names would not work will null parameters:
```
findByNameContainsIgnoreCaseAndActiveAndTypeIn(String name,
                                               Boolean active,
                                               List<Type> types,
                                               Pageable pageable)
```

**Comment by Alpcom** [comment]
There is also many thing that QBE by design can't support :
 - @Hollerweger mentionned the in statement
 - Comparation : DateBetween DateBefore DateAfter GreaterThan LowerThan
 - some kind of thing like maximum research findTopByCountryOrderByRetVersionDesc
 However if QBE is great tool that doesn't match with the attendee here that is handling request that can have a lot of parameter and writting all combinations in java code is an hard work and most of time a source of confusion.

**Comment by ben5311** [comment]
@gregturn Query by Example does not solve the issue because it only allows EQUALS conditions.

What is the solution for GREATER, LESS, CONTAINS, STARTING_WITH, ENDS_WITH and all the other conditions of query methods?

```java
public interface TransactionRepository extends JpaRepository<Transaction, String> {

    List<Transaction> findAllByDateAfterAndDateBefore(Instant after, Instant before)
}
```

Seems like in 2023 we are back again at the state of 10 years ago...

**Comment by rajithavk** [comment]
> Due to the complexity of dealing with `null` being a signal to exclude a field from a query and having Query by Example as a feasible means to do the same, we have updated our decision, choosing not to implement this feature.

So how does one create a method to achieve the functionality of the below 

`@Query("SELECT t FROM Test t WHERE t.name IN :names OR :names IS NULL")`

We've already tried the below and it didn't execute requiring the name to be not null;

` public List<Test> findAllByNameIn(String[] name);`
