### ISSUE TITLE
Specification.toPredicate(…) will be called twice when calling findAll(spec, pageable) [DATAJPA-404]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#812]
**[grf110](https://jira.spring.io/secure/ViewProfile.jspa?name=grf110)** opened **[DATAJPA-404](https://jira.spring.io/browse/DATAJPA-404?redirect=false)** and commented

Use `findAll(Specification<T> spec, Pageable pageable)`. Problem: will be call method `Specification.toPredicate(…)` twice.

Reason:
method `findAll(spec, pageable)` have call
`org.springframework.data.jpa.repository.support.SimpleJpaRepository#readPage`
and
`org.springframework.data.jpa.repository.support.SimpleJpaRepository#getQuery`

they all call

`org.springframework.data.jpa.repository.support.SimpleJpaRepository#applySpecificationToCriteria`
so

`Predicate predicate = spec.toPredicate(root, query, builder);`

Run twice.

---

**Affects:** 1.4.1

**Comment by valerarenny** [comment]
Specification is returning two sets of results with diferent criteria

**Comment by Ixiodor** [comment]
Hellooo! My 5c to that too:
My specification get executed twice too, so I get

> Already registered a copy: SqmEntityValuedSimplePath ...
