### ISSUE TITLE
Add support for lazy loading configuration via JPA 2.1 fetch-/loadgraph. [DATAJPA-466]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#867]
**[Thomas Darimont](https://jira.spring.io/secure/ViewProfile.jspa?name=thomasd)** opened **[DATAJPA-466](https://jira.spring.io/browse/DATAJPA-466?redirect=false)** and commented

We could leverage the new fetch-group feature from JPA 2.1 to provide support for configuring lazy-loading on repository method level

---

**Issue Links:**
- [DATAJPA-208](https://jira.spring.io/browse/DATAJPA-208) Support specification of fetch plans in query methods

- [DATAJPA-560](https://jira.spring.io/browse/DATAJPA-560) Allow programmatic use of entity graphs

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/74

1 votes, 4 watchers

**Comment by provocative168** [comment]
I encountered that dilemma and discovered a solution https://reedabsentee.github.io/stuart/
