### ISSUE TITLE
Spring.io Spring Data JPA:  "Quick Start" guide should include example code for minimal configuration to use a repository. [DATAJPA-532]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#926]
**[Adam Berlin](https://jira.spring.io/secure/ViewProfile.jspa?name=aberlin@pivotallabs.com)** opened **[DATAJPA-532](https://jira.spring.io/browse/DATAJPA-532?redirect=false)** and commented

See:

https://github.com/spring-io/sagan/issues/382

---
No further details from [DATAJPA-532](https://jira.spring.io/browse/DATAJPA-532?redirect=false)

**Comment by gregturn** [comment]
I believe it's generally agreed that Spring Boot-oriented help, whether they are guides or other things, are the general form of "help" we are putting forth.

It's possible to read the reference documentation to see how to use things. But for "quick and easy", we aren't committing to that form of effort. And given the previous references to Spring Framework and the older UI that used to illustrate how to "get started", this has been revamped to link readers to key sections of manuals, talks, and the Spring Initializr.

If you are wishing to wire everything up manually, this will require using the reference docs, and is not something we intend to support directly.
