### ISSUE TITLE
Allow programmatic use of entity graphs [DATAJPA-560]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#951]
**[Andreas Schilling](https://jira.spring.io/secure/ViewProfile.jspa?name=aschilling)** opened **[DATAJPA-560](https://jira.spring.io/browse/DATAJPA-560?redirect=false)** and commented

For clearly separated (query) use cases having different repository methods with different entity graphs applied is a fine way to control what data is fetched during a query. Then we can give this kind of query a clear name.

With a larger number of graphs or when it should be possible to dynamically decide before a query what graph should be used (e.g. the user may select the amount of detail data she sees) however a programmatic way to apply a graph would be good to keep down the amount of query methods.
This is especially the case if the "base query" stays the same (i.e. no dynamic WHERE or the like).

All this is already possible with Specifications, using entity graphs however would feel more natural and result in less boilerplate code

---

**Affects:** 1.6 GA (Dijkstra)

**Issue Links:**
- [DATAJPA-1291](https://jira.spring.io/browse/DATAJPA-1291) Allow findById caller to choose which lazy relations should be fetched
 (_**"is depended on by"**_)
- [DATAJPA-645](https://jira.spring.io/browse/DATAJPA-645) Enable JPA 2.1 EntityGraphs to be specified dynamically
 (_**"is duplicated by"**_)
- [DATAJPA-466](https://jira.spring.io/browse/DATAJPA-466) Add support for lazy loading configuration via JPA 2.1 fetch-/loadgraph

- [DATAJPA-696](https://jira.spring.io/browse/DATAJPA-696) Support ad-hoc fetch graph configurations on repository methods

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/112

4 votes, 8 watchers

**Comment by Darnoj** [comment]
Thank you @schauder for pointing me to this existing issue.

If possible, I would like this feature to be reexamined.
I disagree with @odrotbohm, in this context you cannot hide the persistence technology used to the client.

The current alternative consist in adding X methods in the repository saying : findBySomethingAndFetchThis, findBySomethingAndFetchThisAndThat, which is actually equivalent and more verbose.

Could you have a look at #2556 ?
I can submit a PR with my proposition (which is using JpaEntityGraph as a special parameter).

**Comment by odrotbohm** [comment]
> I disagree with @odrotbohm, in this context you cannot hide the persistence technology used to the client.

Why not? EntityGraphs of course do what you describe: they provide a persistence technology specific way of defining which parts of an aggregate to load. And, yes, if a client wanted to make programmatic use of them, it can't do so without referring to the concept. That's *a problem* of entity graphs, but it doesn't mean that it's a good idea to break the abstraction with them. They suffer from more problems even, as persisting the partially loaded aggregates will wipe data if you're not careful.

Also, consider that there are way less invasive approaches to the fundamental problem. Using DTO or interface projections, and by that basically introducing a dedicated model for specific read requirements, are a much better way to approach this problem. They're store- and even Spring Data independent, and work consistently across the different data modules. Plus, they clearly separate read models from write ones and do not overload the latter with the former.
